### ISSUE TITLE
[Android] MarkerView does not animate with flyTo, moveTo or setCamera methods.

### ISSUE THREAD

**Issue by krakz999** [rnmapbox/maps#1282]
**Describe the bug**  
MarkerView moves with the camera (leaves its coordinates) while the camera is animating when using any of the following methods: `flyTo`, `moveTo`, `setCamera`. However it stays in the correct position when dragging the map manually.

**To Reproduce**  
1. Display marker
2. Animate the camera with any of the following methods: `flyTo`, `moveTo`, `setCamera`

**Expected behavior**  
The MarkerView would stay on the correct coordinates.

**Actual behavior**  
The MarkerView stays on the last screen space position while the camera is animating, and once the animation is finished, it moves to the right coordinate in map view space.

**Videos**  
Wrong behaviour (android): https://www.youtube.com/watch?v=PdSgEfLFc4g
Correct behaviour (iOS): https://www.youtube.com/watch?v=L_DL_suRKbA

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 10
 - Device: Samsung Galaxy S10 Plus
 - Emulator/ Simulator: no
 - Dev OS: [e.g. OSX 11.0.1, Win10]
 - react-native-mapbox-gl Version 8.2.0-beta1
 - React Native Version 0.63.0

**Comment by ferdicus** [comment]
I think (correct me if I'm wrong here @mfazekas ), that's because the difference in implementation between Android and iOS. 
It's a shortcoming in the Android implementation. Similarly to the fact, that the MarkerView will "jiggle" when you move the map (dragging by hand) on Android.

**Comment by planthree1** [comment]
is there any temporary fix for this behavior?

**Comment by sweatherall** [comment]
I'm also wondering if there is any temp fix or if a future solution is possibly in prospect?

**Comment by ferdicus** [comment]
I would assume, that a temporary fix would be to hide the markerview when initiating the camera movement and then show it once the position is reached?
