### ISSUE TITLE
Can't re-set absolute path on image source

### ISSUE THREAD

**Issue by Dawqss** [rnmapbox/maps#1358]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@react-native-mapbox-gl/maps@8.1.0` for the project I'm working on.

When you want to change to new URL with absolute path (RNFetchBlob) after second time it doesn't add `file://` prefix to uri and it crashes

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLImageSource.m b/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLImageSource.m
index 817918b..cf1fe94 100644
--- a/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLImageSource.m
+++ b/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLImageSource.m
@@ -17,7 +17,19 @@ - (void)setUrl:(NSString *)url
 
     if (self.source != nil) {
         MGLImageSource *source = (MGLImageSource *)self.source;
-        source.URL = [NSURL URLWithString:_url];
+
+        NSURL *myURL;
+
+        if ([[_url substringToIndex:4] isEqualToString:@"http"]) {
+            myURL = [NSURL URLWithString:_url];
+        }
+        else {
+            //Default consider it file url path
+            myURL = [NSURL fileURLWithPath:_url];
+        }
+
+        source.URL = myURL;
+
     }
 }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ferdicus** [comment]
feel free to open a proper PR :)

**Comment by James-Firth** [comment]
@Dawqss I'm interested in this issue!
How are you setting your initial URL? 
When I tried setting it `file://` prefix isn't loading even the first time.
If I can get it to work I could test out your changes (though they look sensible to me from reading the source files).
