### ISSUE TITLE
Keep requesting location even when not in foreground

### ISSUE THREAD

**Issue by RobertSasak** [rnmapbox/maps#1363]
**Describe the bug**  
When _<MapboxGL.UserLocation/>_ is used app keeps requesting GPS position from location manager and device. This works as intendend. However app keeps requesting position even when not in foreground. This can happen when user press home button or user switch to another app. App keeps requesting location until is killed by system or manually by user.

**To Reproduce**  
clone repo
```
cd example
yarn
npx react-native run-android --variant=release
```
- Run app on device. 
- Allow app to use location
- Navigate to _User location > Set User Location Render Mode_ or _User Location Updates_
- Verify that you can see you position on the map
- Verify that you can see GPS icon in the status bar. Not all the phones has it and not all the phone can turn it on. I understand that it might be difficult to reprocuce this issue without this icon.
- Press home button
- Verify that you can still see GPS icon in the status bar. **It should not be there.**
- Open task manager and kill Example app
- Verify that GPS icon disapper from status bar

**Expected behavior**  
App should not request GPS postion when paused/in background/switched away. GPS icon in status bar should be visible only when app is in foreground.

**Actual behavior**  
Remove location listeners when app leave foreground.

**Screenshots**  
Note the small GPS icon in both screenshots.

<p float="left">
<img width="200" src="https://user-images.githubusercontent.com/281281/119722649-dab56b00-be6c-11eb-949a-17bd0276c964.jpg">
<img width="200" src="https://user-images.githubusercontent.com/281281/119722728-eacd4a80-be6c-11eb-863d-e4ed95eb7c0e.jpg">
</p>

**Versions:**  
 - Platform: Android
 - Platform OS: Android 9
 - Device: Huawei Y6 Pro 2019
 - Emulator/ Simulator: no
 - Dev OS: MacOS 11.3.1
 - react-native-mapbox-gl Version https://github.com/react-native-mapbox-gl/maps/commit/be4e8682290ebf422568669905de4fac1cf474ec
 - Mapbox GL version 9.6.1
 - React Native Version 0.63.4

**Additional context**  
This issue is quite a big deal as it do not comply with Google Policy. Apps cannot access location while app is not in background unless background permissions and special declariation is made. Apps that do not comply with this are taken down from Google Play Store. More info in the discussion. https://github.com/react-native-mapbox-gl/maps/discussions/1362

**Comment by RobertSasak** [comment]
I managed to make it work. And is seems like that GPS is not used when app leaves foreground when _followUserLocation_ is set to _false_. Below code works.
```html
<MapboxGL.MapView style={style}>
    <MapboxGL.Camera
        followUserMode={'normal'}
        followUserLocation={false}
    />
    <MapboxGL.UserLocation
        visible={true}
        renderMode="normal"
        showsUserHeadingIndicator
    />
</MapboxGL.MapView>
```
GPS is used for two different purposes. One is to draw the blue dot on the map and another to follow users location with camera. Those are two different things. First works fine and register and unregister it's listeners when app enter foreground and leaves it.
Second one does not.

**Comment by ferdicus** [comment]
thanks for the write-up @RobertSasak, I'll look into this today. 
This very well might also be related to #536

**Comment by ferdicus** [comment]
I can't reproduce this with your steps 😭 
I'm on a Samsung Tablet with Android 10 - I hope this is not device/ android version specific stuff ....

I'll try to build some failsafe to prevent locationManager to keep running when the app goes into background nevertheless

**Comment by RobertSasak** [comment]
@ferdicus Thank you for trying.  Does your phone normaly shows little GPS icon in status bar?

**Comment by ferdicus** [comment]
> @ferdicus Thank you for trying. Does your phone normaly shows little GPS icon in status bar?

Yes, just as you mentioned.

**Comment by ferdicus** [comment]
@RobertSasak, can you try with this PR https://github.com/react-native-mapbox-gl/maps/pull/1365  
Caution: known issue, backbutton and return to app crashes it atm - so best to try home button and afterwards get the app back in foreground without using the back button at all

**Comment by RobertSasak** [comment]
When tesing on actual device make sure that you go to Settings > Apps >Example app > Power managment and disable all the fancy power optimalisation. In my case I can see that app is killed within 10s after is in background.

I tried the same concept as in PR https://github.com/react-native-mapbox-gl/maps/pull/1365 directly in my app and it worked.
I did not try the PR itself. 

## Profiling

I played a bit with profiling in Android Studio. It is very unstable and the app crashed a lot. But in the end I managed to get a following screenshot. On a real device it crashed even more and sometimes to not capture location request at all. 

<img src="https://user-images.githubusercontent.com/281281/120099494-002bc880-c13c-11eb-8985-aa16a4aee5c5.png" width="400">

On the screenshot you can see power tab of profiling with CPU, network and location. I started the app navigated to location example, pressed the home butoon and resumed app. "The valley" in the middle is when app was in the background. Those small vertical lines precisely one second apart are actual location updates. 

First row is the mapbox telemetry service. It create a location request but do not really ask for any location. Third and fifth row is the location manager. You can see as it is pause when app was in the background and started again on 5th row when app came back to foreground. 

**On the forth row you can see setFollowUserLocation. It registered for updates and keep registered also while the app is in the background.** 

As this test was performed on Android Emulator with API 29, I think system simply do not send location update while app is in the background. That would explain where there is a gap of vertical lines on line 4.

**Comment by cmpayc** [comment]
I also noticed that the LocationManager is started when the `onHostDestroy` method is called, instead of stopping.
https://github.com/react-native-mapbox-gl/maps/blob/e15a1da9012afb967a47f6bca0c61c776dd7ab20/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLLocationModule.java#L32-L47

**Comment by ferdicus** [comment]
Opened PR #1382 to address the issue you mentioned @cmpayc.
@RobertSasak, maybe you want to test that one out as well? 


Thanks

**Comment by ferdicus** [comment]
any update on this @RobertSasak ?

**Comment by RobertSasak** [comment]
@cmpayc Well done spotting this typo!

I did a profiling as before and I do not see any change. In other words location manager does not unsubscribe while in the background. As far I understand _onHostDestroy_ is not called when app is going into background.

**Comment by ferdicus** [comment]
@RobertSasak, did you also try with PR #1382 ??  
That one specifically checks for AppState

**Comment by RobertSasak** [comment]
Thank you for double cheching. As there was only one line changed I changed it in my local version. I did not see any difference when running profiling.  

I placed break point on _onHostDestroy_. It is not called when app enters background. I think it is only called when is about to be killed.

**Comment by ferdicus** [comment]
oh damn, sorry 😓 .... 
I meant THIS PR: https://github.com/react-native-mapbox-gl/maps/pull/1365

**Comment by RobertSasak** [comment]
Quick reply. I tried similar trick and add/remove `<UserLocation/>` component based on AppState.addEventListener . I don't remember any difference but I am not 100% sure. I will check again and let you know. Perhaps it is different for `<Camera/>` component.

**Comment by ferdicus** [comment]
@RobertSasak , did you find the time to have a look at this? 
Thanks

**Comment by RobertSasak** [comment]
As far I can tell I do not see any difference in proffiling. Location manager keeps the open channel for receiving location updates, but system do not provide any during the time while app is in the background. PR #1365 does not do any difference. I suggest to drop it as there is it does not change anything.
