### ISSUE TITLE
Custom markers not always rendering

### ISSUE THREAD

**Issue by RobTS** [rnmapbox/maps#1401]
**Describe the bug**  

Dear React Native Mapbox GL team,

While porting my app over from Google maps to this library, I found many exciting features, but also discovered a bug: When using custom markers, they are not always rendered on the app. I had this issue particularly often with draggable markers (using PointAnnotation with Image, seemingly the only way), but when creating a sample app, also found this to have bugs for normal custom markers (ShapeSource and SymbolLayer).

Here is the sample application: https://github.com/RobTS/mapbox-sample

Thanks in advance for the help!

**To Reproduce**  

First, add your mapbox key to the sample application (App.tsx as well as android/gradle.properties) and start it. 

1. Tapping (press, not longPress) on random places on the map should add markers connected with lines (they will show in the text field below the map), but are not rendered (first bug or my mistake?). When you toggle the map pressing the respective button twice (off & back on), it will show the markers as it should.
2. When a track has already been created, clicking the "Toggle draggable" button will turn the markers into draggable ones. However, when the map is toggled off & on once more, the line will reappear, but the draggable markers will not. Interestingly, when pressing and holding the places where the marker should be, they can be dragged around.

**Expected behavior**  

Draggable custom markers should always be rendered correctly.

**Actual behavior**  

Draggable markers are not visible on the map.

**Screenshots**  

![photo_2021-06-11 15 55 07](https://user-images.githubusercontent.com/1608080/121697530-71b92e80-cacd-11eb-9057-53848840c6c3.jpeg)
![photo_2021-06-11 15 55 09](https://user-images.githubusercontent.com/1608080/121697524-71209800-cacd-11eb-95b0-ab2897c36c3e.jpeg)

**Versions (please complete the following information):**  
 - Platform: Android confirmed, iOS had some troubles as well if I remember correctly, but will check again.
 - Platform OS: Android 10
 - Device: OnePlus 6
 - Emulator/ Simulator: no
 - Dev OS: OSX 11.2.3
 - react-native-mapbox-gl Version 8.2.0-beta2, but also happening on the current stable
 - Mapbox GL version ?
 - React Native Version 0.64.1

**Comment by ferdicus** [comment]
welcome @RobTS, 
can you try with a newer version of the underlying SDK please and report back. 

You can find a guide here: https://github.com/react-native-mapbox-gl/maps/blob/master/android/install.md#mapbox-maps-sdk

**Comment by RobTS** [comment]
I just checked (and pushed the changes to the sample project), however, the issue persists. In addition to the previous instructions, you'll need to add a key to android/grapdle.properties now as well.

**Comment by ferdicus** [comment]
Thanks for providing the testable sample - I was able to reproduce the first issue reliably. 
Not the second though.  
What is interesting is, that once the map was toggled newly added markers will show up on tab - I would've assumed, that the behaviour would return to the initial one, however from there on, tabbing just merely adds markers... 🤔 

I also built it on iOS and it worked fine there - markers show up on initial tab (without having to toggle the map). 


Unfortunately I don't have more info at the moment, as I had to timebox this - will have a look next week though. 

Thanks again for filling out the issue ticket according to template and providing a sample app 🙇🏿

**Comment by RobTS** [comment]
Thanks for the quick reply! I'll see that I test this on a couple more devices, then, the first one is not an issue I experience in my own app, but the second one is. If it is limited to a certain manufacturer, that would not be great, but not a tragedy, either. Maybe it is a race condition and I'll debug around a little once I have acquainted myself with this library. If I have new findings, I'll add them here as well!

One more question: Did you test on an emulator or real device? The emulator is suuuper slow on my machine, so I did not run it there.

**Comment by RobTS** [comment]
Update: The custom draggable markers also seem to disappear when the `styleURL` changes. I extended the sample app and made another video: https://youtu.be/EcnFbwxejGg

**Comment by ferdicus** [comment]
Hey @RobTS, I came back to this, and wanted to create a minimal example, tackle one issue at a time - just to make sure the `ShapeSource`/ `ShapeLayer` setup itself is working.

first issue on the menu: do markers get added onPress and subsequent markers placed after follow up presses.

Once we tackle that, I feel like we can investigate all others from there. 

I've taken our example apps `example/src/examples/ShapeSourceIcon.js` screen and simplified it as much as possible still adding the functionality that I mentioned above. 


```jsx
import React from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';

import sheet from '../styles/sheet';
import pinIcon from '../assets/pin.png';

import BaseExamplePropTypes from './common/BaseExamplePropTypes';
import Page from './common/Page';

class ShapeSourceIcon extends React.Component {
  static propTypes = {
    ...BaseExamplePropTypes,
  };

  state = { points: [] };

  render() {
    return (
      <Page {...this.props}>
        <MapboxGL.MapView style={sheet.matchParent}
        onPress={(e) => {
          this.setState(prevState => ({
            points: prevState.points.concat([e.geometry])
          }));
        }}
        >
          <MapboxGL.Camera
            centerCoordinate={[-117.20611157485, 52.180961084261]}
          />

          {!!this.state.points.length && this.state.points.map((point, idx) => {
            return (
              <MapboxGL.ShapeSource
                id={`exampleShapeSource${idx}`}
                key={idx}
                shape={point}>
                  <MapboxGL.SymbolLayer id={`exampleIconName${idx}`} style={{iconImage: pinIcon}} />
              </MapboxGL.ShapeSource>)
          })} 
        </MapboxGL.MapView>
      </Page>
    );
  }
}

export default ShapeSourceIcon;
```

With the below setup I was able to:
* have an initial map rendered without markers
* onPress have a marker added on the press coordinates
* on subsequent presses have an additional marker added on _that_ press coordinate

I did all my tests on a physical, Samsung tablet device.



https://user-images.githubusercontent.com/26439946/122539167-93fc0080-d027-11eb-9ad0-fbd715f74c07.mp4

**Comment by ferdicus** [comment]
Any news on this @RobTS ?

**Comment by RobTS** [comment]
Hi there, unfortunately, this is happening in my side project and the schedule with my main client is too tight to make progress on this. Come October, I should have more time to dig into this issue again and try to narrow down which option/constellation might be causing Problem I, considering it does not happen in your sample app. However, Problem II, draggable markers not showing, is still the more relevant one for me, as it is the one happening in my own app.

As a workaround, I have released the [app](https://blueboatlog.com) with Google Maps as the default Map for editing on Android while this is not figured out, so while inconvenient, it is not a blocker right now. Editing is a small part of the experience, you will be happy to hear that the main interactions already happen using your library and it seems to perform well!
