### ISSUE TITLE
signal SIGABRT - dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents

### ISSUE THREAD

**Issue by chuchuva** [rnmapbox/maps#1412]
The app crashes on startup on iOS 14.4 simulator. Error:

> dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents

XCode console output:
```
dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /Users/pavel/Library/Developer/CoreSimulator/Devices/2BB1C101-B7FB-4533-A7C2-83FB2C2741E9/data/Containers/Bundle/Application/23CB6BC2-772F-491E-A5A2-953D876979A4/testmapbox.app/Frameworks/Mapbox.framework/Mapbox
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/pavel/Library/Developer/CoreSimulator/Caches/dyld/19H2/com.apple.CoreSimulator.SimRuntime.iOS-14-4.18D46
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/pavel/Library/Developer/Xcode/DerivedData/testmapbox-cfnflfrokkfcaahjccftfhtwirjw/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulat
(lldb) 
```

**To Reproduce**  

```
npx react-native init testmapbox
cd testmapbox
npm install react-native-mapbox-gl/maps#master --save
npx pod-install
```
Open workspace in XCode. Run project on iOS 14.4 simulator.

**Expected behavior**  
No crash

**Actual behavior**  
Crash

**Versions:**  
 - Platform: iOS
 - Platform OS: iOS 14.4
 - Device: iPhone 11 simulator
 - Emulator/ Simulator: yes
 - Dev OS: OSX 10.15.7
 - react-native-mapbox-gl Version 8.2.0-beta2
 - React Native Version: 0.64.2
 - XCode Version: 12.4
 - Cocoapods version: 1.10.1

**Comment by ferdicus** [comment]
https://github.com/react-native-mapbox-gl/maps/issues/1139

**Comment by chuchuva** [comment]
I don't think it's a duplicate of #1139 - the app starts normally when built against react-native-mapbox-gl version 8.1.0.

Also it's a runtime crash, not a build error.

**Comment by ferdicus** [comment]
sorry, my mistake - thought it might be an M1 related issue.

**Comment by ferdicus** [comment]
hey @chuchuva, did you check this blog post - seems to provide some remedy for the issue you're having: 
https://medium.com/alameda-dev/installing-react-native-mapbox-navigation-in-ios-e35d43c5987a

**Comment by ferdicus** [comment]
also this stackoverflow post: https://stackoverflow.com/questions/24993752/os-x-framework-library-not-loaded-image-not-found

**Comment by chuchuva** [comment]
Thank you! I was able to work around this issue by adding this line to ios/Podfile:

    pod '@react-native-mapbox-gl-mapbox-static', '~> 10.0.0-beta.12'

However it would be good to get to the bottom of this. As I said version 8.1.0 doesn't this issue so it must be a regression, right?

**Comment by ferdicus** [comment]
> Thank you! I was able to work around this issue by adding this line to ios/Podfile:
> 
> ```
> pod '@react-native-mapbox-gl-mapbox-static', '~> 10.0.0-beta.12'
> ```
> 
> However it would be good to get to the bottom of this. As I said version 8.1.0 doesn't this issue so it must be a regression, right?

hmm 🤔 
I guess we might need to update this https://github.com/react-native-mapbox-gl/react-native-mapbox-gl-static-pod @mfazekas ?

**Comment by ferdicus** [comment]
hey @chuchuva, 
please check this discussion for a very similar issue and how it got resolved.

**Comment by chuchuva** [comment]
@ferdicus which discussion? There is no link 🙂

**Comment by ferdicus** [comment]
sorry, was day-dreaming 😅 

This one: https://github.com/react-native-mapbox-gl/maps/issues/1420

**Comment by adeperio** [comment]
Can confirm I am experiencing this too. Similar conditions as @chuchuva. The workarounds don't work for me unfortunately and generate other errors. My setup:

Platform: iOS
Platform OS: iOS 14.5
Device: iPhone 12 simulator
Emulator/ Simulator: yes
Dev OS: OSX 11.2.3
react-native-mapbox-gl Version 8.2.1
React Native Version: 0.64.2
XCode Version: 12.5.1

**Comment by erwannbst** [comment]
Facing same issue with Intel chip

Platform: iOS
Platform OS: iOS 15.1
Device: iPhone 12
Dev OS: OSX 12.0.1
react-native-mapbox-gl Version 8.5.0
React Native Version: 0.63.4
XCode Version: 13.1
