### ISSUE TITLE
Android: Compass will not render for android-sdk:9.6.2 

### ISSUE THREAD

**Issue by mzu** [rnmapbox/maps#1467]
**Describe the bug**  
The compass that normally appears during rotation of the map layer does not show up anymore for the latest android sdk.

**To Reproduce**  

Add following dependencies to your `build.gradle` (as describes in [install.md](https://github.com/react-native-mapbox-gl/maps/blob/b73056fc868faf0a4a9ce7e1ab818bc2a83303dd/android/install.md))

```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.6.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'
```

It's possible to test this with the example project [here](https://github.com/react-native-mapbox-gl/maps/blob/b73056fc868faf0a4a9ce7e1ab818bc2a83303dd/example/src/examples/Map/ShowMap.tsx).

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 11
 - Device: moto g(8) power
 - Emulator/ Simulator: yes, same problem
 - Dev OS: macOS 11.4 
 - react-native-mapbox-gl Version: 8.2.1
 - mapbox-android-sdk: 9.6.2
 - React Native Version: 0.64.1

The compass shows up as expected when testing the same exact code without the custom sdk.

I suspect the problem is connected to [this change here ](https://github.com/mapbox/mapbox-gl-native-android/pull/598/commits/8830f98cb11c0efdbd660c6b7a82dd9ea047ac9f).

Is there anything I can do to make this work again? For example adding any extra configuration to point to the new image resource for the compass since the bitmap version has been deprecated? Or does this require any code changes inside this project?

Many thanks!

**Comment by tr3v3r** [comment]
As a workaround, I've used the following versions for the packages (took [here](https://github.com/react-native-mapbox-gl/maps/blob/d07f296b5e358534826a90eff9f9d912b83d5977/android/rctmgl/build.gradle)):
```
  implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.1.0'
  implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0'      
  implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
  implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0'
```

Compass is present

**Comment by Alexandria** [comment]
Hello! @mzu Just following up on this. Is this still a problem for you? There have been newer versions of the dependancies since then and I can now see the compass. If this is still an issue I can take a look at this.
