### ISSUE TITLE
Pressing the map in user tracking mode: follow [Android]

### ISSUE THREAD

**Issue by andrei-tofan** [rnmapbox/maps#1491]
**Describe the bug**  
Pressing on the map in user tracking mode 'follow' changes user tacking mode in 'none'.

**To Reproduce**  
Open the example app and go to "Set User Tracking Modes" screen in "Camera" section on an Android device.
Press the tab with the label 'Follow', now the user tracking mode is in 'Follow'.
Press anywhere on the map, the user tracking mode will change to 'None'.

**Expected behavior**  
The user tracking mode should remain 'Follow'.

**Actual behavior**  
The user tracking mode changes to 'None'

**Additional context**  
Sometimes users accidentally tap on the map and complain that the user tracking mode has changed.

**Comment by ferdicus** [comment]
hmmm, yes, I can understand your/ users frustration with this, however I think this is valid behaviour.  
What you could to, is check for `onUserTrackingModeChange` and either display some onscreen prompt to re-enable or automatically re-enable it yourself.  

I believe that's also the way map apps like google maps/ waze are behaving, so users are used to that behaviour.

WDYT?
