### ISSUE TITLE
Cannot apply `translate` to a PointAnnotation

### ISSUE THREAD

**Issue by todor-a** [rnmapbox/maps#1508]
**Describe the bug**  
I want to render a custom icon, drawn with CSS, and applied the `translate` property, as an annotation but cannot with `PointAnnotation`. It does work with `MarkerView`, thought, but I also need the annotation to be clickable and `MarkerView` is not.

Example:
```js
import React from 'react';
import MapboxGL from "@react-native-mapbox-gl/maps";

const Annotation = () => {
  return (
    <MapboxGL.PointAnnotation
      id={v.id}
      key={v.id}
      style={{ flex: 1 }}
      selected={isSelected}
      coordinate={coordinate}
      onSelected={feature => this.onAnnotationSelected(v)}
      >
        <View style={[style.annotationContainer]} />
      </MapboxGL.PointAnnotation>
   );
}

const styles = StyleSheets.create({
  annotationContainer: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 50,
    position: "relative",
    transform: [{ rotate: "45deg" }]
  }
});
```

The strange thing is, as I said, that if I switch to a MarkerView, instead of PointAnnotation, the `transform` is applied. I went through the source code of both components but couldn't find anything that might be causing this. I'm willing to submit a PR if you can guide me to where the problem might be.

**Screenshots**  

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 10
 - Device: OnePlus 5
 - Emulator/ Simulator: no
 - Dev OS: Win10
 - react-native-mapbox-gl Version: 8.1.0
 - Mapbox GL version -
 - React Native Version 0.63.4

**Comment by ferdicus** [comment]
@tdranv , guess you don't want to be cool :(

**Comment by tdranv** [comment]
Ops. missed that notification. Will do! :)
