### ISSUE TITLE
Unable to export the iOS Archieve using Cocoapods version 1.10.2

### ISSUE THREAD

**Issue by ghost** [rnmapbox/maps#1509]
**Describe the bug**  
Currently using version ^8.1.0 and  Cocoapods version 1.10.2 and as we are using this version 1.10.2 we are not able to export the Ios build. Now previously we found solution like dump the version to 1.9.3 and then everything started working again but now we have added few libraries like AppFlyer which must require Cocoapods version 1.10 or grater. So if we dump the version
then we have issue with AppFlyer and other libraries and if we use 1.10.2 version then we have issue with mapbox.
We tried below thing but non of that work.
1. If we are using latest version @react-native-mapbox-gl/maps: 8.3.0 getting crash using cocoapods version 1.10.2 (Here we updated the version of mapbox library)
2.  Ifwe are using version @react-native-mapbox-gl/maps: 8.1.0 did not crash, but not able to export the iOS Archieve using Cocoapods version 1.10.2.
3.  Ifwe are using version @react-native-mapbox-gl/maps: 8.1.0 did not crash, but getting an issue with AppsFlyer and Cocoapods version 1.9.3.
**To Reproduce**  
Use version 8.1.0 with Cocoapods version 1.10.2

**Versions (please complete the following information):**  
 - Platform: IOS
 - Platform OS: Mac
 - Device: Iphone 11 (Simulator)
 - Emulator/ Simulator: Yes
 - Dev OS: [e.g. OSX 11.0.1, Win10]
 - react-native-mapbox-gl Version 8.1.0
 - Mapbox GL version [e.g. 6.3.0]
 - React Native Version 0.63.3

**Additional context**  
I am attaching two screenshots one for pod file and another one when we are using version 8.3.0 that crash issue screenshot. Also we tried look into similar issues like this https://github.com/react-native-mapbox-gl/maps/issues/1097 but it did not worked. Any help would be appriciated.
![Screenshot_14](https://user-images.githubusercontent.com/37325426/131149225-41089560-e574-4781-9554-ac41a7acdd40.png)
![Screenshot_15](https://user-images.githubusercontent.com/37325426/131149448-5730cba2-670a-477c-8a5f-6d81904be2cf.png)

**Comment by yudiz-harshad** [comment]
Hi, Thanks for your quick response so when we tried to create different project then everything works fine after adding pre and post install step in podfile. But in current project where we have many other used library also there its not working with cocoapods version 1.10.2. Could you please look into the pod file code i am attaching with this comment.
Podfile

platform :ios, '12.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks!
dynamic_frameworks = ['InsiderMobile', 'InsiderMobileAdvancedNotification', 'Mapbox-iOS-SDK']

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !dynamic_frameworks.include?(pod.name)
      # puts "Overriding the static_framework? mothod for #(pod.name)"
      def pod.static_framework?
      true
    end
    def pod.build_type;
    Pod::BuildType.static_library
  end
end
end
end

target 'TamamAppClient' do
  config = use_native_modules!
  $RNAppsFlyerStrictMode=true
  use_react_native!(:path => config["reactNativePath"])
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'
  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'

end

#Insider library added targets.
target 'InsiderNotificationContent' do
  inherit! :search_paths
  # Pods for InsiderNotificationContent
  pod "InsiderMobileAdvancedNotification"
end

target 'InsiderNotificationService' do
  inherit! :search_paths
  # Pods for InsiderNotificationService
  pod "InsiderMobileAdvancedNotification"
end

**Comment by ferdicus** [comment]
hi 👋🏿, 
cocoapods `1.10.X` also works with mapbox in a clean project?  
Just asking, because you mentioned a clean project builds fine... 

We're using mapbox in a big production project with `1.10.1` and didn't have build issues so far.  
However, we also do not use `use_framework!` - maybe that'll lead to issues - I'm not sure though, just guessing, not really a native iOS/ Android person 🤷🏿

**Comment by printBart** [comment]
I'm actually getting the same issue but with version 8.2.

@ferdicus  what is your mapbox version?

**Comment by ferdicus** [comment]
in our production app we're using:
`react-native-mapbox-gl/maps`: `8.3.0`
`native mapbox ios SDK`: `6.3.0`


You might want to update your native SDK dependencies and try again,   
if you are using the default ones, then you're on `5.8.0` - which is kinda old
