### ISSUE TITLE
Maplibre failing on build

### ISSUE THREAD

**Issue by d3vv3** [rnmapbox/maps#1532]
**Describe the bug**  

```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Required by:
         project :app > org.maplibre.gl:android-sdk:9.4.0
      > Could not resolve com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
         > Could not get resource 'https://dl.bintray.com/maplibre/maplibre-gl-native/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom'.
            > Could not HEAD 'https://dl.bintray.com/maplibre/maplibre-gl-native/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0.
     Required by:
         project :app > org.maplibre.gl:android-sdk:9.4.0
         project :app > project :react-native-mapbox-gl_maps
      > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0.
         > Could not get resource 'https://dl.bintray.com/maplibre/maplibre-gl-native/com/mapbox/mapboxsdk/mapbox-sdk-turf/5.3.0/mapbox-sdk-turf-5.3.0.pom'.
            > Could not HEAD 'https://dl.bintray.com/maplibre/maplibre-gl-native/com/mapbox/mapboxsdk/mapbox-sdk-turf/5.3.0/mapbox-sdk-turf-5.3.0.pom'. Received status code 403 from server: Forbidden

```

**To Reproduce**
> With Mapbox SDK it works fine, but Maplibre is giving me issues.
* On `android/app/build.gradle` I have the following:
```
dependencies {
    // ...
    // Added for Maplibre
    implementation 'org.maplibre.gl:android-sdk:9.4.0'
    // ...
}
```
* On `android/build.gradle` I have the following:
```
buildscript {
    ext {
        // ...
        rnmbglMapboxLibs = {
            implementation ("org.maplibre.gl:android-sdk:9.2.1")
            implementation ("com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0")
        }
        rnmbglMapboxPlugins = {
            implementation ("com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0")
            implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0")    {
                exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
            }
            implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0")        {
                exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
            }
            implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0") {
                exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
            }
        }
    }
}

repositories {
    // ...
    maven {
        url = "https://dl.bintray.com/maplibre/maplibre-gl-native"
    }
}
```

**Expected behavior**  
App to build normally with open-source Maplibre working just fine.
**Actual behavior**  
Build stops with the output given above.

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 11
 - Device: Oneplus 5T
 - Emulator/ Simulator: No
 - Dev OS: Debian Bullseye
 - react-native-mapbox-gl Version 8.3.0
 - Mapbox GL version ?????
 - React Native Version 0.65.1

**Additional context**  
None

**Comment by d3vv3** [comment]
I see that this is solved when using a token. But wasn't it supposed to be free (libre)?

**Comment by ferdicus** [comment]
hmm, not sure I quite follow

settings in `android/build.gradle` look fine to me. 
why do you additionally add `implementation 'org.maplibre.gl:android-sdk:9.4.0'`  in `android/app/build.gradle` ?? 🤔

**Comment by d3vv3** [comment]
Without that line the issue is still the same.

> I added it because of the maplibre documentation, but I removed it.

**Comment by ferdicus** [comment]
can you please try to reproduce it with the `example` application

only have to set this to `true`:
https://github.com/react-native-mapbox-gl/maps/blob/c680562d3eb2a2043a5e738326bc61f95d51d5dc/example/android/build.gradle#L11

**Comment by d3vv3** [comment]
Just tried, with a the `accesstoken` file blank. It compiles, but the map is always black because:

```
 ERROR  Mapbox error {mapboxglexample}[Setup]: loading style failed: A valid access token parameter is required when using a Mapbox service.
Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.Currently provided token is:  {"level": "error", "message": "{mapboxglexample}[Setup]: loading style failed: A valid access token parameter is required when using a Mapbox service.
Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.Currently provided token is: ", "tag": "Mbgl"}
```

Is there any example with Maplibre flavours or styling?

**Comment by ferdicus** [comment]
Are you trying to access Mapbox tiles? 
You can not use the tile service without having a valid accessToken.

You can use the library without any token - you can not use tile data without having a valid accessToken. 

Makes sense?

**Comment by jbreuer95** [comment]
I am getting the same errors, i see in the maplibre docs that they stopped using bintray and moved to mavenCentral

**Comment by Hergeirs** [comment]
Thank you.
I cannot fix speak for @d3vv3  but I had the same build problem, and making the change in @ferdicus comment fixed my build issues.

**Comment by tomihuttunen** [comment]
Adding jcenter was the only way for me to get the build working also. 

Any plans or ideas when jcenter will (soon?) be shutdown? 
Anything that can be done in the build scripts to exclude this mapbox sdk dependency when using maplibre option?
