### ISSUE TITLE
Unable to use temporary access tokens to interact with Mapbox

### ISSUE THREAD

**Issue by andersonvom** [rnmapbox/maps#1541]
**Describe the bug**  
Using temporary access tokens (created via the [create token API][1]) leads to an invalid token alert: `A valid access token parameter is required when using a Mapbox service.`

[1]: https://docs.mapbox.com/help/tutorials/get-started-tokens-api/

**To Reproduce**  
* Try to start the example app with a temporary token created via the [create token API][1].

```sh
# create a temporary token with:
secret_token="<secret-token-here>"
curl \
  -H "Content-Type: application/json" \
  -X POST \
  -d '{"expires": "2021-09-17T11:20:00.000-04:00","scopes": ["styles:read", "fonts:read"]}' \
  "https://api.mapbox.com/tokens/v2/amesquita-dataminr?access_token=${secret_token}"

# The token is valid to load tiles
curl --head "https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/1/0/0.png?access_token=tk.eyJ1IjoiYW1lc3F1aXRhLWRhdGFtaW5yIiwiZXhwIjoxNjMxODkzODAwLCJpYXQiOjE2MzE4OTA3NjIsInNjb3BlcyI6WyJzdHlsZXM6cmVhZCIsImZvbnRzOnJlYWQiXSwiY2xpZW50IjoiYXBpIn0.zgRENhgfiRargyOPQ0l4iA"
HTTP/1.1 200 OK
Content-Type: image/png
Content-Length: 19522
Connection: keep-alive
Date: Fri, 17 Sep 2021 15:43:21 GMT

# however the app says the token is invalid
# adding all public scopes does not solve the problem either
```

**Expected behavior**  
The temporary token should be valid to interact with the mapbox

**Actual behavior**  
An invalid token alert is displayed: `A valid access token parameter is required when using a Mapbox service.`

**Versions (please complete the following information):**  
- Platform: Android
- Platform OS: Android 11 and 12
- Device: Pixel 3a XL
- Emulator/ Simulator: yes (also happens on emulator)
- Dev OS: OSX 11.6
- react-native-mapbox-gl Version 8.3.0
- Mapbox GL version default
- React Native Version 0.64

**Comment by ferdicus** [comment]
hi 👋🏿 

what response do you get back when making the initial `curl` request?

I wasn't able to reproduce your issue on current `master` while building and using the `example` app.

I am using the `curl` request as described on the `create Token API` page you linked to
```sh
curl -H "Content-Type: application/json" -X POST -d '{"note": "{token_name}","scopes": ["styles:read", "fonts:read"]}' 'https://api.mapbox.com/tokens/v2/<MY_ORG>?access_token=<🤫>'
```

With that I'm getting back an `accessToken` which I save in the `example/accesstoken` file for the `example` app. 

Builds fine, shows map

**Comment by andersonvom** [comment]
Hi @ferdicus, thanks for reaching back!

I ended up linking the wrong page in the docs 😔; this is the relevant page: [Create a temporary token][1]. The issue I'm seeing happens when using _temporary_ tokens, not just any token. When creating tokens, you can pass an optional `expires` attribute allowing you to create a token that expires up to 1 hour in the future. If this attribute is not present, a public or secret token (depending on the specific scopes) is created instead.

You can get a temporary token with the curl command I mentioned above (i.e. by adding `"expires": "2021-09-17T10:00:00.000-04:00"` to the request payload (the actual date/time needs to be within the hour of issuing the curl command). The response you get from this new request contains only one attribute (`token`) and looks similar to:

```javascript
// notice the token starts with the `tk.` prefix
{"token":"tk.**********"}
```

I just tested it again on `master` and this is the error I see ([screenshot][2]):

```
ERROR  Mapbox error {mapboxglexample}[Setup]: loading style failed: A valid access token parameter is required when using a Mapbox service.
Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
Currently provided token is: tk.******.****** {"level": "error", "message": "{mapboxglexample}[Setup]: loading style failed: A valid access token parameter is required when using a Mapbox service.
```

Everything works as expected if I use a public token (e.g. `pk.*****`).

[1]: https://docs.mapbox.com/api/accounts/tokens/#create-a-temporary-token
[2]: https://user-images.githubusercontent.com/69922/134680494-b053e9e0-77a8-4be1-88eb-a1d78aa8f39e.png

**Comment by ferdicus** [comment]
I was able to reproduce this with the default and `mapbox-android-sdk:9.6.1`. 
Is this some kind of newer feature, or is this restricted to the JS SDK?! 🤔

**Comment by andersonvom** [comment]
Good question. It's hard to tell when this was added, but [it has been there at least since Jan/2021][1].

The MR I linked above should fix the issue in the android SDK. After that, upgrading the SDK over here should fix the problem for good. 

[1]: https://web.archive.org/web/20210115142737/https://docs.mapbox.com/api/accounts/tokens/#create-a-temporary-token

**Comment by ferdicus** [comment]
Oh wow, they released a new SDK version? Color me impressed :D

> upgrading the SDK over here should fix the problem for good.

We actually do not upgrade the default pack-in SDK version:
* does not require `token` to download
* was the one before they changed their terms of service

But you can point to specific versions/ flavors - it's described within the install guides

🤞🏿 hoping that they will release soon

**Comment by RicardoDolNL** [comment]
So... when will this be finally fixed?
