### ISSUE TITLE
ANDROID : MapboxGL.PointAnnotation can't display Image and Text at the same time

### ISSUE THREAD

**Issue by huytq98** [rnmapbox/maps#1548]
**Describe the bug**  
MapboxGL.PointAnnotation can't display Image and Text at the same time (ANDROID)

const _renderAnnotation = (counter) => {
    const id = `pointAnnotation${counter}`;
    const coordinate = coordinates[counter];
    return (
      <MapboxGL.PointAnnotation
        key={id}
        id={id}
        title="Test"
        coordinate={coordinate}
        onSelected={() => _handlePressPopup(counter)}>
        <Image
          style={styles.circleCategory}
          // source={{uri: Config.BASE_URL + '' + place[counter]?.avatar}}
          source={{uri: `data:image/png;base64,${place[counter]?.avatar}`}}
        />
        <Text
          style={
            isActive === 0
              ? {fontSize: 10}
              : {fontSize: 10, color: Colors.white}
          }>
          {address[counter]}
        </Text>
      </MapboxGL.PointAnnotation>
    );
  };
  const _renderAnnotations = () => {
    const items = [];
    for (let i = 0; i < coordinates.length; i++) {
      items.push(_renderAnnotation(i));
    }
    return items;
  };
...

 <MapboxGL.MapView
              style={styles.map}
              styleURL={mapStyle}
              ref={(node) => (ref._map = node)}
              // onDidFinishLoadingMap={_onDidFinishLoadingStyle}
            >
              <MapboxGL.Camera
                zoomLevel={11.7}
                centerCoordinate={CENTER_COORD}
              />
              {_renderAnnotations()}
            </MapboxGL.MapView>

**Screenshots**  
Android
[https://imgur.com/OorATOi](url)

IOS
[https://imgur.com/2adEKZM](url)

**Versions (please complete the following information):**  
 - Platform: [Android]
 - Platform OS: [Android 10, iOS 13.5]
 - Emulator/ Simulator: [yes]
 - Dev OS: [OSX 11.5.1]
 - react-native-mapbox-gl Version [8.1.0-rc.2]
 - Mapbox-iOS-SDK (5.9.0):
 - React Native Version [0.62.2]

**Additional context**  
It works fine on IOS devices but on ANDROID it only displays text, any suggestions?

**Comment by ferdicus** [comment]
can you please edit the issue ticket to a form that makes it more readable? Thanks

**Comment by ansarikhurshid786** [comment]
did you tried refresh method

**Comment by ombogdan** [comment]
same problem
