### ISSUE TITLE
centerCoordinate and flyTo does not work

### ISSUE THREAD

**Issue by buog** [rnmapbox/maps#1552]
Describe the bug
The map is intitially at [0,0] instead of the coordinate I set to. Also flyTo does not work.

```
<MapboxGL.MapView
          style={styles.map}
          pitchEnabled={false}
          rotateEnabled={false}>
          <MapboxGL.Camera
            zoomLevel={12}
            maxZoomLevel={16}
            animationMode={'flyTo'}
            animationDuration={1000}
            followUserLocation={true}
            logoEnabled={false}
            centerCoordinate={[49.2624218, -123.2583474]}
          />
</MapboxGL.MapView>
```

Versions (please complete the following information):
"react": "16.13.1",
"react-native": "0.63.4",
 "@react-native-mapbox-gl/maps": "^8.3.0",

**Comment by EyadAlghamdi** [comment]
I believe its because you have `followUserLocation` true? try to set it to `false` and see if it still doesnt center the location?
