### ISSUE TITLE
RN 0.66 Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0

### ISSUE THREAD

**Issue by gentlee** [rnmapbox/maps#1572]
**Describe the bug**  
After upgrading React Native from 0.63.4 to 0.66 android project does not compile, showing the error:

```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Required by:
         project :app > project :react-native-mapbox-gl_maps > com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0
```

**Versions (please complete the following information):**  
 - Platform: Android
 - Dev OS: macOS 11.6
 - react-native-mapbox-gl Version 8.3.0
 - React Native Version 0.66

**Comment by ferdicus** [comment]
notice, that this is probably just a temporary workaround as jcenter as a dep repo is no longer maintained indefinitely (some time 2022 I believe). 
I couldn't get it to work with `mavenCentral` unfortunately, although I believe, that mapbox did move their deps there 😕

**Comment by francistec** [comment]
> can you please try with:
> 
> `android/build.gradle`
> 
> ```groovy-gradle
> repositories {
>     // ...
>     jcenter()
> }
> ```

works for me, really thank you

**Comment by dacx** [comment]
jcenter() is no longer supported in new RN versions

**Comment by ryanjwessel** [comment]
`jcenter.bintray.com` is consistently returning error codes today. Because of that, we are removing `jcenter` from `build.gradle` to unblock Android builds locally. Doing so results in the error mentioned in this Issue's original description. 

```
> Could not resolve all files for configuration ':app:dataminrStagingDebugRuntimeClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
       - https://dl.google.com/dl/android/maven2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
       - https://www.jitpack.io/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
     Required by:
         project :app > project :react-native-mapbox-gl_maps > com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0
```

Despite the fact that [Jfrog says it will maintain it as read-only indefinitely](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), my team has seen issues where Jcenter + Bintray are unavailable which blocks any new Android builds. 

It would be beneficial to move these dependencies to an actively-maintained dependency repository, like `mavenCentral`, to avoid the potential pain caused by `jcenter`'s reliability diminishes over time.

**Comment by ryanjwessel** [comment]
I also saw [this Pull Request](https://github.com/rnmapbox/maps/pull/1712) that references the flakiness of `jcenter` in January of this year.

**Comment by NathanNovak** [comment]
We spent the majority of the morning trying to fix this issue.  Seems the conclusion was that jcenter was down and now it is back up.  We are using React-Native 0.64.1, because some dependencies have not yet updated, and jcenter was still kept on as read only.

**Comment by kooinam-ridebeam** [comment]
> `jcenter.bintray.com` is consistently returning error codes today. Because of that, we are removing `jcenter` from `build.gradle` to unblock Android builds locally. Doing so results in the error mentioned in this Issue's original description.
> 
> ```
> > Could not resolve all files for configuration ':app:dataminrStagingDebugRuntimeClasspath'.
>    > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
>      Searched in the following locations:
>        - https://repo.maven.apache.org/maven2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
>        - https://dl.google.com/dl/android/maven2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
>        - https://www.jitpack.io/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
>      Required by:
>          project :app > project :react-native-mapbox-gl_maps > com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0
> ```
> 
> Despite the fact that [Jfrog says it will maintain it as read-only indefinitely](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), my team has seen issues where Jcenter + Bintray are unavailable which blocks any new Android builds.
> 
> It would be beneficial to move these dependencies to an actively-maintained dependency repository, like `mavenCentral`, to avoid the potential pain caused by `jcenter`'s reliability diminishing over time.

Hi we're experiencing the same issue, are you able to resolve the issue by now?

**Comment by Bad-Listener** [comment]
Still not building...Any news or workaround? 


Thanks!

**Comment by Bad-Listener** [comment]
I confirm, it's the only way to build right now getting rid of jcenter dependencies. Thanks mate!

PS. Be aware to follow the process of issuing a download token, and everything should be fine!

**Comment by Dakuan** [comment]
I've followed these instructions to the letter but still no joy

**Comment by m7amad-7asan** [comment]
@Dakuan Did you find anyway to fix it ?
