### ISSUE TITLE
Can't trigger onPress for Pressable components positioned absolutely above map

### ISSUE THREAD

**Issue by 1mike12** [rnmapbox/maps#1595]
**Describe the bug**  
Any absolutely positioned item in the page cannot be pressed

**To Reproduce**  
Place any absolutely positioned pressable withing the map boundries

Example:
```js
import React from 'react';
import {
    MapView,
    ShapeSource,
    LineLayer,
    Camera,
} from '@react-native-mapbox-gl/maps';
import {Pressable, View, Text} from "react-native";

const aLine = {
    type: 'LineString',
    coordinates: [
        [-74.00597, 40.71427],
        [-74.00697, 40.71527],
    ],
};
const spacer = {height: 200}
const canClick = {position: "absolute", top: 10}
const cantClick = {position: "absolute", top: 300}
class BugReportExample extends React.Component {
    render() {
        return (
            <View>
                <View style={spacer}>
                    <View style={canClick}>
                        <Pressable onPress={()=> console.log("works")}>
                            <Text>can click since outside map</Text>
                        </Pressable>
                    </View>
                    <View style={cantClick}>
                        <Pressable onPress={()=> console.log("can't trigger this")}>
                            <Text>can click since outside map</Text>
                        </Pressable>
                    </View>
                </View>
                <MapView style={{flex: 1}}>
                    <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
                    <ShapeSource id="idStreetLayer" shape={aLine}>
                        <LineLayer id="idStreetLayer" />
                    </ShapeSource>
                </MapView>
            </View>
        );
    }
}
```

**Expected behavior**  
Pressables to work even if they are positioned above the map

**Actual behavior**  
Pressables can't be triggered if they lie within the map boundries

**Screenshots**  
Can't click any of the absolutely positioned results
![New Project (1)](https://user-images.githubusercontent.com/4983282/139280095-76db099f-d9ab-4db8-be79-89595a693ddc.jpg)

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 10
 - Device: Emulator, Oneplus 8T
 - Emulator/ Real device: both
 - Dev OS: OSX 11
 - react-native-mapbox-gl Version 8.4.0
 - Mapbox GL version ??
 - React Native Version: 0.66

**Additional context**  
Apparently there's bugs where pressable & absolute don't work in general, but here's what I've found from briefly testing:

* absolutely positioned items on the same page of the map, as long as they don't intersect work fine. 
* there are suggestions to wrap the pressable in fragments or other views. Niether of these work for me
* other suggestions to use Touchable Highlight dont work

**Comment by dorthwein** [comment]
I've run into this as well actually.  Very lost on root cause.  My guess is some lingering view isn't being unloaded on hot refreshes or something.
