### ISSUE TITLE
SIGSEGV Segmentation violation on Android

### ISSUE THREAD

**Issue by reyalpsirc** [rnmapbox/maps#1598]
**Describe the bug**  
We have a launched App which is reporting some Mapbox crashes from time to time, specially when the App is in use in background. When we also test the App, sometimes we also get the crash but it happens in a very random way which don't allow us to find a perfect way to reproduce it.

The crash showing on Bugsnag is from a tombstone and shows the following:

	SIGSEGV Segmentation violation (invalid memory reference) 
	    /data/app/com.imaginerun.imaginerun-MPKOMr6IOOZKaUjTGO8pGw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmapbox-gl.so:610772 0x72f33441d4
	    /data/app/com.imaginerun.imaginerun-MPKOMr6IOOZKaUjTGO8pGw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmapbox-gl.so:875904 0x72f3384d80
	    /data/app/com.imaginerun.imaginerun-MPKOMr6IOOZKaUjTGO8pGw==/oat/arm64/base.odex:1817088 0x7c57945a00

After symbolicating it, what we get is this:

	SIGSEGV Segmentation violation (invalid memory reference) 
	    libmapbox-gl std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::basic_string(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
	    libmapbox-gl _ZZN3jni16MakeNativeMethodIZNS_17NativeMethodMakerIMZNS_30NativePeerMemberFunctionMethodIMN4mbgl7android5LayerEFNS_6UniqueINS_6ObjectINS_9StringTagEEENS_17DefaultRefDeleterIXadL_ZN7_JNIEnv14DeleteLocalRefEP8_jobjectEEEEEERSB_EXadL_ZNS5_5getIdESG_EEEclIS5_S5_vEEDaRKNS_5FieldIT0_lEEEUlSG_RNS7_IS5_EEE_KFSF_SG_SR_EJEEclISS_EEDaPKcRKT_EUlPSB_PNS_7jobjectEE_EEDaSY_SY_S11_PNSt6__ndk19enable_ifIXsr3std8is_classISZ_EE5valueEvE4typeEENUlTyS12_DpT_E_8__invokeIJS14_EEEDaS12_S1C_
	    /data/app/~~nN2B4AZdnlc6tsb4squB1A==/com.imaginerun.imaginerun-pq4atDagtpquJBYR0D3z2Q==/oat/arm64/base.odex:1198592 0x789087ba00

Since this is a hard bug to replicate (because sometimes happens after 5-10 minutes but other times it takes hours and there's even plenty of times that it doesn't happen at all), I would like to know at least if there's a better way to track it down and help the community on how to identify its cause

I post this here and not on the Android lib directly because in the end, we are using react-native-mapbox-gl on our project and we don't know if the cause of this is linked to the implementation of the native library here or not

**To Reproduce**  
Unfortunately like I said above, this random happens a bit random and to +/- 15% of our users. The only clue we have is that it happens only on Android and mostly when our App is in use in background (since it is a walking/running activity tracker App)

**Expected behavior**  
The App should not crash while the user is doing an activity either if it is in Foreground or Background and specially not in a random way. Or at least we should have a better crash log of the reason, since the presented screen is always the same and we can't identify what's being released from memory without our knowledge.

**Actual behavior**  
Like said above, our published App crash on Android in a random way when doing a walking/running activity (mostly when the app is in Background but also happens sometimes with the App in Foreground)

**Screenshots**  
This is a screenshot of the content on the screen when the App crashes:
![Screenshot_20211029_094605_com imaginerun imaginerun test](https://user-images.githubusercontent.com/5243311/139405298-45f6fb5c-a3d6-4e11-aa39-6358aa2fe1df.jpg)

**Versions:**  
 - Platform: Android
 - Platform OS: From 7 to 11 at least
 - Device: Any
 - Emulator/ Simulator: Difficult to test due to the need to GPS usage
 - Dev OS: OSX 11.6
 - react-native-mapbox-gl Version: 8.2.1
 - Mapbox GL version: 9.6.1 and 9.6.2 (tested both)
 - React Native Version 0.61.5

**Comment by mfazekas** [comment]
I'm closing this, pls reopen if you have more information

**Comment by reyalpsirc** [comment]
@mfazekas how can I look for more information to give you knowing that only some Android users of our App reported the crashes? Is there some other kind of log that I can check for and send here?

**Comment by mfazekas** [comment]
@reyalpsirc sorry I don't really have concrete tips for that. Some bug report tools collect breadcrumbs. You can make theories where the crash is, and add breadcrumbs to confirm/deny the theory. Sorry, I understand that it's a hard problem, but even if we had resources we could not figure out such issue without steps to reproduce. (Not that we have resources)
