### ISSUE TITLE
Unable to resolve module ...resolveAssetSource.js.... #1624

### ISSUE THREAD

**Issue by moldender** [rnmapbox/maps#1625]
Hi guys!

I wanted to make a demo like thing with this package on snack.expo.dev but i'm always getting this error: 
```
Unable to resolve module 'react-native/Libraries/Image/resolveAssetSource.js'
  Evaluating react-native/Libraries/Image/resolveAssetSource.js
  Evaluating @react-native-mapbox-gl/maps.js
  Evaluating App.js
  Loading App.js
```

is there any way that i can use `react-native-mapbox-gl` in expo? Used with the latest versions

```
"@react-native-mapbox-gl/maps": "*"
"prop-types": "*"
```

**Comment by mfazekas** [comment]
We don't support redeeming in the web at the moment
