### ISSUE TITLE
Pod installing yields different Podfile.lock spec checksum

### ISSUE THREAD

**Issue by antonigiske** [rnmapbox/maps#1628]
In our team we started out with two different keys in the .netrc file. That created a a lot of merge conflicts because of Podfile.lock spec checksum diff. So we got the whole team using the same credentials in the .netrc file. Unfortunately the issue still persist with. Prior to using the .netrc file we had no issues.

![image](https://user-images.githubusercontent.com/271969/141104262-9375805f-a9fd-41c4-9d46-5a44ed4e7bd9.png)

It messes up our fastlane builds and is really annoying at this point and we can't seem to figure out how and where this is cached, if that is even the problem.

If anyone have any idea why this is happening that would be amazing, thanks.

Quick edit: 
We've tried deleting the Pods/ directory, `pod cache clean --all`, removing derived data, cloned a fresh project, made sure we are on the same versions etc. We're really out of ideas here.

**Comment by mfazekas** [comment]
A potential workaround could be using SwiftPackageManager to consume the Mapbox SDK.

In current main it's 
```ruby
$RNMapboxMapsSwiftPackageManager = {
url: "https://github.com/mapbox/mapbox-maps-ios.git",
      requirement: {
        kind: "exactVersion",
        version: "10.3.0",
      },
      product_name: "Mapbox"
}
```
