### ISSUE TITLE
Not being able to open the 'RCTMGL.xcodeproj' project

### ISSUE THREAD

**Issue by DimmyMaenhout** [rnmapbox/maps#1646]
**Describe the bug**  
When trying to open the 'RCTMGL.xcodeproj' you get the error that the project cannot be opened due to parse errors

**To Reproduce**  
Download the repo, go to the iOS folder and click on 'RCTMGL.xcodeproj'

**Expected behavior**  
Being able to open the RCTMGL.xcodeproj 

**Actual behavior**  
Showing a pop up with the error "The project 'RCTMGL' is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts."

**Versions (please complete the following information):**  
 - Platform: [iOS]
 - Dev OS: [e.g. OSX 11.6.1]

**Comment by janeviceral08** [comment]
I experience same problem did you already find a solution?

**Comment by mfazekas** [comment]
You don't need the RCTMGL.xcodeproj, it was for pre CocoaPods ReactNative integration we don't support any more
