### ISSUE TITLE
MapView not generating TouchEnd events

### ISSUE THREAD

**Issue by trevorarmstrong** [rnmapbox/maps#1667]
With the following snippet I only get a touch start and a single touch move and no touch end events. If I delete the MapView my View gets the expects 1 start, N move, and 1 end events. Is there a better way to know when a touch interaction is complete? 

```
      <View 
        onTouchMove={() => {
          console.log("VIEW TOUCH MOVE");
        }}
        onTouchEnd={() => {
          console.log("VIEW TOUCH END");
        }}
        onTouchStart={() => {
          console.log("VIEW TOUCH START");
        }}
        style={{
          height: '100%',
          width: '100%',
        }}>
        <MapboxGL.MapView
          style={{
              flex: 1,
            }}
          onTouchMove={() => {
            console.log("MAPBOX TOUCH MOVE");
          }}
          onTouchEnd={() => {
            console.log("MAPBOX TOUCH END");
          }}
          onTouchStart={() => {
            console.log("MAPBOX TOUCH START");
          }}>
        </MapboxGL.MapView>
      </View>
```

**Comment by timdemeyer** [comment]
The Mapview has an "onRegionDidChange" event which is fired when you drag and release, if that's what you're looking for? https://github.com/rnmapbox/maps/blob/main/docs/MapView.md

**Comment by mfazekas** [comment]
I'm closing this. If it's still an issue explain, please explain the use case in more details

**Comment by lgspacil** [comment]
I am also experiencing these same issues but on iOS only. The use case is to add drawing capabilities to to mapbox. I can not use onRegionDidChange since I want to lock the map while moving an edge of a polygon.
