### ISSUE TITLE
How can I use the onpress event for layers added from Mapbox studio?

### ISSUE THREAD

**Issue by BerkayAkgurgen** [rnmapbox/maps#1687]
I create my layers in mapbox studio. But I cannot access their properties by assigning the onpress event to these layers. How can I achieve this?

**Comment by RNaoki** [comment]
Any updates on this?

**Comment by BerkayAkgurgen** [comment]
> Any updates on this?

I solved it by using the tileset I loaded from Mapbox in "shapesource" and assigning the onPress event to it.

**Comment by RNaoki** [comment]
> > Any updates on this?
> 
> I solved it by using the tileset I loaded from Mapbox in "vectorsource" and assigning the onPress event to it.
> 
> ```
>  <MapboxGL.VectorSource
>             id="example"
>             url={MAPBOX_TILESET_URL}
>             onPress={touchPoint}
>           >
>             <MapboxGL.CircleLayer
>               id={MAPBOX_TILESET_ID}
>               sourceLayerID={MAPBOX_TILESET_ID}
>             />
>           </MapboxGL.VectorSource>
> ```

So I can't get them from the studio?

**Comment by tkulpa** [comment]
> > > > Any updates on this?
> > > 
> > > 
> > > I solved it by using the tileset I loaded from Mapbox in "vectorsource" and assigning the onPress event to it.
> > > ```
> > >  <MapboxGL.VectorSource
> > >             id="example"
> > >             url={MAPBOX_TILESET_URL}
> > >             onPress={touchPoint}
> > >           >
> > >             <MapboxGL.CircleLayer
> > >               id={MAPBOX_TILESET_ID}
> > >               sourceLayerID={MAPBOX_TILESET_ID}
> > >             />
> > >           </MapboxGL.VectorSource>
> > > ```
> > 
> > 
> > So I can't get them from the studio?
> 
> No, you can just get tilesets.

Code above dosen't seem to work, still I'm not sure what is `MAPBOX_TILESET_URL` as tilesets don't have url in mapbox studio, only ids

**Comment by BerkayAkgurgen** [comment]
> > > > > Any updates on this?
> > > > 
> > > > 
> > > > I solved it by using the tileset I loaded from Mapbox in "vectorsource" and assigning the onPress event to it.
> > > > ```
> > > >  <MapboxGL.VectorSource
> > > >             id="example"
> > > >             url={MAPBOX_TILESET_URL}
> > > >             onPress={touchPoint}
> > > >           >
> > > >             <MapboxGL.CircleLayer
> > > >               id={MAPBOX_TILESET_ID}
> > > >               sourceLayerID={MAPBOX_TILESET_ID}
> > > >             />
> > > >           </MapboxGL.VectorSource>
> > > > ```
> > > 
> > > 
> > > So I can't get them from the studio?
> > 
> > 
> > No, you can just get tilesets.
> 
> Code above dosen't seem to work, still I'm not sure what is `MAPBOX_TILESET_URL` as tilesets don't have url in mapbox studio, only ids

You can checkout how can you find your tileset url; https://docs.mapbox.com/mapbox-gl-js/example/vector-source/

**Comment by tkulpa** [comment]
I got this code:
```
        <Mapbox.MapView
          ref={mapRef}
          styleURL='mapbox://styles/tkulpa/clxwwnqkx00iv01r08fg79dey/draft'
          style={styles.map}
        >
          <Mapbox.Camera defaultSettings={{
            centerCoordinate: [12.568337, 55.676098],
            zoomLevel: 9
          }} />
          {/* FROM https://github.com/rnmapbox/maps/issues/1687 */}
          <Mapbox.VectorSource
            url="mapbox://tkulpa.clxulacvx1gus1tnirps5zq53-6msg4"
            existing
            onPress={() => console.log('WORKS')}
          >
            <Mapbox.CircleLayer
              id="tkulpa.clxulacvx1gus1tnirps5zq53-6msg4"
              sourceLayerID="tkulpa.clxulacvx1gus1tnirps5zq53-6msg4"
            />
          </Mapbox.VectorSource>
        </Mapbox.MapView>
```
And this dosen't seem to work, followed link that you sent and I cannot track user interactions on my own style using VectorSource. I tried to use `existing` property both on `VectorSource` and `CircleLayer` but without luck

![image](https://github.com/rnmapbox/maps/assets/18174866/76d3b61a-b645-4ae7-a0a3-5c53a5a589c0)
