### ISSUE TITLE
How to show offline maps ? download completed successfully but how to display in offline mode using asyncstorage

### ISSUE THREAD

**Issue by sabarikobagapau** [rnmapbox/maps#1691]
How to display downloaded offline maps ? 

class offlineMap extends React.Component {

constructor(props) {
super(props);

this.state = {
  name: `test-${Date.now()}`,
  offlineRegion: null,
  offlineRegionStatus: null,
};

this.onDownloadProgress = this.onDownloadProgress.bind(this);
this.onDidFinishLoadingStyle = this.onDidFinishLoadingStyle.bind(this);
}

componentWillUnmount() {
// avoid setState warnings if we back out before we finishing downloading
MapboxGL.offlineManager.deletePack(this.state.name);
MapboxGL.offlineManager.unsubscribe('test');
}

async onDidFinishLoadingStyle() {

const options = {
  name: this.state.name,
  styleURL: MapboxGL.StyleURL.Street,
  bounds: [
  [-84.589219, 38.046448],
    [-84.62574, 38.021028],
  ],
  minZoom: 10,
  maxZoom: 20,
};

// start download
MapboxGL.offlineManager.createPack(options, this.onDownloadProgress);
}

onDownloadProgress(offlineRegion, offlineRegionStatus) {
this.setState({
name: offlineRegion.name,
offlineRegion,
offlineRegionStatus,
});
}

render() {

return (
  <View>
    <MapboxGL.MapView
      ref={c => (this._map = c)}
      onPress={this.onPress}
      onDidFinishLoadingMap={this.onDidFinishLoadingStyle}
      style={{flex:1}>
      <MapboxGL.Camera zoomLevel={10} centerCoordinate={ [-84.589219, 38.046448]} />
    </MapboxGL.MapView>

    </View>
);
}
}

export default CreateOfflineRegion;

**Versions (please complete the following information):**  
 - Platform: [e.g. Android, iOS]
 - Platform OS: [ Android 11, iOS 14]
 - Device: [iPhone11]
 - Emulator/ Simulator: [simulaotor]
 - Dev OS: [Bigsur Macos, Win10]
 - react-native-mapbox-gl Version [8.1.0]
 - React Native Version [0.63.4]

**Additional context**

**Comment by Faarookh** [comment]
same issue here

**Comment by monuv10** [comment]
Any update??
