### ISSUE TITLE
Nesting layer within a custom component leads to silent bug.

### ISSUE THREAD

**Issue by cglacet** [rnmapbox/maps#1700]
I retrieved an old code of mine and something that used to work in older version doesn't seem to work anymore. 

I try defining a custom component that returns one (or several) symbol layers, but the layers never show. On the other hand when the layer is included directly under the shape component it does work.

Here is an example in which the same layer is used to draw 3 concentric circles (blue, green and red). The green circle is encapsulated in a sub-component which highlights the bug.

Versions used: 

```
"react": "^17.0.1",
"react-native": "0.63.3",
"@react-native-mapbox-gl/maps": "8.5.0",
```

The code: 

```
import React from 'react';
import Mapbox from '@react-native-mapbox-gl/maps';
import {point } from '@turf/helpers';

const mapboxToken = 'pk.xxx';
Mapbox.setAccessToken(mapboxToken);

const coord = [0, 45];

export default function App() {
    return (
      <Mapbox.MapView style={{flex: 1}}>
        <Mapbox.Camera centerCoordinate={coord} zoomLevel={14} />
        <Mapbox.ShapeSource id="test shape" shape={point(coord)}>
            <Mapbox.CircleLayer
                 id={'blue'}
                style={{'circleColor': 'blue', 'circleRadius': 50}}
            />
            <Green/>
            <Mapbox.CircleLayer
                id={'red'}
                style={{'circleColor': 'red', 'circleRadius': 20}}
            />
        </Mapbox.ShapeSource>
        
      </Mapbox.MapView>
    );
}

function Green() {
    return <Mapbox.CircleLayer
        id={'green'}
        style={{'circleColor': 'green', 'circleRadius': 40}}
    />;
}
```

What it displays (both Android and iOS):

<img width="281" alt="Screenshot 2022-01-12 at 15 41 55" src="https://user-images.githubusercontent.com/28622118/149161599-e279ab94-c35e-49e4-b5f4-dc04c959400c.png">

The expected result is: 

<img width="226" alt="Screenshot 2022-01-12 at 15 50 53" src="https://user-images.githubusercontent.com/28622118/149163269-cb544b9c-4f3c-4399-b8bf-c0cd92908fd1.png">

Any idea how to deal with this? (I would like avoiding rewriting the existing code if possible). 

This also happens with SymbolLayer, I haven't tested more layers, but I guess it happens too.

**Comment by ludvigeriksson** [comment]
Does it work if you put `sourceID="test shape"` on the nested CircleLayer?

**Comment by cglacet** [comment]
@ludvigeriksson yes it works, thanks! 

I feel like this should be explained somewhere because it's not intuitive. Maybe in the README directly? Or maybe I'm just the only one wanting to separate layers from shape sources.

**Comment by ludvigeriksson** [comment]
I agree, I spent quite some time debugging this as well. As soon as a layer isn't a direct child of the source (a Fragment is enough) you have to specify the source ID. This seems weird, I would have assumed React contexts were used to pass down the source ID automatically.

**Comment by ferdicus** [comment]
guys, feel free to add a screen to the `/example` app 👍🏿

**Comment by ludvigeriksson** [comment]
@ferdicus Perhaps a clarification like this could be beneficial? #1718
