### ISSUE TITLE
React-native Android build fails with:   Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1.

### ISSUE THREAD

**Issue by crayne** [rnmapbox/maps#1711]
**Describe the bug**

I have a very basic react-native app that builds and runs perfectly in iOS.  When I build it in Android Studio, the result is:
```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1.
     Required by:
         project :app > project :react-native-mapbox-gl_maps
      > Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-sdk/9.7.1/mapbox-android-sdk-9.7.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-sdk/9.7.1/mapbox-android-sdk-9.7.1.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.14.0.
     Required by:
         project :app > project :react-native-mapbox-gl_maps
      > Could not resolve com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.14.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-plugin-localization-v9/0.14.0/mapbox-android-plugin-localization-v9-0.14.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-plugin-localization-v9/0.14.0/mapbox-android-plugin-localization-v9-0.14.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1.
     Required by:
         project :app > project :react-native-mapbox-gl_maps > com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0
         project :app > project :react-native-mapbox-gl_maps > com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0
      > Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-sdk/9.7.1/mapbox-android-sdk-9.7.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-sdk/9.7.1/mapbox-android-sdk-9.7.1.pom'. Received status code 403 from server: Forbidden
```
The build.gradle file is: 
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
        rnmbglMapboxLibs = {
            implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1'
            implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.8.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.8.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0'
        }

        rnmbglMapboxPlugins = {
            implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.14.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0'
        }
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        maven { url 'https://www.jitpack.io' }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = 'token removed'
            }
        }
    }
}
```

**Versions (please complete the following information):**

- Platform: Android
- Dev OS: macOS 12.0.1
- react-native-mapbox-gl Version 8.50
- React Native Version 0.66

**Comment by ferdicus** [comment]
hi there, 
which version of the native android sdk are you using?

**Comment by crayne** [comment]
Hi,
Android 10.0 (Q) and Android R Preview are installed

**Comment by joshua-smith4** [comment]
This issue may be due to jcenter being flakey recently. Does adding mavenCentral to the android/build.gradle in your node_modules/@react-native-mapboxgl/maps/android/build.gradle fix the issue?

**Comment by crayne** [comment]
I did try this and unfortunately it did not solve the problem.

**Comment by simonbuerger** [comment]
jcenter is beyond flakey at this point I'm afraid. It is deprecated, read-only and entirely unusable for anything production with a CI/CD pipeline as there also seems to be some kind of rate limiting on it now

**Comment by crayne** [comment]
Can you suggest a workaround?  Would it be possible to put the libraries directly on the device?  It looks like you have done this in the example app. If this is possible, some guidance would be much appreciated.
Shameless appeal to emotions:  I am with AccesSOS.  We are creating a mobile app for both iOS and Android to help people who cannot listen and/or speak, to communicate with 911 using text instead of voice.  Mapbox does a beautiful job  when we run our app on iOS (thank you!) but we obviously can't even get started with Android.

**Comment by ferdicus** [comment]
can you simply try again today please - jcenter was down, however should be up again

**Comment by crayne** [comment]
I just tried, but no joy

**Comment by ferdicus** [comment]
Maybe it's something with your credentials - did you make sure to follow the install guide? 
Did you try building the `/example` app ?

**Comment by ferdicus** [comment]
the `example` app only gets the dependency for _this_ repo - instead of installing it via `npm` into the `node_modules` folder. 

All native dependencies, be it for iOS or Android, are downloaded separately.

**Comment by crayne** [comment]
I copied the build.gradle from the mapbox example to my sample app build.gradle, and then my sample app worked with a few tweeks.  Specifically, I had to change the minSDK to 26, and in ReactNativeFlipper.java, I had to change the variable "networkFlipperPlugin" to final.  Now I will test my actual app. Thank you for your help.

**Comment by crayne** [comment]
Now I'm having an issue with the build of the AccesSOS app. I looked at the app-level build.gradle in your example and saw that there weren't any implementation statements for mapbox libraries.  So I removed them from my app-level build.gradle.  I am seeing this message:
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.core:core-splashscreen:1.0.0-alpha02.
     AAR metadata file: /Users/susancrayne/.gradle/caches/transforms-3/08eb6edeab90a26e4ff7596cf24fe72e/transformed/jetified-core-splashscreen-1.0.0-alpha02/META-INF/com/android/build/gradle/aar-metadata.properties.
```

**Comment by crayne** [comment]
Today I ran the same build of my sample app and it failed.  Yesterday it succeeded.  I assume that means that jcenter is down.  Is there a way I can check if it's up without doing a build?

**Comment by jarto666** [comment]
I am observing the same issue with a new project which by default uses mavenCentral (since jcenter is deprecated). I must say that old project, built for sdk 26 and jcenter still works.

**Comment by jarto666** [comment]
@crayne Try following this page. You have to setup access key now in buid.gradle it seems
https://github.com/react-native-mapbox-gl/maps/blob/master/android/install.md

**Comment by crayne** [comment]
Thank you. I am actually able to build now without that.  But I'm having trouble running the app now -- I might try putting it back.

**Comment by codydaig** [comment]
I think I am having similar issues where I can't get dependencies from bintray. The build consistently fails and has failed for the past month for me all related to bintray. I haven't tried the example directly as that won't do me much good. I have used the build.gradle with no luck. It's trying to pull in dependencies from bintray and bintray is unaccessible for me and has been for a while. Any advice?

**Comment by Arnaod** [comment]
Anyone succeded in building an app on Android with MapBox ?
We've been stuck on this issue for a few weeks, seems odd to me that it can't be built.
