### ISSUE TITLE
android/install.md outdated instructions for MapLibre

### ISSUE THREAD

**Issue by Themis3000** [rnmapbox/maps#1721]
The install.md file suggests you add the following to your `android/build.gradle` file:

```
allprojects {
    repositories {
        // ...
        maven {
            url = "https://dl.bintray.com/maplibre/maplibre-gl-native"
        }
    }
}
```

bintray.com is shutting down permanently now though, and `https://dl.bintray.com/maplibre/maplibre-gl-native` returns a 502 error.

How do I use this library with MapLibre? I can't seem to find any updated instructions for it.

Edit: the install.md file I'm referring to as being outdated in this issue is here: https://github.com/react-native-mapbox-gl/maps/blob/master/android/install.md

**Comment by BelyaninD** [comment]
@Themis3000 
https://github.com/maplibre/maplibre-gl-native/blob/master/README.md#android

```gradle
        allprojects {
            repositories {
                ...
                mavenCentral()                
            }
        }
```
> Note: [Bintray was turn off May 1st, 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) so we migrated all packages to maven central.

**Comment by Themis3000** [comment]
@BelyaninD I see, thank you for directing me to that.

I'm pretty new to working with .gradle files though so I don't think I'm totally understanding the instructions maybe. I tried placing `mavenCentral()` inside the `allprojects > repositories` scope inside `android/build.gradle`, but I got and error saying `> Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.`

I checked the link and saw there was the extra instruction saying to place `implementation 'org.maplibre.gl:android-sdk:9.4.0'` in the `dependencies` scope in "your module build.gradle". What exactly does "your module build.grade" mean? I assumed it meant `android/app/build.gradle`, but placing in the `dependencies` there yielded a lot of build errors. Where do I place `implementation 'org.maplibre.gl:android-sdk:9.4.0'` exactly?

Thank you for your help.

**Comment by tomarsnap** [comment]
It seems react-native-mapbox-gl doesn't support maplibre 9.4.0. It will work if you add 9.2.1. But then you have to fix a [telemetry bug](https://github.com/mapbox/mapbox-gl-native-android/issues/425) by adding another line there. It should look like this:
```
buildscript {
    ext {
        ...
        useMapLibre = true

        if (useMapLibre) {
            rnmbglMapboxLibs = {
                implementation ("org.maplibre.gl:android-sdk:9.2.1")
                implementation ("com.mapbox.mapboxsdk:mapbox-android-telemetry:6.2.2")
                implementation ("com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0")
            }

            rnmbglMapboxPlugins = {
                implementation ("com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0")
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0")    {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0")        {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0") {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
            }
        }
    }
```
and in allprojects:
```
allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        ...
```

**Comment by Themis3000** [comment]
> It seems react-native-mapbox-gl doesn't support maplibre 9.4.0. It will work if you add 9.2.1. But then you have to fix a [telemetry bug](https://github.com/mapbox/mapbox-gl-native-android/issues/425) by adding another line there. It should look like this:
> 
> ```
> buildscript {
>     ext {
>         ...
>         useMapLibre = true
> 
>         if (useMapLibre) {
>             rnmbglMapboxLibs = {
>                 implementation ("org.maplibre.gl:android-sdk:9.2.1")
>                 implementation ("com.mapbox.mapboxsdk:mapbox-android-telemetry:6.2.2")
>                 implementation ("com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0")
>             }
> 
>             rnmbglMapboxPlugins = {
>                 implementation ("com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0")
>                 implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0")    {
>                     exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
>                 }
>                 implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0")        {
>                     exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
>                 }
>                 implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0") {
>                     exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
>                 }
>             }
>         }
>     }
> ```
> 
> and in allprojects:
> 
> ```
> allprojects {
>     repositories {
>         mavenCentral()
>         mavenLocal()
>         ...
> ```

Thanks for the response. For some reason it doesn't seem to be working out for me though. I'm getting a bunch of errors that look like this:

```
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/mapbox/mapboxsdk/mapbox-sdk-turf/5.3.0/mapbox-sdk-turf-5.3.0.pom
       - file:/C:/Users/(my username)/.m2/repository/com/mapbox/mapboxsdk/mapbox-sdk-turf/5.3.0/mapbox-sdk-turf-5.3.0.pom
       - file:/D:/webstorm/(my project dir)/node_modules/react-native/android/com/mapbox/mapboxsdk/mapbox-sdk-turf/5.3.0/mapbox-sdk-turf-5.3.0.pom
       - file:/D:/webstorm/(my project dir)/node_modules/jsc-android/dist/com/mapbox/mapboxsdk/mapbox-sdk-turf/5.3.0/mapbox-sdk-turf-5.3.0.pom
       - https://dl.google.com/dl/android/maven2/com/mapbox/mapboxsdk/mapbox-sdk-turf/5.3.0/mapbox-sdk-turf-5.3.0.pom
       - https://www.jitpack.io/com/mapbox/mapboxsdk/mapbox-sdk-turf/5.3.0/mapbox-sdk-turf-5.3.0.pom
     Required by:
         project :app > project :react-native-mapbox-gl_maps
         project :app > project :react-native-mapbox-gl_maps > org.maplibre.gl:android-sdk:9.2.1
```

Here's what my android/build.gradle looks like:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"

        useMapLibre = true

        if (useMapLibre) {
            rnmbglMapboxLibs = {
                implementation ("org.maplibre.gl:android-sdk:9.2.1")
                implementation ("com.mapbox.mapboxsdk:mapbox-android-telemetry:6.2.2")
                implementation ("com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0")
            }

            rnmbglMapboxPlugins = {
                implementation ("com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0")
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0")    {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0")        {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0") {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
            }
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}
```

Is their anything wrong with my build.gradle or any outside configuration I have to do outside of that file?

**Comment by mfazekas** [comment]
Can you test the new main?! 

See Maplibre install instructions: https://github.com/rnmapbox/maps/blob/main/android/install.md

**Comment by Themis3000** [comment]
> Can you test the new main?!
> 
> See Maplibre install instructions: https://github.com/rnmapbox/maps/blob/main/android/install.md

Hey - sorry I'm not in a place right now where I have time to build and test it. I'll let you know if I test it in the future or if the change is part of a future release I'll test it out.
