### ISSUE TITLE
Unable to render text in a SymbolLayer while using map in offline mode

### ISSUE THREAD

**Issue by josh-cohen-rm** [rnmapbox/maps#1734]
**Describe the bug**  
I am unable to render text in a SymbolLayer while using the map in offline mode if I have not already opened Mapbox before in the app. I am receiving error "Failed to load glyph range 0-255 for font stack Open Sans Bold,Arial Unicode". I am unable to render text in a SymbolLayer in offline mode. My guess is that the OfflineManager is not downloading glyphs for specified styles.

**To Reproduce**  
**Context**
I have been able to successfully view a map in offline mode by creating offline packs with various styleUrls.

  let packStyleUrl = 'mapbox://styles/mapbox/dark-v10';
  // packStyleUrl = mapbox://styles/mapbox/light-v10
  // packStyleUrl = mapbox://styles/mapbox/satellite-v9
  await MapboxGL.offlineManager.createPack({
      name: packId,
      styleURL: packStyleUrl,
      minZoom: 14,
      maxZoom: 22,
      bounds: bounds
    }, progressListener, errorListener)

In my map, I have a symbol layer for rendering some text on the map:
<MapboxGL.SymbolLayer id={'layer_id'} style={myStyle}/>

When I attempt to render the map in offline mode if I have not , my symbol layer does not display. I see the "Failed to load glyph" error in my console.

*** Standalone react Component
```js
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
  SymbolLayer
} from '@react-native-mapbox-gl/maps';

class BugReportExample extends React.Component {
  const CENTER_COORDINATE = [-71.416555631,42.662938497];

  const TEXT_SHAPE = {
    'type':'Feature',
    'properties':{},
    'geometry':{
      'type':'Point',
      'coordinates':CENTER_COORDINATE
    }
  };

  render() {
    return (
      <MapView style={{flex: 1}}>
        <MapboxGL.ShapeSource
          id={`my_shape_id`}
          shape={TEXT_SHAPE}
        >
          <MapboxGL.SymbolLayer id={`my_id`} style={{ textField: 'glyph_downloader_text' }}/>
        </MapboxGL.ShapeSource>
      </MapView>
    );
  }
}
```

**Expected behavior**  
When I view the map in offline mode and I haven't opened mapbox before, I expect to see symbol layer text. See text 'Row 1,1'
![IMG_7008](https://user-images.githubusercontent.com/97318865/152417149-e77bf565-e5be-4c82-a8d2-d67e680eccc7.PNG)

**Actual behavior**  
When I view the map in offline mode and I haven't opened mapbox before, I see no symbol layer text.

![IMG_7009](https://user-images.githubusercontent.com/97318865/152417077-0066b08d-4bcb-4159-805a-a21b65b9c0b6.PNG)

**Versions (please complete the following information):**  
 - Platform: iOS, Android
 - Platform OS: all
 - Device: all
 - Emulator/ Simulator: also repros on simulator
 - Dev OS: all
 - react-native-mapbox-gl Version [e.g. 8.1.0

**Additional Debugging**  
To verify that I am using a style which DOES have an appropriate font stack, I tried this process with a manual style.

I manually created a style in Mapbox Studio which I know has font 'DIN Pro Regular'. I then used this style when downloading my offline pack, by specifying styleUrl 'mapbox://styles/josh-cohen-rm/ckyampo5e02co14o7tjvb06y2'. I updated my SymbolLayer to use font "DIN Pro Regular'. I verified in the progressListener that offline tiles were downloaded. However, when I navigate to the map, I see error 'Failed to load glyph range 0-255 for font stack DIN Pro Regular'.

**Additional Context**
Worth noting that once I've opened Mapbox once before, in all future offline sessions I have no issue rendering text in a symbol layer. Seems likely that Mapbox fetches the necessary glyph range when mapbox is opened and caches it for future use. The issue seems to be that OfflineManager will not download this glyph range.

It seems that SymbolLayers require extra precaution in offline mode -- I see a callout in the Mapbox offline mode documentation indicating:

"When adding symbol layers to an existing map with the Mapbox Maps SDKs for iOS and Android, you will need to take additional precautions for them to be visible offline:" (https://docs.mapbox.com/help/troubleshooting/mobile-offline/#working-with-offline-maps)

However, my understanding is that I have downloaded appropriate style packs, so I should be able to see text!

**Thank you in advance for your help!**

**Comment by bryanboyko** [comment]
@josh-cohen-rm were you able to find a solution? I believe i have correctly downloaded my style pack and I'm getting the following error when the downloaded region is showing while offline

```
 ERROR  Mapbox error MapLoad error Failed to load glyphs:  {"level": "error", "message": "MapLoad error Failed to load glyphs: "}
```

**Comment by josh-cohen-rm** [comment]
@bryanboyko I wasn't able to find a clean solution to download glyphs for offline use, so I introduced a hack that worked for my use case.

I noticed that if I displayed a map with text once, Mapbox wouldn't have issues displaying glyphs in the future, even after cold start. Seems like Mapbox caches glyph ranges locally.

My hack was to show an invisible mapbox map with text on the download page. Solution:
```
/**
 * GlyphDownloader is an invisible component which handles downloading
 * Mapbox glyph ranges necessary to display SymbolLayers with text on
 * the map in offline mode.
 *
 * This is a hack to compensate for an issue where the Mapbox offline
 * manager does not download glyph ranges for a style by default. Issue
 * outlined here: https://github.com/react-native-mapbox-gl/maps/issues/1734
 * By displaying an invisible mapbox map with a SymbolLayer at an arbitrary coordinate,
 * we can force Mapbox to download glyph ranges necessary to display SymbolLayers
 * with text.
 */
const GlyphDownloader = () => {

  initMapboxErrorHandling();

  const CENTER_COORDINATE = [-71.416555631,42.662938497];

  const TEXT_SHAPE = {
    'type':'Feature',
    'properties':{},
    'geometry':{
      'type':'Point',
      'coordinates':CENTER_COORDINATE
    }
  };

  return (
    <MapboxGL.MapView
      style={{ left: 0, top: 0, height: 50, width: 50, zIndex: -1, position: 'absolute', opacity: 0}}
    >
      <MapboxGL.Camera
        centerCoordinate={CENTER_COORDINATE}
      />
      <MapboxGL.ShapeSource
        id={'glyph_downloader_shape_id'}
        shape={TEXT_SHAPE}
      >
        <MapboxGL.SymbolLayer
          id={'glyph_downloader_layer_id'}
          style={{ textField: 'glyph_downloader_text' }}
        />
      </MapboxGL.ShapeSource>
    </MapboxGL.MapView>
  );
};

export default GlyphDownloader;
```
