### ISSUE TITLE
ShapeSource onPress not being triggered on iOS devices and emulator.

### ISSUE THREAD

**Issue by RNaoki** [rnmapbox/maps#1746]
Description:
ShapeSource element not triggering onPress from iOS devices, only on android.

To Reproduce
```<View style={{ flex: 1 }}>
      <MapboxGL.MapView
        style={{ flex: 1 }}
        styleURL={STYLE_URL}
        compassEnabled={true}
        ref={map}
      >
        <MapboxGL.Camera zoomLevel={mapZoom} centerCoordinate={coordinates} />
        <MapboxGL.ShapeSource
          onPress={(e) => {
            console.log(e);
          }}
        />
      </MapboxGL.MapView>
    </View>
```
Simple screen with only a styled map with tilesets added to it via studio, and add a ShapeSource element and a onPress(e) => console.log(e), on android it returns the json with the tileset info on it, but on iOS it does not even trigger it.

Expected behavior
When user presses the map, return a json with the layer information.

Actual behavior
On iOS is not triggered the onPress, but on android does.

 - Platform: iOS
 - Platform OS:  iOS
 - Device: iPhone 8
 - Emulator/ Simulator: yes
 - react-native-mapbox-gl Version [e.g. 7.0.9]
 - Mapbox GL version: 8.3.0
 - React Native Version: 0.65.1

**Comment by mwmcode** [comment]
@RNaoki did you manage to get around this issue?
