### ISSUE TITLE
Compass not rendering on android

### ISSUE THREAD

**Issue by Artotim** [rnmapbox/maps#1759]
**Describe the bug**  
The compass that is supposed to appear during rotation of the map it's not rendering (android).

**To Reproduce**  
Followed the instructions from [install.md](https://github.com/react-native-mapbox-gl/maps/blob/b73056fc868faf0a4a9ce7e1ab818bc2a83303dd/android/install.md)

With versions:

        rnmbglMapboxLibs = {
            implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1'
            implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.8.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.8.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0'
        }

        rnmbglMapboxPlugins = {
            implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.14.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0'
        }

and a clean install.

Please include a single standalone React Native component.  

    export default class MapBoxScreen extends Component {
        constructor(props) {
            super(props);
            this.state = {
            };
        }
    
        render() {
            return (
                <MapboxGL.MapView
                    style={{flex:.9}}
                    compassEnabled={true}
                    compassViewPosition={1}
                >
                </MapboxGL.MapView>
            );
        }
    }

**Expected behavior**  
Expected the compass to show on rotation on the top right corner. 

**Actual behavior**  
Compass is not rendering

**Screenshots**  
![image](https://user-images.githubusercontent.com/55847858/156839090-37e38994-dbb9-490c-9d8d-93a16be97ce5.png)

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Andorid 11
 - Device: Redmi Note 10
 - Emulator/ Simulator: no
 - Dev OS: Win10
 - react-native-mapbox-gl Version: 8.5.0
 - Mapbox GL version [e.g. 6.3.0]
 - React Native Version 0.65.1

**Comment by Artotim** [comment]
Closing issue because it got fixed by the last update (8.6.0)

**Comment by RobertSasak** [comment]
I am facing the same issue of missing compass. However simple update in _package.json_ did not help. I do have the same version for implementation as stated above. 
```diff
-"@react-native-mapbox-gl/maps": "8.5.0",
+"@react-native-mapbox-gl/maps": "8.6.0-beta.0",
```
@Artotim  Have you done any other changes?

So far only solution was to remove whole section of _rnmbglMapboxLibs_ from _build.gradle_. Which downgrades _mapbox-android-sdk_ to 9.1.0.
```gradle
rnmbglMapboxLibs = {
        implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1'
        implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.8.0'
        implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.8.0'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0'
    }

    rnmbglMapboxPlugins = {
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.14.0'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0'
    }
````

**Comment by RobertSasak** [comment]
I still don't know why it does not work, but I found following workaround. It simply set compass image again. Remember to also set **compassViewPosition** on _Map_. Please let me know if there is a better solution.

```diff
diff --git a/node_modules/@rnmapbox/maps/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java b/node_modules/@rnmapbox/maps/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
index 6019a22..1ea3445 100644
--- a/node_modules/@rnmapbox/maps/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
+++ b/node_modules/@rnmapbox/maps/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java
@@ -1165,6 +1165,7 @@ public class RCTMGLMapView extends MapView implements OnMapReadyCallback, Mapbox
         }
 
         if (mCompassViewPosition != -1 && uiSettings.isCompassEnabled()) {
+            uiSettings.setCompassImageResource(R.drawable.mapbox_compass_icon);
             switch (mCompassViewPosition) {
                 case 0:
                     uiSettings.setCompassGravity(Gravity.TOP | Gravity.START);
```
