### ISSUE TITLE
How we can know the integrated package is for maplibre(open source) or map box for react native android.

### ISSUE THREAD

**Issue by atalsingh1244** [rnmapbox/maps#1790]
Can anyone help me on map libre, Can we develop react native android with maplibre(using java script) or only we have to integrate native SDK and need to code ios/android(swift, java) native respectively.

As official doumentation says"MapLibre is an OSS fork of MapboxGL. This is the default, and should work without any changes in gradle files."

So if we install map box package using 
1.npm i @react-native-mapbox-gl/maps

If we will not change anything in gradle file and if we use the sample demo code with public access token, then it will treat as mablibre(open source) or map box, Please help me on this.

Below code is for map box or map libre.

import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

MapboxGL.setAccessToken('<YOUR_ACCESSTOKEN>');

export default class App extends Component {
  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map} />
        </View>
      </View>
    );
  }
}

 Platform: Android
 Platform OS: [e.g. Android 9]
 Emulator/ Simulator: No
 Dev OS:  Win10
 react-native-mapbox-gl Version : react-native-mapbox-gl/maps: ^8.6.0-beta.0
 React Native Version: 0.67.3

Any sample code to integrate maplibre with react native android(java script).

**Comment by jbreuer95** [comment]
MapLibre is the default for android starting with version 10.* of this library that is not released yet. 
For v8.6.0 see instructions here https://github.com/rnmapbox/maps/blob/v8/android/install.md#using-maplibre
