### ISSUE TITLE
UserLocation does not use high accuracy on Android 12

### ISSUE THREAD

**Issue by benjamin-sweney** [rnmapbox/maps#1795]
**Describe the bug**  
After users have upgraded to Android 12 the UserLocation component no longer appears to use high accuracy mode. This is indicated by the users location darting around (as opposed to being true to their actual location) and the location status icon is no longer shown. On Android 11 the location status icon was shown regardless.

Using React Native Geolocation with a watch and high accuracy mode turned on corrects to the expected behaviour showing an accurate location and the location status icon.

**To Reproduce**  
Use a UserLocation component on _any_ Android 12 device. I have been using a S20 FE and an S21 to confirm (Android 12 vs still on Android 11)

Example:
```js
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
  UserLocation,
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <UserLocation />
      </MapView>
    );
  }
}
```

**Expected behavior**  
The users location is shown correctly and the location status icon is shown indicating use of high accuracy location.

**Actual behavior**  
Users location darts around and no location status icon is shown.

**Screenshots**  

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 12
 - Device: Android S20 FE
 - Emulator/ Simulator: no
 - Dev OS: MacOS 12.1
 - @rnmapbox/maps Version 8.4.0
 - Mapbox GL version 9.7.1
 - React Native Version 0.66.4

**Additional context**  
N/A

**Comment by RobertSasak** [comment]
Good job spotting that is the issue that occurs on Android 12. I think the solution is describe here https://developer.android.com/training/location/permissions#approximate-request so more of us can read it up.

**Comment by RobertSasak** [comment]
In my case I call *requestAndroidLocationPermissions* which implementaion is here https://github.com/rnmapbox/maps/blob/dda13db0c723c5f7e84341176cee77cd6897eb6c/javascript/index.js#L45-L48

It ask for both Coarse and Fine locations. On Android 11 and below user is shown a dialog for grating location permission. On Android 12 user in addition can decide also to give **Precise** or **Approximate** location. 

As written in the https://developer.android.com/training/location/permissions#approximate-request app should always request both Fine and Coarse permissions together. There is no way to force user to only grant Fine precision. However user can be informed about his/her decision and ask to upgrade to Precise. https://developer.android.com/training/location/permissions#upgrade-to-precise

This can be done by requesting again for both Coarse and Fine location again.

As I don't have a Android 12 telephone at the moment, @benjamin-sweney can you please confirm this behaviour? 
Can you also verify that you can change granted permission in the telephone settings under app settings?
Does switching to **Precise** permission solve the issue?

**Comment by benjamin-sweney** [comment]
@RobertSasak I use the `MapboxGL.requestAndroidLocationPermissions();` function on boot of my application to call the correct permissions. This includes both required permission calls as needed on Android 12.
