### ISSUE TITLE
Map libre is not supported with empty token MapboxGL.setAccessToken('')

### ISSUE THREAD

**Issue by atalsingh1244** [rnmapbox/maps#1796]
Can anyone help me on map libre, Can we develop react native android with maplibre(using java script) or only we have to integrate native SDK and need to code ios/android native respectively.

As official doumentation says"MapLibre is an OSS fork of MapboxGL. This is the default, and should work without any changes in gradle files."

So if we install map box package using 
1.npm install rnmapbox/maps#main --save

If we will not change anything in gradle file and if we use the sample demo code with public access token, then it will treat as mablibre(open source) or map box, Please help me on this.

import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

MapboxGL.setAccessToken('');

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF'
  },
  container: {
    height: 300,
    width: 300,
    backgroundColor: 'tomato'
  },
  map: {
    flex: 1
  }
});

export default class App extends Component {
  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map} />
        </View>
      </View>
    );
  }
}

Expected behavior
Map view should appear on the screen with no error message(with empty token because I am using as map libre)

Actual behavior
Map is being appear but with error message like must provide valid access token

Screenshots
![Screenshot_20220317-102408_mapdemo](https://user-images.githubusercontent.com/37287871/158740387-afa65c7a-6186-4729-ae75-3e70b95b722f.jpg)

Versions (please complete the following information):
 - Platform:  Android
 - Platform OS: Android 10
 - Device: Samsung A7
 - Emulator/ Simulator: No(physical device)
 - Dev OS: Win10
 - @rnmapbox/maps Version: 8.6.0-beta.0
 - React Native Version: 0.67.3

android/build.gradle 
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"

         useMapLibre = false

        if (useMapLibre) {
            rnmbglMapboxLibs = {
                implementation ("org.maplibre.gl:android-sdk:9.2.1")
                implementation ("com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0")
            }

            rnmbglMapboxPlugins = {
                implementation ("com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0")
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0")    {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0")        {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
                implementation ("com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v9:0.4.0") {
                    exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
                }
            }
        }    
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by BelyaninD** [comment]
I think you should specify styleURL or styleJSON, by default the style is requested from Mapbox

**Comment by jbreuer95** [comment]
@atalsingh1244 when using MapLibre you cannot use the maps provided by Mapbox without an access key (`MapboxGL.StyleURL.Street` is the default), you need to provide a `styleURL` or `styleJSON` on the MapView  to 

A Your own title server 
B A free title server like https://openmaptiles.org/
C Use a mapbox key to use the build in style

https://github.com/rnmapbox/maps/blob/main/docs/MapView.md#props
