### ISSUE TITLE
Map displays as a black screen in V10 example (iOS)

### ISSUE THREAD

**Issue by naftalibeder** [rnmapbox/maps#1804]
**Description**  
The map displays a black frame instead of the expected map contents. It looks like the screenshot below - the same on simulator and device.

I know the V10 library is very much a work in progress, but my understanding is that it should at least display a map at this point, so I'm wondering if anybody else has had success with the example.

**Reproduction**  
1. Do a standard installation of `rnmapbox/maps` with `$RNMapboxMapsImpl = 'mapbox'`:
```sh
git clone git@github.com:rnmapbox/maps.git
cd maps && npm i
cd example && npm i
```

2. Delete the existing `MapLibre` Swift package, and add `https://github.com/mapbox/mapbox-maps-ios.git` as a new one.
3. Launch the app on device or simulator.
4. Navigate to the `V10` section and launch either of the options.

**Expected behavior**  
The map should look like a ... map.

**Actual behavior**  
The map looks like a flat black rectangle.

**Screenshots**  
<img src="https://user-images.githubusercontent.com/2423291/159556953-fc2fdb4a-84ba-422c-806a-1dfa0d9f269a.png" height="600" />

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: iOS 15.3.1
 - Device: iPhone 12s
 - Emulator/ Simulator: Simulator and device
 - Dev OS: macOS 12.2 (21D49)
 - @rnmapbox/maps Version: 10.0.0-beta.0
 - React Native Version: 0.66.0

**Other**
Note that I was getting a `Multiple commands produce...` build error, which I was able to resolve by deleting one of the binary links - specifically the one at `Build Phases > Link Binary With Libraries > MapboxMaps`.

**Comment by mfazekas** [comment]
@naftalibeder thanks for the report. Yes by default the example project has MapLibre added as swift pacakge manager, but when you set `$RNMapboxMapsImpl` to `mapbox` it adds, mapbox-v10 via cocoa pods.
So you don't need to add Mapbox v10 again using Swift Package Manager, just remove MapLibre swift package manager dependency. I know it's confusing a will try to figure something out.

I've not yet tried to use Mapbox v10 with swift package manager, I assume it would work, in it's own but not when also added as a CocoaPod dependency. 

I've tried this and it was working for me:
```sh
git clone git@github.com:rnmapbox/maps.git
cd example && yarn I
# change $RNMapboxMapsImpl = 'maplibre' to $RNMapboxMapsImpl = 'mapbox' in iOS/Podfile
cd iOS && pod install
open RNMapboxGLExample.xcworkspace
# remove swift pacakge manager dependency for maplibre
```

<img width="397" alt="image" src="https://user-images.githubusercontent.com/52435/159603483-a88032f9-cbf6-41bb-9a8e-65b99b814b6c.png">

**Comment by mfazekas** [comment]
@naftalibeder could you get it working?! In #1808  I'm now issuing a warning if Mapbox is added both with SPM and Coccoapods. And also you can set `$RNMapboxMapsSwiftPackageManager` to `manual` meaning you'll add/manage the dependency yourself. And the pod file will not add mapbox libs either via SPM or CocoaPods.

**Comment by naftalibeder** [comment]
Unfortunately it's still not working - I started clean and followed your instructions exactly.

I have `rnmapbox-maps` showing as one of the `Development Pods`, and I have zero `Package Dependencies`. Both examples still show a black screen, on both simulator and device.

The only confounding factors I can think of are:
1. I'm running this on an M1 Mac. I could see it being this, but usually the problem surfaces with build errors, not a runtime issue. But I guess it would be helpful if another person with an M1 could check. (I have a colleague with one who could check on Monday.)
2.  I installed Cocoapods project-locally via a `Gemfile`. (There should be literally no difference with this...?)

**Comment by mfazekas** [comment]
@naftalibeder I don't think `Gemfile` has anything to do with the issue. It could be M1 (as I still have an intel Mac), but I'm pretty sure v10 SDK works great on m1 Macs, or access token, or network. Do you see anything in Xcode console - during runtime?!

You can also try setting `$RNMapboxMapsVersion = '~> 10.4.0'` to test with the just released 10.4

FWIW  my ruby, pod, and installed pods versions:
```zsh
ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin20]
pod --version
1.11.2
```

```zsh
less Podfile.lock | grep Mapbox
  - MapboxCommon (21.1.0)
  - MapboxCoreMaps (10.3.2):
    - MapboxCommon (~> 21.1)
  - MapboxMaps (10.3.0):
    - MapboxCommon (= 21.1.0)
    - MapboxCoreMaps (= 10.3.2)
    - MapboxMobileEvents (= 1.0.7)
  - MapboxMobileEvents (1.0.7)
    - MapboxMaps (~> 10.3.0)
    - MapboxMaps (~> 10.3.0)
    - MapboxCommon
    - MapboxCoreMaps
    - MapboxMaps
    - MapboxMobileEvents
  MapboxCommon: 019dac381fcb3aab115b5d488593261c810253ad
  MapboxCoreMaps: 418b6e02464c00d7227e778164f6ca67755ae6a1
  MapboxMaps: fc490ab5b8df6f74a82d35c56bc2ea4d576ad4ee
  MapboxMobileEvents: f7f3e8daeb4b83688ae62a4172dce79169a97233
 ```

**Comment by naftalibeder** [comment]
It's still doing the same thing, sadly. Below is the output that I'm getting for the same commands.

I'm going to ask a couple of colleagues to try it out, hopefully with and without M1 Macs. I'll report back.

```sh
~ ruby --version
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
~ bundle exec pod --version
1.11.3
~ less Podfile.lock | grep Mapbox
  - MapboxCommon (21.2.0)
  - MapboxCoreMaps (10.4.1):
    - MapboxCommon (~> 21.2)
  - MapboxMaps (10.4.1):
    - MapboxCommon (= 21.2.0)
    - MapboxCoreMaps (= 10.4.1)
    - MapboxMobileEvents (= 1.0.7)
  - MapboxMobileEvents (1.0.7)
    - MapboxMaps (~> 10.4.0)
    - MapboxMaps (~> 10.4.0)
    - MapboxCommon
    - MapboxCoreMaps
    - MapboxMaps
    - MapboxMobileEvents
  MapboxCommon: eb826fdc45e8b77f87aca2519986d992fd4881b7
  MapboxCoreMaps: 13892567aa2a0e1cf8713887678f82998e2ff015
  MapboxMaps: 92e3eb21102beee5eca7cb4d9144162d6d1813c5
  MapboxMobileEvents: f7f3e8daeb4b83688ae62a4172dce79169a97233
```

**Comment by naftalibeder** [comment]
Got it working!

A little embarrassing, but for the sake of any future travelers: check `example/ios/env.json` and make sure that the access token is in there as well.

I hadn't thought through the fact (clearly listed in the readme 🤦) that the token is added during dependency installation (the `postinstall` script), not at build time. It's a silly mistake but hard to debug!

**Comment by mfazekas** [comment]
> Got it working!

Good to hear. We certainly can and should make it fail with a more visible error if accessToken is not passed/not valid.
