### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by LeonidSobolev** [rnmapbox/maps#1806]
Good afternoon, I connected the library immediately after npx react-native init
Went through all the settings. I get an error

Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/leonidsobolev/Desktop/mapboxv10test/node_modules/@rnmapbox/maps/android/rctmgl/build.gradle' line: 14

* What went wrong:
A problem occurred evaluating project ':rnmapbox_maps'.
> Could not find method safeExtGet() for arguments [kotlinVersion, 1.4.10] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at makeError (/Users/leonidsobolev/Desktop/mapboxv10test/node_modules/execa/index.js:174:9)
    at /Users/leonidsobolev/Desktop/mapboxv10test/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/leonidsobolev/Desktop/mapboxv10test/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/leonidsobolev/Desktop/mapboxv10test/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.

**Comment by mfazekas** [comment]
@LeonidSobolev thank I could reproduce it. 

For now please add definition of sefeExtGet to your root `build.gradle`:
https://github.com/rnmapbox/maps/blob/ae52011721c48890097d63672a51133ba7b32b96/example/android/build.gradle#L53-L55
