### ISSUE TITLE
[Fabric][ReactNative 0.68] Support Fabric architecture

### ISSUE THREAD

**Issue by Alaa-Ben** [rnmapbox/maps#1828]
**Describe the bug**  
The new Fabric architecture isn't supported yet. Are there any plans to ? Or am I doing something wrong ?

**To Reproduce**  
Just enable fabric on an app that uses mapbox.

**Expected behavior**  
Map is working.

**Actual behavior**  
Getting a lot of messages that mapbox doesn't support Fabric (see screenshot).

**Versions:**  
 - Platform:  Android, iOS
 - Platform OS: Android 12, iOS 15
 - Device: [e.g. iPhone 11, Galaxy S10]
 - Emulator/ Simulator: Emulator and Device
 - Dev OS: MacOS Monterey 12.3
 - @rnmapbox/maps Version 8.6.0 beta
 - Mapbox GL version: Tried legacy mapbox (mapbox-gl) and mapbox (v10)
 - React Native Version: 0.68

**Comment by mfazekas** [comment]
Thanks, for the report, we'd like to eventually, PR-s welcome!

**Comment by naftalibeder** [comment]
Dropping this here for later reference:

https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/back-fabric-comp#setup

**Comment by Alaa-Ben** [comment]
@mfazekas Hi !
I just saw the "completed" ! has this been done ? I couldn't find commits about this !

**Comment by mfazekas** [comment]
It’s not completed or started. We’ll do it when we get to it. I’ve closed as a cleanup in issues

**Comment by Alaa-Ben** [comment]
Sure !
I might be able to help with that if I can find some time off.
I might open a PR if possible.
