### ISSUE TITLE
styleURL has not effect in v10 Maps 

### ISSUE THREAD

**Issue by gomathi4015** [rnmapbox/maps#1840]
**Describe the bug**  
styleURL has not effect in v10 Maps 

**To Reproduce**  
change the styleURL to 
MapboxGL.StyleURL.Outdoors
or 
MapboxGL.StyleURL.Dark

Example:
```js
import React from 'react';
import MapboxGL, {MapView,Camera} from '@rnmapbox/maps';


class TwoByTwo extends React.Component {

  render() {
    return (
      <MapboxGL.MapView 
  style={{flex: 1}}
  styleURL={MapboxGL.StyleURL.Satellite}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
      </MapboxGL.MapView>
    );
  }
}

export default TwoByTwo;

```
**Expected behavior**  
Map Style need to be changed

**Actual behavior**  
Map Style need to be changed

**Screenshots**  

<img width="302"  alt="Screenshot 2022-04-16 at 3 09 48 PM" src="https://user-images.githubusercontent.com/101688081/163670103-ee9dafe7-9ab3-49c9-8425-0a8e70abf9d3.png">

**Comment by mfazekas** [comment]
@gomathi4015 this looks like maplibre implementation. Not sure how maplibre handles style url-s.

**Comment by gomathi4015** [comment]
@mfazekas  can you help how to use mapbox implementation with v10,  so that i can apply styleURL MapboxGL.StyleURL.Outdoors

**Comment by afouadm** [comment]
> @mfazekas can you help how to use mapbox implementation with v10, so that i can apply styleURL MapboxGL.StyleURL.Outdoors

There are sections for that in the [Android](https://github.com/rnmapbox/maps/blob/main/android/install.md) and the [iOS](https://github.com/rnmapbox/maps/blob/main/ios/install.md) guides

**Comment by diospyros** [comment]
Not sure if this is the design intent, but I got it work using styles from cloud.maptiler (vector style).  Couldn't get it to work with mapbox styles, though.

![image](https://user-images.githubusercontent.com/24415229/164763074-4411d632-8d94-4f6f-bbae-41446b644f5d.png)

**Comment by nesjett** [comment]
I'm stuck with this in iOS, even using "styleUrl" prop with the suggested cloud.maptiler service seems not to affect the result, I always get the same default maplibre tiles.

Not sure if I'm missing something new, but in v8 with mapbox tiles everything was working properly

**Comment by deepaksinghcb** [comment]
> On android I got this error. The map was working good a few days ago.
> 
> ```
> Mapbox error [HTTP] Unable to parse resourceUrl mapbox://styles/mapbox/streets-v11 {"level": "error", "message": "[HTTP] Unable to parse resourceUrl mapbox://styles/mapbox/streets-v11", "tag": "Mbgl-HttpRequest"}
> ```

Confirming this issue on Android 12

**Comment by mfazekas** [comment]
On #main branch and if you're not setting `RNMapboxMapsImpl` it'll default to maplibre. Pls use [`MapboxGL.setWellKnownTileServer`](https://github.com/rnmapbox/maps/blob/main/docs/MapboxGL.md) with maplibre to use mapbox tiles. something like this

```jsx
MapboxGL.setWellKnownTileServer(MapboxGL.TileServer.Mapbox)
MapboxGL.setAccessToken(...)
```

**Comment by deepaksinghcb** [comment]
> On #main branch and if you're not setting `RNMapboxMapsImpl` it'll default to maplibre. Pls use [`MapboxGL.setWellKnownTileServer`](https://github.com/rnmapbox/maps/blob/main/docs/MapboxGL.md) with maplibre to use mapbox tiles. something like this
> 
> ```js
> MapboxGL.setWellKnownTileServer(MapboxGL.TileServer.Mapbox)
> MapboxGL.setAccessToken(...)
> ```

Property 'TileServer' does not exist on type 'typeof MapboxGL'.ts(2339)

**Comment by alexanderhalpern** [comment]
> ```js
> MapboxGL.setWellKnownTileServer(MapboxGL.TileServer.Mapbox)
> ```

You can just put
```js
MapboxGL.setWellKnownTileServer(MapboxGL.TileServer.Mapbox)
MapboxGL.setAccessToken(...)
````

**Comment by xD3CODER** [comment]
Got this error after putting `MapboxGL.setWellKnownTileServer("mapbox")`

```
FATAL EXCEPTION: main
Process: com.urbendo, PID: 16287
java.lang.IllegalArgumentException: No enum constant com.mapbox.mapboxsdk.WellKnownTileServer.mapbox
	at java.lang.Enum.valueOf(Enum.java:257)
	at com.mapbox.mapboxsdk.WellKnownTileServer.valueOf(WellKnownTileServer.java:3)
	at com.mapbox.rctmgl.impl.InstanceManagerImpl.getInstance(InstanceManagerImpl.java:18)
	at com.mapbox.rctmgl.modules.RCTMGLModule$1.run(RCTMGLModule.java:306)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:254)
	at android.app.ActivityThread.main(ActivityThread.java:8219)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
	````

**Comment by wiulma** [comment]
> > On #main branch and if you're not setting `RNMapboxMapsImpl` it'll default to maplibre. Pls use [`MapboxGL.setWellKnownTileServer`](https://github.com/rnmapbox/maps/blob/main/docs/MapboxGL.md) with maplibre to use mapbox tiles. something like this
> > ```js
> > MapboxGL.setWellKnownTileServer(MapboxGL.TileServer.Mapbox)
> > MapboxGL.setAccessToken(...)
> > ```
> 
> @mfazekas Property 'TileServer' does not exist on type 'typeof MapboxGL'.ts(2339)

this works for me too, it's just a type error. ok...not the best ...but it's just a type error

**Comment by ethanwc** [comment]
To be clear, for `@rnmapbox/maps` maplibre to work on expo, you need to explicitly specify 'well known tile server' before your call to `setAccessToken`

```typescript
MapboxGL.setWellKnownTileServer("Mapbox")
```

**Comment by AtlanteanOne** [comment]
iOS throws an error if I don't specify lowercase "mapbox", ditto Android expecting uppercase "Mapbox". So this works for me:

`MapboxGL.setWellKnownTileServer(Platform.OS === 'android' ? 'Mapbox' : 'mapbox')`

**Comment by michaelshum** [comment]
On expo I'm still getting a warning on Android even when setting `MapboxGL.setWellKnownTileServer(Platform.OS === 'android' ? 'Mapbox' : 'mapbox')`, does anyone have any suggestions for what would resolve this? It seems setting to 'mapbox' works fine for iOS

```
Mapbox warning, setWellKnownTileServer: only mapbox is supported, Object {
  "level": "warning",
  "message": "setWellKnownTileServer: only mapbox is supported",
  "tag": "InstanceManagerImpl",
}
at node_modules/@rnmapbox/maps/javascript/utils/Logger.js:106:8 in onLog
at node_modules/@rnmapbox/maps/javascript/utils/Logger.js:75:6 in loggerEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/_EventEmitter.js:150:10 in EventEmitter#emit
```
