### ISSUE TITLE
Using iconImage crashes app in release build

### ISSUE THREAD

**Issue by rastapasta** [rnmapbox/maps#1866]
**Describe the bug**  

Inlcuding a custom image symbol works fine in Debug builds, but crashes instantly in Release builds.

Also crashes in Debug build when app can't connect to metro.

No difference between requiring the images inline or using the ```Images``` component.

**To Reproduce**  

Use a ```SymbolLayer```, style it with ```iconImage``` (use or adapt [CustomIcon example](https://github.com/rnmapbox/maps/blob/main/example/src/examples/SymbolCircleLayer/CustomIcon.js)) in a Release build.

Example:
```js
import React from 'react';
import { MapView,  ShapeSource,  SymbolLayer, Camera} from '@rnmapbox/maps';

const shape = {
  type: 'FeatureCollection',
  features: [{
    type: 'Feature',
    geometry: {
      type: 'Point'
      coordinates: [
        [-74.00597, 40.71427],
        [-74.00697, 40.71527],
      ]
    }
 }]
};

export default () =>
  <MapView style={{flex: 1}}>
    <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
    <ShapeSource id="markers" shape={shape}>
         <SymbolLayer id="example" style={{iconImage: require('./marker.png')} />
    </ShapeSource>
  </MapView>
```

**Expected behavior**  
App not crashing

**Actual behavior**  
App crashing at

https://github.com/rnmapbox/maps/blob/main/ios/RCTMGL-v10/RCTMGLImageQueue.swift#L78

**Screenshots**  
![Screenshot 2022-04-23 at 17 23 26](https://user-images.githubusercontent.com/1259904/164912744-b1431680-b35d-4131-a24e-63e018d5a088.png)

**Versions**  
 - Platform: iOS
 - Platform OS: 15.4.1
 - Device: iPhone Xs
 - Emulator/ Simulator: yes
 - Dev OS: OSX
 - @rnmapbox/maps Version main branch
 - Mapbox GL version 10.4.3
 - React Native Version 0.68.1

**Comment by naftalibeder** [comment]
Haven’t tested myself yet, but glancing at the error in your Swift code, seems like `self` is just getting deallocated. Could you just jump into the dependency code in your project and try prefacing the async block like so:

```
weak var weakSelf : RCTMGLImageQueueOperation! = self

DispatchQueue.global(qos: .default).async {
  guard let weakSelf = weakSelf else {
    return
  }

  // Everything else.
}

and run it? Theoretically that should work. 🤔

**Comment by naftalibeder** [comment]
Should be good in `main` - can you verify?

**Comment by rastapasta** [comment]
Thanks @naftalibeder and @mfazekas - working like a charm!
Love to see all this fresh vibes around here 🥰
