### ISSUE TITLE
onRegionDidChange is not being called on iOS

### ISSUE THREAD

**Issue by 1mike12** [rnmapbox/maps#1887]
**Describe the bug**  
the callback supplied to `onRegionDidChange` is not being called on my iOS device, but is on android. 

**To Reproduce**  
Steps to reproduce the behavior. 

BTW this repro bug templatejs is not public anymore:
 [our BugReportTemplate](https://github.com/rnmapbox/maps/blob/main/example/src/examples/BugReportTemplate.js) screens 

```js
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapboxGL.MapView
               onRegionDidChange={()=> console.log("not working on ios")}
            >

               <MapboxGL.UserLocation
                  onUpdate={this.onUserLocationUpdated}
               />
               <MapboxGL.Camera
                  zoomLevel={12}
                  animationMode={"flyTo"}
                  centerCoordinate={[0,0]}
               />
            </MapboxGL.MapView>
    );
  }
}
```

**Expected behavior**  
callback to be called

**Actual behavior**  
callback not calling for iOS

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: iOS 15.2
 - Device: iphone 13
 - Emulator/ Simulator: yes
 - Dev OS: osx 12.2.1
 - @rnmapbox/maps Version 10.0.0-beta.1
 - Mapbox GL version unknown
 - React Native Version 0.67.2
 
**additinoal info**
my setup is with mapbox

**Comment by rastapasta** [comment]
Aloha @1mike12 , ```onRegionDidChange``` is deprecated since v10. Check out ```onMapIdle``` or ```onCameraChanged``` of [MapView](https://github.com/rnmapbox/maps/blob/main/docs/MapView.md) - cheers!

**Comment by rastapasta** [comment]
example usage:
```js
        onMapIdle={({properties: {center, zoom, bounds}}) => ... }
```

**Comment by 1mike12** [comment]
thanks, unfortuantely the new props don't work in the reverse direction now haha. I'll try a combo of both for now
