### ISSUE TITLE
onMapIdle and onCameraChanged not called on Android

### ISSUE THREAD

**Issue by 1mike12** [rnmapbox/maps#1888]
**Describe the bug**  
the callback supplied to `onMapIdle` and `onCameraChanged` is not being called on my Android device, but is on iOS. This is the mirror opposite of this earlier bug I filed https://github.com/rnmapbox/maps/issues/1887

**To Reproduce**  
Steps to reproduce the behavior. 

BTW this repro bug templatejs is not public anymore:
 [our BugReportTemplate](https://github.com/rnmapbox/maps/blob/main/example/src/examples/BugReportTemplate.js) screens 

```js
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapboxGL.MapView
               onMapIdle={()=> console.log("not working on android")}
            >

               <MapboxGL.UserLocation
                  onUpdate={this.onUserLocationUpdated}
               />
               <MapboxGL.Camera
                  zoomLevel={12}
                  animationMode={"flyTo"}
                  centerCoordinate={[0,0]}
               />
            </MapboxGL.MapView>
    );
  }
}
```

**Expected behavior**  
callback to be called

**Actual behavior**  
callback not calling for Android

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: API 30
 - Device: pixel 5
 - Emulator/ Simulator: yes
 - Dev OS: osx 12.2.1
 - @rnmapbox/maps Version 10.0.0-beta.1
 - Mapbox GL version unknown
 - React Native Version 0.67.2
 
**additinoal info**
my setup is with mapbox

**Comment by mfazekas** [comment]
@naftalibeder what's the reason for the change?!  

My understand  is that now on js interface what was `onRegionDidChange` is now `onMapIdle`. And `onRegionIsChanging` is now `onCameraChanged`. Also instead of passing a geojson feature with properties they just pass the properties directly?!

**Comment by naftalibeder** [comment]
@mfazekas @1mike12 It's not working because it's not implemented yet on Android! See https://github.com/rnmapbox/maps/pull/1889#discussion_r866908334 and the ensuing conversation.

**Comment by mfazekas** [comment]
@naftalibeder I understand, but I was wondering about the reason for change?

You commit, doesn't give on much explanation why we needed to change callback names.

https://github.com/rnmapbox/maps/pull/1856
https://github.com/rnmapbox/maps/commit/92f1d27efec5d79ae18c26cccdaed59493b68b6c

**Comment by naftalibeder** [comment]
It seemed better to me to match the Mapbox v10 API, and in my opinion the new names are clearer too. `onRegionWillChange` isn't a provided event, so we would have to sort of fake it.

If you feel strongly, I would be somewhat okay using the old names, but either way we should deprecate `onRegionWillChange` because it doesn't mean anything anymore (not sure it ever did?).

**Comment by mfazekas** [comment]
@naftalibeder in my view this is a transitional release. 

I see the argument that they have better names and simpler parameters, although those are subjective. 

On the other hand I value it much more if we can help user migrate their code. Minimal changes means they can run the same program on earlier versions of react-native-mapbox-gl or they can use the same code with the v10 or mapbox-gl engine. 

Also if we're going to do breaking changes we need to add warning messages in case users pass unsupported callbacks, we need to add proper docs to changelogs and we need ot migrate our code in samples.

Not sure about `onRegionWillChange` you're probably right.

**Comment by naftalibeder** [comment]
> value it much more if we can help user migrate their code

Totally fair, I was just prioritizing differently. No need to do a breaking change for these functions

**Comment by mfazekas** [comment]
@1mike12 On main `onRegionDidChange` and `onRegionIsChanging` should work on both android and iOS and across mapbox/maplibre backends. I've kept `onMapIdle`  and `onCameraChanged` too, but they were marked as experimental and implemented only on iOS, mapboxv10 for now.

**Comment by naftalibeder** [comment]
@mfazekas I actually see no reason to keep `onMapIdle` and `onCameraChanged`, if we’re going to keep the old callbacks too. No need to make the API more complex. Thoughts on just removing them?

**Comment by mfazekas** [comment]
@naftalibeder sure it's fine to remove them. For now (I mean in version `10.*`) I'd like to keep the old names functional. If we're to migrate to the new names, I prefer gradual migration where we first we implement new methods, deprecate and warn on old callbacks, but they still working, and in next major release remove them.

**Comment by 1mike12** [comment]
@mfazekas I don't really care either way, I _do_ agree that it should match whatever mapbox's own js api looks like. 

What I'm more concerned about is if I follow the main install instructions on the readme, and that points to the #main branch, then the stuff mentioned in the rest of the documentation should work. I know it's an open source project, but more important than names or callback signatures, the biggest thing is actually working. 

No breaking commits should be merged without at least making a mention of breaking stuff in the relevant readme

**Comment by naftalibeder** [comment]
@1mike12 To be fair, none of the map callbacks had been implemented on iOS for v10 yet - so this wasn't a breaking change so much as implementing a new feature differently from the documentation. Still - point taken! :)
