### ISSUE TITLE
curl: (22) The requested URL returned error: 401

### ISSUE THREAD

**Issue by goodgood111** [rnmapbox/maps#1899]
<img width="1118" alt="Screen Shot 2022-05-12 at 9 56 02 PM" src="https://user-images.githubusercontent.com/65444735/168214049-fb34176c-39c7-46f2-9191-eed20e03d0be.png">

This error occurs when I do pod install in iOS folder.

I did clone and followed installation guide.

How can I solve this problem?

**Comment by mfazekas** [comment]
you have not configured your mapbox access tokens

**Comment by goodgood111** [comment]
How can I do that?

**Comment by vankhoa01** [comment]
Hi @mfazekas,
I had same issue.
I config token same as image below.
Is it right or wrong ?
<img width="855" alt="Screen Shot 2022-07-13 at 3 39 15 PM" src="https://user-images.githubusercontent.com/8953129/178689897-31e55ee0-afc0-4a12-a4be-bfb8cc2c5993.png">

**Comment by vankhoa01** [comment]
Tried and resolved the issue with this help: https://github.com/mapbox/mapbox-navigation-ios/issues/2692

**Comment by johhansantana** [comment]
> Tried and resolved the issue with this help: [mapbox/mapbox-navigation-ios#2692](https://github.com/mapbox/mapbox-navigation-ios/issues/2692)

Where exactly do I add the .netrc file ?
