### ISSUE TITLE
How to create `Circle`s with "real" sizes?

### ISSUE THREAD

**Issue by Myzel394** [rnmapbox/maps#1902]
I'm really struggling with this and apparently there literally seems to be no one else wanting this.

How do I make circles that have a "real" size? By "real size" I mean that a given circle has e.g. a radius of 50 meters and then scales accordingly to the current zoom factor, so that it always has a radius of 50 meters (and not 50 pixels).

**Comment by tech-newurtopia** [comment]
+1
