### ISSUE TITLE
Undefined error on expo

### ISSUE THREAD

**Issue by djc1111** [rnmapbox/maps#1907]
**Steps:**
  expo init
  expo install rnmapbox/maps#main
  
  app.json:`"plugins": [
        [
          "@rnmapbox/maps",
          {
            "RNMapboxMapsImpl": "mapbox",
            "RNMapboxMapsDownloadToken": "sk..."
          }
        ]
      ]`
  App.tsx: `MapboxGL.MapboxGL.setAccessToken('pk...');`
  
  eas build --profile development
  expo start --dev-client

**Error:**
  TypeError: undefined is not an object (evaluating '_maps.default.MapboxGL.setAccessToken')

Sorry for the inconvenience and thanks for your help

**Comment by gustaflindqvist** [comment]
@djc1111 we seems to get the same error. We had expo in our project and then removed it, but this might be connected as well. 

https://github.com/rnmapbox/maps/issues/1901

**Comment by djc1111** [comment]
Yes, I'm using typescript.

After trying a lot of things, rolling back to #1892 resolved the issue:
`expo install rnmapbox/maps#d064bb15589fa268419d77fc73faefc9536adfec`

If you have issues with the components not being recognized as JSX Components; updating react, react-dom and their types to the latest version fixes that:
`yarn add @types/react@latest @types/react-dom@latest --dev`
`yarn add react@latest react-dom@latest`
(from [https://bobbyhadz.com/blog/react-cannot-be-used-as-a-jsx-component](url))
