### ISSUE TITLE
Compilation error on iOS

### ISSUE THREAD

**Issue by rastapasta** [rnmapbox/maps#1913]
**Describe the bug**  
Build fails on current version on main.

**To Reproduce**  
Build application with rnmapbox.

Example:

```sh
npx react-native init sample
cd sample
yarn add https://github.com/rnmapbox/maps.git
# activate V10 in Podfile & pod install
react-native run-ios
```

**Expected behavior**  
Building should work like some PRs ago.

**Actual behavior**  
Build stops at https://github.com/rnmapbox/maps/blob/main/ios/RCTMGL-v10/RCTMGLMapView.swift#L89
error: "overriding non-open instance method outside of its defining module"

**Screenshots**  
![Screenshot 2022-05-17 at 17 16 23](https://user-images.githubusercontent.com/1259904/168848608-1eb743e0-1317-4e54-816b-80cb3a5f1c99.png)

**Versions:**  
 - Platform: iOS
 - Dev OS: OSX 12.3/12.4
 - @rnmapbox/maps Version #main
 - Mapbox GL version 10.4.3
 - React Native Version 0.68.1

**Comment by mfazekas** [comment]
@rastapasta we've upgraded Mapbox to `1.5.0` recently, and it should compile with that. Are you setting RNMapboxImplVersion to 10.4.3?

**Comment by rastapasta** [comment]
Dear @mfazekas - sorry for stealing your time, you're absolutely right, I missed that update and was still setting Mapbox to ~10.4.3. Thanks!
