### ISSUE TITLE
queryRenderedFeaturesAtPoint doesn't return any features

### ISSUE THREAD

**Issue by cbracewell** [rnmapbox/maps#1917]
**Describe the bug**  
Tapping a POI and calling `queryRenderedFeaturesAtPoint` with the coordinates from the onPress event, no feature is returned.

Example output:
```
{ "features": [], "type": "FeatureCollection" }
```

**To Reproduce**  
1. `npm start`
2. `npm run ios`

Example:
```jsx

import React, {useRef, useEffect} from 'react';
import {View, StyleSheet} from 'react-native';
import MapboxGL from '@rnmapbox/maps';

export const CustomMap = ({coordinates, stylesURL}) => {
  useEffect(() => {
    MapboxGL.setAccessToken(accessToken);
  }, []);

  const mapRef = useRef();

  const getFeatureAtPoint = async feature => {
    try {
      const result = await mapRef.current.queryRenderedFeaturesAtPoint(
        feature.geometry.coordinates,
      );
      console.log(result);
      // {"features": [], "type": "FeatureCollection"}
    } catch (error) {
      console.error(error);
    }
  };

  const handleMapClick = feature => {
    console.log(feature);
    /**
     * {
     * "geometry": {
     *   "coordinates": [-74.20771913934769, 42.20212862585046],
     *   "type": "Point"
     * },
     * "properties": { "screenPointX": 142.66665649414062, "screenPointY": 390 },
     * "type": "Feature"
     *}
     */

    getFeatureAtPoint(feature);
  };

  return (
    <View style={styles.wrapper}>
      <MapboxGL.MapView
        style={styles.map}
        styleURL={stylesURL}
        onPress={handleMapClick}
        ref={mapRef}
        attributionPosition={{bottom: 45, right: 10}}
        logoPosition={{bottom: 45, left: 10}}>
        <MapboxGL.Camera
          zoomLevel={13}
          centerCoordinate={coordinates}
          pitch={70}
        />
      </MapboxGL.MapView>
    </View>
  );
};
```

**Expected behavior**  
An array of the features under the coordinates pressed on.

**Actual behavior**  
When calling `queryRenderedFeaturesAtPoint` on the map ref, I receive `{"features": [], "type": "FeatureCollection"}`

### Versions 
 - Platform: iOS
 - Platform OS: iOS13
 - Device: iPhone13
 - Emulator/ Simulator: no
 - Dev OS: MacOS Monterey
 - @rnmapbox/maps rnmapbox/maps#main 
(from here https://github.com/rnmapbox/maps/commit/d49faf3c83997032f873aabfd761950e4ac9863b)
 - Mapbox GL version Latest as of commit ^
 - React Native Version 0.68.1

**Additional context**  

I recreated the same app in with React web and the following works as expected
```
    map.current.on("click", (e) => {
      const features = map.current.queryRenderedFeatures(e.point);
      console.log(features);
    });
 ```

**Comment by mfazekas** [comment]
See docs and example at, you should be query based on screen coordinates not map coordinates
https://github.com/rnmapbox/maps/blob/e31444817d0c5aa6302b672d138ba8c90bd1cef8/example/src/examples/FillRasterLayer/QueryAtPoint.js#L40-L47


> Mapbox GL version Latest as of commit ^

Can you confirm if it's Mapbox v10 or Mapbox GL (aka less than v10)

**Comment by cbracewell** [comment]
@mfazekas - I can confirm it's Mapbox v10.

I'm now using the point position but not seeing any features. Is this supported in V10?

Query now looks like..
```
  const getFeatureAtPoint = async feature => {
    try {
      const result = await mapRef.current.queryRenderedFeaturesAtPoint([
        feature.properties.screenPointX,
        feature.properties.screenPointY,
      ]);
      console.log(result);
      // {"features": [], "type": "FeatureCollection"}
    } catch (error) {
      console.error(error);
    }
  };
```

**Comment by sharathprabhal** [comment]
@cbracewell I'm experience a similar issue. Did you find a solution?

**Comment by cbracewell** [comment]
@sharathprabhal I didn't, decided on using `react-native-maps` for the time being.

I think the reason I wasn't seeing my features through the `queryRenderedFeaturesAtPoint` method was because I was loading my layers into the map through Mapbox studio editor vs passing them into the MapView components MapView Layers feature.

I thought the functionality would be anything clicked on the map would appear in `queryRenderedFeaturesAtPoint` but doesn't seem so.

@mfazekas do you think that assumption is accurate? Thanks!
