### ISSUE TITLE
{ position: 'absolute' } style within PointAnnotation and MarkerView not rendering on v10

### ISSUE THREAD

**Issue by WoodburyShortridge** [rnmapbox/maps#1921]
**Describe the bug**  
Using  `{ position: 'absolute' }` style as part of children of either PointAnnotation or MarkerView results in the view not being rendered on v10. This style works on earlier versions.

**To Reproduce**  
- create example app
- add PointAnnotation or MarkerView to map
- add test View w/ `{ position: 'absolute' }` style as children of PointAnnotation or MarkerView
- no views positioned absolute are rendered

Example:
```js
import React from 'react';
import {
  MapView,
  Camera,
  PointAnnotation
} from '@rnmapbox/maps';

const BugReportExample = () => {

  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <PointAnnotation 
           coordinate={[-74.00597, 40.71427]}
           children={<View style={{position: 'relative', justifyContent: 'center', alignItems: 'center'}} ><View style={{ position: 'absolute', top: 0, left: 0, width: 10, height: 10, backgroundColor: 'red'}} /></View>}
        />
        <MarkerView 
           coordinate={[-74.01597, 40.72427]}
           children={<View style={{position: 'relative', justifyContent: 'center', alignItems: 'center'}} ><View style={{ position: 'absolute', top: 0, left: 0, width: 10, height: 10, backgroundColor: 'red'}} /></View>}
        />
      </MapView>
    );
  }
}
```

**Expected behavior**  
Both position absolute views should render

**Actual behavior**  
Neither views render, but they do if you remove `position: 'absolute'`

**Versions (please complete the following information):**  
- Platform: iOS
 - Platform OS: iOS 15.2
 - Device: iPhone 12
 - Emulator/ Simulator: both
 - Dev OS: OSX
 - @rnmapbox/maps latest from #main
 - Mapbox GL version 10.5.0
 - React Native Version 0.68.2

**Comment by mfazekas** [comment]
@WoodburyShortridge note that `PointAnnotation` will not support `Animated.View` for `PointAnnotation` if the view was updated `refresh` methods needs to be called so it's refreshed on the map.

MarkerView should work hovewer

**Comment by WoodburyShortridge** [comment]
@mfazekas ah yes thanks, I see now animation does work in MarkerView in v10 and refresh works as well on PointAnnotation. Issue was I was testing w/ position absolute as well. This is still not working, anything styled w/ position absolute as child of MarkerView or PointAnnotation is not rendered. 

I'll update the ticket. Thanks for the response.

**Comment by WoodburyShortridge** [comment]
closing as I found a workaround:

for some reason position absolute views will not render unless there's also a sibling without position absolute and with a height/width. 

e.g.

this does NOT render as a MarkerView:
```
<View style={{position: 'relative', justifyContent: 'center', alignItems: 'center'}}>
   <View style={{position: 'absolute', width: 50, height: 50, backgroundColor: 'red'}} />
   <View style={{position: 'absolute', width: 30, height: 30, backgroundColor: 'blue'}} />
</View>
```

but this DOES render as a MarkerView
```
<View style={{position: 'relative', justifyContent: 'center', alignItems: 'center'}}>
   <View style={{position: 'absolute', width: 50, height: 50, backgroundColor: 'red'}} />
   <View style={{position: 'absolute', width: 30, height: 30, backgroundColor: 'blue'}} />
   <View style={{height: 1, width: 1}} /> // this is needed
</View>
```
