### ISSUE TITLE
getVisibleBounds() method doen't work

### ISSUE THREAD

**Issue by karimelsaidy** [rnmapbox/maps#1932]
getVisibleBounds() method doen't work in map box v10
```
class ....{
.....
onRegionDidChange(){
          const  bounds = await this.mapBoxRef.current.getVisibleBounds();
.....}

render{    
return( <Mapbox.MapView
                ref={this.mapBoxRef}
          { flex: 1 }]}
                
                onRegionDidChange={e => {
                  this.mapUpdate(e);
                }}>
                <Mapbox.Camera
                  ref={ref => (this.cameraBoxRef = ref)}
                  zoomLevel={10}
                  centerCoordinate={[
                    this.state.mapBoxInitial
                      ? this.state.mapBoxInitial[0]
                      : 46.620784,
                    this.state.mapBoxInitial
                      ? this.state.mapBoxInitial[1]
                      : 24.810133,
                  ]}
                />
     </Mapbox.MapView>)
}}
```

**Versions (please complete the following information):**  
 - Platform: [ Android]
 - Platform OS: [ Android 9]
 - Dev OS: [e.g. OSX ]
 - @rnmapbox/maps Version [e.g. 10.5]
 - React Native Version [e.g. 66.4]

.

**Comment by mfazekas** [comment]
@karimelsaidy thanks for the report, `getVisibleBounds` doesn't seems to be implemented for either iOS or android for v10 at the moment.

**Comment by bryanboyko** [comment]
We were relying on this for our app's core map UX - is there another way to get visible bounds?

**Comment by bryanboyko** [comment]
Heads up to anyone else wondering about the last question - MapView onRegionDidChange callback returns an object that holds `visibleBounds`

**Comment by NathanNovak** [comment]
Thanks @bryanboyko ! That helps!

**Comment by giograf** [comment]
My two cents added to the solution by @bryanboyko 

`<MapboxGL.MapView
        style={styles.map}
        scaleBarEnabled={true}
        onRegionDidChange={regionChangedHandler}
      >`
  Then you can just console.log to get the bounds and you will see them changing in the console as you move around your map:
      `
      function regionChangedHandler(state) {
        console.log(state.properties.visibleBounds)
      }
      `
      
 **Beware**, we noticed that we had 10.0.0-beta.1 and visibleBounds would return constants looking something like [[-90, 90], [-180, 180], **update package to the latest version** (10.0.0-beta.11 as of now and bug that I describe is not appearing anymore)

**Comment by karimelsaidy** [comment]
the same thing !! it's unsolved until now!
Platform: [ Android]
Platform OS: [ Android 9]
Dev OS: [e.g. OSX ]
@rnmapbox/maps Version [e.g. 10.5]
React Native Version [e.g. 66.4]

**Comment by bryanboyko** [comment]
Shoot looks as though `shape.properties.visibleBounds` is undefined for android in onRegionDidChange callback - did anybody else bump into this?

**Comment by wen-kai** [comment]
^^ @bryanboyko seeing this on android only when onRegionDidChange is called the visibleBounds are always `[[180, 90], [-180, 90], [-180, -90], [180, -90]]`

**Comment by wen-kai** [comment]
as another workaround we're using @mapbox/geo-viewport package to estimate bounding boxes based on center, zoom level, and map width/height.

https://github.com/mapbox/geo-viewport#boundsviewport-zoom-dimensions-tilesize

**Comment by vadim312** [comment]
It's happening again now
https://github.com/rnmapbox/maps/issues/2317
