### ISSUE TITLE
Module 'Mapbox' not found - issue with m1 pro chip, XCODE - 13.3.1

### ISSUE THREAD

**Issue by Rajat-verma-99** [rnmapbox/maps#1952]
I'm unable to render a map in a new project that does not have any other dependencies rather than Mapbox.

Attached are all required screenshots

1. Error
<img width="1501" alt="Screenshot 2022-06-01 at 11 18 50 PM" src="https://user-images.githubusercontent.com/53261284/171553296-d02e52ba-5ef0-47fb-9d1d-31e7f9749762.png">

2. Package.josn
<img width="1512" alt="Screenshot 2022-06-01 at 11 22 14 PM" src="https://user-images.githubusercontent.com/53261284/171553391-c74583ea-49df-4634-b8d0-f73b56819d95.png">

3. Setup the key at root as per the SDK
<img width="743" alt="Screenshot 2022-06-01 at 11 21 32 PM" src="https://user-images.githubusercontent.com/53261284/171553429-c16108a8-aa98-421d-b2a0-df6470c7d1bb.png">

4. setup the key in the project as per the SDK
<img width="1512" alt="Screenshot 2022-06-01 at 11 20 40 PM" src="https://user-images.githubusercontent.com/53261284/171553530-45ba542a-1c40-48f9-890e-6ff0fcac194b.png">

5. Added the required dependencies as per SDK
<img width="1512" alt="Screenshot 2022-06-01 at 11 19 11 PM" src="https://user-images.githubusercontent.com/53261284/171553634-fa66502a-679d-46d4-8b96-ac0ee464274a.png">

**Comment by Rajat-verma-99** [comment]
@mfazekas I have followed the setup only, I have attached screenshots of added libraries as well which are listed in the documentation.

**Comment by fliip92** [comment]
any luck solving this?
