### ISSUE TITLE
error when using SymbolLayer with textField on IOS

### ISSUE THREAD

**Issue by sossnowski** [rnmapbox/maps#1954]
**Describe the bug**  
when run app on IOS it is crashing because of SymbolLayer with textField (when I comment Symbol Layer it is working fine). There is no problem on android. On IOS there is error:

finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600001481320 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask

my style.json file:
```json
{
    "tilejson": "2.2.0",
    "version": 8,
    "name": "Land",
    "sources": {
        "map": {
            "type": "raster",
            "tiles": [
                "https://custom-map-server/tiles/{z}/{x}/{y}.png"
            ],
           // ...
        }
    },
    "layers": [
       //  ...
    ],
    "center": [
        // ...
    ],
    "glyphs": "https://custom-map-server/fonts/{fontstack}/{range}/font.pbf"
}
```

There is no request to my server about font, firstly app crushes.

**To Reproduce**  
Use <MapView.SymbolLayer style={{textField: 'tmp', textSize: 14}}> with custom styles 
run app on iOS. 

Example:
```js
import React from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      < MapboxGL.MapView style={{flex: 1}}>
        <MapboxGL.Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <MapboxGL.ShapeSource
            id="tmp"
            shape={{
              type: 'FeatureCollection',
              features: [{
          type: 'Feature',
          geometry: {
            coordinates: [-73.970895, 40.723279],
            type: 'Point'
          },
          id: 1,
          properties: {},
        }],
            }}
          >
            <MapboxGL.SymbolLayer
              id="styleTmp"
              style={{textField: 'test', textSize: 14}}
            />
          </MapboxGL.ShapeSource>
      </MapboxGL.MapView>
    );
  }
}
```

**Expected behavior**  
displaying text on map 

**Actual behavior**  
map not displaying at all

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: iOS 15
 - Device: iPhone12
 - Dev OS: OSX 11.0.1]
 - @rnmapbox/maps Version 8.6.0-beta.0
 - React Native Version [e.g. 0.68]

**Comment by mfazekas** [comment]
Closing as we only deal with #main and v10 issues. Also reproduction is non-trivial.
