### ISSUE TITLE
how to draw polygon on map using this react native mapbox-gl-draw ?

### ISSUE THREAD

**Issue by SanjanaTailor** [rnmapbox/maps#1962]
I am looking for the solution same as given link below to achieve in react native mapbox GL ?

Link : https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/ 

so here in this library I am trying to install same library and adding mapbox draw but unable to achieve the same. 
can you please suggest some ways to implement the same thing ?

Thank you in advanced.

**Comment by jfaq89** [comment]
Anyone knows a way / an alternative to achieve this?
