### ISSUE TITLE
Android - Official Example Crashed  (Symbol/CircleLayer - Shape Source From Icon)

### ISSUE THREAD

**Issue by HAIHAI211** [rnmapbox/maps#1965]
**Describe the bug**  

When using the official example (using v10), add an additional icon to MapboxGL.Images in ShapeSourceIcon.js. Everything works fine on ios, but crashes on android.

**To Reproduce**  
Steps to reproduce the behavior. 

![image](https://user-images.githubusercontent.com/12226279/172764303-7a9f77fa-2241-45a4-8a5f-ea272a70315f.png)

** Reason **
![image](https://user-images.githubusercontent.com/12226279/172764867-712ebc70-f8c0-47ea-9ec6-c7710cc2f58c.png)
AsyncTask executes repeatedly

**Comment by Carabine** [comment]
Have the same issue on Android, when using more than 1 properties in images object. ``` images: {example: example1} ``` works, ``` ``` images: {example2: example2} ``` crahes
