### ISSUE TITLE
Using "get" Expression results in "feature referenced out of range key" error and nothing rendered in VectorSource

### ISSUE THREAD

**Issue by ryanjwessel** [rnmapbox/maps#1971]
**Describe the bug**  
I have a style expression for a `FillLayer` that is wrapped in a `VectorSource` component. It looks like this:

```js
const style = {
  fillOpacity: [
    'case', 
    ['in', ['get', 'guid'], ['literal', selectedGuids]],
    style.opacity,
    0.0,
  ],
};
```

For one of my layers, the `['get', 'guid']` portion of this Expression causes all lines and fill layers in the `VectorSource` to not be rendered, and emits this error:

```
Mapbox error [event]:Style [code]:-1 [message]:Failed to load tile 1/0/0=>1 for source: feature referenced out of range key
{
  message: "[event]:Style [code]:-1 [message]:Failed to load tile from source COUNTY: feature referenced out of range key",
  line: 30,
  level: "error",
  filePath: "virtual bool mbgl::MGLCoreLoggingObserver::onRecor…erity, mbgl::Event, int64_t, const std::string &)"
}
```

**To Reproduce**  

I do not have a reproducible example, as this must be related to company data that has changed over time. I will do my best to provide code samples. 

What would be most helpful out of this ticket is understanding **why** this error would be emitted. I checked all of the rendered `feature`'s, and each one has `properties.guid` in its object.

Why would I receive a "feature referenced out of range key" error? [This is where the error is emitted](https://github.com/mapbox/vector-tile/blob/bc2f7f44cdb0d9af2b282ea4a755f85a13ba713a/include/mapbox/vector_tile.hpp#L170) in Mapbox source code. 

It seems to indicate that we're accessing a key that is outside the bounds of the keys in the layer?

Here is the most code I could provide from our example: 

```tsx
    const guid = () => ['get', 'guid'];
    const guidIn = (guids: string[]) => ['in', guid(), ['literal', guids]];
    const fillStyle: StyleProp<FillLayerStyle> = {
        fillColor: style.color,
        fillOpacity: [
            'case',
            guidIn(Array.from(selectedGuids)),
            0.3,
            0.0,
        ],
    };

    return (
        <MapboxGL.VectorSource
            tileUrlTemplates={[...]}
            onPress={onSelectRegion}
        >
            <MapboxGL.LineLayer
                id={`line-${jurisdiction}`}
                sourceLayerID={layerId}
                style={{ lineColor: getRGBAColor('gray', 90) }}
            />
            <MapboxGL.FillLayer
                id={`fill-${jurisdiction}`}
                sourceLayerID={layerId}
                style={fillStyle}
            />
        </MapboxGL.VectorSource>
    );
```

**Expected behavior**  

If every rendered feature has `properties.guid`, running `'get', 'guid'` in a style Expression should not break the rendering for `VectorSource` and its child components. 

If the Expression is failing in a way that breaks rendering, I would expect some error log that indicates why the Expression has failed.

**Actual behavior**  

Vector components stop rendering when trying to access known keys in the `properties` object of our `feature`'s when there is some data issue.

**Screenshots**  

**Versions (please complete the following information):**  
 - Platform: Android & iOS
 - Platform OS: Android 11 & iOS 15
 - Device: Pixel 4XL & iPhone 13 Pro
 - Emulator/ Simulator: Emulator, Simulator, and physical devices run into the same problem
 - Dev OS: macOS 12.3.1
 - @react-native-mapbox-gl/maps Version: 8.3.0
 - React Native Version: 0.63.4

**Additional context**  
This was working previously until an unknown data change caused this issue.

[This is the only Issue](https://www.google.com/search?q=feature+referenced+out+of+range+key&rlz=1C5GCEM_enUS995US995&oq=feature+referenced+out+of+range+key&aqs=chrome..69i57j0i512l3j69i64l3j69i60.3326j0j7&sourceid=chrome&ie=UTF-8) I could find online that references the same error from a different Mapbox library.

**Comment by ryanjwessel** [comment]
[This](https://github.com/rnmapbox/maps/issues/913) was also a relevant Issue where a `'has'` Expression caused the app to crash.

**Comment by mfazekas** [comment]
Can you verify this on v10?! We don't have resources to look into issues on older versions.
