### ISSUE TITLE
MapboxGL.offlineManager.getPack -> MapView styleJSON -> `MapLoad error Failed to load glyphs`

### ISSUE THREAD

**Issue by bryanboyko** [rnmapbox/maps#1975]
**Describe the bug**  
The following error occurs after downloading a set of tiles for a given style via `MapboxGL.offlineManager.createPack`, loading the tiles via `MapboxGL.offlineManager.getPack`, and then passing the stringified result to `styleJSON` prop of `MapView`

ERROR Mapbox error MapLoad error Failed to load glyphs: {"level": "error", "message": "MapLoad error Failed to load glyphs: "}

**To Reproduce**  
- Successfully download tiles via `MapboxGL.offlineManager.createPack`
- Load download result via `MapboxGL.offlineManager.getPack`
- Attempt to load map by passing stringified download result to `styleJSON` prop of `MapView`

Example:
```js
import React from 'react';

let MapboxGL;
if (Constants.appOwnership !== 'expo') {
  MapboxGL = require('@rnmapbox/maps').default;
}

class BugReportExample extends React.Component {
  render() {
    return (
        <MapboxGL.MapView 
          ref={(ref) => (this._map = ref)}
          style={styles.map} 
          styleJSON={styleJSON}
          showUserLocation
          onRegionDidChange={async (shape) => {
            if (!shape) { return; }

            // Keep track of current zoom level
            this._zoomLevel = await this._map.getZoom();
            this._visibleBounds = shape.properties.visibleBounds;
          }} 
          minZoomLevel={1}
          maxZoomLevel={MAPPBOX_MAX_ZOOM_LEVEL}
        >
          <MapboxGL.Camera 
            ref={(ref) => (this._camera = ref)}
            zoomLevel={initialZoomLevel}
            centerCoordinate={initialCenterCoordinate || [0, 0]}
            minZoomLevel={1}
            maxZoomLevel={MAPPBOX_MAX_ZOOM_LEVEL}
            animationDuration={10}
          />
          <MapboxGL.UserLocation />

          {this._renderFeatures()}

        </MapboxGL.MapView> 
    );
  }
}
```

**Expected behavior**  
MapView successfully loads with downloaded style

**Actual behavior**  
ERROR Mapbox error MapLoad error Failed to load glyphs: {"level": "error", "message": "MapLoad error Failed to load glyphs: "}

**Screenshots**  
<img width="417" alt="Screen Shot 2022-06-10 at 6 29 45 PM" src="https://user-images.githubusercontent.com/8292189/173110745-beb16856-03bb-437b-a730-85970a19eff0.png">

**Versions (please complete the following information):**  
 - Platform OS: iOS 15.4
 - Device: iPhone 12
 - Emulator/ Simulator: yes
 - Dev OS: MacOS 12.4
 - @rnmapbox/maps Version 10.5.0
 - Mapbox GL version github:rnmapbox/maps#main
 - React Native Version 0.64.3

**Additional context**  
- Is the object returned by `MapboxGL.offlineManager.getPack` supposed to be passed directly to `MapView` `styleJSON` prop, or should it be used to somehow fetch the styling json that would then be passed to `MapView`?

**Comment by mfazekas** [comment]
@bryanboyko `getPack` only returns information about a pack but not the style itself. You cannot pass that to `styleJSON`

**Comment by bryanboyko** [comment]
Thanks @mfazekas! Unless I'm missing it, some explanation in the rnmapbox docs of how offline getPack should be used would be much appreciated.

Since the RN API is different than the iOS offline manager API and the Android offline manager API (neither has a getPack function or at least its not mentioned in the docs linked below), I'm not sure exactly how the RN OfflineManager API should work. 

After spending more time with it, my best guess is as follows:
- Download desired style from Mapbox (via account login), store to client filesystem, then load from filesystem and inject into MapView styleJSON prop when offline
- Download desired tyles for the above style via `createPack`
- Call `getPack` for the same tiles stored via `createPack.` This presumably sets up any instance of MapView to show the tiles for this pack?

References:
https://docs.mapbox.com/ios/maps/guides/offline/
https://docs.mapbox.com/android/maps/guides/offline/

**Comment by mfazekas** [comment]
See https://github.com/rnmapbox/maps/blob/main/example/src/examples/Map/CreateOfflineRegion.js
and https://github.com/rnmapbox/maps/blob/main/docs/OfflineManager.md

Use of offline packs should be transparent, if you use a region that's already cached, it will display the region from cache.
Our api is based on old mapbox api:

https://docs.mapbox.com/help/troubleshooting/mobile-offline/
https://docs.mapbox.com/ios/legacy/maps/examples/offline-pack/

**Comment by bryanboyko** [comment]
@mfazekas thanks again! 

Noted about the old api. This example is perfect - I'll give it a go.
