### ISSUE TITLE
UserLocation with renderMode native does not show up on iOS

### ISSUE THREAD

**Issue by arnaudschlupp** [rnmapbox/maps#1983]
UserLocation with renderMode "native" seems to not work (the user location is not being shown, it does work with renderMode "normal") on iOS simulator (xCode Version 13.3.1 on Macbook Pro M1) + device (iPhone 13 mini) using `"@rnmapbox/maps": "rnmapbox/maps#main"`

Example:
```js
import React from "react";
import MapboxGL from "@rnmapbox/maps";

export const BugIOSUserLocation = () => {
  return (
    <MapboxGL.MapView style={{ flex: 1 }} tintColor={"red"}>
      <MapboxGL.Camera />
      <MapboxGL.UserLocation
        renderMode="native"
        showsUserHeadingIndicator={true}
      />
    </MapboxGL.MapView>
  );
};
```

**Comment by mysport12** [comment]
Are you using v10? I noticed this as well. Neither of the native rendering modes on iOS show the user location marker. Looking through the source files it doesn't appear that these have been built out yet for v10 but I could be mistaken.

**Comment by bryanboyko** [comment]
After updating to latest `Installing rnmapbox-maps 10.0.0-beta.22 (was 10.0.0-beta.18)`, UserLocation is no longer visible on iOS simulator

**Comment by mfazekas** [comment]
This seems to work for me just fine with latest version - beta.43
