### ISSUE TITLE
Map Pointer Issue with react-native-mapbox-gl/maps

### ISSUE THREAD

**Issue by shreesols** [rnmapbox/maps#1987]
We are building a react native property app and using mapbox plugin to build our map page. On the map page we want to show Properties on map. Now, when a location has a lot of surrounding properties pointers are overlapping, see the screenshot: 
https://prnt.sc/TWBA8d6W2wef. So we need a way out where we can set the zoom of the map as per quantity of the property for a location or may please guide us where map autoset its zoom based on the number of pointers

**Comment by xD3CODER** [comment]
Look at `clusterRadius` props in `ShapeSource`
