### ISSUE TITLE
Android Official Example - mapview v10 - can't display compass & scaleBar (Even though I set scaleBarEnabled={true})

### ISSUE THREAD

**Issue by HAIHAI211** [rnmapbox/maps#1990]
![image](https://user-images.githubusercontent.com/12226279/174536522-a73407fe-f214-4fd1-942a-7643ddb9990c.png)

**Comment by TIEverton** [comment]
I'm having the same problem, in my case compassEnable={false} doesn't work.

**Comment by felixgourdeau** [comment]
v10 is still a work in progress, and scalebar is not working yet for android.

**Comment by portugaAndre** [comment]
@felixgourdeau I'm using v8 and having this same problem.

**Comment by mysport12** [comment]
[@react-native-mapbox-gl+maps+8.5.0.patch.txt](https://github.com/rnmapbox/maps/files/9064545/%40react-native-mapbox-gl%2Bmaps%2B8.5.0.patch.txt)

@portugaAndre I am using v8 still (moving to v10 soon hopefully) and this is the patch I am using. Scale bar is working in our app

**Comment by portugaAndre** [comment]
Is it disabling as expected ?

Em qui., 7 de jul. de 2022 às 11:19, Craig Martin ***@***.***>
escreveu:

**Comment by mysport12** [comment]
Truth be told, we always have the compass and scale bar enabled so I haven't tested the disabling side of the functionality in quite some time. But to get both to render the patch works

**Comment by mfazekas** [comment]
Compass settings added in #2036

**Comment by portugaAndre** [comment]
Actually we are using compassEnabled = False, but it's not working.
Sometimes it works, but sometimes it doesn't.

Em seg., 11 de jul. de 2022 às 02:14, Miklós Fazekas <
***@***.***> escreveu:

**Comment by portugaAndre** [comment]
I saw you just merged with master. I'll try again.

Em seg., 11 de jul. de 2022 às 08:36, André Vinicius Andrade <
***@***.***> escreveu:

**Comment by arcticfly** [comment]
It sounds like a few people in this thread are actually having trouble getting the scale bar to disable in v10 (which is affecting our app as well). I created a new issue specifically for the ability to disable scale bar in v10: https://github.com/rnmapbox/maps/issues/2295.

**Comment by mfazekas** [comment]
Scale bar should be addressed now
