### ISSUE TITLE
setTelemetryEnabled seems to be deprecated in v10

### ISSUE THREAD

**Issue by Andarius** [rnmapbox/maps#2010]
**Describe the bug**  
`MapboxGL.setTelemetryEnabled` is undefined with the new Mapbox version

**To Reproduce**  

Call `MapboxGL.setTelemetryEnabled(false)` from the latest version

Looking at https://www.mapbox.com/telemetry/#opt-out and https://github.com/mapbox/mapbox-maps-android/issues/772 it seems that we cannot disable the telemetry on behalf of the user anymore. 

Should `setTelemetryEnabled` be removed from the MapboxGL namespace ?

**Comment by mfazekas** [comment]
For this version it should return a warning that `.setTelemetryEnabled` is not supported on v10, and will be removed in the future, PR's Wellcome.

**Comment by beisert1** [comment]
@mfazekas  What is the reason for removing this call? We need to comply with GDPR so this was an important function for us. The native SDK's still appear to support this.

**Comment by traviswimer** [comment]
Adding to what's been said, an option to disable telemetry is also part of MapBox's terms:

> Developers employing our Maps SDKs for iOS and Android are required by Mapbox to provide the ability for users to opt out of location telemetry reporting and must provide a location opt-out feature within the settings of any native app.

https://www.mapbox.com/telemetry

**This means v10 can't be used without violating MapBox's terms of use.**

@mfazekas Has this capability been added somewhere else or why is the method being removed?

**Comment by rastapasta** [comment]
Same here, working on a project with a no-default-data-sharing requirement. Wrote Mapbox a mail to clarify the Terms of Use in context of setting ```MGLMapboxMetricsEnabled``` to ```false``` while still offering the user the possibility to opt-in again.

**Comment by NTKrieger** [comment]
I see that this issue is closed and that a PR was merged, but I am hoping to get a bit of clarification.  I am migrating from V8 and it appears to me that Mapbox.setTelemetryEnabled(false) still throws 'undefined is not a function' on Android.   I believe that Mapbox is the V10 namespace....what am I missing?

**Comment by mfazekas** [comment]
@NTKrieger see #2789
