### ISSUE TITLE
onRegionDidChange always returns same visibleBounds on Android

### ISSUE THREAD

**Issue by bryanboyko** [rnmapbox/maps#2037]
**Describe the bug**  
`MapboxGL.MapView` `onRegionDidChange` returned object visibleBounds is always returns same value on Android `onRegionDidChange shape.properties.visibleBounds:  [[180, 90], [-180, 90], [-180, -90], [180, -90]]`

**To Reproduce**  
Interact with map and monitor onRegionDidChange callback

**Expected behavior**  
visibleBounds should be correct bounds (same as it does for iOS)

**Actual behavior**  
visibleBounds is always the same value posted above

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 12
 - Device:Pixel 6
 - Emulator/ Simulator: no
 - Dev OS: MacOS 12.4
 - @rnmapbox/maps `@rnmapbox/maps": "github:rnmapbox/maps#main`
 - React Native Version 0.64.3

**Comment by mfazekas** [comment]
Should be fixed in recent versions

**Comment by RemarkableM** [comment]
Nope
