### ISSUE TITLE
Set the filter on a layer from a base map style

### ISSUE THREAD

**Issue by davegurnell** [rnmapbox/maps#2039]
Hi! I believe I'm trying to do something that's not supported by `@react-native-mapbox-gl/maps` (I'm using v8). I'm not sure whether I'm missing something? I'm happy to work on a PR if there's no way of doing this currently:

**Synopsis**

I want to update the filter property of a layer that's baked into a style file. Note that I'm not adding the layer programatically via `<Layer>` and `<Source>` - it's part of the base map style.

**Detail**

My app contains a map that users can tap on to select features. I do this using two layers: one that I can listen to tap events on, and one that I can set the filter on to show/hide selected features.

The app needs to work offline. I've baked all the my two layers a style file and hosted it on my API server to work with `OfflineManager`. I'm not adding the layers with `<Layer>` components, so IIUC I can't modify the filter property on my visual feedback layer.

**Proposal**

If I'm missing something here then please accept my apologies. If not, I'm happy to work on this feature. I've put together a [draft of the functionality](https://github.com/cartographerio/rnmapbox-maps/tree/feature/set-filter) in a fork of this repo and I'm happy to raise a PR if it seems like the right way to go.

**Comment by mfazekas** [comment]
@davegurnell thanks, can you open a PR so we can discuss it there?! 

Form the logic of RNMBGL the interface would be 

```
<MapView ...>
  ...
  <FillLayer id='lake' filter={['>', ['get', 'ph'], 7]} />
  ...
</MapVIew>
```

But it might work already as is without changes.

**Comment by davegurnell** [comment]
Hi @mfazekas. Thanks for your response!

My bad - it looks like this _does_ work. You can use a layer component to refer to a layer that's already baked into a map. I assume the same is also true for source compoments. I'm not sure why I couldn't get it working before (it would have saved me a bunch of effort) but I just managed to get it working now. 

My PR is unnecessary. However, it might be worth clarifying in the documentation that source and layer components can be used in this way. I'll look into this.
