### ISSUE TITLE
Custom Font and Sprites

### ISSUE THREAD

**Issue by LucasBerger** [rnmapbox/maps#2048]
Hello,

is there a way to use custom Fonts and Sprites when using the styleJSON as styling for my map?

I seem to be getting 404 HTTP Errors with 'Failed to load glyphs' but I am using the font in my project.
Also I am getting 'Failed to load sprites' but didn't see an option to add sprites to the map styling.

Thanks for looking into this

**Comment by LucasBerger** [comment]
For more Information I am using the new v10 version of the MapboxImplementation

**Comment by mfazekas** [comment]
I’m not sure if it’s supported by native sdk. In case it is, we can implement that
