### ISSUE TITLE
Mapbox rendering only country borders

### ISSUE THREAD

**Issue by flashin** [rnmapbox/maps#2049]
**Describe the bug**  
Mapbox map is rendering only country borders. Each country in different color. But there is no more detailization when I am zooming the map

**To Reproduce**  
Here's the code:
```js
import React from 'react';
import { View } from 'react-native';
import MapboxGL from '@rnmapbox/maps';
import { MAP_BOX_ACCESS_TOKEN } from './config/constants';

MapboxGL.setAccessToken(MAP_BOX_ACCESS_TOKEN); // MAP_BOX_ACCESS_TOKEN was generated from Mapbox developer account.

const App = () => {
  return (
    <View style={styles.mainContainer}>
      <View style={styles.mapContainer}>
           <MapboxGL.MapView style={styles.map} zoomEnabled={true} styleURL={MapboxGL.StyleURL.Satellite}>
               <MapboxGL.Camera allowUpdates={true} centerCoordinate={[-0.1463695010623152, 51.5232834827981]} zoomLevel={3} />
          </MapboxGL.MapView>
        </View>
    </View>
  );
};

export const styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        width: '100%',
    },
    mapContainer: {
        width: '100%',
        aspectRatio: 39.0 / 30.0,
    },
    map: {
        width: '100%',
        height: '100%',
    },
});
```
Adding the screenshots how it looks like for zoomLevel 3 and 8. It is light blue with zoom level 8 because UK is colored with this color. Not because it cannot get the correct coordinate. If I navigate it to Ireland, it becomes yellow. Is this a problem with an access token? I am using public access token generated from Mapbox developer account.

I am using 10.0.0-beta.18 version of @rnmapbox/maps@rnmapbox/maps#main

![mapbox3](https://user-images.githubusercontent.com/1597866/179422498-7694b64f-554c-4ba3-9ae4-c400f096cdde.jpg)
![mapbox8](https://user-images.githubusercontent.com/1597866/179422501-515a5c49-7a7f-48de-9817-428e43e28869.jpg)

**Comment by mfazekas** [comment]
Hi, this looks like maplibre (default impl) for me. You either need to use mapbox v10 with RNMapboxMapsImpl grade/pod file setting, or add setWellknownTileserver with maplibre so it can consume mapbox url

**Comment by alfredvaa** [comment]
I had the same problem. Is this documented somewhere @mfazekas ?

**Comment by mengnans** [comment]
Facing the same issue with expo & mapbox implementation
