### ISSUE TITLE
 Mapbox error fireEvent failed: <rnmapbox_maps.RCTMGLEvent: 0x60000237f9e0> - callback is null 

### ISSUE THREAD

**Issue by Rajat-verma-99** [rnmapbox/maps#2053]
console.error: Mapbox error fireEvent failed: <rnmapbox_maps.RCTMGLEvent: 0x60000237f9e0> - callback is null {"level":"error","message":"fireEvent failed: <rnmapbox_maps.RCTMGLEvent: 0x60000237f9e0> - callback is null"}

construct
    [native code]:0
construct
    [native code]:0
_construct
    construct.js:19:9
Wrapper
    wrapNativeSuper.js:26:22
construct
    [native code]:0
_createSuperInternal
    index.bundle?platform=ios&dev=true&minify=false:29476:321
SyntheticError
    index.bundle?platform=ios&dev=true&minify=false:29494:31
reactConsoleErrorHandler
    ExceptionsManager.js:187:33
overrideMethod
    backend.js:2134:10
overrideMethod
    [native code]:0
console.error
    LogBox.js:33:4
registerError
    YellowBox.js:169:6
errorImpl
    YellowBox.js:84:8
console.error
    YellowBox.js:63:4
SphericalMercator
    sphericalmercator.js:23:24
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:293517:21
emit
    EventEmitter.js:189:10
__callFunction
    MessageQueue.js:425:19
__guard$argument_0
    MessageQueue.js:112:6
__guard
    MessageQueue.js:373:10
callFunctionReturnFlushedQueue
    MessageQueue.js:111:4
callFunctionReturnFlushedQueue
    [native code]:0

    
    
![Simulator Screen Shot - iPhone 11 - 2022-07-18 at 23 12 04](https://user-images.githubusercontent.com/53261284/179571029-795d71f4-b411-4f29-aa22-981f2d0ea65f.png)

**Comment by mmelk** [comment]
@Rajat-verma-99 Check your UserLocation component. I fixed this issue by improving my UserLocation component.

**Comment by sparethme** [comment]
Hey @mfazekas do you mind sharing how exactly you improved your UserLocation component?

**Comment by MichaelDanielTom** [comment]
I think this error has resurfaced due to some of the [event coalescing changes in v10.0.8](https://github.com/rnmapbox/maps/pull/2883), and occurs whenever any function is passed to `MapView` for `onCameraChange`. Reverting to v10.0.7 fixes the issue for me.

Also of note is that we use reanimated 3, and after doing some debugging, it looks like for some reason a `REAEventDispatcher` is being passed around within `RCTMGLMapView.swift`, which is responsible for the error.

**Comment by kesteer** [comment]
To just affirm what Michael has mentioned, I am  also seeing the same issue with anything over v10.0.8. 
It doesn't seem to be particularly critical ( the application will still work properly) but it is annoying nonetheless.

**Comment by lmalvasia** [comment]
We have the same issue using the latest version (10.0.15)

**Comment by bumjin1013** [comment]
same in 10.0.15
