### ISSUE TITLE
MapLoad error Failed to load tile - createPack success, getPack success, but map fails to show downloaded region

### ISSUE THREAD

**Issue by bryanboyko** [rnmapbox/maps#2061]
**Describe the bug**  

Tiles and sprites fail to load in a region contained within downloaded pack at a zoom level between min and max zoom level for downloaded pack

**To Reproduce**  
1. Delete app and re-install to ensure all mapbox tiles are cleared
2. createPack
```
    await MapboxGL.offlineManager.createPack({
      name: 'pack_name',
      styleURL: MapboxGL.StyleURL.Outdoors,
      minZoom: 1,
      maxZoom: 10,
      bounds: [[-110, 40], [-112, 39]],
    }, this.progressListener, this.errorListener);
```

3. getPack  (keep app open and then cut internet so getPack returns successfully - https://github.com/rnmapbox/maps/issues/2054)
```
const mapPack = await MapboxGL.offlineManager.getPack('pack_name');
```

4. Attempt to show region contained within tiles pack at zoom level less than max level of tile pack
```
      <View style={StyleSheet.flatten([styles.mapContainer, style])}>
        <MapboxGL.MapView 
          ref={(ref) => (this._map = ref)}
          style={styles.map} 
          styleURL={MapboxGL.StyleURL.Outdoors}
          minZoomLevel={1}
          maxZoomLevel={10}
        >
          <MapboxGL.Camera 
            ref={(ref) => (this._camera = ref)}
            zoomLevel={8}
            centerCoordinate={[-111, 39]}
            bounds={{
              ne: [-110, 40],
              sw: [-112, 38],
            }}
            minZoomLevel={1}
            maxZoomLevel={10}
            animationDuration={10}
          />

        </MapboxGL.MapView> 
      </View>
```
5. Attempt to view map and note the following errors
```
 ERROR  Mapbox error MapLoad error Failed to load sprite:  {"level": "error", "message": "MapLoad error Failed to load sprite: "}
 ERROR  Mapbox error MapLoad error Failed to load tile:  {"level": "error", "message": "MapLoad error Failed to load tile: "}
```

6. Enable network and navigate back to map - note that map tiles are visible as expected

**Versions:**  
 - Platform: iOS
 - Platform OS: iOS 15.5
 - Device: iPhone 12
 - Emulator/ Simulator: yes
 - Dev OS: MacOS 12.4
 - @rnmapbox/maps: "@rnmapbox/maps": "github:rnmapbox/maps#main",
 - MapboxImpl: $RNMapboxMapsImpl = 'mapbox'
- Mapbox version: $RNMapboxMapsVersion = '~> 10.5.0'
 - React Native Version: 0.64.3

**Comment by wen-kai** [comment]
Running into the same issue. Only when a map is previously cached via loading online will it show offline; otherwise, calling `createPack` on a new never-loaded region and attempting to load it offline results in the above MapLoad errors with blank tiles. It appears regions aren't being stored successfully after calling createPack.

**Comment by bryanboyko** [comment]
Same issue after trying the exact configuration in the example offlineManager implementation found here https://github.com/nitaliano/react-native-mapbox-gl/blob/master/example/src/components/CreateOfflineRegion.js

**createPack **
```
    const screenDims = Dimensions.get('window');
    const CENTER_COORD = [-73.970895, 40.723279];
    const MAPBOX_VECTOR_TILE_SIZE = 512;
    const bnds = geoViewport.bounds(
      CENTER_COORD,
      12,
      [screenDims.width, screenDims.height],
      MAPBOX_VECTOR_TILE_SIZE,
    );

    const options = {
      name: 'pack_name',
      styleURL: MapboxGL.StyleURL.Street,
      bounds: [[bnds[0], bnds[1]], [bnds[2], bnds[3]]],
      minZoom: 10,
      maxZoom: 20,
    };
```

**getPack **
```
{"_metadata": null, "pack": {"bounds": "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Point\",\"coordinates\":[-74.00442123413086,40.668399962792876]}},{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Point\",\"coordinates\":[-73.93747329711914,40.77820166245534]}}]}", "metadata": "{
  \"name\" : \"pack_name\"
}"}}
```

**Map implementation**
```
      <View style={StyleSheet.flatten([styles.mapContainer, style])}>
        <MapboxGL.MapView 
          ref={(ref) => (this._map = ref)}
          style={styles.map} 
          styleURL={MapboxGL.StyleURL.Outdoors}
          minZoomLevel={10}
          maxZoomLevel={20}
        >
          <MapboxGL.Camera 
            ref={(ref) => (this._camera = ref)}
            zoomLevel={15}
            centerCoordinate={CENTER_COORD}
            bounds={{

              ne: [bnds[0], bnds[1]],
              sw: [bnds[2], bnds[3]],
            }}
            minZoomLevel={10}
            maxZoomLevel={20}
            animationDuration={10}
          />

        </MapboxGL.MapView> 
      </View>
```

**Comment by wen-kai** [comment]
Looks like our bounds were reversed -- we were using nw & se. Documentation specifies ne & sw. After adjusting bounds it works perfectly.

**Comment by bryanboyko** [comment]
Our mistake! Per above message - we are good to go for this issue

If it's an easy add, some error feedback from createPack for incorrect bounds would be much appreciated.

**Comment by sahni01** [comment]
is it fixed for android since I am still getting this issue not able to see downloaded map in mapview when device is offline  also when downloading tile counts seems too less as per the area , in create pack bounds i am passing what i am getting in on Region changed event visibleBounds.
