### ISSUE TITLE
Android: MarkerView changes anchor for a millisecond, when size of child is changed.

### ISSUE THREAD

**Issue by danielknorn** [rnmapbox/maps#2075]
**Describe the bug**  
Hi, i have a Problem with changing the width and height of the MakerView child. On Android, when i change the size of the Child it looks like the anchor is moved to the center of the MarkerView for just a millisecond. So it looks like the Marker is jumping.
I didn't figure out why this is happening, in the example below i have just a SVG as Child, in the long run i want the size to be animated, but when i do the same Issue occurs.

On Ios it works fine. I already looked in RCTMGLMarkerView.kt and tried to remove the offset on refresh at all with no luck. At the moment i haver no clue why this is happening.

Thanks in advance

**To Reproduce**  
Change the size of the Child in the MarkerView

Example:
```tsx
import React from 'react';

import { Pressable, View } from 'react-native';

import MapboxGL from '@rnmapbox/maps';

export const TourDetailsMapPreview: React.FC = () => {
  const [selected, setSelected] = React.useState('');

  // EXAMPLE coordinates
  const pois = [
    {
      id: '1',
      coords: [9.682665724519548, 50.5185294909178],
    },
    {
      id: '2',
      coords: [9.678227256461529, 50.51601169897917],
    },
  ];

  return (
    <MapboxGL.MapView
      styleURL="mapbox://styles/mapbox/streets-v11"
      scaleBarEnabled={false}
      logoEnabled={false}
      compassEnabled={false}
      style={{ flex: 1 }}
      attributionEnabled={false}>
      <MapboxGL.Camera
        defaultSettings={{
          zoomLevel: 14,
          heading: 45,
          padding: {
            paddingTop: 50,
            paddingRight: 50,
            paddingBottom: 50,
            paddingLeft: 50,
          },
          centerCoordinate: [9.679336840861156, 50.515693524812995],
        }}
      />
      {pois.map(poi => (
        <MapboxGL.MarkerView
          key={`EXAMPLE-${poi.id}`}
          id={`EXAMPLE-${poi.id}`}
          coordinate={[poi.coords[0], poi.coords[1]]}
          anchor={{ x: 0.5, y: 1.0 }}>
          <Pressable onPress={() => setSelected(poi.id)}>
            <View
              style={{
                backgroundColor: selected === poi.id ? '#fff' : '#000',
                width: 32 * (selected === poi.id ? 2 : 1),
                height: 50 * (selected === poi.id ? 2 : 1),
              }}
            />
          </Pressable>
        </MapboxGL.MarkerView>
      ))}
    </MapboxGL.MapView>
  );
};

```

**Expected behavior**  
The size should change without looking like the anchor is changed for a millisecond

** Environment **
 - Platform: Android
 - Platform OS: Android 9
 - Device: Galaxy S8
 - Emulator/ Simulator: no
 - Dev OS: OSX 12.3.1
 - @rnmapbox/maps Version: 10.0.0-beat.19
 - Mapbox: v10
 - React Native Version: 0.67.4

**Comment by mfazekas** [comment]
> import { Box, Pressable } from 'native-base';
> import MarkerSVG from '../../../Base/svg/MarkerSvg';

Hi, please remove those dependencies, as it makes complicated to just copy your code into our [BugRepExample.js](https://github.com/rnmapbox/maps/blob/main/example/src/examples/BugReportExample.js) and try out.

The simpler to reproduce the issue the more likely we can look into it. Thanks for the understanding.

**Comment by danielknorn** [comment]
Hi @mfazekas i've updated the original file above. Thanks for looking into this.

**Comment by danielknorn** [comment]
Hi @mfazekas i've updated the example and removed other package dependencies. Thanks for looking into this.

**Comment by mfazekas** [comment]
@danielknorn thanks! It's still missing a MapView component and require parameters.

**Comment by danielknorn** [comment]
@mfazekas yeah sorry you are right. In my Project it is in another File. Updated it for a full Example. Thanks

**Comment by mfazekas** [comment]
@danielknorn so what happens is that, when you change the size of view it's rendered (1). And we detect the change, and adjust the position, anchor(2). Then mapbox updates the MarkerView position(3), and it's rendered. Ideally we'd do it as an atomic thing (1-3) with no render in between, but we cannot really do. So it's possible that a non consistent state appears in the view.
