### ISSUE TITLE
Can't set clear background / background color when using projection globe

### ISSUE THREAD

**Issue by natew** [rnmapbox/maps#2095]
## Environment

- Mapbox (GL) implementation: v10
- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version #main
- Platform: iOS
- React Native Version 0.69.0
- Platform OS: iOS 15.5
- Device: iPhone 13
- Emulator/ Simulator: Sim
- Dev OS: OSX 12.5

## Standalone component to reproduce

The bugreport template link is invalid, but I've tried many variations so not sure which would be the one to test from, there's no way to get a transparent BG:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/12100/182986819-0c7d3016-5477-4e76-949d-f2c824eaf899.png">

`BackgroundLayer` set's on the globe itself, not behind. `style` attribute doesn't do anything.

**Comment by natew** [comment]
Seeing there's a SkyLayer, will test after I finish a new build..

**Comment by jmy10241024** [comment]
Hey man, how did you set projection globe with react-native? I do not find the property about it.

**Comment by DavidGonzalezGutierrez** [comment]
Hola buenas, ahi alguna solucion para este problema?
