### ISSUE TITLE
Errors on EAS / Expo build

### ISSUE THREAD

**Issue by Dakuan** [rnmapbox/maps#2097]
## Environment
- Expo EAS

## Steps to reproduce

Use Expo EAS to build

```sh   
eas build -p android
```

results in a build error

```
[stderr] 
FAILURE: Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Could not determine the dependencies of task ':app:mergeReleaseNativeLibs'.
[stderr] 
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
[stderr] 
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
[stderr] 
     Searched in the following locations:
[stderr] 
- file:/home/expo/.m2/repository/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
- 
```

EAS / Expo folks saying its a package maintainer issue related to jcenter?

**Comment by Dakuan** [comment]
could be related to https://github.com/rnmapbox/maps/issues/1572 ?

**Comment by Dakuan** [comment]
its literally every project...no steps needed, the build is broken.

**Comment by Dakuan** [comment]
here you go, fresh project https://github.com/Dakuan/mapboxfresh

```
eas build -p android --profile development
```

includes the suggest fix in a patch https://github.com/ChirpBirding/rnmapbox/blob/main/android/build.gradle

can we reopen this please? We are currently completely unable to ship our app, arent able to fix this ourselves (just in time for a major marketed release). Going to be fun explaining all this to the CEO this morning!

**Comment by Dakuan** [comment]
If the maven issue can be fixed I will very happily submit a PR that updates the config plugin to use the mapbox download token

**Comment by mfazekas** [comment]
@Dakuan Sorry, it's an open source project with very limited resources. Currently the `8.*` version is not a priority for us. We're focused on `#main` branch, and v10 implementation, ideally that should work with expo. PR-s always welcome. Thanks for your understanding.

**Comment by Dakuan** [comment]
v10 isn't really production ready for us - we can't just not ship any code for the next few months?

**Comment by Dakuan** [comment]
does anyone have any copies of these packages so I can host them on my own maven server or something like that?

**Comment by deadbelly** [comment]
> here you go, fresh project https://github.com/Dakuan/mapboxfresh
> 
> ```
> eas build -p android --profile development
> ```
> 
> includes the suggested fix in a patch https://github.com/Dakuan/mapboxfresh/blob/main/patches/%40react-native-mapbox-gl%2Bmaps%2B8.5.0.patch#L30
> 
> can we reopen this please? We are currently completely unable to ship our app, arent able to fix this ourselves (just in time for a major marketed release). Going to be fun explaining all this to the CEO this morning!

I've also been struggling with this for a while. I think the solution here is to add the patch you're talking about with mavenCentral() and mapbox credentials to `node_modules/expo/android/build.gradle` instead of `node_modules/react-native-mapbox-gl/maps/android/build.gradle`. You also need to add `"eas-post-install": "patch-package"` to your package.json so that expo will run patch-package while building. I also patched mavenCentral() into the react-native-mapbox-gl build.gradle but I'm not 100% sure if that's actually part of what fixed it.
