### ISSUE TITLE
Transition doesn`t applies to expression value

### ISSUE THREAD

**Issue by Crysp** [rnmapbox/maps#2102]
## Environment

- Mapbox (GL) implementation: MapboxGL
- Mapbox (GL) version: [e.g. 6.3.0]
- @rnmapbox/maps Version #main
- Platform: iOS
- React Native Version: 0.69.2
- Platform OS: iOS 15
- Device: iPhone X
- Emulator/ Simulator: simulator and physical device
- Dev OS: macOS Monterey 12.5

## Standalone component to reproduce

```js
import React, { useState, useEffect } from 'react';
import {
  MapView,
  ShapeSource,
  Camera,
  CircleLayer,
} from '@rnmapbox/maps';

const BugReport = () => {
  const [feature, setFeature] = useState({
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [30.319378097536216, 59.879647222152855],
    },
    properties: {
      accuracy: 10,
    },
  });

  useEffect(() => {
    setInterval(() => {
      setFeature(f => ({
        ...f,
        properties: { accuracy: Math.random() * 100 },
      }));
    }, 5000);
  }, []);

  return (
    <MapView style={{ flex: 1 }}>
      <Camera
        defaultSettings={{
          centerCoordinate: feature.geometry.coordinates,
          zoomLevel: 16,
        }}
      />
      <ShapeSource id='people' shape={feature}>
        <CircleLayer
          id='accuracy'
          sourceID='people'
          style={{
            circleRadius: ['get', 'accuracy'],
            circleRadiusTransition: { duration: 200, delay: 0 },
            circleOpacity: 0.5,
          }}
        />
      </ShapeSource>
    </MapView>
  );
};
```

## Observed behavior and steps to reproduce

https://user-images.githubusercontent.com/13776478/183295101-a2a7dfa2-3b86-45e4-abdd-06c317d030fe.MP4

## Expected behavior

https://user-images.githubusercontent.com/13776478/183295242-e58728bf-56fa-43c1-9b6a-58f25bd13d4b.MP4

**Comment by mfazekas** [comment]
@Crysp ideally it's fixed on iOS as I'm now passing correct transition values. But not sure it was not rendered correctly for me, pls try and report back

**Comment by mfazekas** [comment]
@Crysp we'll need to try with a native iOS example, if that works, we need to figure out what's different in the RN version. If it doesn't we need to report as a native mapbox lib issue.

**Comment by mfazekas** [comment]
@Crysp yes this is the same on upstream version, works fine when using constant, but doesn't with expression.

See https://github.com/mapbox/mapbox-gl-js/issues/3170

**Comment by Crysp** [comment]
@mfazekas thx for reference
