### ISSUE TITLE
UserLocation no longer visible in 10.0.0-beta.22 and version 10.7.0

### ISSUE THREAD

**Issue by bryanboyko** [rnmapbox/maps#2103]
## Environment

$RNMapboxMapsImpl = 'mapbox'
$RNMapboxMapsVersion = '~> 10.7.0'
- @rnmapbox/maps Version #main `Installing rnmapbox-maps 10.0.0-beta.22 (was 10.0.0-beta.18)`
- Platform: iOS
- React Native Version 0.68.2
- Platform OS: iOS 15.5
- Device: iPhone 13
- Emulator/ Simulator: yes
- Dev OS: MacOS 12.4

## Standalone component to reproduce

```js
import React from 'react';
import {
  MapView,
  UserLocation,
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
         <UserLocation
            showsUserHeadingIndicator
            visible
          />
      </MapView>
    );
  }
}
```

## Observed behavior and steps to reproduce

User location icon doesn't show

## Expected behavior

User location icon shows

**Comment by mfazekas** [comment]
This one renders user location for me.

```jsx
import React from 'react';
import { MapView, UserLocation, Camera } from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{ flex: 1 }}>
        <Camera followUserLocation={true} />
        <UserLocation showsUserHeadingIndicator visible />
      </MapView>
    );
  }
}

export default BugReportExample;
```

**Comment by bryanboyko** [comment]
@mfazekas found a mistake on my end. Thanks and sorry for the trouble!
