### ISSUE TITLE
MarkerView (PointAnnotation) renders the default red pin when only Callout is passed as child on iOS

### ISSUE THREAD

**Issue by Pika-Pool** [rnmapbox/maps#2109]
## Environment

- Mapbox (GL) implementation: v8, MapboxGL
- @rnmapbox/maps Version: 8.6.0-beta.0
- Platform: iOS
- React Native Version: 0.69.1
- Platform OS: iOS 15.5 and iOS 13
- Emulator/ Simulator: yes

## Standalone component to reproduce

```js
import React from 'react';
import MapboxGL, {
  MapView,  Camera,
} from '@react-native-mapbox-gl/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        
        <MapboxGL.MarkerView
          id='location service center callout'
          coordinate={[-74.00597, 40.71427]}
          anchor={{ x: 0.3, y: 1.4 }}
        >
          <MapCallout title='Request Accepted' />
        </MapboxGL.MarkerView>
      </MapView>
    );
  }
}
```

## Observed behavior and steps to reproduce
The red pin marker is rendered due to the above `MarkerView`
![MicrosoftTeams-image](https://user-images.githubusercontent.com/33688622/183581119-6ecd5cbc-1cdf-4ce2-9bad-bfda0df83264.png)

## Expected behavior
The red pin should not be rendered, or atleast there should be an option to disable it.

**Comment by mfazekas** [comment]
`MarkerView` on `mapbox-gl` implementation on iOS is just `PointAnnotation` you can just add second child other than Callout, it can be small opaque view. I don't think we have this behaviour  - default pin with v10 anymore.

**Comment by michaelshum** [comment]
@mfazekas I'm still getting a default red pin when rendering a `PointAnnotation` with a hidden View. Is there a way to render a Callout on its own (eg Mapbox has Popup)? 

If not, is there a best practice for how to render a hidden PointAnnotation that has callout open? Even with a hidden view as child + PointAnnotation `selected={true}`, still not finding a way to render just a Callout on its own. Thank you!

**Comment by Pika-Pool** [comment]
I ended up creating my own Marker with a callout, which works both on ios and android, without showing the default red pin. Here is the code for it:

```tsx
import MapboxGL, { PointAnnotationProps } from '@react-native-mapbox-gl/maps';
import React from 'react';
import {
  StyleSheet,
  Text,
  View,
  type ColorValue,
  type StyleProp,
  type TextStyle,
  type ViewStyle,
} from 'react-native';

export interface IMapAnnotationProps extends PointAnnotationProps {
  Icon?: React.ReactNode;
  backgroundColor?: ColorValue;
  textColor?: ColorValue;
  calloutText?: string;
  containerStyle?: StyleProp<ViewStyle>;
  tipStyle?: StyleProp<ViewStyle>;
  calloutTextStyle?: StyleProp<TextStyle>;
}

export default function MapAnnotation({
  Icon,
  backgroundColor = '#4582da',
  textColor = 'white',
  calloutText,
  containerStyle,
  tipStyle,
  calloutTextStyle,
  ...pointAnnotationProps
}: IMapAnnotationProps) {
  return (
    <MapboxGL.PointAnnotation {...pointAnnotationProps}>
      <View style={[styles.calloutContainer, containerStyle]}>
        {calloutText != undefined && (
          <View>
            <Text
              style={[
                styles.text,
                { backgroundColor, color: textColor },
                calloutTextStyle,
              ]}
            >
              {calloutText}
            </Text>

            <View
              style={[
                styles.tip,
                { borderTopColor: backgroundColor },
                tipStyle,
              ]}
            />
          </View>
        )}

        {Icon}
      </View>
    </MapboxGL.PointAnnotation>
  );
}

const styles = StyleSheet.create({
  calloutContainer: {
    backgroundColor: 'transparent',
    justifyContent: 'center',
    flex: 1,
  },
  text: {
    fontSize: 10,
    borderRadius: 5,
    paddingVertical: 5,
    paddingHorizontal: 15,
  },
  tip: {
    marginLeft: 7.5,
    alignSelf: 'flex-start',
    borderWidth: 8,
    borderBottomWidth: 0,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
});
```
Note,`id` must be passed as a prop to `PointAnnotation` or it may throw an error. Typescript also gives error as `id` is a required prop.

**Comment by michaelshum** [comment]
@Pika-Pool, makes sense, looks like this also has the benefit of avoiding Animated.View in https://github.com/rnmapbox/maps/blob/main/javascript/components/Callout.js. Thanks for the response, I appreciate it!
