### ISSUE TITLE
Mapbox iOS SDK 10.7 causes bug in iPhone 7 on device, unable to down grade to 10.6 

### ISSUE THREAD

**Issue by Gnative** [rnmapbox/maps#2110]
Please feel free to disregard this issue or leave this as an issue for now for those potentially seeing problems with iPhone 7 and the current Mapbox iOS v10.7 implementation. 

There is currently a bug for iPhone 7 and Mapbox iOS SDK 10.7 where 3D displays are not working correctly and the app is crashing. https://github.com/mapbox/mapbox-maps-ios/issues/1508

I'm unable to down grade to an earlier version of the Mapbox SDK with out manually altering the RCTMGL swift code due to the use of new layer attributes such as `fillExtrusionAmbientOcclusionIntensity` & `fillExtrusionAmbientOcclusionIntensity` that have been introduced in the newest version of the Mapbox SDK 

Just wonder if there is a need to implement SDK specific code in this library.

**Comment by Gnative** [comment]
Probibly just should stop supporting soon to be legacy devices - thou my iPhone 7 still works perfectly well.

**Comment by mfazekas** [comment]
> Just wonder if there is a need to implement SDK specific code in this library.

It's autogenerated code. And we need it to support latest features of the libraries.

Those two lines get's the versions for android/iOS.
https://github.com/rnmapbox/maps/blob/038abe17beaf3c8f7a8505270d379978a6716a13/scripts/autogenerate.js#L62-L63

You should be able to change `rnMapboxMapsDefaultMapboxVersion` and `implementation 'com.mapbox.maps:android:` versions in your iOS/android build files and run autogenerate again to get a version that works on older map boxes.

**Comment by Gnative** [comment]
Thanks @mfazekas, that is good to know - just thought it good to leave this here for anyone else thats looking.
