### ISSUE TITLE
Remove changePadding from RCTMGLCamera.swift

### ISSUE THREAD

**Issue by mfazekas** [rnmapbox/maps#2120]
With Mapbox 1.8.0 supporting animation in camera padding, we can remove our own implementation. (After we've updated to 1.8)

See:
https://github.com/mapbox/mapbox-maps-ios/issues/1286
https://github.com/mapbox/mapbox-maps-ios/pull/1479

**Comment by naftalibeder** [comment]
Oh that’s great!
