### ISSUE TITLE
Camera.fitBounds does no longer work, v10

### ISSUE THREAD

**Issue by nixolas1** [rnmapbox/maps#2121]
## Environment

- Mapbox (GL) implementation:v10
- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version #main
- Platform: Android (Not tested on iOS)
- React Native Version 0.68.3
- Platform OS: Android 12
- Device: Samsung S21
- Emulator/ Simulator: no
- Dev OS: OS X

```js
camera?.fitBounds(
    [59.91, 60.88, 62.11, 63.43],
    [10.74, 11.54, 10.61, 10.39],
      [100, 200],
    500
  )
```

## Observed behavior and steps to reproduce

Nothing happens when fitBounds is called, no matter what valid input is given. Invalid input crashes, as normal.

## Expected behavior

fitBounds worked like expected before the upgrade to v10

## Notes / preliminary analysis
Maybe Mapbox SDK has changed how to fit camera in bounds?

**Comment by fernandoamz** [comment]
Does anyone have the fix for this? I am having the same issue

**Comment by fernandoamz** [comment]
I can confirm that this issue is happening at ios too but with versions above ios 15.14

**Comment by nixolas1** [comment]
Much appreciated!
