### ISSUE TITLE
Projection 'globe'

### ISSUE THREAD

**Issue by alexpchin** [rnmapbox/maps#2125]
After reading the setup instructions and also looking through the library, it's still unclear to me whether it's possible to display the projection globe as per https://docs.mapbox.com/mapbox-gl-js/example/globe/

Can anyone assist with this?

**Comment by mfazekas** [comment]
It seems to be possible in native sdk, but we don't support it in RN wrappers - https://docs.mapbox.com/ios/maps/api/10.3.0/Structs/GlobeMapProjection.html#/s:10MapboxMaps18GlobeMapProjectionV19transitionZoomLevel12CoreGraphics7CGFloatVvpZ

**Comment by alexpchin** [comment]
> It seems to be possible in native sdk, but we don't support it in RN wrappers - https://docs.mapbox.com/ios/maps/api/10.3.0/Structs/GlobeMapProjection.html#/s:10MapboxMaps18GlobeMapProjectionV19transitionZoomLevel12CoreGraphics7CGFloatVvpZ

Do you know if this on the roadmap to support in this library?
