### ISSUE TITLE
V8.5.0 Android 12 telemetry crash

### ISSUE THREAD

**Issue by beisert1** [rnmapbox/maps#2134]
## Environment

- Mapbox (GL) implementation: MapboxGL
- Mapbox (GL) version: V8.5.0
- @rnmapbox/maps Version V8.5.0
- Platform: Android
- React Native Version: 0.67.3
- Platform OS: Android 12
- Device: Samsung Galaxy S21
- Emulator/ Simulator: Both emulator and physical device
- Dev OS: OSX 12.3.1

## Standalone component to reproduce

```js
MapboxGL.setTelemetryEnabled(false)
```

## Observed behavior and steps to reproduce

Target Android 12 and attempt to disable telemetry with: MapboxGL.setTelemetryEnabled(false) 

## Expected behavior

MapboxGL.setTelemetryEnabled(false) should turn off telemetry and not crash.

## Notes / preliminary analysis

When updating our app to target Android 12, we are getting an error when calling MapboxGL.setTelemetryEnabled(false) on Android.

Error:
![image](https://user-images.githubusercontent.com/6433253/185238162-f4f46a2f-bb91-4ede-9221-285118cb2524.png)

## Additional links and references

Duplicate issue for the MapboxGL.setTelemetryEnabled(false) crash: https://github.com/rnmapbox/maps/issues/1677

**Comment by beisert1** [comment]
Proposed solutions on other issues did not work such as:

    implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.2.2'

Also, tried moving MapboxGL.setTelemetryEnabled(false) after map is fully loaded event. Seems no matter what, this call is unavailable on Android with targeting Android 12.

**Comment by mfazekas** [comment]
@beisert1 I'm sorry we don't have resources for the 8.* version of the sdk, we're working on releasing the v10. Thank you for your understanding.
