### ISSUE TITLE
On iphone 13 pro, heading does not update as phone rotates (normal and native location indicator)

### ISSUE THREAD

**Issue by arcticfly** [rnmapbox/maps#2147]
## Environment

- Mapbox (GL) implementation: MapboxGL
- Mapbox (GL) version: 8.5.0
- @rnmapbox/maps Version #main
- Platform: iOS
- React Native Version: 0.68.2
- Platform OS: iOS 15
- Device: iPhone13 Pro
- Emulator/ Simulator: no
- Dev OS: OSX 12.4

## Standalone component to reproduce

```js
const BugReportExample = () => {
  return (
    <View style={{ flex: 1 }}>
      <MapboxGL.MapView style={{ flex: 1 }}>
        <MapboxGL.UserLocation showsUserHeadingIndicator renderMode="native" />
      </MapboxGL.MapView>
    </View>
  );
};
```

## Observed behavior and steps to reproduce

No matter how we turn our iPhone13 Pro, the compass heading does not change.

------ EDIT -------
We were able to get our hands on another iPhone13 Pro, and the compass heading updated as expected.  However, the first iPhone13 Pro's heading still will not update, though it updates properly in other map apps on the phone.

## Expected behavior

As we turn our iPhone13 Pro, the compass heading should update.

## Notes / preliminary analysis

The same code works properly on iPhone11, the only other iPhone we've been able to test.

**Comment by mfazekas** [comment]
I think it was addressed in b41
