### ISSUE TITLE
"isUserInteraction" always is "false"

### ISSUE THREAD

**Issue by Crysp** [rnmapbox/maps#2151]
## Environment

- Mapbox (GL) implementation: v10
- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version #main
- Platform: iOS
- React Native Version 0.69.4
- Platform OS: iOS 15
- Device: iPhone X
- Emulator/ Simulator: yes
- Dev OS: OSX 12.5

## Standalone component to reproduce

```js
import React from 'react';
import {
  MapView,
  Camera,
} from '@rnmapbox/maps';

const coordinate = [30.319378097536216, 59.879647222152855];

const BugReport = () => {
  return (
    <MapView
      style={{ flex: 1 }}
      onRegionDidChange={region => {
        console.log(region.properties.isUserInteraction);
      }}
    >
      <Camera
        defaultSettings={{
          centerCoordinate: coordinate,
          zoomLevel: 16,
        }}
      />
    </MapView>
  );
};
```

## Observed behavior and steps to reproduce

Move camera by any kind of gesture and property `isUserInteraction` is `false`.

## Expected behavior

`isUserIneraction` should be `true`

**Comment by VolkerLieber** [comment]
Should be fixed by #2225
