### ISSUE TITLE
Windows token script generating invalid json

### ISSUE THREAD

**Issue by Koxx3** [rnmapbox/maps#2155]
## Environment

- Mapbox (GL) implementation: v10 example
- @rnmapbox/maps Version : #main
- Dev OS: Win10

## Standalone component to reproduce

```
git clone https://github.com/rnmapbox/maps.git
cd maps
cd example
# generate xxxxxxxxxxxxx access tocken with download permission
echo "xxxxx" > accesstoken 

npx yarn install
```

## Observed behavior and steps to reproduce

![image](https://user-images.githubusercontent.com/11454444/186356559-849806be-dd57-4941-b0e6-7e397dc9604a.png)

## Expected behavior

Valid json

**Comment by mfazekas** [comment]
This is still an issue but I'm closing this as we don't have win10 to address the issue. PR-s welcome!
