### ISSUE TITLE
V10. Documentation and example clarification

### ISSUE THREAD

**Issue by rusakovic** [rnmapbox/maps#2160]
## Environment

- Mapbox (GL) implementation: v10
- @rnmapbox/maps  #main
- Platform: iOS
- React Native Version 0.69.4
- Platform OS:  iOS 15.5
- Device: iPhone 13
- Emulator/ Simulator: yes
- Dev OS: macOS

## Standalone component to reproduce

1. I used this example: https://github.com/rnmapbox/maps/blob/main/example/src/examples/FillRasterLayer/CustomVectorSource.js
2. My file:
```
const VECTOR_SOURCE_URL = 'mapbox://mapbox.country-boundaries-v1';

const App = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <MapboxGL.MapView style={{width: '100%', height: '100%'}}>
        <MapboxGL.VectorSource
          id="customSourceExample"
          url={VECTOR_SOURCE_URL}
          onPress={e => {
            console.log(`VectorSource onPress: ${e.features}`, e.features);
          }}>
          {/* <MapboxGL.FillLayer
            id="customSourceFill"
            style={{fillColor: 'red'}}
          /> */}
          <MapboxGL.LineLayer id="layer1" style={{lineColor: 'red'}} />
        </MapboxGL.VectorSource>
      </MapboxGL.MapView>
    </SafeAreaView>
  );
};
```

3. Tried to Fill and Line these layers.
4. Source is taken here: 
![image](https://user-images.githubusercontent.com/17801144/186496586-c5fa433b-a296-4351-a15e-f43cafc4f753.png)

5. Should show country boundaries 

![image](https://user-images.githubusercontent.com/17801144/186496679-b8ac3e52-df7a-44df-800b-8bd2eaa225e3.png)

6. But in reality - nothing.

![image](https://user-images.githubusercontent.com/17801144/186496760-be6b2515-cfc0-43cd-a1c7-68252da1e442.png)

**Question:**
Where is the mistake placed?

**What I did**
Tried to understand this part doc:
https://github.com/rnmapbox/maps/blob/main/docs/FillLayer.md

Maybe `id` prop - is the key to issue.

![image](https://user-images.githubusercontent.com/17801144/186497298-3a52ed68-2ad3-43dd-92a6-fc3893fb28e8.png)

Where is ` the source in the style ` defined?

Thank you for your help.

Will be happy to add some video to docs after clarification for other developers.

**Comment by rusakovic** [comment]
@mfazekas 
Seems it's not only my issue
https://github.com/rnmapbox/maps/discussions/1991
https://github.com/rnmapbox/maps/discussions/1991

If you could navigate to docs or send very simple example with Fill and Line example for general  `mapbox.country-boundaries-v1` , I will be appreciate for your help.

**Comment by rusakovic** [comment]
Plus I checked this manual https://docs.mapbox.com/mapbox-gl-js/example/vector-source/

And tried to replicate in React Native. The result is the same -> no lines showed.

![image](https://user-images.githubusercontent.com/17801144/186508827-a4c6209d-10e5-4acd-98aa-9da05984d7d1.png)

**Comment by amoiseenko-sc** [comment]
@rusakovic Did you manage to make it work?
