### ISSUE TITLE
Raster Tiles aren't saved via OfflineManager

### ISSUE THREAD

**Issue by wen-kai** [rnmapbox/maps#2169]
## Environment

- Mapbox (GL) implementation: v10
- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version #main
- Platform: iOS
- React Native Version 0.68
- Platform OS: iOS 15
- Device: any
- Emulator/ Simulator: yes
- Dev OS: Monterey

## Standalone component to reproduce

```js
import React from 'react';
import {StyleSheet, View} from 'react-native';
import MapboxGL from '@rnmapbox/maps';

const styles = StyleSheet.create({
    mapView: {flex: 1},
});

class BugExample extends React.Component {
    constructor(props) {
      super(props);

      this.state = {
        showMap: false, // change to true to show map
      };
    }

    async componentDidMount() {
        // delete for testing
        // console.log(await MapboxGL.offlineManager.deletePack('field-1'));

        console.log('>>>>>>>>>>start creating pack', );
        await MapboxGL.offlineManager.createPack(
            {
                name: 'field-1', // any
                bounds: [[32.23782523101579, 46.39912398458027], [33.43887899585923, 47.041693870480955]], // any LARGE area
                styleURL: MapboxGL.StyleURL.Satellite,
                minZoom: 10,
                maxZoom: 12,
            },
            (pack, status) => {
                console.log('>>>>>>>>>>pack progress', pack.name, status.percentage, status.completedTileCount);
            },
            (pack, error) => {
                console.log('>>>>>>>>>>pack error', pack.name, error);
            },
        );

        console.log(await MapboxGL.offlineManager.getPacks());
    }

    render() {
        // change showMap to true to render map when offline (wifi off / airplane mode) to test offline loading of tiles
        if (!this.state.showMap) return <View />;

        return (
            <View style={styles.mapView}>
                <MapboxGL.MapView
                    ref={(c) => (this._map = c)}
                    onPress={this.onPress}
                    style={styles.mapView}
                    styleURL={MapboxGL.StyleURL.Satellite}
                >
                    <MapboxGL.Camera
                        zoomLevel={10}
                        centerCoordinate={[33.43887899585923, 47.041693870480955]}
                    />
                </MapboxGL.MapView>
            </View>
        );
    }
}

export default BugExample;
}
```

## Observed behavior and steps to reproduce

Any raster style (eg; Satellite or SatelliteStreet) is able to be downloaded successfully; however, when loaded offline the raster images aren't rendered. The vector assets are rendered successfully (streets, city names, etc). The rest of the map is blurry as it is unable to load the raster images.

1. start sample app & wait until download is complete
2. go offline
3. flip `state.showMap` to true
4. Map is rendered without raster tiles and only shows vector assets

## Expected behavior

Raster tiles should be rendered when offline.

## Notes / preliminary analysis

The map pack is created successfully for a raster style; however, it doesn't seem like the raster assets are actually downloaded.

EDIT: It appears the iOS code is outdated and the zoom range needs to be passed in the TilesetDescriptorOptions. Android appears to still be broken however.

**Comment by wen-kai** [comment]
There appears to be a workaround by modifying the style source as raster images aren't supported in TileStore at this time:
https://github.com/mapbox/mapbox-maps-android/issues/1460#issuecomment-1182559542

**Comment by maclne** [comment]
I have implemented OfflineManager on both iOS and Android, and caching of the satellite maps seems to work fine on iOS, but not on Android.

**Comment by maclne** [comment]
@wen-kai 
self.getOfflineManager().loadStylePack(for: styleURI, loadOptions: stylePackLoadOptions, progress: { [weak self] (progress) in....

Then when that completes:

//styleURI is "mapbox://styles/mapbox/satellite-v9"
let tilesetOptions = TilesetDescriptorOptions(styleURI: styleURI, zoomRange: minZoom...maxZoom)
let descriptor = self.getOfflineManager().createTilesetDescriptor(for: tilesetOptions)
let tileRegionLoadOptions = TileRegionLoadOptions(geometry: geometry, descriptors: [descriptor], metadata: ["cachefolder" : myCacheFolder], acceptExpired: true, networkRestriction: NetworkRestriction.none, averageBytesPerSecond: nil)

self.getTileStore().loadTileRegion(forId: regionID, loadOptions: tileRegionLoadOptions) {....

**Comment by wen-kai** [comment]
@maclne thank you! is the difference between the current code (https://github.com/rnmapbox/maps/blob/main/ios/RCTMGL-v10/RCTMGLOfflineModule.swift#L330) that you're calling loadStylePack? do you happen to have a forked repo with the changes?

**Comment by maclne** [comment]
@wen-kai I was following this: https://docs.mapbox.com/ios/maps/guides/offline/

**Comment by wen-kai** [comment]
@maclne ah thank you!

It appears the rnmapbox ios code is out of date and using `minZoom` and `maxZoom` instead of `zoomRange` for the TilesetDescriptorOptions which is specified in the latest ios mapbox docs:
https://docs.mapbox.com/ios/maps/api/10.7.0/Extensions/TilesetDescriptorOptions.html#/s:So27MBMTilesetDescriptorOptionsC10MapboxMapsE8styleURI9zoomRange10pixelRatio0f4PackC0AbC05StyleG0V_SNys5UInt8VGSfSo08MBMStylel4LoadC0CSgtcfc

I tested on iOS and it works perfectly! I'll submit a PR later this evening.

I'm still unsure about how to implement for Android though.

**Comment by wen-kai** [comment]
@mfazekas should we leave this open as it's still broken for Android?
