### ISSUE TITLE
Incorrect camera position with bounds and padding

### ISSUE THREAD

**Issue by Crysp** [rnmapbox/maps#2170]
## Environment

- Mapbox (GL) implementation: v10
- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version: #v10.0.0-beta.32
- Platform: Android
- React Native Version: 0.69.4
- Platform OS: Android 11
- Device: Nokia C01
- Emulator/ Simulator: both (emulator and device)
- Dev OS: OSX 12.5.0

## Standalone component to reproduce

```js
import React, { useRef } from 'react';
import { Button, StyleSheet, View } from 'react-native';
import {
  MapView,
  Camera,
} from '@rnmapbox/maps';

const BugReport = () => {
  const camera = useRef(null);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-end',
        paddingBottom: 40,
      }}
    >
      <MapView style={{ ...StyleSheet.absoluteFillObject }}>
        <Camera
          ref={camera}
          defaultSettings={{
            bounds: {
              ne: [29.87488244318364, 59.68250669940879],
              sw: [30.952489630943578, 60.22209891764351],
            },
            padding: {
              paddingBottom: 80,
              paddingLeft: 80,
              paddingRight: 80,
              paddingTop: 80,
            },
          }}
        />
      </MapView>
      <Button
        title='Set bounds'
        onPress={() => {
          if (camera.current) {
            camera.current.setCamera({
              bounds: {
                ne: [30.382347106933594, 59.9522034],
                sw: [30.4136494, 59.98061460864758],
              },
              animationDuration: 500,
              animationMode: 'easeTo',
              padding: {
                paddingBottom: 80,
                paddingLeft: 80,
                paddingRight: 80,
                paddingTop: 80,
              },
            });
          }
        }}
      />
    </View>
  );
};
```

## Observed behavior and steps to reproduce

Just tap several times to "Set bounds"

https://user-images.githubusercontent.com/13776478/187171566-d9ee7450-c7ea-4dfc-84d1-fc5e265fe8ec.mp4

## Expected behavior

Camera should be closer to bounds and should not to jump every time I taps "Set bounds"

## Notes / preliminary analysis

Without `padding` works fine

Converted bounds to GeoJSON polygons (bigger is default bounds, smaller is target of "Set bounds"):

```geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              29.87488244318364,
              59.68250669940879
            ],
            [
              30.952489630943578,
              59.68250669940879
            ],
            [
              30.952489630943578,
              60.22209891764351
            ],
            [
              29.87488244318364,
              60.22209891764351
            ],
            [
              29.87488244318364,
              59.68250669940879
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              30.382347106933594,
              59.9522034
            ],
            [
              30.4136494,
              59.9522034
            ],
            [
              30.4136494,
              59.98061460864758
            ],
            [
              30.382347106933594,
              59.98061460864758
            ],
            [
              30.382347106933594,
              59.9522034
            ]
          ]
        ]
      }
    }
  ]
}
```

**Comment by michaek** [comment]
I'm observing something similar. If I do not set `padding`, the bounds work reliably, but if I set `padding` it looks like the padding is incremented by the padding amount until the minimum zoom is reached. My first thought was to investigate [this method](https://github.com/rnmapbox/maps/blob/c49635b49f6438825f36d872e3eafdebca201238/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L328-L331) but I'm still working on getting Android Studio set up properly, so I have no idea yet if that's the wrong tack.

**Comment by michaek** [comment]
This issue is strightforward to reproduce without any code changes in the `example/` app in Android. In the "Camera -> Fit" example, choose either "Top" or "Bottom" as the padding option, set the zoom to "undef", then toggle back and forth between "House (bounds)" and "Town (bounds)".

The Java method in my previous comment doesn't seem to be in the Kotlin that's running in the app. (Does that mean it's just not invoked anywhere?) I put some watches in the debugger and found some weird output in `RCTMGLMapView.makeRegionPayload`. Here are the bounding boxes from first, selecting "House (bounds)" without padding, then with padding:

```
[southwest: Point{type=Point, bbox=null, coordinates=[-74.13752221626393, 40.794257121392064]}, northeast: Point{type=Point, bbox=null, coordinates=[-74.1333057837336, 40.797229845330406]}, infiniteBounds: false]
[southwest: Point{type=Point, bbox=null, coordinates=[-74.14894364078641, 40.76856906879195]}, northeast: Point{type=Point, bbox=null, coordinates=[-74.10213737186463, 40.80157433448113]}, infiniteBounds: false]
```

And here are the bounds from selecting "House (bounds)" after first selecting "Town (bounds)", with padding:

```
[southwest: Point{type=Point, bbox=null, coordinates=[-138.7906076402934, -79.92509236503284]}, northeast: Point{type=Point, bbox=null, coordinates=[137.53751465678664, 75.51265455817946]}, infiniteBounds: false]
```
(It's expanded to contain a big chunk of the world map.)

I haven't got to the point where I understand the code well enough to see why that's happening or make a suggestion for a solution, but I wanted to share what I've found so far in case it was helpful.

**Comment by michaek** [comment]
I can confirm the changes from #2183 resolve this issue. Thanks, @mfazekas!
