### ISSUE TITLE
MapView with multiple `ShapeSource`s has Exception in onDidFinishLoadingStyle

### ISSUE THREAD

**Issue by michaelshum** [rnmapbox/maps#2176]
## Environment

- Mapbox (GL) implementation: MapboxGL ("RNMapboxMapsImpl": "mapbox-gl")
- @rnmapbox/maps Version: #main
- Platform: Android
- React Native Version 0.64.3
- Platform OS: Android 13
- Device: Pixel 6

## Standalone component to reproduce

Stripped down EarthQuakes example from https://github.com/rnmapbox/maps/blob/main/example/src/examples/SymbolCircleLayer/EarthQuakes.js. Added a single ShapeSource `<MapboxGL.ShapeSource id="temp" />`

```js
import React from 'react';
import MapboxGL from '@rnmapbox/maps';

const earthQuakesJSON = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -120.8033371,
          36.2426682,
          5.47
        ]
      },
      "id": "nc73694191"
    },
  ]
}

class EarthQuakes extends React.Component {
  render() {
    return (
      <>
          <MapboxGL.MapView
            style={{ flex: 1 }}
            styleURL={MapboxGL.StyleURL.Dark}
          >
            <MapboxGL.Camera
              zoomLevel={6}
              centerCoordinate={[-122.09034,37.3892038]}
            />

            <MapboxGL.ShapeSource
              id="earthquakes"
              shape={earthQuakesJSON}
            >
              <MapboxGL.SymbolLayer
                id="pointCount"
              />
            </MapboxGL.ShapeSource>
            <MapboxGL.ShapeSource id="temp" />
          </MapboxGL.MapView>
      </>
    );
  }
}

export default EarthQuakes;
```

## Observed behavior and steps to reproduce

Running on managed Expo workflow, screen goes dark and app crashes. 
Logs are 
```
Mapbox error, Exception in onDidFinishLoadingStyle, Object {
  "level": "error",
  "message": "Exception in onDidFinishLoadingStyle",
  "tag": "Mbgl-MapChangeReceiver",
}
at node_modules/@rnmapbox/maps/javascript/utils/Logger.js:103:20 in onLog
at node_modules/@rnmapbox/maps/javascript/utils/Logger.js:74:9 in subscribe
at node_modules/react-native/Libraries/vendor/emitter/_EventEmitter.js:135:10 in EventEmitter#emit
```

## Expected behavior

Have used multiple sources on Mapbox GL web previously, if this isn't expected behavior from rnmapbox we could note it in https://github.com/rnmapbox/maps/blob/main/docs/ShapeSource.md

**Comment by michaelshum** [comment]
Follow-up: Still not sure _why_ this works, but adding a shape to the ShapeSource lets this work. `shape` isn't required in https://github.com/rnmapbox/maps/blob/main/docs/ShapeSource.md though, so I assume this is still a bug?

```
import React from 'react';
import MapboxGL from '@rnmapbox/maps';

const earthQuakesJSON = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -120.8033371,
          36.2426682,
          5.47
        ]
      },
      "id": "nc73694191"
    },
  ]
}

class EarthQuakes extends React.Component {
  render() {
    return (
      <>
          <MapboxGL.MapView
            style={{ flex: 1 }}
            styleURL={MapboxGL.StyleURL.Dark}
          >
            <MapboxGL.Camera
              zoomLevel={6}
              centerCoordinate={[-122.09034,37.3892038]}
            />

            <MapboxGL.ShapeSource
              id="earthquakes"
              shape={earthQuakesJSON}
            >
              <MapboxGL.SymbolLayer
                id="pointCount"
              />
            </MapboxGL.ShapeSource>
            <MapboxGL.ShapeSource id="temp" shape={earthQuakesJSON} />
          </MapboxGL.MapView>
      </>
    );
  }
}

export default EarthQuakes;
```

**Comment by mfazekas** [comment]
@michaelshum on iOS I get a reasonable error message:

It seems a ShapeSource should either have a shape or url.

```
 ERROR  Mapbox error SyleSource.addToMap id: Optional("temp") GeoJSON source must have a data value {"level": "error", "message": "SyleSource.addToMap id: Optional(\"temp\") GeoJSON source must have a data value"}
 ```

What is the use case for adding a ShapeSource without url or shape?!

We could improve error message on android, and also improve documentation.

**Comment by michaelshum** [comment]
Ah, hadn't seen the corresponding issue on iOS. Yup, it'd be great to update the error message on Android and note in documentation that additional ShapeSources require a data source. Re: your question, I was just testing (what I thought was) the most barebones version to debug.

However if a MapView has only a single ShapeSource it seems to work fine without `shape`: is there a reason why `shape` is not required when there's just one source, but is if it's a second one?

**Comment by mfazekas** [comment]
> However if a MapView has only a single ShapeSource it seems to work fine without shape: is there a reason why shape is not required when there's just one source, but is if it's a second one?

Can you post an example where a single ShapeSource works fine without shape/url?!
