### ISSUE TITLE
Camera Properties followUserLocation, followUserMode, followHeading/Pitch/ZoomLevel not working properly on v10

### ISSUE THREAD

**Issue by tyler-whitman** [rnmapbox/maps#2178]
## Environment

- Mapbox (GL) implementation: v10
- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version: rnmapbox/maps#v10.0.0-beta.32
- Platform: Android & iOS
- React Native Version: 0.69.1
- Platform OS: Android 12, iOS 15.5
- Device: Any
- Emulator/ Simulator: Both Simulator and Real Device
- Dev OS: OSX 12.5.1

## Standalone component to reproduce

```js
import React from 'react';
import {
  MapView,
  Camera,
  UserLocation
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <UserLocation
          showsUserHeadingIndicator
          visible
          renderMode="native"
          androidRenderMode="compass"
        />
        <Camera 
          centerCoordinate={[-74.00597, 40.71427]} 
          zoomLevel={14} 
          followUserLocation
          followUserMode="compass" 
          followHeading={5}
          followPitch={5}
          followZoomLevel={10}
        />
      </MapView>
    );
  }
}
```

## Observed behavior and steps to reproduce

In Mapbox v10 it looks like `UserTrackingMode` is no longer supported via `followUserMode`. I am able to get the camera to follow the user, but the camera heading will not change with movement of the compass. Also, I can not find a way to get the navigation user location icon. Along with this the `followHeading`, `followPitch` and `followZoomLevel` do nothing and do not change the camera when following.

## Expected behavior

I would expect the `followHeading`, `followPitch` and `followZoomLevel` to change the camera view when the camera is in follow mode. I also tried manually changing the camera `heading`, `pitch`, and `zoom` while in `followUserLocation` mode but nothing happens with the camera. Along with this I would expect a way to change the user location icon to navigation mode.

## Notes / preliminary analysis

It looks like in v10 `UserTrackingMode` has been removed and you now need to use the Navigation SDK. I'm not sure if this should be supported? I just wanted to confirm that these options no longer work, and see if there was any plan around Navigation?

## Additional links and references

https://github.com/mapbox/mapbox-navigation-ios/issues/3540
https://docs.mapbox.com/ios/navigation/guides/map-and-camera/navigation-camera/

**Comment by mysport12** [comment]
@tyler-whitman Check out the changes in #2197

**Comment by mysport12** [comment]
As for the location icon (white circle with blue nav icon), that has not been implemented yet in v10 from what I can tell.

**Comment by Gnative** [comment]
I'm getting some really weird functionality with Camera `followUser` properties 

- If set only `followUserLocation={false}`: `followUserLocation` is enabled, it should
- If I set only `followHeading={100}`: `followUserLocation` is enabled, should not be enabled unless set
- If I set only `followZoomLevel={10} `: `followPitch` pitch is not 0, should be 0 (note funnily `followUserLocation` is not enabled with only this prop)
- If set only `followUserLocation={true}`: `followPitch` is set to a pitch by default, should be 0

This is just some of the variations tested that don't work as you would expect.

**Comment by Gnative** [comment]
Also user location icon shows ion device (ios) but doesn't in simulator.

**Comment by Gnative** [comment]
@mysport12 notice you have been doing some work on this, thanks, if you fancy teaming up resolving on this let me know.

**Comment by mysport12** [comment]
@Gnative I am on vacation but will try to resolve when I get back. It might be as simple as bailing from the update function if followUserMode isn't enabled... But will check when I get back

<img width="371" alt="image" src="https://user-images.githubusercontent.com/10301026/190249021-38b6b925-5107-4691-905b-dd86f1ce35c1.png">

**Comment by mysport12** [comment]
@mfazekas I tried to get follow modes working on Android (Mapbox docs make it seem similar to iOS - accessing the viewport plugin from the map view) but have hit a bunch of dead ends. Hoping it's something you might be able to look into as my java/kotlin isn't as proficient as my ObjC/Swift (and that isn't saying much 😄 ).
