### ISSUE TITLE
MapBox styleURL bug, doesn't show anything

### ISSUE THREAD

**Issue by Pietro-Putelli** [rnmapbox/maps#2184]
## Environment

- @rnmapbox/maps = ^10.0.0-beta.32
- Platform = iOS
- React Native Version = 0.67.3
- Device = iPhone Xr

## Standalone component to reproduce

      <MapboxGL.MapView
        styleURL={"mapbox://styles/mapbox/streets-v11"}
      />

## Observed behavior and steps to reproduce

When I try to use one of these styles (https://docs.mapbox.com/api/maps/styles/), or create a custom one, the following errors occur: 

Mapbox error [event]:Setup [code]:-1 [message]:loading style failed: unsupported URL {"filePath": "virtual bool mbgl::MGLCoreLoggingObserver::onRecord(mbgl::EventSeverity, mbgl::Event, int64_t, const std::string &)", "level": "error", "line": 30, "message": "[event]:Setup [code]:-1 [message]:loading style failed: unsupported URL"} ´´´

Mapbox error Requesting: (null) failed with error: <MGLNativeNetworkManager: 0x280bcadc0> {"filePath": "-[MGLNetworkConfiguration errorLog:]", "level": "error", "line": 129, "message": "Requesting: (null) failed with error: <MGLNativeNetworkManager: 0x280bcadc0>"}

![IMG_7839](https://user-images.githubusercontent.com/64473929/188338163-6c4133b8-4d71-41c2-aced-4157ee729326.PNG)

Obviously the expected behaviour is that the map show with the right style.
Thank you

**Comment by mfazekas** [comment]
@Pietro-Putelli  You forgot to specify the mapbox implementation you're using. If you have not set to anything it defaults to maplibre. Mapblibre needs setWellKnownTileServer and setAccessToken to load mapbox urls

**Comment by Pietro-Putelli** [comment]
Thank you, is there an example?
