### ISSUE TITLE
[Bug]: Please ensure that the hosting activity/fragment is a valid LifecycleOwner

### ISSUE THREAD

**Issue by alexanderoskin** [rnmapbox/maps#2201]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.33

### Standalone component to reproduce

```javascript
import React from 'react';
import { StyleSheet, View } from 'react-native';
import MapboxGL from '@rnmapbox/maps';

MapboxGL.setAccessToken('<YOUR_ACCESSTOKEN>');

const App = () => {
  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <MapboxGL.MapView style={styles.map} />
      </View>
    </View>
  );
}

export default App;

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    height: 300,
    width: 300,
  },
  map: {
    flex: 1
  }
});
```

### Observed behavior and steps to reproduce

Android app crashes when `<MapboxGL.MapView />` is available in a next screen or modal.

We have a ScreenA where we have a map `<MapboxGL.MapView />`. And we have a ScreenB (where map opens in a full screen) with a same `<MapboxGL.MapView />`.

When we navigate from ScreenA to the ScreenB the app freezes with out any errors. So we need to kill the app to start use it again.

If we remove `<MapboxGL.MapView />` from the ScreenA or from the ScreenB everything works fine.

If instead of ScreenB we will use modal we got error `Please ensure that the hosting activity/fragment is a valid LifecycleOwner`.

If we remove `<MapboxGL.MapView />` from the ScreenA or from the modal everything works fine.

So the error occurs if `<MapboxGL.MapView />` is available on the current screen and on the next screen to what you will navigate from the current screen.

On iOS everything works with out any errors.

<img width="435" alt="Снимок экрана 2022-09-11 в 20 08 11" src="https://user-images.githubusercontent.com/5063096/189620791-1adffbe7-3b31-4910-b20c-590c23ec2469.png">

**Comment by mfazekas** [comment]
If you could add a component that reproduces the issue that would help us fixing it.

**Comment by alexanderoskin** [comment]
> If you could add a component that reproduces the issue that would help us fixing it.

Below is very quickly made example component. If something needed more let me know.

Click 'Open Map Modal' and will be `Please ensure that the hosting activity/fragment is a valid LifecycleOwner` error.

Click 'Go to Map Screen' and then click back to 'Home' and the app will freeze.

```javascript
import React, { useState } from "react";
import { Button, StyleSheet, Text, View, Modal, Pressable } from "react-native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { NavigationContainer } from "@react-navigation/native";
import MapboxGL from '@rnmapbox/maps';

MapboxGL.setAccessToken('token');

function HomeScreen({navigation}) {
  const [modalVisible, setModalVisible] = useState(false);

  return (
    <View style={styles.screen}>
      <Text>ScreenA</Text>
      <View style={styles.containerA}>
        <MapboxGL.MapView style={styles.map} />
      </View>
      <Button
        title="Go to Map Screen"
        onPress={() => navigation.navigate('Map')}
      />
      <Button
        title="Open Map Modal"
        onPress={() => setModalVisible(!modalVisible)}
      />
      <Modal
        animationType="slide"
        transparent={true}
        visible={modalVisible}
        onRequestClose={() => {
          setModalVisible(!modalVisible);
        }}
      >
        <View>
          <View>
            <Text>Hello World!</Text>
            <Pressable
              onPress={() => setModalVisible(!modalVisible)}
            >
              <View style={styles.containerA}>
                <MapboxGL.MapView style={styles.map} />
              </View>
            </Pressable>
          </View>
        </View>
      </Modal>
    </View>
  );
}

function MapScreen() {
  return (
    <View style={styles.screen}>
      <Text>ScreenB</Text>
      <View style={styles.containerB}>
        <MapboxGL.MapView style={styles.map} />
      </View>
    </View>
  );
}

const Stack = createNativeStackNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Map" component={MapScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  containerA: {
    height: 200,
    width: 300,
  },
  containerB: {
    height: 500,
    width: 300,
  },
  map: {
    flex: 1,
  },
});

export default App;
```

**Comment by alexanderoskin** [comment]
And `scaleBarEnabled  true/false` prop of the `MapView` has no effect on Android. On Android scale bar is impossible to hide and it looks like:
<img width="115" alt="Снимок экрана 2022-09-12 в 16 45 42" src="https://user-images.githubusercontent.com/5063096/189670590-20212a64-b667-41b8-9a8d-9be56a4b0e18.png">
