### ISSUE TITLE
Cannot find 'RCTMGLSwiftLog' in scope when building v10 for IOs due to naming conflict with react-native-video

### ISSUE THREAD

**Issue by rjdestigter** [rnmapbox/maps#2213]
## Environment
- OSX 12.5
- XCode 13.x, 14.x
- ruby 2.7.5
- CocoaPods 1.11.3

## Steps to reproduce

Follow steps here under _Configure your secret token_ so the project can download MapBox SDK https://docs.mapbox.com/ios/maps/guides/install/

1. Clone https://github.com/rjdestigter/amypond
2. Run `yarn` in the project root
3. Run `pod install` in the project's _ios_ folder

The issue was called out in this PR https://github.com/rnmapbox/maps/pull/2055 but unfortunately does not seem to resolve the issue. I checked to see if reverting [this change](https://github.com/rnmapbox/maps/pull/2055/files#diff-3feb35914a86a25a4b1b47abc27582bcde4c91f26f4d0d59ef4c03b7f0dc4026L255) to see if it would make a difference but it did not.

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/14314519/190223161-684e9a0e-7186-46ef-abc2-08a43ebe6d28.png">

**Comment by mfazekas** [comment]
@rjdestigter thanks for the bug report, you should be able to just do replace replace all `/RCTLog(.+)/` => `RCTMGLLog$1` in `*.swift`.

Can you submit a PR, for this?!

**Comment by rjdestigter** [comment]
I have a draft started https://github.com/rnmapbox/maps/pull/2214

Going to test this in the repo mentioned above

**Comment by rjdestigter** [comment]
@mfazekas Unfortunately the build is still failing with that solution in place

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/14314519/190243850-69e59600-e77e-4166-8ca5-6067ba2a36cb.png">

**Comment by mysport12** [comment]
@rjdestigter did you update from an older version of the plugin? You should run `pod update` in the iOS folder to make sure it grabs all of the latest changes. I too use react-native-video (v6 alpha build) and don't have any issues building locally or on Bitrise

**Comment by mysport12** [comment]
You may also need a swift bridging header in your iOS project. I didn't see one when I quickly looked at your linked repo

**Comment by rjdestigter** [comment]
@mysport12 What plugin are you referring to?

I added `"@rnmapbox/maps": "https://github.com/rjdestigter/rnmapbox-maps/#issue-2213",` as a dependency and then did a clean install:

```
rm -rf ios/build && rm -rf node_modules && rm -rf ~/Library/Developer/Xcode/DerivedData/ && rm -rf ios/Pods
yarn
cd ios
pod install
```

**Comment by rjdestigter** [comment]
> You may also need a swift bridging header in your iOS project. I didn't see one when I quickly looked at your linked repo

Ah, ok. Any pointers on how to add that?

**Comment by rjdestigter** [comment]
The orignal project I ran into this issue in has a header file added so I'm going to test it in that first

**Comment by rjdestigter** [comment]
Confirmed! Build succeeds in the project that does have the bridging header file in place

**Comment by mysport12** [comment]
Glad to hear you had success in getting it to build with the bridging header in place. Let me know if something else needs attention regarding this issue.

**Comment by mfazekas** [comment]
Let us know if there is anything we can do in @rnampbox/maps to solve it. PR welcome!

**Comment by lmalvasia** [comment]
@mysport12 I'm having the same issue on my current project. I don't have a bridging header, do you know how I can add it? Thanks

**Comment by mysport12** [comment]
@lmalvasia You can add an empty swift file to your project in Xcode and it should prompt you to add a bridging header. If not, you can add a header file to your project with the name being ${APP_NAME}-Bridging-Header and adding the line 

```#import <React/RCTBridgeModule.h>```

Then in Build Settings, go to the Swift Compiler - General section and add the bridging header file to the Objective-C Bridging Header field
