### ISSUE TITLE
[Bug]: React 18 typing error with MarkerView

### ISSUE THREAD

**Issue by azuken** [rnmapbox/maps#2215]
### Mapbox Implementation

Mapbox GL

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

8.6.0-beta.0

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
        <MapboxGL.MarkerView id={'ID'} coordinate={[0, 0]}>
            <Image source={'IMAGE'} />
          </MapboxGL.MarkerView>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

TS2769: No overload matches this call.   Overload 1 of 2, '(props: MarkerViewProps | Readonly<MarkerViewProps>): MarkerView', gave the following error.     Type '{ children: Element; id: string; coordinate: number[]; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<MarkerView> & Readonly<MarkerViewProps>'.       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<MarkerView> & Readonly<MarkerViewProps>'.   Overload 2 of 2, '(props: MarkerViewProps, context: any): MarkerView', gave the following error.     Type '{ children: Element; id: string; coordinate: number[]; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<MarkerView> & Readonly<MarkerViewProps>'.       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<MarkerView> & Readonly<MarkerViewProps>'.

### Expected behavior

No typescript error

**Comment by mfazekas** [comment]
@azuken thanks for the report, unfortunately we don't actively maintain 8.6.0 branch anymore, because lack of resources. Please test with 10.0.0
