### ISSUE TITLE
Are we deprecating `PointAnnotation`?

### ISSUE THREAD

**Issue by naftalibeder** [rnmapbox/maps#2233]
I'm a little unclear about the overlap between `MarkerView` and `PointAnnotation` in v10. Is `PointAnnotation` just a fallback for pre-v10? If so, we should get the Swift file out of the v10 dir.

**Comment by mfazekas** [comment]
See https://github.com/rnmapbox/maps/blob/main/docs/Annotations.md, PointAnnotation is a static image, while MarkerView can host an interactive RN component. Both has it's own advantages/disadvantages.
