### ISSUE TITLE
[Bug]: [iOS v10]: Occasional crash when MapView is unmounted before fully loaded

### ISSUE THREAD

**Issue by wen-kai** [rnmapbox/maps#2240]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.7.0

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';
import {
View,
TouchableOpacity,
} from 'react-native';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  constructor(props) {
    super(props);
    this.state = { showMap: true };
  }
  render() {
    return (
      <View style={{ flex: 1 }}>
        <TouchableOpacity onPress={() => this.setState({ showMap: !this.state.showMap })}>
         <View style={{ width: 100, height: 70, backgroundColor: 'red' }} />
       </TouchableOpacity>
       { this.state.showMap &&
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
      }
      </View>
    );
  }
}
```

### Observed behavior and steps to reproduce

In our app we unmount the MapView onBlur during navigation to a new screen to prevent multiple MapViews from being rendered at once in the navigation view stack. Sometimes if the user navigates too quickly before the map is fully loaded a native exception is thrown as seen below:

`rnmapbox_maps/RCTMGLMapViewManager.swift:32: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2022-09-23 16:33:02.701738-0700 xxx[xxxx] rnmapbox_maps/RCTMGLMapViewManager.swift:32: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

![image (2)](https://user-images.githubusercontent.com/1305459/192114235-e81f38b7-bbe3-4af6-8f24-104380fa8411.png)

### Expected behavior

MapView should unmount without crashing the app

**Comment by mfazekas** [comment]
@wen-kai thanks for the report.

I've tried but could not reproduce on  `v10.0.0-beta.42` and mapbox 10.8.1, and simulator.

Please try with latest version and comment if you can still reproduce
