### ISSUE TITLE
Get Mapbox's default feature collection of street names and places

### ISSUE THREAD

**Issue by flaviokicis** [rnmapbox/maps#2245]
## New Feature

Get the Mapbox's default Feature Collection to use on top of a custom RasterSource

## Why

Cause when I add my custom RasterSource streets and places names disappear, so I'd like to add it on top of the RasterLayer that is covering the default one

**Comment by mfazekas** [comment]
We do have `querySourceFeatures`, pls try to use that

**Comment by flaviokicis** [comment]
Where do I find that? It's not on MapView ref

**Comment by flaviokicis** [comment]
The only method called querySourceFeatures I found is in Java, I need to use it on the JavaScript level.

**Comment by mfazekas** [comment]
Yeah you're probably right, we have ShapeSource.features, but you'd need this on MapView level which we don't have at the moment
