### ISSUE TITLE
[Bug]: Raster Source does not load tiles with dynamically generated URL.

### ISSUE THREAD

**Issue by ansarikhurshid786** [rnmapbox/maps#2246]
### Mapbox Implementation

Mapbox GL

### Mapbox Version

6.9.0

### Platform

iOS

### `@rnmapbox/maps` version

8.5.0

### Standalone component to reproduce

```
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  constructor(){
this.state = {
myRaster: "rasterProvider/export?layers=show:0&bbox={bbox-epsg-3857}&bboxSR=3857&imageSR=3857&size=256,256&transparent=true&format=png&f=image";
}

updateRaster(){
this.setState({ myRaster: newRasterUrl });
}

}
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <MapboxGL.RasterSource id="mySourceId" key="mySourceId" tileUrlTemplates={[myRaster]} minZoomLevel={15} tileSize={256}>
                                <MapboxGL.RasterLayer id="mySourceId2" key="mySourceId" source="mySourceId" />
                            </MapboxGL.RasterSource>
      </MapView>
    );
  }
}
```
```

### Observed behavior and steps to reproduce

_No response_

### Expected behavior

After raster map service update it show that data on the map.

### Notes / preliminary analysis

_No response_

### Additional links and references

I have same issue reported on previous repository
https://github.com/nitaliano/react-native-mapbox-gl/issues/1077

**Comment by mfazekas** [comment]
@ansarikhurshid786 pls try with version 10. We no longer fix bugs in 8.* versions

**Comment by ansarikhurshid786** [comment]
will it support to update url in version 10? I will try and see.

**Comment by DanijelBojcic** [comment]
I have the same issue. Dynamically changing the `tileUrlTemplates` does not reload the `Source`.
What happens is, the `RCTMGLRasterSourceManager.java` class registers the prop change, but the tiles are never rebuilt.
[This](https://github.com/rnmapbox/maps/blob/main/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/sources/RCTMGLTileSource.java#L78) function is only called when the `Source` is mounted.

**Comment by DanijelBojcic** [comment]
I've found a workaround by always changing the key of the Source in JS, this way the native component is always unmounting and remounting.

```javascript
 <MapboxGL.RasterSource
      key={`RasterSource_${Date.now()}`}
      ...
```

**Comment by ansarikhurshid786** [comment]
yes you are right. i update key and id as well so it recreate.

**Comment by tomskopek** [comment]
Thanks for this tip @DanijelBojcic  😄
