### ISSUE TITLE
Error when trying to run android build with Mapbox V10 method

### ISSUE THREAD

**Issue by m0hamad** [rnmapbox/maps#2250]
## Environment
- Dev OS: MacOS 12.6 (Monterey)

## Steps to reproduce

```
Could not determine the dependencies of task ':rnmapbox_maps:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':rnmapbox_maps:debugCompileClasspath'.
   > Could not find com.mapbox.maps:android:10.8.0.
     Required by:
         project :rnmapbox_maps
   > Could not find com.mapbox.mapboxsdk:mapbox-sdk-turf:6.4.0.
     Required by:
         project :rnmapbox_maps
```

I am having this issue when I run `yarn android`, this is my `android/build.gradle` setup:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }

        RNMapboxMapsImpl = "mapbox" // required for v10

    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}

```

I have also configured my secret token by following the instructions here: https://docs.mapbox.com/android/maps/guides/install/

I had issues running the iOS build but after following the instructions on the Mapbox website it worked for Mapbox V10, but I have not had much luck with the Android one, any help would be greatly appreciated, thank you.

**Comment by mfazekas** [comment]
You'll need to add Mapbox maven repo to all repositories. See https://github.com/rnmapbox/maps/blob/main/android/install.md#adding-mapbox-maven-repo

**Comment by m0hamad** [comment]
@mfazekas Thank you. I've gone ahead and added it to the `build.grade` file, but now I am getting this error:

```
Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.8.0/android-10.8.0.pom'. Received status code 401 from server: Unauthorized
```

I've added the secret token to the `gradle.properties` file and followed the remainder of the instructions, any suggestions? Thank you.

**Comment by bimix** [comment]
> @mfazekas Thank you. I've gone ahead and added it to the `build.grade` file, but now I am getting this error:
> 
> ```
> Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.8.0/android-10.8.0.pom'. Received status code 401 from server: Unauthorized
> ```
> 
> I've added the secret token to the `gradle.properties` file and followed the remainder of the instructions, any suggestions? Thank you.

have you found a solution? I am having the same problem
