### ISSUE TITLE
null is not an object (evaluating 'MapboxGL.StyleURL')

### ISSUE THREAD

**Issue by AnatoleLucet** [rnmapbox/maps#2251]
## Environment
- Dev OS: Linux Manjaro

## Steps to reproduce

- Clone this repo : https://github.com/AnatoleLucet/rnmapbox-expo-issue
- Add your Mapbox token in `App.tsx`
- `yarn start`

## Issue

I've been trying to get rnmapbox to work with Expo but I keep facing the following error:
```
TypeError: null is not an object (evaluating 'MapboxGL.StyleURL')
at <project>/node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at <project>/node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at <project>/node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at <project>/node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at <project>/node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.1.45:19000/index.ts.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in global code
```

The error seems to appear on a fresh Expo project after following the [install doc](https://github.com/rnmapbox/maps/blob/main/plugin/install.md) (see the repo in *Steps to reproduce*).

**Comment by mfazekas** [comment]
You'll need to build a client with `eas build` or something like that, pls see expo documentation, you cannot use the prebuild expo go app.
