### ISSUE TITLE
Package @rnmapbox/maps contains invalid configuration

### ISSUE THREAD

**Issue by mmelk** [rnmapbox/maps#2254]
## Environment
- Dev OS: MacBook Pro M1
- React Native version: 0.70
- Node version: 18.9.1
- npm version: 8.19.1

## Steps to reproduce

```sh   
react-native init sample --version react-native@0.70
cd sample
npm install rnmapbox/maps#main --save
# or released version `npm install @rnmapbox/maps@10.0.0-beta.43 --save`
react-native run-android
# or react-native run-ios
```

After these I get this Warning

![image](https://user-images.githubusercontent.com/108338732/192771842-75097533-8cd0-488f-9da6-1cfe56291fdc.png)

**Comment by mfazekas** [comment]
We've added this at: #1824 to work around auto link not working.

It we remove it it'll be a breaking change for older rn cli

> BREAKING CHANGE: it won't work with react-native CLI 4.2.2 as it will search for an xcode project
