### ISSUE TITLE
v10 build failed in Xcode with Cannot find type 'StyleImageMissingPayload' in scope ERROR

### ISSUE THREAD

**Issue by kaiykwok2** [rnmapbox/maps#2255]
## Environment
- Dev OS: Mac OS 12.6
-   "react-native": "^0.64.0",

## Steps to reproduce

1. follow this [guide](https://github.com/rnmapbox/maps/blob/main/ios/install.md) to upgrade from Mapbox gl to Mapbox v10
2. $RNMapboxMapsVersion = '~> 10.6.0' in podfile.  since 10.9.0 is not working
3. pod 'MapboxMaps', '10.6.0' inside target '<appName> do since 10.9.0 is not working
4. npm install, cd iOS and do arch -x86_64 pod install --repo-update in Apple M1 PC
5. clean build folder
6. build in Xcode
7. show below error in Xcode when build to iPhone 11 IOS 14

<img width="453" alt="Screenshot 2022-09-29 at 12 36 28 PM" src="https://user-images.githubusercontent.com/50578218/192939927-eef56e96-8295-4156-a87c-013d4f771b4d.png">

<img width="1167" alt="Screenshot 2022-09-29 at 12 37 13 PM" src="https://user-images.githubusercontent.com/50578218/192940014-90b2fc18-7325-438a-a3d4-2a58963a8cb7.png">

**Comment by mfazekas** [comment]
Remove `$RNMapboxMapsVersion =` I've changed the guide to make it clear that that is only for advanced use cases only.
