### ISSUE TITLE
onRegionDidChange called multiple time 

### ISSUE THREAD

**Issue by babar-ali-memon** [rnmapbox/maps#2259]
### Mapbox Implementation

Mapbox

### Mapbox Version

rnmapbox/maps#main

### Platform

Android

### `@rnmapbox/maps` version

rnmapbox/maps#main

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}
onRegionDidChange={(region)=>{
// this method is calling everytime without changing a region.
}}
>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

onRegionDidChange method is calling multiple times without changing the region.

### Expected behavior

It should be called only when the region is changed completely.

### Notes / preliminary analysis

no notes...

### Additional links and references

no, I can provide the screen recording if needed

**Comment by mfazekas** [comment]
@babar-ali-memon I cannot reproduce this problem with the lates main. Running on android emulator and adding a console.log I only see the msg by console log if the map was changeds
