### ISSUE TITLE
[Bug]: Icons from ShapeSource/Images are much smaller on Android

### ISSUE THREAD

**Issue by KiwiKilian** [rnmapbox/maps#2278]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```tsx
import React from 'react';
import MapboxGL from '@rnmapbox/maps';

import sheet from '../../styles/sheet';
import exampleIcon from '../../assets/example.png';
import pinIcon from '../../assets/pin.png';
import BaseExamplePropTypes from '../common/BaseExamplePropTypes';
import Page from '../common/Page';

const styles = {
  icon: {
    iconImage: ['get', 'icon'],

    iconSize: [
      'match',
      ['get', 'icon'],
      'example',
      1.2,
      'airport-15',
      1.2,
      /* default */ 1,
    ],
  },
};

const featureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'example',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.20611157485, 52.180961084261],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'airport-15',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.205908, 52.180843],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'pin',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.206562, 52.180797],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4553',
      properties: {
        icon: 'pin3',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.206862, 52.180897],
      },
    },
  ],
};

class ShapeSourceIcon extends React.Component {
  static propTypes = {
    ...BaseExamplePropTypes,
  };

  state = {
    images: {
      example: exampleIcon,
    },
  };

  render() {
    const { images } = this.state;

    return (
      <Page {...this.props}>
        <MapboxGL.MapView style={sheet.matchParent}>
          <MapboxGL.Camera
            zoomLevel={17}
            centerCoordinate={[-117.20611157485, 52.180961084261]}
          />
          <MapboxGL.Images
            nativeAssetImages={['pin']}
            images={images}
            onImageMissing={(imageKey) =>
              this.setState({
                images: { ...this.state.images, [imageKey]: pinIcon },
              })
            }
          />
          <MapboxGL.ShapeSource
            id="exampleShapeSource"
            shape={featureCollection}
          >
            <MapboxGL.SymbolLayer id="exampleIconName" style={styles.icon} />
          </MapboxGL.ShapeSource>
        </MapboxGL.MapView>
      </Page>
    );
  }
}

export default ShapeSourceIcon;
```

### Observed behavior and steps to reproduce

Icons added through `Images` are roughly three times smaller on Android than on iOS. Screenshots were made on Simulator of Pixel 3a and iPhone 14 Pro. While it's hard to exactly compare the sizes, the ratios are totaly different when comparing the icons with header or other parts of the map etc. Looking at the screenshots at 100% shows the the map itself is very similar sized, while only the icons differ a lot. Screenshots are taken from the examples `ShapeSourceIcon` and `CustomIcon`.

This comparison was created looking at the screenshots at 100%.

<img width="1512" alt="Icon Bug" src="https://user-images.githubusercontent.com/18724559/194048432-655f33ea-e78c-44d6-a0f0-00154c7aadef.png">

iOS             |  Android
:-------------------------:|:-------------------------:
![Icon Bug iOS 1](https://user-images.githubusercontent.com/18724559/194048517-db8867f9-3587-4b11-8f84-6bef89046730.png)  |  ![Icon Bug Android 1](https://user-images.githubusercontent.com/18724559/194048511-f6298378-7ec3-424e-b032-a586731f9a3f.png)
![Icon Bug iOS 2](https://user-images.githubusercontent.com/18724559/194048518-316905dd-1177-466e-a202-d5200957f85d.png) | ![Icon Bug Android 2](https://user-images.githubusercontent.com/18724559/194048514-117506fb-c82b-49ab-a190-eb00d5260343.png)

### Expected behavior

Look and feel of the sizes should be roughly the same on both platforms.

**Comment by mysport12** [comment]
@KiwiKilian in the interim you can multiple your icon size on Android by the PixelRatio (import from RN). There was a patch on the old version of the plugin that I don't believe has made it over to the latest version yet. I don't have time at the moment, but if I don't see it fixed in the next week or so I'll get a PR in

**Comment by KiwiKilian** [comment]
@mysport12 thanks! Using this as a workaround for now:
```
iconSize: Platform.select({ ios: 0.5, android: PixelRatio.get() * 0.5 }),
```
