### ISSUE TITLE
IOS map styles are not loading

### ISSUE THREAD

**Issue by codemeall** [rnmapbox/maps#2292]
## Environment
- Dev OS: [e.g. OSX 11.0.1]

## Steps to reproduce

```sh   
react-native init sample 
cd sample
yarn add rnmapbox/maps#main
cd ios && pod install
```

The map launches with no style and if I try adding any style it doesn't work

<img width="343" alt="Screenshot 2022-10-12 at 12 55 09 PM" src="https://user-images.githubusercontent.com/30825551/195277191-417ae31e-df58-4eb6-80e8-7a6360239cd0.png">

**Comment by Ajmal0197** [comment]
Follow these links for v10 proper integration and Usage:
https://dev.to/ajmal_hasan/react-native-mapbox-v10-installation-7ga
https://dev.to/ajmal_hasan/react-native-mapbox-v10-usage-4gbp
