### ISSUE TITLE
[Bug]: `minZoomLevel` and `maxZoomLevel` not respected

### ISSUE THREAD

**Issue by SkySails** [rnmapbox/maps#2297]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.32

### Standalone component to reproduce

```javascript
import React from 'react';
import { MapView, Camera } from '@rnmapbox/maps';
import { Text, View } from 'react-native';

const cameraProps = {
  centerCoordinate: [13, 59],
  zoomLevel: 3,
  maxZoomLevel: 5,
  minZoomLevel: 3,
};

const MinMaxZoomReport = () => {
  const [zoomLevel, setZoomLevel] = React.useState(cameraProps.zoomLevel);

  const isBannedZoomLevel = React.useCallback((zl: number) => {
    return zl < cameraProps.minZoomLevel || zl > cameraProps.maxZoomLevel;
  }, []);

  return (
    <>
      <View
        style={{
          flexDirection: 'row',
          justifyContent: 'space-around',
          padding: 10,
        }}
      >
        <Text>Min ZL: {cameraProps.minZoomLevel}</Text>
        <Text>Max ZL: {cameraProps.maxZoomLevel}</Text>
      </View>
      <View
        style={{
          alignItems: 'center',
          marginBottom: 10,
        }}
      >
        <Text style={{ color: isBannedZoomLevel(zoomLevel) ? 'red' : 'black' }}>
          Current ZL: {zoomLevel.toFixed(3)}
        </Text>
      </View>
      <MapView
        style={{ flex: 1 }}
        onRegionIsChanging={(f) => setZoomLevel(f.properties.zoomLevel)}
      >
        <Camera {...cameraProps} />
      </MapView>
    </>
  );
};

export default MinMaxZoomReport;

```

### Observed behavior and steps to reproduce

Add the standalone component to the examples in this repository and open it. The example sets min/max zoomLevels, which are then not respected when zooming in/out in the map.

![Simulator recording of min/max zoomlevels not being respected](https://user-images.githubusercontent.com/46646495/195830077-4feb8bc3-9659-424d-b1c1-f14f6bd02dc6.gif)

### Expected behavior

I expected the map to be limited to zoomLevels between the set min/max values.

### Notes / preliminary analysis

Judging by [this](https://github.com/rnmapbox/maps/blob/v10.0.0-beta.32/ios/RCTMGL-v10/RCTMGLCamera.swift#L339-L345), it looks like there is some work done to limit the zoom values. Perhaps this only applies when changing the camera programmatically through a ref?

**Comment by xharris** [comment]
I'm also experiencing this issue. Additionally, I set `zoomLevel` using a camera ref and `setCamera` and it does not change the zoom level.

**Comment by xharris** [comment]
Nevermind, I turned off `followUserLocation` and `zoomLevel` works for me now.. `minZoomLevel` and `maxZoomLevel` still don't work however.

**Comment by SkySails** [comment]
@mfazekas Thanks for fixing this so quickly! 🙌
