### ISSUE TITLE
[Bug][Android]: MapView.takeSnap method does not resolve on the Android.

### ISSUE THREAD

**Issue by NikitaDudin** [rnmapbox/maps#2299]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.46

### Standalone component to reproduce

```javascript
function Map() {
  const mapRef = useRef(null);

  const takeSnapShot = async () => {
    const uri = await mapRef?.current?.takeSnap(true); // never resolves on the Android platform
  };

  return (
    <MapboxGL.MapView
      ref={mapRef}
      {...}
    >
      {...}
    </MapboxGL.MapView>
  );
}
```

### Expected behavior

Expected: Resolves "takeSnap" MapView method and return result string: path to file or base64 string.  

Actual: Taking MapView snapshot via "takeSnap" method  never resolves on the Android.

**Comment by mfazekas** [comment]
Fixed by #2300
