### ISSUE TITLE
Execution failed for task ':rnmapbox_maps:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by salimsea** [rnmapbox/maps#2301]
## Issue
I am working on a react-native app with Mapbox GL library ("@rnmapbox/maps": "rnmapbox/maps#main"). When I try to run my app for Android, I always get this error :

```sh   
        ..........
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
this is build.gradle setting

![image](https://user-images.githubusercontent.com/49223890/196010652-999e9aef-eb77-4c29-9c10-066da0199285.png)

## Environment
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 87.35 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      Android NDK: Not Found
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
  npmPackages:
    react-native: 0.67.4 => 0.67.4

**Comment by mfazekas** [comment]
Sorry the log you've added contains no relevant info about the failure.
```
Execution failed for task ':rnmapbox_maps:compileDebugJavaWithJavac'.
```

just tells us that there were some issue but doesn't tells us what the issue was

**Comment by zoobibackups** [comment]
Please reopen this. i have still the same ussye
