### ISSUE TITLE
[Bug]: app crash on android when the map finished loading

### ISSUE THREAD

**Issue by kaiykwok2** [rnmapbox/maps#2302]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.8.1

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.47

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
UserLocation
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
    <UserLocation
                                            animated={false}
                                            renderMode={'native'}
                                            onUpdate={updateLocation}
                                            showsUserHeadingIndicator={true}
                                            minDisplacement={30}
                                            visible={true}>
                                        </UserLocation>
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce
![Crash screen](https://user-images.githubusercontent.com/50578218/196317429-46b2f65a-4477-4b20-913a-f285d0c2a420.jpg)

When the userLocation is there, the app will crash when loading map on android platform
when the userLocation is being commented out, it will not crash

**Comment by doylemark** [comment]
Not sure if the same issue as there's no description in this issue other then "crash" but we're seeing the inclusion of TSX components in the beta .47's distribution. (`javascript/components`)

```js
SyntaxError: /Users/markdoyle/orbx/volanta-mobile/node_modules/@rnmapbox/maps/javascript/components/PointAnnotation.tsx: Unexpected token (122:43)

  120 |  */
  121 | class PointAnnotation extends NativeBridgeComponent(
> 122 |   React.PureComponent<PointAnnotationProps>,
      |                                            ^
  123 |   NATIVE_MODULE_NAME,
  124 | ) {
  125 |   static defaultProps = {
```

**Comment by kaiykwok2** [comment]
Please find the crash error screenshot
![Crash screen](https://user-images.githubusercontent.com/50578218/196317338-6b12bd77-8074-447a-92eb-f5287967bbde.jpg)

**Comment by mmelk** [comment]
Same issue here.

**Comment by mfazekas** [comment]
I cannot reproduce it android emulator - Pixel 4 API 26. Also your example  uses `updateLocation` but doesn't define it.


pls check https://stackoverflow.com/questions/74085319/class-was-expected-declaration-of-com-google-android-gms-location-fusedlocatio

**Comment by swey** [comment]
In my case the development in emulator worked fine, but the release build always crashed as well when using `UserLocation`.

```
IncompatibleClassChangeError
Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient'
```
> pls check https://stackoverflow.com/questions/74085319/class-was-expected-declaration-of-com-google-android-gms-location-fusedlocatio

Locking it to version 20.0.0 helped. Hopefully futures versions will be compatible to 21+ as well.

(Don't forget `./gradlew clean` after locking it)
