### ISSUE TITLE
[Bug]: map doesn't load iOS v10 SDK

### ISSUE THREAD

**Issue by vadim312** [rnmapbox/maps#2305]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.7.0

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

When app starts loading map, it crashed with following
![image](https://user-images.githubusercontent.com/75946509/196290822-e3fe1285-a300-473d-8508-b81866487b5b.png)

### Expected behavior

Running without error

### Additional links and references

Packaer debuger: `error: node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx: /Volumes/Data/Github/Vadim/Semih/react-native-mobile-app/node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx: Unknown node type: "TSInstantiationExpression"
`
![image](https://user-images.githubusercontent.com/75946509/196290937-6f14094d-06ae-481e-b8ac-cf25c8239091.png)

**Comment by mfazekas** [comment]
pls attach `npx react-native info`

**Comment by A-Tokyo** [comment]
happens to me as well

**Comment by mfazekas** [comment]
See https://github.com/rnmapbox/maps/issues/2423#issuecomment-1328003731
