### ISSUE TITLE
 module 'Mapbox' not found

### ISSUE THREAD

**Issue by Splicer97** [rnmapbox/maps#2309]
## Environment
- Dev OS: [e.g. OSX 12.6]
-  "react-native": "0.69.3",
- xcode: Version 14.0.1 (14A400)
- ios 16.0
@rnmapbox/maps [10.0.0-beta.47](https://www.npmjs.com/package/@rnmapbox/maps/v/10.0.0-beta.47)
## Steps to reproduce

```sh   
yarn add rnmapbox/maps#main
cd ios && pod install
cd ..
yarn ios
```

**Comment by Ajmal0197** [comment]
Follow these links for v10 proper integration and Usage:
https://dev.to/ajmal_hasan/react-native-mapbox-v10-installation-7ga
https://dev.to/ajmal_hasan/react-native-mapbox-v10-usage-4gbp
