### ISSUE TITLE
Add Android UserLocation heading direction when in "native" render mode v10

### ISSUE THREAD

**Issue by arcticfly** [rnmapbox/maps#2314]
## New Feature
In v8, rendering the UserLocation in native mode with compass enabled gave a pretty smooth and accurate indication of which way the user was facing. In v10, the native Android UserLocation doesn't have a compass indicator at all, and the "normal" (non-native) UserLocation indicator's heading direction is inaccurate and choppy.

Please add heading direction back to the native Android UserLocation indicator.

## Why
This feature will allow Android users to quickly see which direction they are facing without the confusion that comes from "normal" rendering mode inaccuracy and choppiness.

**Comment by mfazekas** [comment]
Please provide a component to reproduce the issue. Android user location component should be much better now.
