### ISSUE TITLE
[Bug]: onRegionDidChange callback unreliable on Android

### ISSUE THREAD

**Issue by arcticfly** [rnmapbox/maps#2317]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.47

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}} onRegionDidChange={() => console.log('onRegionDidChange')}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Once out of every 20 or so times that the region changes, the map takes anywhere from several seconds to more than a minute to fire the `onRegionDidChange` callback.  This is especially evident when the map is zoomed out.

### Expected behavior

The onRegionDidChange callback should be called soon (< 1s) after the map stops moving, as it is on iOS.

**Comment by vadim312** [comment]
same here, also it's called but `visibleBounds` from parameter wrong.
Expected: `[[-122.44491575397831,37.768458362943534],[-122.45328424602278,37.754140944230755]]` on ios
Current: `[[180,90],[-180,90],[-180,-90],[180,-90]]` on android

**Comment by danidaryaweesh** [comment]
Was this solved in later beta versions? can anyone confirm?

**Comment by vadim312** [comment]
> Was this solved in later beta versions? can anyone confirm?

My package.json `"@rnmapbox/maps": "rnmapbox/maps#main"` latest version

**Comment by greenafrican** [comment]
Getting this error too again

```
"@rnmapbox/maps@rnmapbox/maps#main":
  version "10.0.0-beta.46"
...
```

**Comment by veb-ioki** [comment]
Just tested something alike with `"@rnmapbox/maps": "10.0.0-beta.65"`:
by logging several of the `MapView` callback props:

```
 <MapboxGL.MapView
      style={styles.container}
      styleURL={mapStyle}
      onWillStartLoadingMap={() => {
        console.log('>>>MapView onWillStartLoadingMap ');
      }}
      onDidFinishLoadingStyle={() => {
        console.log('>>>MapView onDidFinishLoadingStyle ');
      }}
      onRegionDidChange={reg => {
        console.log('>>>MapView onRegionDidChange ' , reg);
      }}
      onDidFinishRenderingMapFully={() => {
        console.log('>>>MapView onDidFinishRenderingMapFully ');
      }}
      compassEnabled={false}
      {...props}
    >
      {children}
    </MapboxGL.MapView>
  );
```

On Android none of the console.logs show up, whereas they do on iOS as expected.

Sidenote: for `onDidFinishRenderingMapFully` on iOS there is a warning:
`WARN  rnmapbox maps: DidFinishRenderingMapFully is not supported`

**Comment by RyanTG** [comment]
I've also noticed that (on 10.0.10) none of the above console logs show up in Android. Do these functions work in Android? 

We have inconsistent initial map load times on different Android devices, and so it seems useful to use `ondidfinishrenderingmapfully` if it was available.
