### ISSUE TITLE
[Bug]: onTouchEnd stops firing on iOS after modal sheet opened

### ISSUE THREAD

**Issue by arcticfly** [rnmapbox/maps#2318]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.47

### Standalone component to reproduce

```javascript
import React, {useEffect} from 'react';
import MapboxGL, {MapView} from '@rnmapbox/maps';

import {BottomSheetModal, BottomSheetModalProvider} from '@gorhom/bottom-sheet';
import {Button, SafeAreaView, View} from 'react-native';
import {MAPBOX_TOKEN} from './utils';

MapboxGL.setAccessToken(MAPBOX_TOKEN);

const App = () => {
  const bottomSheetModalRef = React.useRef<BottomSheetModal>(null);

  const [sheetOpen, setSheetOpen] = React.useState(false);

  useEffect(() => {
    if (sheetOpen) {
      bottomSheetModalRef.current?.present();
    } else {
      bottomSheetModalRef.current?.dismiss();
    }
  }, [sheetOpen]);

  return (
    <BottomSheetModalProvider>
      <SafeAreaView>
        <MapView
          style={{height: '100%', width: '100%'}}
          onTouchEnd={() => console.log('onTouchEnd')}
        />
        <BottomSheetModal
          ref={bottomSheetModalRef}
          snapPoints={[200]}
          enableContentPanningGesture={false}>
          <View />
        </BottomSheetModal>
        <View
          style={{
            position: 'absolute',
            top: 128,
            right: 32,
            backgroundColor: 'white',
          }}>
          <Button
            title="Toggle sheet"
            onPress={() => setSheetOpen(!sheetOpen)}
          />
        </View>
      </SafeAreaView>
    </BottomSheetModalProvider>
  );
};

export default App;
```

### Observed behavior and steps to reproduce

The MapView stops sending onTouchEnd events once the bottom sheet is opened, and even after it is closed.

Steps to reproduce:

1. Open app
2. Move the map around, tap it etc (notice how 'onTouchEnd' is printed to console)
3. Press the 'Toggle sheet' button to open the sheet
4. Move the map around, tap it etc (notice how 'onTouchEnd' is no longer printed to console)
5. Close the sheet, notice that 'onTouchEnd' is still not printed to console

### Expected behavior

'onTouchEnd' should continue being logged to console.

### Notes / preliminary analysis

When I wrap the MapView in a TouchableWithoutFeedback and listen to `onPressOut` instead of the MapView's `onTouchEnd`, the callbacks continue to be registered after the modal sheet is opened/closed.

### Additional links and references

Working reproducible example: https://github.com/arcticfly/onTouchEndExample

**Comment by Gnative** [comment]
Hi @arcticfly I don't think this is so much an issue with this package but rather how **BottomSheet** and **react-native-gesture-handler** is being used with in the bottom sheet and it needs theses gesture handler events to be draggable.

Have you looked at wrapping the map in the [BottomSheetView](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetview) component ?

Or looked at the Trouble Shooting section with BottomSheet for [Gesture interaction gets conflicted](https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#my-component-gesture-interaction-gets-conflicted-with-bottom-sheet-interactions-)

**Comment by mfazekas** [comment]
@arcticfly pls check [@Gnative's comment above ](https://github.com/rnmapbox/maps/issues/2318#issuecomment-1328953023)
