### ISSUE TITLE
Android Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6

### ISSUE THREAD

**Issue by linhvovan29546** [rnmapbox/maps#2323]
### Versions:

- rnmapbox version: v10.0.0-beta.48
- React Native version: 0.65.1
- Platform: Android

### Description:

- When i build android app it returns this error: Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

<img width="764" alt="Screen Shot 2022-10-21 at 10 11 16 AM" src="https://user-images.githubusercontent.com/84692183/197102636-ff877ec1-9d74-4bb7-b34f-abfdafb7e641.png">

**Comment by linhvovan29546** [comment]
I solved it by adding this line in build.gradle     `kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }`

**Comment by mfazekas** [comment]
@linhvovan29546 thanks, not sure about this, it doesn't seems to be an issue with recent react-native releases. 

Does it have to be added in the library gradle file?! Can't you add this to application level?!

**Comment by linhvovan29546** [comment]
> thanks, not sure about this, it doesn't seems to be an issue with recent react-native releases.
> 
> Does it have to be added in the library gradle file?! Can't you add this to application level?!

Yes, since in my project there are other libraries using 1.6, so i can just add in the library gradle file
