### ISSUE TITLE
[Bug]: onUpdate kept firing even when location is off 

### ISSUE THREAD

**Issue by kaiykwok2** [rnmapbox/maps#2324]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.8.1

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.47

### Standalone component to reproduce

<UserLocation
                                            animated={false}
                                            renderMode={'native'}
                                            onUpdate={()=> console.log("track motion!!")}
                                            showsUserHeadingIndicator={true}
                                            minDisplacement={100}
                                            visible={true}
                                        >
                                        </UserLocation>

### Observed behavior and steps to reproduce

Scenario 1 (Pass):
When the iphone is placed still and location service is on, there is no onUpdate firing

Scenario 2 (Bug):
When moving the iphone (with nearly zero displacement) and location service is ON, onUpdate kept firing when moving the iphone

Scenario 3 (Bug):
When moving the iphone (with nearly zero displacement) and location service is OFF, onUpdate kept firing when moving the iphone

### Expected behavior

onUpdate should not associated to the iphone motion and restricted by the minDisplacement

**Comment by mfazekas** [comment]
Please provide a full component

**Comment by mfazekas** [comment]
This should be addressed in later betas, let me know if it's still happens
