### ISSUE TITLE
[Bug]: CircleLayer onPress not working

### ISSUE THREAD

**Issue by felixerdy** [rnmapbox/maps#2328]
### Mapbox Implementation

Maplibre

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.48

### Standalone component to reproduce

```typescript
import MapboxGL from '@rnmapbox/maps';
import React from 'react';
import {SafeAreaView, View} from 'react-native';

const App = () => {
  return (
    <SafeAreaView>
      <View style={{width: '100%', height: '100%'}}>
        <MapboxGL.MapView style={{flex: 1}}>
          <MapboxGL.ShapeSource
            url="https://api.opensensemap.org/boxes?minimal=true&format=geojson"
            onPress={({features}) => {
              console.log(features);
            }}>
            {/* onPress is not working properly here */}
            <MapboxGL.CircleLayer
              id="circle"
              style={{
                circleColor: '#4eaf47',
              }}
            />

            {/* onPress is working properly here */}
            {/* <MapboxGL.SymbolLayer
              id="symbol"
              style={{
                textField: 'X',
              }}
            /> */}
          </MapboxGL.ShapeSource>
        </MapboxGL.MapView>
      </View>
    </SafeAreaView>
  );
};

export default App;

```

### Observed behavior and steps to reproduce

The remote GeoJSON gets rendered fine by the `CircleLayer` but the `ShapeSource` `onPress` event does not return the clicked circle. It returns features that are either at the north pole or features that are not visible in the viewport or nothing. It depends on the viewport and where you pressed.

Using the `SymbolLayer` with the `textField: "X"` as an example is however working as intended

### Expected behavior

Pressing on a feature of the `CircleLayer` returns the pressed feature

**Comment by mfazekas** [comment]
For me this example doesn't render anything 

![image](https://user-images.githubusercontent.com/52435/198044542-55d36be0-ea7c-4e9e-b13c-e4a8fe6b4e4d.png)

**Comment by felixerdy** [comment]
> For me this example doesn't render anything

Using Mapbox, I wasn't able to render anything as well. Using Maplibre it was working with the mentioned issues however.

**Comment by mfazekas** [comment]
@felixerdy ah thanks sorry, for overlooking that.

**Comment by felixerdy** [comment]
I just did some further testing and came across a strange behaviour that might help to identify the issue

Instead of loading the remote GeoJSON, I added a simple point 
```ts
...

const shape: GeoJSON.FeatureCollection = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {},
      geometry: {
        coordinates: [0, 0],
        type: "Point",
      },
    },
  ],
};

...

<MapboxGL.ShapeSource
  shape={shape}
  onPress={({ features }) => {
    console.log(features[0]);
  }}
>
```

With the position of the point at `[0, 0]`, the `onPress` event gets triggered everywhere on the map. Changing the position to `[0.1, 0.1]` however limits the area `onPress` is triggered to everything south of the point. Additionally, that also depends on the viewport (e.g. `onPress` is not working on zoom level 0)

The Screenshots below indicate the `onPress` "areas" for this example

| `[0, 0]`   |      `[0.1, 0.1]`      |  
|----------|:-------------:|
| ![0](https://user-images.githubusercontent.com/12086004/198264559-afd59999-02cd-4bb7-aaeb-15d02df3e9c8.png) |  ![1](https://user-images.githubusercontent.com/12086004/198264622-d51ec5dd-b1ad-44ea-be46-5576653f44c1.png) |

**Comment by mfazekas** [comment]
That sounds like more an upstream issue, than RN wrapper issue. Sorry we don't have resources to look into maplbre issues.
