### ISSUE TITLE
"Missing package product 'Mapbox'"

### ISSUE THREAD

**Issue by allthetime** [rnmapbox/maps#2332]
## Environment
Xcode Version 13.2.1 (13C100)
react-native 0.63.25
@rnmapbox/maps@^10.0.0-beta.49 ()
macos 12.6 (M1)

## Steps to reproduce

Podfile has:

```
$RNMapboxMapsImpl = 'mapbox'

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
 end
```

Attempting to build debug project for simulator quickly gives this error:
<img width="677" alt="Screen Shot 2022-10-25 at 2 41 24 PM" src="https://user-images.githubusercontent.com/6376965/197887567-1006ed03-386c-4b95-be27-ec8e8d381983.png">

**Comment by majirosstefan** [comment]
same here
