### ISSUE TITLE
Custom tile server with Offlinemanager / serve self-hosted tiles

### ISSUE THREAD

**Issue by ahmedkhelifi** [rnmapbox/maps#2344]
## New Feature
Download tiles for offline use from my own server instead through Mapbox. Add a function to set Tile server before initiating the download.

## Why
Serving thousands of users for non commercial app (free of charge) that need offline maps is insanely expensive. If each  user downloads a region with 6000 tiles, it would only take 34 users to bypass the 200k free tiles and for me to start getting  charged. 
The option the be able to host few regions on my own server and serve the tiles from there would be very useful in that case. Especially if the users are mostly from the same region.

**Comment by mfazekas** [comment]
Not sure about the question, you can use tile servers for vector sources already, can't you?!

**Comment by ahmedkhelifi** [comment]
Sorry if that wasn't clear.

The issue is, I'm downloading third party tiles but yet I'm still being charged by Mapbox. Here's the code I'm using to accomplish this.

```
import MapboxGL from "@rnmapbox/maps"
const ACCESS_TOKEN = "my maptiler access code"
MapboxGL.setAccessToken(ACCESS_TOKEN)
MapboxGL.setWellKnownTileServer(MapboxGL.TileServers.MapTiler)

//Download tiles
download_offline = async() => {
    await MapboxGL.offlineManager.createPack({
        name: route.id,
        styleURL: 'https://api.maptiler.com/maps/xxxxx' ,
        minZoom: zoom,
        maxZoom: zoom+1,
        bounds: [ne, sw]
    }, progressListener, errorListener)
}
```

What I'm basically doing is trying to download tiles from MapTiler for offline use by calling the download_offline function. Yet I'm being charged by Mapbox and the Tile Request API number in my Mapbox account keeps going up whenever I run this.


Also might be important to note, that I'm using Mapbox style for navigation when a user is online use (in a different file). That's where I set my mapbox token key. That's the only way mapbox would know which account to charge.

**My Guess:**
these two lines aren't really doing anything and Mapbox still somehow using the key from the other files and sending the request to Mapbox servers instead (cache??):
```
MapboxGL.setAccessToken(ACCESS_TOKEN)
MapboxGL.setWellKnownTileServer(MapboxGL.TileServers.MapTiler)
```

**Comment by mfazekas** [comment]
@ahmedkhelifi are you using MapLibre implementation!?
  
The report doesn't make sense to me. I mean if you're only having your maptiler access code, then how would it connect to mapbox servers that requires mapbox token to access?
