### ISSUE TITLE
assets folder not included in the node_modules anymore

### ISSUE THREAD

**Issue by BubbleTrouble14** [rnmapbox/maps#2350]
## Environment
- Dev OS:  Win11

## Steps to reproduce

I just updated the library version and now there isn't any assets folder under the node_modules/@rnmapbox anymore. I can verify that it used to be there as I still had an sperate project where I checked what was inside its node_modules. So I think its somehow being excluded from the npm installation for some reason.

Error: 

```sh   
None of these files exist:
  * heading.png
  * node_modules\@rnmapbox\maps\assets\heading.png\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  1 | import React from 'react';
  2 |
> 3 | import headingIcon from '../../assets/heading.png';
    |                          ^
  4 |
  5 | import { SymbolLayer } from './SymbolLayer';
```

**Comment by mfazekas** [comment]
> ## Environment
> * Dev OS:  Win11
> 
> ## Steps to reproduce
> I just updated the library version and now there isn't any assets folder under the node_modules/@rnmapbox anymore. I can verify that it used to be there as I still had an sperate project where I checked what was inside its node_modules. So I think its somehow being excluded from the npm installation for some reason.
> 
> Error:
> 
> ```shell
> None of these files exist:
>   * heading.png
>   * node_modules\@rnmapbox\maps\assets\heading.png\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
>   1 | import React from 'react';
>   2 |
> > 3 | import headingIcon from '../../assets/heading.png';
>     |                          ^
>   4 |
>   5 | import { SymbolLayer } from './SymbolLayer';
> ```

Thanks for the report, can you try `v10.0.0-beta.52` it should have assets folder now.

**Comment by BubbleTrouble14** [comment]
Great thx for the quick reply, as I was a little confused why it was throwing an error all of the sudden.

**Comment by BubbleTrouble14** [comment]
No matching version found for @rnmapbox/maps@^10.0.0-beta.52. Guess I have to wait a little ?

**Comment by BubbleTrouble14** [comment]
@mfazekas Okay running the beta.52. but now it says:

So maybe there still are some stuff missing ?

```
 ERROR  Native part of Mapbox React Native libraries were not registered properly, double check our native installation guides.
 ERROR  TypeError: Cannot read property 'StyleURL' of null, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```
