### ISSUE TITLE
Missing pod spec file on 10.0.0-beta.52

### ISSUE THREAD

**Issue by dpyeates** [rnmapbox/maps#2353]
Upon a pod install you get:

[!] No podspec found for `rnmapbox-maps` in `../node_modules/@rnmapbox/maps`

Looking into the @rnmapbox dir, this is true - the pod spec is missing?

**Comment by NikitaDudin** [comment]
Missed native code into the @rnmapbox dir.

Native code is missing in next versions:
-  10.0.0-beta.50
-  10.0.0-beta.51
-  10.0.0-beta.52

<img width="345" alt="image" src="https://user-images.githubusercontent.com/25579397/198727970-451a5823-3eb7-496a-b462-9c553ac559b1.png">

**Comment by naftalibeder** [comment]
Confirmed, this is the diff that broke it: https://github.com/rnmapbox/maps/compare/eca88f530771f6b412b358587659c1db08f5a56b...e7121889255463f4dfeb01dc1cd43b8d0f622a6f

**Comment by mfazekas** [comment]
Also related to #2351

I've now unpublished the bad packages from npm. 
We'll need to extend the files section to contain index.d.ts and pod spec, and maybe other files.

https://github.com/rnmapbox/maps/blob/0e581d7bc50faeb5f087e16ad9cb97677642a6fa/package.json#L123-L131
