### ISSUE TITLE
> Task :rnmapbox_maps:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by salimsea** [rnmapbox/maps#2354]
## Issue
I'm having trouble installing Mapbox into the project, I've followed the steps given in the document, when I run it gives me an error like this, maybe there's a solution?

I always get this error :

```sh   
> Task :rnmapbox_maps:compileDebugKotlin FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
188 actionable tasks: 16 executed, 172 up-to-date
e: /Volumes/HDD+/SALIM/Proyek/Kantor/GitLab/swg.sch/Swg.Sch.Mobile.Attendance/node_modules/@rnmapbox/maps/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLModule.kt: (115, 55): Unresolved reference: Promise

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 24s
```

![image](https://user-images.githubusercontent.com/49223890/198817027-07ba52c2-d8b3-4780-8af9-b30f6e93f99e.png)

## Environment
 OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 281.03 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
    SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4

**Comment by Crysp** [comment]
I also get this error when trying to build example of android project

**Comment by mfazekas** [comment]
> java-v10/com/mapbox/rctmgl/modules/RCTMGLModule.kt: (115, 55): Unresolved reference: Promise

This was checked in at #2343 

And also I see this error on our CI at
https://github.com/rnmapbox/maps/actions/runs/3344342448/jobs/5538629043

> Task :rctmgl:compileDebugKotlin
[180](https://github.com/rnmapbox/maps/actions/runs/3344342448/jobs/5538629043#step:8:181)
e: /home/runner/work/maps/maps/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLModule.kt: (115, 55): Unresolved reference: Promise

**Comment by ezos86** [comment]
I am still getting this, I just setup the rnmapbox recently - not sure if this error has been resolved for everyone?
