### ISSUE TITLE
How to solve CocoaPods could not find compatible versions for pod "rnmapbox-maps":

### ISSUE THREAD

**Issue by aiibara** [rnmapbox/maps#2355]
[!] CocoaPods could not find compatible versions for pod "rnmapbox-maps":
  In Podfile:
    rnmapbox-maps (from `../node_modules/@rnmapbox/maps`)

Specs satisfying the `rnmapbox-maps (from `../node_modules/@rnmapbox/maps`)` dependency were found, but they required a higher minimum deployment target.

-----------------------

"@rnmapbox/maps" -> "^10.0.0-beta.28",

Podfile
platform :ios, ‘10.0’

$RNMapboxMapsImpl = ‘mapbox’

pre_install do |installer|
 $RNMapboxMaps.pre_install(installer)
end

post_install do |installer|
 $RNMapboxMaps.post_install(installer)
end

**Comment by mfazekas** [comment]
Pls use beta 49 . 50-52 published without podfile
