### ISSUE TITLE
[Bug]: setTelemetryEnabled is undefined

### ISSUE THREAD

**Issue by creitmeier701x** [rnmapbox/maps#2357]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.9.0

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.49

### Standalone component to reproduce

MapboxGL.setTelemetryEnabled(false);
 is undefined function

### Observed behavior and steps to reproduce

 ERROR  TypeError: undefined is not a function

**Comment by mfazekas** [comment]
FWIW iOS was implemented in #2331 which should be in beta52.
