### ISSUE TITLE
TransformError /node_modules/@rnmapbox/maps/javascript/components/Atmosphere.tsx: Unexpected token (4:12)

### ISSUE THREAD

**Issue by aiibara** [rnmapbox/maps#2360]
error: bundling failed: SyntaxError: node_modules/@rnmapbox/maps/javascript/components/Atmosphere.tsx: Unexpected token (4:12)

  

2 | import { HostComponent, requireNativeComponent } from 'react-native';
  3 | 
> 4 | import type { AtmosphereLayerStyleProps } from '../utils/MapboxStyles';
    |             ^
  5 | import { StyleValue, transformStyle } from '../utils/StyleValue';
  6 | 
  7 | export const NATIVE_MODULE_NAME = 'RCTMGLAtmosphere';
 LOG  BugReporting extraData: {"AppRegistry.runApplication1": "Running \"Orbit\" with {\"rootTag\":1,\"initialProps\":{}}"}

##Environment
- "react-native": "0.61.5"
- "@rnmapbox/maps": "^10.0.0-beta.49"

**Comment by mfazekas** [comment]
@aiibara I think the issue is that your babel version is too old and doesn't support the `import type` syntax introduced in typescript 3.8. 

What babel version do you have?! Esp. what is your babel-plugin-transform-typescript version.

See also https://github.com/babel/babel/pull/11173
