### ISSUE TITLE
[Expo] PluginError: Package "@rnmapbox/maps" does not contain a valid config plugin.

### ISSUE THREAD

**Issue by thomasgrivet** [rnmapbox/maps#2361]
## Environment
- Dev OS: macOS 12.2.1

## Steps to reproduce

Hello, I created a new Expo project using `npx create-expo-app testapp` and `yarn add @rnmapbox/maps` as well as adding the necessary plugins entries in my app.json.
However, I always get the same error when trying to `yarn start` which is:

```
PluginError: Package "@rnmapbox/maps" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module
```

**Comment by mfazekas** [comment]
@thomasgrivet thanks, which @rnmapbox/maps do you have installed?!

**Comment by thomasgrivet** [comment]
Thanks for the quick answer! I'm currently using 10.0.0-beta.49 as it is the last one which works for me, the 53 throw the error

**Comment by tooniwi** [comment]
Same issue with ver 10.0.0-beta.53 happened to me.

**Comment by KiwiKilian** [comment]
Looking good with 10.0.0-beta.54.
