### ISSUE TITLE
[Bug]: Possible memory leak with Map

### ISSUE THREAD

**Issue by mysport12** [rnmapbox/maps#2366]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.9.0

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.54

### Standalone component to reproduce

```javascript
import MapboxGL from '@react-native-mapbox-gl/maps'
import * as React from 'react'
import { View } from 'react-native'
import { Footer } from '../components'

export default function MapStripped() {
  return (
    <View style={{ flex: 1 }}>
      <MapboxGL.MapView styleURL="mapbox://styles/mapbox/streets-v11" style={{ flex: 1 }} />
      <Footer />
    </View>
  )
}
```

### Observed behavior and steps to reproduce

Note: Footer in example code is simply a tab bar to navigate between screens

The map is not cleaning up its memory usage when unmounted (like on a screen switch) and subsequent loads of the map screen adds to the memory consumption until eventually the app crashes for OOM. Our app is using react-navigation with a drawer navigator where the screens are unmounted on blur.

Here is the memory graph switching back and forth between the barebones map screen provided and our Home screen:

<img width="946" alt="Screenshot 2022-10-31 at 4 49 57 PM" src="https://user-images.githubusercontent.com/10301026/199107930-0f6251d3-61f2-4aa6-b074-da4735388706.png">

Here is the memory graph for the switching back and forth between the same Home screen and another one of our screens that has a lot of images on it. The initial spike at the beginning of the graph is the map screen.

<img width="914" alt="Screenshot 2022-10-31 at 4 28 58 PM" src="https://user-images.githubusercontent.com/10301026/199107032-d27e5093-26f3-4596-97e5-01f90d779fd6.png">

### Expected behavior

Map should properly clean up its memory consumption when unmounted

**Comment by mfazekas** [comment]
@mysport12 thanks much for the report! 

Using memory graph in Xcode (
![image](https://user-images.githubusercontent.com/52435/199240622-b02e86ca-7bfd-4c08-9bfe-c2c81e7c0081.png)) and filtering for RCTMGLMapView it's easy to see that it's indeed a leak, caused by retain cycles. Added a fix for it in #2372

**Comment by mysport12** [comment]
@mfazekas I found a few more yesterday (in addition to the changes you pushed earlier).

https://github.com/mysport12/maps/commit/3a1738d9021ddd337d1fd49ef285fe12e5fc47df
https://github.com/mysport12/maps/commit/6b37fdd91cee66373c5213516121e67b7a5980a1

As a result of all the changes made, seeing dramatically better memory consumption/cleanup

**Comment by mfazekas** [comment]
> @mfazekas I found a few more yesterday (in addition to the changes you pushed earlier).
> 
> [mysport12@3a1738d](https://github.com/mysport12/maps/commit/3a1738d9021ddd337d1fd49ef285fe12e5fc47df) [mysport12@6b37fdd](https://github.com/mysport12/maps/commit/6b37fdd91cee66373c5213516121e67b7a5980a1)
> 
> As a result of all the changes made, seeing dramatically better memory consumption/cleanup

I'm not sure all of that is necessary, for example keeping a strong reference to bridge should not be an issue.

**Comment by mysport12** [comment]
Created a new PR #2377

**Comment by mysport12** [comment]
Noted. Happy to make any changes you propose
