### ISSUE TITLE
Expo: android error when building app with mapbox and @rnmapbox/maps beta54

### ISSUE THREAD

**Issue by saltron85** [rnmapbox/maps#2367]
## Environment
- Dev OS:  windows 11

## Steps to reproduce

start a new project and install @rnmapbox/maps

then build the project using eas build -p android

here are some pics of my set up and error

<img width="1343" alt="Screenshot 2022-10-31 155340" src="https://user-images.githubusercontent.com/116847540/199124957-eba48d93-bd14-428f-b940-9a29
<img width="1343" alt="Screenshot 2022-10-31 155319" src="https://user-images.githubusercontent.com/116847540/199124973-2ada0f77-4e4a-469b-a4a9-0b726cf871f4.png">
ba3cf49d.png">
<img width="1921" alt="Screenshot 2022-10-31 155227" src="https://user-images.githubusercontent.com/116847540/199124983-d8dcdfed-2f99-4c62-a59b-472d938dd8f4.png">

**Comment by mfazekas** [comment]
Somehow mapbox repos was not added to gradle

**Comment by saltron85** [comment]
I think I know why after reading further. The key I used wasn't the right one. I used the old key we were using for mapbox-gl think it's not valid and I have to create one.

**Comment by mfazekas** [comment]
Oh access issue can be also the cause for this.
