### ISSUE TITLE
iconImage can also be a string, but not according to Typescript

### ISSUE THREAD

**Issue by YousefED** [rnmapbox/maps#2380]
https://github.com/rnmapbox/maps/blob/edbbea8dfe5e82ef326e4996e08f87644a7d8658/javascript/utils/MapboxStyles.d.ts#L700

If I understand it correctly, we can pass a `string` to iconImage when using an [Images](https://github.com/rnmapbox/maps/blob/main/docs/Images.md) component to define assets.

However, the Typescript definition of iconImage doesn't accept a string

**Comment by VolkerLieber** [comment]
Can you please provide an example of the string you are trying to use?

**Comment by MorganDavid** [comment]
with locationBlue and locationDark in the Images component, this works, but fails typecheck.
```js
  style={{
    iconImage: selectedLocality
      ? [
          "match",
          ["get", "localityCode"],
          selectedLocality?.localityCode,
          "locationBlue",
          "locationDark",
        ]
      : "locationDark",
  }}
```

**Comment by VolkerLieber** [comment]
I think the mapbox way to do it would be: `iconImage: ['image', 'IMAGE_KEY']` which works
