### ISSUE TITLE
setup-jest.js no longer included in package

### ISSUE THREAD

**Issue by cameronmurphy** [rnmapbox/maps#2384]
This commit (https://github.com/rnmapbox/maps/commit/e7121889255463f4dfeb01dc1cd43b8d0f622a6f) added a list of files to be included in the package, and `setup-jest.js` isn't in the list. So if you configure Jest as per the README, running Jest throws this error:

```
● Validation Error:

  Module @rnmapbox/maps/setup-jest in the setupFilesAfterEnv option was not found.
```

README jest config:
```
"setupFilesAfterEnv": ["@rnmapbox/maps/setup-jest"],
```

## Environment
- Dev OS: macOS 13.0 (22A380)

**Comment by mfazekas** [comment]
Fixed by: https://github.com/rnmapbox/maps/commit/ee91c8137a5038db1a718590ea98e2f879104c56
