### ISSUE TITLE
Expo Config-Plugin Dependencies 

### ISSUE THREAD

**Issue by KiwiKilian** [rnmapbox/maps#2389]
## Why
With the release of Expo SDK 47 the expo team has released [docs](https://docs.expo.dev/guides/config-plugins/#installing-dependencies) on how to add the dependencies for an expo config-plugin and how to import them. @rnmapbox/maps should adhere to this guide. The [release post](https://blog.expo.dev/expo-sdk-47-a0f6f5c038af) describes the benefits:

>  This will save you time in the future because you won’t need to update the @expo/config-plugins version for each release anymore, and your library will be immediately compatible with new expo releases (provided that there have been no breaking changes to the config-plugins API, which is relatively stable at this point).

## Problem
@rnmapbox/maps currently uses the following private APIs:

```js
import {
  mergeContents,
  removeGeneratedContents,
} from '@expo/config-plugins/build/utils/generateCode';
```

So it's not currently possible to completely adhere to the new guide.
While we can apply most of the suggestions, I would like to keep this issue as a todo until these two methods are re-exported aswell, see https://github.com/expo/expo/pull/18855#issuecomment-1248803973.

**Comment by KiwiKilian** [comment]
@mfazekas shall I copy the private functions over as [mentioned here](https://github.com/expo/expo/pull/18855#issuecomment-1309550520)?

**Comment by mfazekas** [comment]
@KiwiKilian yep I think it makes sense
