### ISSUE TITLE
[Bug]: PointAnnotation onSelected should not be called on double tap

### ISSUE THREAD

**Issue by bviebahn** [rnmapbox/maps#2395]
### Mapbox Implementation

Maplibre

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.56

### Standalone component to reproduce

```javascript
import { Camera, MapView, PointAnnotation } from '@rnmapbox/maps';
import React from 'react';
import { View } from 'react-native';

function BugReportExample() {
    const [color, setColor] = React.useState('#f00');
    return (
        <MapView style={{ flex: 1 }}>
            <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
            <PointAnnotation
                key={color}
                coordinate={[-74.00597, 40.71427]}
                onSelected={() => {
                    console.log('onSelected');
                    setColor((c) => (c === '#f00' ? '#0f0' : '#f00'));
                }}
            >
                <View
                    style={{
                        width: 50,
                        height: 50,
                        backgroundColor: color,
                    }}
                />
            </PointAnnotation>
        </MapView>
    );
}

export default BugReportExample;
```

### Observed behavior and steps to reproduce

When double tapping on a PointAnnotation, `onSelected` is called. This only happens on iOS. I think this is a bug and `onSelected` should not be called, or there should be some way to detect if it was a single or double tap.

### Expected behavior

onSelected should not called on double tap.

**Comment by mfazekas** [comment]
Seems to be fixed with 10.10.0 update, could not repro with v10 on the current main

https://github.com/mapbox/mapbox-maps-ios/blob/main/CHANGELOG.md#changelog-for-mapbox-maps-sdk-v10-for-ios
