### ISSUE TITLE
[Bug]: jest setup-tests files does not exist.

### ISSUE THREAD

**Issue by A-Tokyo** [rnmapbox/maps#2399]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

v10.0.0-beta.56

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

add this to jest.config.js as per documentation
```
  setupFilesAfterEnv: [
    '@rnmapbox/maps/setup-jest',
  ],
```

Run tests `yarn test`

Jest crashes with file not found exception

### Expected behavior

'@rnmapbox/maps/setup-jest' file should be exported and available in the NPM package

**Comment by mfazekas** [comment]
This should be fixed in latest beta: 
https://github.com/rnmapbox/maps/blob/894f9a212b060d265e6cbe77748c4417d2d1812d/package.json#L134
