### ISSUE TITLE
[Bug]:< MapboxGL.Terrain> throws Invariant Violation: requireNativeComponent: "RCTMGLTerrain" was not found in the UIManager.

### ISSUE THREAD

**Issue by ahmedkhelifi** [rnmapbox/maps#2400]
### Mapbox Implementation

Maplibre

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

v10.0.0-beta.56

### Standalone component to reproduce

```
class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        ...
        <MapboxGL.Terrain sourceID="terrainSource" exaggeration={2} />
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

The error happens whenever you try to use MapboxGL.Terrain, even in a new empty project.
The following error is thrown and the app crashes:

`Invariant Violation: requireNativeComponent: "RCTMGLTerrain" was not found in the UIManager.
`

(Same error happens if you also try to use [RasterDemSource](https://github.com/rnmapbox/maps/blob/main/docs/RasterDemSource.md) as well)

### Expected behavior

Be able to add terrain layer and exagerate it to create 3D effect

**Comment by ahmedkhelifi** [comment]
Also wondering, is there maybe another way to set terrain? Trying to add 3D terrain by adding a 'raster-dem'. On Maplibre-gl in React I did it as following:

```
    useEffect(() => {
        const map = new maplibregl.Map({
            container: mapContainerRef.current,
            style: 'styleurl',
            center: [11.39085, 47.27574],
            zoom: 12,
            pitch: 52,
        });

        map.on('load', () => {
            map.addSource("terrain", {
                "type": "raster-dem",
                "url": "url_here",
            })
            map.setTerrain({
                source: "terrain",
                exaggeration: 2
            })
        });

        return () => {
            map.remove();
        }
    }, []);
```

🙂

**Comment by ahmedkhelifi** [comment]
UPDATE:
So playing around with the code, it appears that <MapboxGL.Terrain> is only a feature of Mapbox V10 and not Maplibre SDK at the moment 😢.

**Comment by mfazekas** [comment]
Closing as it's maplibre issue.
