### ISSUE TITLE
StyleURL not working properply

### ISSUE THREAD

**Issue by Kevinminh** [rnmapbox/maps#2404]
## Environment
- IOS 16.1 - React Native
## Steps to reproduce

1.MapboxGL.setAccessToken("<My TOKEN IS HERE>");
2. I try to set StyleURL="mapbox://styles/mapbox/streets-v11" inside MapBoxGL.Mapview 
3. I Build The app "npm run iOS"
4. The app opens with The map bring black. I can see mapbox logo.

this text displays in The terminal: [appName] Failed loading map Error Domain=MGLErrorDomain Code=5 "The map failed to load because the style can't be loaded." UserInfo={NSLocalizedDescription=The map failed to load because the style can't be loaded.,
NSLocalizedFailureReason=loading style failed: unsupported URL}

What am doing that is wrong?

**Comment by Kevinminh** [comment]
So this works fine on Android, the style is loading. However, this seems to only be a problem on IOS for some reason. 
![image](https://user-images.githubusercontent.com/56735050/201470138-52d5516e-cf66-4e49-9fb6-f612edc39629.png)

**Comment by mfazekas** [comment]
@Kevinminh maybe you're using maplibre implementation. Have you configured `RNMapboxMapsImpl`?!

```pod
$RNMapboxMapsImpl = 'mapbox'
```

https://github.com/rnmapbox/maps/blob/main/ios/install.md#mapbox-maps-sdk-v10
