### ISSUE TITLE
[Bug]: Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'

### ISSUE THREAD

**Issue by hellforever** [rnmapbox/maps#2411]
### Mapbox Implementation

Mapbox GL

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

8.5.0

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Notes / preliminary analysis

Upgrade React Native version to 0.70, Mapbox uses ViewPropTypes which have been removed from React Native, please adapt to the latest RN version

**Comment by hellforever** [comment]
@danidaryaweesh But the setup was changed and there is still no stable version, do you have any ideas when the stable version will be released?

**Comment by danidaryaweesh** [comment]
@hellforever Yes that's correct. I followed the slightly changed setup and was able to run exact same code pre v10 Mapbox SDK on version v10.0.0-beta.54 of this library. I tried V10, but it was not stable enough for production in my opinion and for that reason I decided to wait.

**Comment by chris-gaona** [comment]
The following worked for me if you're using version 8 still. I am using version `8.6.0-beta.0` & was getting this `ViewPropTypes` warning (it looks like this warning is actually changed to throw an error in the latest version of react-native ). I noticed the `ViewPropTypes` fix is in the latest code changes in the `v8` branch so I installed the latest from the `v8` branch using `yarn add https://github.com/rnmapbox/maps.git#v8` & the warning no longer shows up. Keep in mind that this warning could still show up for you if any of your other deps still uses the deprecated `ViewPropTypes`.

**Comment by mfazekas** [comment]
Should be fixed in v8 branch, and also in main and v10 release. We don't plan to release more from the old version.

**Comment by everettblakley** [comment]
> The following worked for me if you're using version 8 still. I am using version `8.6.0-beta.0` & was getting this `ViewPropTypes` warning (it looks like this warning is actually changed to throw an error in the latest version of react-native ). I noticed the `ViewPropTypes` fix is in the latest code changes in the `v8` branch so I installed the latest from the `v8` branch using `yarn add https://github.com/rnmapbox/maps.git#v8` & the warning no longer shows up. Keep in mind that this warning could still show up for you if any of your other deps still uses the deprecated `ViewPropTypes`.

@chris-gaona thank you for this! I am trying to upgrade an app that's on a deprecated Expo version, so I'm taking it version by version. This got me past that dreaded `ViewPropTypes` error. Still planning on migrating to v10 of this library, but was stuck on this issue for far too long.
