### ISSUE TITLE
[Bug]: Vertical panning inside ScrollView not working

### ISSUE THREAD

**Issue by saeedghasemi72** [rnmapbox/maps#2413]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.9.0

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.57

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
<ScrollView style={{
    alignItems: "center",
    direction: "ltr",
    flex: 1,
    justifyContent: "center",
  }}>
 // other components
      <View style={{    height: "100%",
          position: "relative",
          width: "60%"
      }}>
        <MapView style={{flex: 1}}>
          <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
          <ShapeSource id="idStreetLayer" shape={aLine}>
            <LineLayer id="idStreetLayer" />
          </ShapeSource>
        </MapView>
      </View>
// other components
</ScrollView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Hi guys, when I use MapBox inside ScrollView, panning (vertical) map not working, and parent ScrollView panning worked.
this issue exist just in android.

### Expected behavior

panning on map

**Comment by mfazekas** [comment]
I ge this when I try to run the example provided:

![image](https://user-images.githubusercontent.com/52435/203748242-6f3a4c86-aa95-427c-81c0-995dc766dea7.png)

**Comment by Miyaguisan** [comment]
Sorry, not the author and I know this issue was closed.

But this is a problem on Android.
Here's the same example from the author, without the error:

<h3>Observed behavior and steps to reproduce</h3>

```JavaScript
import React from 'react';
import { ScrollView } from 'react-native';
import {
  Camera,
  MapView,
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <ScrollView style={{flex: 1}}>
        // other components
        <MapView style={{
          height: "60%",
          width: "100%"
        }}>
          <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        </MapView>
        // other components
      </ScrollView>
    );
  }
}
```

When MapView is inside a ScrollView:
* Panning vertically won't work on <b>Android</b>, but horizontal does.

On iOS it works perfectly fine in both directions.

**Comment by samuelgja** [comment]
Please some fix for this?
