### ISSUE TITLE
[Bug][MapboxV10] wrong getCoordinateFromView on Android

### ISSUE THREAD

**Issue by Alaa-Ben** [rnmapbox/maps#2416]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.57

### Standalone component to reproduce

```javascript
import React, { useRef, useState } from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
  CircleLayer,
} from '@rnmapbox/maps';
import { Dimensions } from 'react-native';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

const BugReportExample = () => {
  const { width, height } = Dimensions.get('window');
  const [centerPoint, setCenterPoint] = useState({
    type: 'Point',
    coordinates: [-74.00597, 40.71427],
  });
  const center = [width / 2, height / 2];
  const mapRef = useRef();
  const onRegionDidChange = async () => {
    const centerInCoords = await mapRef?.current?.getCoordinateFromView?.(
      center,
    );
    setCenterPoint({
      type: 'Point',
      coordinates: centerInCoords,
    });
    console.log(centerInCoords);
  };
  return (
    <MapView
      style={{ flex: 1 }}
      ref={mapRef}
      onRegionDidChange={onRegionDidChange}
    >
      <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
      <ShapeSource id="idStreetSource" shape={aLine}>
        <LineLayer id="idStreetLayer" />
      </ShapeSource>
      <ShapeSource id="idCenterSource" shape={centerPoint}>
        <CircleLayer
          id="idCenterLayer"
          style={{ circleColor: 'red', circleRadius: 3 }}
        />
      </ShapeSource>
    </MapView>
  );
};

export default BugReportExample;
```

### Observed behavior and steps to reproduce

Hello !
Seems like [this old issue](https://github.com/rnmapbox/maps/issues/576) has come back to life.
Just call the getCoordinateFromView on the same pixel point, and you won't get the same values depending on the platform. 
It's correct on IOS, wrong on Android.
In my practical case, I discovered this because my app has markers. And when I was on 8.5.0, my algo was working, but not anymore on v10. 

### Expected behavior

getCoordinateFromView should return correct values on Android

**Comment by nixolas1** [comment]
I am still experiencing this bug on latest release 10.0.0-beta.62 (checked installed package.json version to make sure)
` let point = await map.current.getPointInView([longitude, latitude])
    const newCoords = await map.current.getCoordinateFromView(point)
    console.log(newCoords, [longitude, latitude])
    ...
    [11.797216544651832, 60.90877448620131] [11.750504, 60.928799]
    `

**Comment by FrederickEngelhardt** [comment]
I think for some of the 10.0.6 or lower I was seeing this. Had to write a workaround

```javascript
      const viewPoint = await current.getPointInView(coordinates)
      /**
       * @deprecated the return value is in pixels and needs to be converted.
       *
       */
      const offsetInDP = viewPoint[1] / PixelRatio.getPixelSizeForLayoutSize(1)
```

**Comment by trungledangAxonActive** [comment]
> I think for some of the 10.x.x for android you need this workaround due to it returning the actual pixels not the pixel density that react-native uses.
> 
> ```js
>       const viewPoint = await current.getPointInView(coordinates)
>       /**
>        * @deprecated the return value is in pixels and needs to be converted.
>        *
>        */
>       const offsetInDP = viewPoint[1] / PixelRatio.getPixelSizeForLayoutSize(1)
> ```

@FrederickEngelhardt I think it should be PixelRatio.get() instead of PixelRatio.getPixelSizeForLayoutSize(1), because 
PixelRatio.getPixelSizeForLayoutSize will round the returned value which may not be precise. 
![image](https://github.com/rnmapbox/maps/assets/111328770/b1f74b9d-42b5-4c5e-b196-b3c3e82d37a4)

**Comment by chris-gaona** [comment]
Thanks for the information. I just ran into this issue as well where my algorithm using `getPointInView` worked with version 8 on Android but not in version 10. I can confirm that `PixelRation.get()` seems to be the more accurate approach that fixed my issue. Thanks!
