### ISSUE TITLE
[Bug][MapboxV10] Map not showing on simulator on IOS 12.4

### ISSUE THREAD

**Issue by Alaa-Ben** [rnmapbox/maps#2417]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.57

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

I have simulators and devices running different IOS versions.
On simulator IOS 16, the map is displayed.
On device IOS 15, the map is displayed.
On simulator IOS 12.4, the map isn't displayed (but the scale is).

### Expected behavior

Map is displayed for IOS 11+ (it's the min version required on the native IOS SDK)
<img width="362" alt="Capture d’écran 2022-11-16 à 11 32 39" src="https://user-images.githubusercontent.com/26058727/202157264-418e759a-c63d-47c8-a6bf-f47f4d8158b4.png">

**Comment by mfazekas** [comment]
Sounds like an upstream issue, we're happy to accept patches for this, but sorry we don't have time to investigate
