### ISSUE TITLE
[Bug]: Swift error abort trap 6

### ISSUE THREAD

**Issue by devWaleed** [rnmapbox/maps#2422]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.57

### Standalone component to reproduce

Unable to build the app. No components used so far.

### Observed behavior and steps to reproduce

❌  error: compile command failed due to signal 6 (use -v to see invocation)
.
.
.
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening ec.xcworkspace. Run CLI with --verbose flag for more details.
.
.
.

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/waleed/Desktop/ec/ec-admin/packages/mobile/node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLCamera.swift (in target 'rnmapbox-maps' from project 'Pods')
	CompileSwift normal x86_64 /Users/waleed/Desktop/ec/ec-admin/packages/mobile/node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLCameraManager.swift (in target 'rnmapbox-maps' from project 'Pods')
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'rnmapbox-maps' from project 'Pods')
(3 failures)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mobile@0.0.1 debug-ios-qa: `react-native run-ios --scheme "Ec-QA" --simulator='iPhone 13 Pro Max' && wml start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mobile@0.0.1 debug-ios-qa script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waleed/.npm/_logs/2022-11-17T09_58_02_820Z-debug.log
waleed@waleed-baig-1329 mobile % 

### Notes / preliminary analysis

xCode Version 13.1 (13A1030d)

I am not able to install the latest Mapbox version on my iOS platform.

### Additional links and references

1

**Comment by mfazekas** [comment]
Can you try with Xcode 14.1?!
We're happy to accept patch that doesn't crash the compiler on 13.1 but we don't have time investigate this.

**Comment by devWaleed** [comment]
Xcode 14.1 fixes the issue and I am able to build and run the app in the simulator.
