### ISSUE TITLE
[Bug]: React Native IOS pins (MapboxGL.PointAnnotation) disappears when zooming in or zooming out

### ISSUE THREAD

**Issue by thillendrin-poovalingam** [rnmapbox/maps#2424]
### Mapbox Implementation

Mapbox GL

### Mapbox Version

10.0.0-beta.11

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

```jsx
const Marker = () => (
  <View>
    <Image
      source={require('./pin.png')}
      style={{height: 32, width: 32, resizeMode: 'contain'}}
    />
  </View>
);

const PointAnnotationCrossPlatorm = props =>
  Platform.select({
    ios: (
      <MapboxGL.PointAnnotation {...props}>
        <Marker />
      </MapboxGL.PointAnnotation>
    ),
    android: <MapboxGL.PointAnnotation {...props} />,
  });

  /**
   * This shows the final soil sampling after placing pins from grid view (Red points) before confirming
   */
  displayPins() {
    if (
      this.state.showSoilSamplePins &&
      this.state.soilSampleCentrePoints &&
      this.state.soilSampleCentrePoints.length > 0
    ) {
      let pins = this.state.soilSampleCentrePoints.map((point, index) => {
        return (
          <PointAnnotationCrossPlatorm
            key={JSON.stringify(point.geometry.coordinates)}
            id={'FarmPins' + index}
            coordinate={point.geometry.coordinates}
            anchor={{x: 0.5, y: 1}}
            draggable={true}
            onDragStart={this.soilSampleOnDrag}
            onDragEnd={this.soilSampleOnDragEnd}
          />
        );
      });
      return pins;
    }
  }



  /**
   * Main render view of the all the renders
   */
  renderMain() {
    return (
      <View
        style={styles.fixedcontainer}
        onLayout={event => {
          this.viewLayout(event);
        }}>
        <MapboxGL.MapView
          ref={ref => (this.myMapView = ref)}
          style={monStyles.map}
          styleURL={this.state.mapType}
          zoomEnabled={this.state.mapViewZoomEnabled}
          rotateEnabled={this.state.mapViewRotateEnabled}
          scrollEnabled={this.state.mapViewScrollEnabled}
          onLongPress={this.onStartShouldSetResponder}
          onTouchEnd={this.onTouchEnd}
          onPress={this.onPress}
          logoEnabled={false}>
          <MapboxGL.Camera
            ref={ref => (this.mapViewCameraRef = ref)}
            // pass coordinates for the current location
            centerCoordinate={
              !this.state.showSoilSampleCenter
                ? [this.state.longitude, this.state.latitude]
                : [0, 0]
            }
          />
          {this.displayPins()}
        </MapboxGL.MapView>
        <SafeAreaInsetsContext.Consumer>
          {({bottom}) => (
            <Toast
              ref={c => {
                this.toast = c;
              }}
              style={{
                backgroundColor: '#147efb',
                bottom: bottom > 16 ? bottom : 16,
              }}
            />
          )}
        </SafeAreaInsetsContext.Consumer>
      </View>
    );
  }
  render() {
    return <SafeAreaProvider>{this.renderMain()}</SafeAreaProvider>;
  }
```

### Observed behavior and steps to reproduce

On IOS:
Generate pins to display within boundaries of a Polygon. 

- Firstly, it takes long to display 
- When zooming in or out, the pins disappear and reappear randomly. Sometimes the pins do not reappear at all.

### Expected behavior

Pins should always display irrespective of the zoom level

**Comment by mfazekas** [comment]
pls include a standalone example, we can just put to into our test app.  

Like this one: 
https://github.com/rnmapbox/maps/blob/main/example/src/examples/BugReportExample.js

The example you provided uses `soilSampleCentrePoints` for example but it doesn't defines it

**Comment by thillendrin-poovalingam** [comment]
import React from 'react';
import {View, Platform} from 'react-native';

/** Mapbox */
import MapboxGL from '@react-native-mapbox-gl/maps';
import {SafeAreaProvider} from 'react-native-safe-area-context';

const farms = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: {
        key: 0,
        FIELDNAME: 'T1',
        color: 'black',
        fill: 2,
        fillColor: 'rgba(123,239,178,0.3)',
      },
      geometry: {
        type: 'Polygon',
        coordinates: [
          [
            [27.083133502638844, -26.753195393053446],
            [27.090952158060333, -26.744334739728693],
            [27.082568298625148, -26.73794118123736],
            [27.074592642087595, -26.74725098036823],
          ],
        ],
      },
    },
  ],
  fileName: 'Boundary',
};

const soilSamplePins = [
  {
    geometry: {
      coordinates: [27.081969148728703, -26.73873178682836],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.081969148728703, -26.740742830706886],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.084221008113516, -26.740742830706886],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.079717290170166, -26.742753839759807],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.081969148728703, -26.742753839759807],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.084221008113516, -26.742753839759807],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.086472868315198, -26.742753839759807],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.088724726047516, -26.742753839759807],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.077465430794675, -26.744764813976964],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.079717290170166, -26.744764813976964],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.081969148728703, -26.744764813976964],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.084221008113516, -26.744764813976964],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.086472868315198, -26.744764813976964],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.088724726047516, -26.744764813976964],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.07521357172554, -26.74677575042162],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.077465430794675, -26.74677575042162],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.079717290170166, -26.74677575042162],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.081969148728703, -26.74677575042162],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.084221008113516, -26.74677575042162],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.086472868315198, -26.74677575042162],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.088724726047516, -26.74677575042162],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.077465430794675, -26.748786653502407],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.079717290170166, -26.748786653502407],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.081969148728703, -26.748786653502407],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.084221008113516, -26.748786653502407],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.086472868315198, -26.748786653502407],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.079717290170166, -26.750797519545003],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.081969148728703, -26.750797519545003],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
  {
    geometry: {
      coordinates: [27.084221008113516, -26.750797519545003],
      type: 'Point',
    },
    properties: {},
    type: 'Feature',
  },
];

const Marker = () => (
  <View>
    <Image
      source={require('./pin.png')}
      style={{height: 32, width: 32, resizeMode: 'contain'}}
    />
  </View>
);

const PointAnnotationCrossPlatorm = props =>
  Platform.select({
    ios: (
      <MapboxGL.PointAnnotation {...props}>
        <Marker />
      </MapboxGL.PointAnnotation>
    ),
    android: <MapboxGL.PointAnnotation {...props} />,
  });

class IOSMapView extends React.Component {
  constructor(props) {
    super(props);
    MapboxGL.setWellKnownTileServer(
      Platform.OS === 'android' ? 'Mapbox' : 'mapbox',
    );
    MapboxGL.setAccessToken(MAPBOX_ACCESS_TOKEN);
  }

  /**
   * This renders all the farms boundaries
   */
  renderFarms() {
    return (
      <MapboxGL.ShapeSource
        maxZoomLevel={13}
        id={'FarmsSorce'}
        shape={farms}>
        <MapboxGL.LineLayer
          id={'LineLayer' + '{key}'}
          style={{
            lineColor: ['get', 'color'],
            lineWidth: ['get', 'fill'],
            lineJoin: 'bevel',
          }}
        />
        <MapboxGL.SymbolLayer
          id={'Symbolayer' + '{key}'}
        />
        <MapboxGL.FillLayer
          id={'Fill' + '{key}'}
          style={{
            fillColor: ['get', 'fillColor']
          }}
        />
      </MapboxGL.ShapeSource>
    );
  }

  /**
   * This shows the final soil sampling after placing pins from grid view (Red points) before confirming
   */
  displayPins() {
    let pins = soilSamplePins.map((point, index) => {
      return (
        <PointAnnotationCrossPlatorm
          key={JSON.stringify(point.geometry.coordinates)}
          id={'FarmPins' + index}
          coordinate={point.geometry.coordinates}
          anchor={{x: 0.5, y: 1}}
          draggable={true}
        />
      );
    });
    return pins;
  }

  /**
   * Main render view of the all the renders
   */
  renderMain() {
    return (
      <View
        style={{
          flex: 1,
          justifyContent: 'flex-start',
          alignItems: 'stretch',
          height: 'auto',
        }}>
        <MapboxGL.MapView
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
          }}
          styleURL={'mapbox://styles/mapbox/streets-v11'}
          logoEnabled={false}>
          <MapboxGL.Camera
            // pass coordinates for the current location
            centerCoordinate={[0, 0]}
          />
          {this.renderFarms()}
          {this.displayPins()}
        </MapboxGL.MapView>
      </View>
    );
  }
  render() {
    return <SafeAreaProvider>{this.renderMain()}</SafeAreaProvider>;
  }
}

**Comment by thillendrin-poovalingam** [comment]
Above is an example I used to populate a boundary and pins within the boundary
