### ISSUE TITLE
Bug: Wrong path in built library for assets

### ISSUE THREAD

**Issue by Andarius** [rnmapbox/maps#2439]
Current version:  10.0.0-beta.58

When running `jest` on a view using `@rnmapbox/maps`, I get the following error:

```
 FAIL  __tests__/screens/Modals/MapModal.test.tsx
  ● Test suite failed to run

    Cannot find module '../../assets/heading.png' from 'node_modules/@rnmapbox/maps/lib/commonjs/components/HeadingIndicator.js'

    Require stack:
      node_modules/@rnmapbox/maps/lib/commonjs/components/HeadingIndicator.js
      node_modules/@rnmapbox/maps/lib/commonjs/components/UserLocation.js
      node_modules/@rnmapbox/maps/lib/commonjs/index.js
```

The library is looking for the `assets` folder that is 2 level above as defined here: 
https://github.com/rnmapbox/maps/blob/b641c3d92f0a7ed4be50b1d48bb735174f425561/javascript/components/HeadingIndicator.tsx#L3

However, once bundled, the path is 3 level above as all the code is now located in `lib`.

![image](https://user-images.githubusercontent.com/5070712/203256561-274c3638-c16a-4cb5-8cef-d3ebf9a35002.png)

Is this something that can be fixed by tweaking the configuration of `react-native-builder-bob` ?

**Comment by mfazekas** [comment]
I've moved assets that required inside `javascript` folder that seems to be work with `react-native-builder-bob`
