### ISSUE TITLE
[issue] : Help!  GPS userlocation showing up at cell tower instead of current location

### ISSUE THREAD

**Issue by Eagleames** [rnmapbox/maps#2450]
Seeing an issue on SOME installs on SOME phones where the userLocation seems to be showing up consistently at the user's cell-tower location instead of their GPS location.

This continues to occur if they check google maps, and google maps shows the correct, current location.
I have seen this issue myself on my test phone on one build, but then after the upgrade to rnmapbox/maps the issue is now gone for me but still exists for other users.

Any help or questions I'm happy to try an answer.  
<img src="https://user-images.githubusercontent.com/24260928/203877490-5dbf1cac-af53-4a19-a213-38189ca22314.png" width=30% height=30%>
In this image case, the actual GPS location is 0.5 km to the southwest.

I wish I had more / better information to share

**Comment by mfazekas** [comment]
Sorry I have no idea, why this happens.
