### ISSUE TITLE
Can't Run Example folder

### ISSUE THREAD

**Issue by putuoka** [rnmapbox/maps#2451]
i do clone this project and go to example folder then create accesstoken file and i add Default public token from https://account.mapbox.com/access-tokens/ then i run yarn install after that yarn android this is what i get
```

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mapbox.maps:android:10.9.1.
     Required by:
         project :app > project :rctmgl
      > Could not resolve com.mapbox.maps:android:10.9.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.9.1/android-10.9.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.9.1/android-10.9.1.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.8.0.
     Required by:
         project :app > project :rctmgl
      > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.8.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.8.0/mapbox-sdk-turf-6.8.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.8.0/mapbox-sdk-turf-6.8.0.pom'. Received status code 401 from server: Unauthorized

```

**Comment by mfazekas** [comment]
Set up token for download Mapbox as described on https://docs.mapbox.com/android/maps/guides/install/#configure-credentials

**Comment by putuoka** [comment]
> Set up token for download Mapbox as described on https://docs.mapbox.com/android/maps/guides/install/#configure-credentials

how about if i want to run example folder with maplibre do i need to sign up to the mapbox site and get the token?

**Comment by putuoka** [comment]
After set secret token from mapbox website to root file accesstoken & in gradle.properties MAPBOX_DOWNLOADS_TOKEN i successfully running the example folder but after tap on allow location "while using the app only" the app crash

![Screenshot_1669440352](https://user-images.githubusercontent.com/20880839/204073756-9c7dcbc3-37c2-468b-8a44-826f23492fdd.png)


how do i use maplibre in example folder? i though the default is maplibre. still can't successfully running example folder please help

**Comment by geoffreyp** [comment]
I have the same problem only for android. 
It works for ios.
My token works on other projects but I can't use it on example project for android
