### ISSUE TITLE
[Bug]: Force layer to refetch data

### ISSUE THREAD

**Issue by wmonecke** [rnmapbox/maps#2452]
### Mapbox Implementation

Mapbox GL

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

I am currently able to show a set of "zones" in my map. However, at a certain point, the app gets notified and we need to refetch all layers (e.g. because the color of a zone changed).

How do I force the refetching of a layer (the one below)?

I tried passing in a `ref` and doing `ref.current.forceUpdate()` but that doesn't work.

After receiving the update to refetch data, if I zoom in and out - at certain zoom levels the right color shows but if I zoom in too much it disappears. Is this a bug? Is this a cache issue?

Any help is greatly appreciated.

```javascript
          <MapboxGL.VectorSource
            id="zone_layer"
            minZoomLevel={MinZoomLevel}
            tileUrlTemplates={buildTileTemplatesURLs('zone')}>
            <MapboxGL.FillLayer
              ref={zoneRef}
              id="evacuation_zone"
              style={{
                fillColor: ['get', 'color'],
                fillOpacity: 0.4,
                fillOutlineColor: '#232323',
              }}
              sourceID="zone_layer"
              sourceLayerID="zone"
            />
....
```

### Expected behavior

I expect the layer to refetch and redraw all the tiles.

**Comment by mfazekas** [comment]
There is no `forceUpdate` you might be able to use react-native `key` to force readd of source/layer

**Comment by wmonecke** [comment]
@mfazekas changing the key did not work. The layer stays the same. On the web, it's working properly.
