### ISSUE TITLE
Mapbox warning setAccessToken requires setWellKnownTileServer for MapLibre

### ISSUE THREAD

**Issue by putuoka** [rnmapbox/maps#2455]
Mapbox warning setAccessToken requires setWellKnownTileServer for MapLibre, see setWellKnownTileServer docs for implications {"level": "warning", "message": "setAccessToken requires setWellKnownTileServer for MapLibre, see setWellKnownTileServer docs for implications", "tag": "InstanceManagerImpl"}

## Environment
- Dev OS: Win 10

## Steps to reproduce

```sh   
react-native init sample --version react-native@0.69.3
cd sample
npm install rnmapbox/maps#main --save
# or released version `npm install @rnmapbox/maps@8.0.0-rc1 --save`
```

import

```
import {Marker} from 'react-native-maps';
import MapboxGL from '@rnmapbox/maps';
```

set secret token in code

```
 MapboxGL.setAccessToken(
    'sk.eyJ1Ijoia2FybWxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  );
```
```

const defaultStyle = {
    version: 8,
    name: 'Land',
    sources: {
      map: {
        type: 'raster',
        tiles: ['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'],
        tileSize: 256,
        minzoom: 1,
        maxzoom: 19,
      },
    },
    layers: [
      {
        id: 'background',
        type: 'background',
        paint: {
          'background-color': '#f2efea',
        },
      },
      {
        id: 'map',
        type: 'raster',
        source: 'map',
        paint: {
          'raster-fade-duration': 100,
        },
      },
    ],

 <View
                style={{
                  height: 475,
                  width: 966,
                  borderColor: 'red',
                  borderWidth: 4,
                }}>
                <MapboxGL.MapView
                  style={{flex: 1}}
                  styleJSON={JSON.stringify(defaultStyle)}
                />
              </View>

```

```
react-native run-android
```

**Comment by mfazekas** [comment]
Works as intended. Please submit documentation patches if the current docs aren't clear regarding this

**Comment by modenero** [comment]
> Works as intended. Please submit documentation patches if the current docs aren't clear regarding this

where are the current Docs?

`https://docs.mapbox.com/?q=setWellKnownTileServer` returns:

> Hmmm, we didn't find anything. Reword your search, or [contact Support](https://support.mapbox.com/hc/en-us).

**Comment by Ladvace** [comment]
I'm getting those warnings too even though I've set `Mapbox.setWellKnownTileServer(Mapbox.TileServers.Mapbox)` and `$RNMapboxMapsImpl = 'mapbox'` 

```
 WARN  @rnmapbox/maps: Non v10 implementations are deprecated and will be removed in next version - see https://github.com/rnmapbox/maps/wiki/Deprecated-RNMapboxImpl-Maplibre
 WARN  Mapbox warning setAccessToken requires setWellKnownTileServer for MapLibre, see setWellKnownTileServer docs for implications {"level": "warning", "message": "setAccessToken requires setWellKnownTileServer for MapLibre, see setWellKnownTileServer docs for implications", "tag": "InstanceManagerImpl"}
 ```

**Comment by Ladvace** [comment]
> I'm getting those warnings too even though I've set `Mapbox.setWellKnownTileServer(Mapbox.TileServers.Mapbox)` and `$RNMapboxMapsImpl = 'mapbox'`
> 
> ```
>  WARN  @rnmapbox/maps: Non v10 implementations are deprecated and will be removed in next version - see https://github.com/rnmapbox/maps/wiki/Deprecated-RNMapboxImpl-Maplibre
>  WARN  Mapbox warning setAccessToken requires setWellKnownTileServer for MapLibre, see setWellKnownTileServer docs for implications {"level": "warning", "message": "setAccessToken requires setWellKnownTileServer for MapLibre, see setWellKnownTileServer docs for implications", "tag": "InstanceManagerImpl"}
> ```

I solved the setWellKnownTileServer warning but I still get the deprecation one
