### ISSUE TITLE
Camera's user location follow reset & user location follow bugs

### ISSUE THREAD

**Issue by itekhi** [rnmapbox/maps#2456]
This is kind of feature request and a bug report ;)
Right now, camera's follow user location feature is very laggy...

## New Feature
Some way to reset the camera's following user location feature...

I tried this with `followUserLocation` set to boolean from `useState`, and setting it to `false` and then `true` on a button press, didn't work... Am I missing something or is it a bug?

## Why
At first load, camera automatically starts to follow user location if `followUserLocation` = `true`, and if user drags the map, it disables and as I understand, it can not be enabled again.

## Bugs
I noticed that **on app start**, when `followUserLocation` is `true`, `defaultSettings` don't apply, and map zooms and changes position from some point in the world.
I think this is some kind of 'ordering' issue, because I tried to fix this with setting `followUserLocation` after 1s after `onDidFinishLoadingMap`, and this happened:
I've set `defaultSettings` with `centerCoordinate` and `zoomLevel`(without these map was going crazy, as I said earlier), and `followZoomLevel`, map loads, then after 1s, zoom suddenly goes to `followZoomLevel` without animation and then camera animates to user location.
If I remove `followZoomLevel`, everything is ok. I noticed that in this case, first the position animates and then zoom.

Also padding doesn't apply when following the user. I'm pretty sure this is a mapbox thing(because it animates to center when zooms in 🤣), but this is a bummer, I wanted to make a UI under user's position with it in the center.

I'm pretty much off the topic at this point, and I don't know if I should write this in a separate issue or not, but I wanted to write what I experienced, because this library is awesome and I plan to use it a lot 😄

**Comment by mfazekas** [comment]
@itekhi for bug reports please submit a concrete example
