### ISSUE TITLE
Mapbox Integration with React Native 0.63.5

### ISSUE THREAD

**Issue by devWaleed** [rnmapbox/maps#2460]
## Environment
macOS ventura 13.0.1

## Steps to reproduce

1. Create a new project with react-native version 0.63.5
2. yarn and install all basic things
3. Install mapbox 10.0.0-beta.57, setup only the maven repository link and secret key
4. npx react-native run-android will give you the following two errors:
```

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/waleed/.gradle/caches/transforms-2/files-2.1/2dd7532fa5bc010dd7d83c04f64ed0b7/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

Solving the issues:

1. Updated my minSDK to 21, target and compileSDKs to 31 along with build tools and error no 1 is gone.
2. Error no 2 is still there and unable to resolve it.

I have tried different kotlin versions but none solves the error no 2. 

./android/build.gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        RNMapboxMapsImpl = "mapbox"

    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        maven { url 'https://www.jitpack.io' }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }     
        jcenter()   
    }
}

```

**Comment by putuoka** [comment]
try install 
yarn add @react-native-masked-view/masked-view @react-navigation/elements react-native-screens

if still not working try run example folder if you can make it work

**Comment by devWaleed** [comment]
I am able to run the project on 0.65.3 using the following gradle settings:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {

        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "20.1.5948944"

        RNMapboxMapsImpl = "mapbox"
        
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.1")
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }
    }
}
```

I have not tested on 0.64 so for now 0.65 is the lowest version which can run rnmapbox.

**Comment by putuoka** [comment]
> I am able to run the project on 0.65.3 using the following gradle settings:
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
> 
>         buildToolsVersion = "31.0.0"
>         minSdkVersion = 21
>         compileSdkVersion = 31
>         targetSdkVersion = 31
>         ndkVersion = "20.1.5948944"
> 
>         RNMapboxMapsImpl = "mapbox"
>         
>     }
>     repositories {
>         google()
>         mavenCentral()
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:4.2.1")
>         classpath 'com.google.gms:google-services:4.2.0'
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0'
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenCentral()
>         mavenLocal()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
> 
>         google()
>         jcenter()
>         maven { url 'https://www.jitpack.io' }
>         maven {
>             url 'https://api.mapbox.com/downloads/v2/releases/maven'
>             authentication {
>                 basic(BasicAuthentication)
>             }
>             credentials {
>                 // Do not change the username below.
>                 // This should always be `mapbox` (not your username).
>                 username = 'mapbox'
>                 // Use the secret token you stored in gradle.properties as the password
>                 password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
>             }
>         }
>     }
> }
> ```
> 
> I have not tested on 0.64 so for now 0.65 is the lowest version which can run rnmapbox.

i can't work it on 0.69.3 could u please help? i try with fresh install npx react-native init testrnmap --version 0.69.3
after that i add MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1Ijoia2FybWFncm91cCIsIxxxxxxxx into gradle.properties then change the build.gradle file in /android/build.gradle like your setting above then run yarn android and got an error

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 3 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - D:\Users\oka\.gradle\caches\transforms-3\a8108ce710a662637a30dedebdb0a106\transformed\jetified-react-native-0.71.0-rc.0-debug\jni\arm64-v8a\libc++_shared.so
      - D:\Users\oka\.gradle\caches\transforms-3\55a79da02fe6523455619019f5554473\transformed\jetified-common-23.1.1\jni\arm64-v8a\libc++_shared.so
      - D:\Users\oka\.gradle\caches\transforms-3\1a8b906c1649e97dbca55059e0091063\transformed\jetified-fbjni-0.3.0\jni\arm64-v8a\libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

```

**Comment by devWaleed** [comment]
@putuoka following the docs, it is mentioned how to resolve this issue:

```
   packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
```
