### ISSUE TITLE
Support for Mapbox-iOS-SDK 

### ISSUE THREAD

**Issue by 1stdevfriend** [rnmapbox/maps#2461]
## New Feature
Support for Mapbox-iOS-SDK ~ 6.0.0

## Why
Mapbox-iOS-SDK is developing very fast but npm module is not in sync with the versions. Thus, creating force installs and non compatible dependencies.

**Comment by mfazekas** [comment]
@1stdevfriend  not sure what are you talking about latest released iOS mapbox version is 10.9.1, deprecated mapbox gl has releases  6.* maybe that's called Mapbox-iOS-SDK but that's also supported.
