### ISSUE TITLE
Mapbox Navigation

### ISSUE THREAD

**Issue by allthetime** [rnmapbox/maps#2472]
Hi, not seeing anything in the docs, is navigation / directions supported for this library?

If not, I think I'll be developing it, curious if there are any guidelines for adding new capabilities...

Thanks

**Comment by danidaryaweesh** [comment]
Thanks for the tip @allthetime ! I will check it out. I looked at it briefly and it seems that we will have to use java/kotlin & swift native code in order to get it to work. Definitely worth a try though.
