### ISSUE TITLE
[Bug]: Failed to load glyph range 0-255 for font stack DIN Pro Medium,Arial Unicode MS Regular: unsupported URL

### ISSUE THREAD

**Issue by marialovellecamacho** [rnmapbox/maps#2473]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.0-beta.59

### Platform

iOS

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

const styleUrl = encodeURI('mapbox://styles/allblazing/clbc6thqr000015pg1h8vg2oq');

<MapboxGL.MapView
          styleURL={styleUrl}
          style={styles.map}
          compassEnabled={false}
          zoomEnabled={true}
        >
</MapboxGL.MapView>

### Observed behavior and steps to reproduce

I keep encountering this error after upgrading from `@react-native-mapbox-gl/maps": "^8.6.0-beta.0` to  `@rnmapbox/maps": "rnmapbox/maps#main`. Seems like the mapbox styleURLs are not supported by iOS.

I already updated the style typography to a different font but the error still persists. Has anyone encountered this and have you found a solution?

<img width="759" alt="image" src="https://user-images.githubusercontent.com/11880748/206094975-b8bcf9d7-2377-4cba-b66f-5355c9c0e4c5.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/11880748/206094994-ea9f611f-af3d-4718-921d-861b2f1cedd9.png">

### Expected behavior

Map should load

**Comment by mfazekas** [comment]
Closing as there is not much we can do about this. It's your style and the undrelying native libs.
