### ISSUE TITLE
[Bug]: rnmapbox maps: WillStartLoadingMap is not supported

### ISSUE THREAD

**Issue by azuken** [rnmapbox/maps#2476]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.59

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}                
          onWillStartLoadingMap={() => {
            console.log('action')
          }}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Just load the map, and warning appears.

 WARN  rnmapbox maps: WillStartLoadingMap is not supported 

Indeed, code is not executed here

### Expected behavior

Have the property working

### Notes / preliminary analysis

onDidFinishLoadingMap is not working either.

I've just migrated to Mapbox v10 and new configurations (token on build etc..) but with this simple events not working, I have to wait to deploy this update...

**Comment by mfazekas** [comment]
@azuken pls document your use case, the v10 sdk has no direct equivalent to this event, so you'll need to find some other way to achieve what you'd like

**Comment by azuken** [comment]
Hi @mfazekas, just saw your PR (thank you for the reactivity 😃), but I also talked about `onDidFinishLoadingMap` in my notes, for Android.
If I use `onWillStartLoadingMap` with android, go to user location does not work (action seems to be executed too early), and it is the same behaviour the other way.
Can this event be added too ?
