### ISSUE TITLE
[Bug]: takeSnap (with map) method on android returns always a null value, also in this repository example

### ISSUE THREAD

**Issue by whiteHatCip** [rnmapbox/maps#2484]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.9.1

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.60

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

The takeSnap method always resolves to a null value. In the Mapbox file `MapboxRenderer.kt`, the `snapshot(listener: OnSnapshotReady)` method needs that the readyForSnapshot property is true. no matter the time that I perform the snapshot request, the resolved value is null. The weird thing is that setting a breakpoint in the takeSnap method inside the `RCTMGLMapView.kt` file, there is a time when the snapshot value is NOT null, therefore probably some kind of event listener should be setup, in order to receive the proper map snapshot filled with data.

### Expected behavior

The snapshot resolved value should not be nil if I ask for a snapshot when the map is not being moved around with panning and other interactions.

### Notes / preliminary analysis

This issue is being experienced also in this repo example project, meaning that the feature has not been tackled yet

**Comment by whiteHatCip** [comment]
This is driving me nuts. I even added an event listener to make sure that I perform the takeSnap method only when the map did finish to render FULLY, But nothing changed.
What I noticed is that the issue presents itself only the first time that I ask for a snapshot. The subsequent times, the `readyForSnapshot` property inside the `MapboxRendere.kt` file from Mapbox is finally true. The problem is that the application doesn't crash when I am in debug mode, but crashes when I package the apk, because mapbox throws an error that crashes the app:
 `logE(TAG, "Could not take map snapshot because map is not ready yet.")`

An help on this matter would be really appreciated.

**Comment by mfazekas** [comment]
@whiteHatCip I could not reproduce with current main, both Camera > Take Snapshot with Map and Camera > Take snapshot without map worked
