### ISSUE TITLE
Can't make the Expo Setup work (mainly iOS)

### ISSUE THREAD

**Issue by Chris-Syon** [rnmapbox/maps#2485]
As mentioned in the title I recently cannot get the setup to work in my expo project. 

1-2 weeks earlier I got it to run but I had to switch to another project in the meantime. Coming back now, I cannot get it to run (especially on iOS)

**current relevant packages:**
  "expo": "~46.0.17",
  "react": "18.0.0",
  "react-native": "0.69.6",
  "@rnmapbox/maps": "10.0.0-beta.57"

**previously working packages:**
  "expo": "~46.0.17",
  "react": "18.0.0",
  "react-native": "0.69.6",
  "@rnmapbox/maps": "^10.0.0-beta.57"

**app.json (previously working & current are the same) added as in the expo get started guide:**
 "plugins": [
      [
        "@rnmapbox/maps",
        {
          "RNMapboxMapsImpl": "maplibre"
        }
      ]
    ],

By changing the package "@rnmapbox/maps": "^10.0.0-beta.57" to "@rnmapbox/maps": "10.0.0-beta.57" (removing the ^ version modifier) I was able to get my packages installed, however it will make my iOS app crash instantly without any logs or errors. (It just says that it stopped working, no logging output)

If I don't remove the ^ version modifier I will not be able to install my packages using npm nor yarn. I will always get the error that it was not able to find/resolve the module expo config/plugins even though the package is potentially to be found in the node modules.

**Things I tried:**
 - deleting node_modules, reinstalling
 - deleting temporary/cached expo folders
 - deleting ios & android folders

**Please note:** I was not able to "npm install --save rnmapbox/maps#main" because the download just would not start whatsoever.

Any suggestions or help would be very welcome,
thank you in advance!

**Comment by mfazekas** [comment]
There were some recent changes in expo config plugin, see release notes on GitHub releases. Not sure why iOS crashes, try to get some logs, otherwise we can't really look into it.
