### ISSUE TITLE
[Bug]: Geoserver wmts layer not visible on map

### ISSUE THREAD

**Issue by neslihanorhan** [rnmapbox/maps#2486]
### Mapbox Implementation

Mapbox

### Mapbox Version

8.6.0-beta.0

### Platform

iOS

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```javascript
import React from 'react';
import {StyleSheet} from 'react-native';
import Config from 'react-native-config';
import MapboxGL from '@react-native-mapbox-gl/maps';

function BugReportExample() {
  MapboxGL.setAccessToken(Config.MAPBOX_ACCESS_TOKEN);
  const administrativeBorders =
    'https://geoserver.something.com/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=<something>%3A<something>&STYLE=&TILEMATRIX=EPSG:3857:{z}&TILEMATRIXSET=EPSG:3857&FORMAT=application/vnd.mapbox-vector-tile&TILECOL={x}&TILEROW={y}';

  return (
    <MapboxGL.MapView style={styles.map} styleURL={MapboxGL.StyleURL.Light}>
      <MapboxGL.Camera zoomLevel={3.5} centerCoordinate={[34.0801, 39.6632]} />
      <MapboxGL.VectorSource
        id="vectorSourceExample"
        minZoomLevel={3.5}
        maxZoomLevel={22}
        tms={true}
        tileUrlTemplates={[administrativeBorders]}
        onPress={e => console.log('features', e.features)}>
        <MapboxGL.LineLayer
          id="bordersLine"
          sourceID="vectorSourceExample"
          sourceLayerID="vectorSourceExampleLayerID"
          minZoomLevel={3.5}
          maxZoomLevel={22}
          style={{lineColor: '#1ad356', lineWidth: 2, visibility: 'visible'}}
        />
      </MapboxGL.VectorSource>
    </MapboxGL.MapView>
  );
}

const styles = StyleSheet.create({
  map: {
    width: '100%',
    height: '100%',
  },
});

export default BugReportExample;
```

### Observed behavior and steps to reproduce

I have a geoserver, that has a vector layer, published from Postgis table (polygons). Geoserver has Vector Tiles extension installed and running.
I edited the url accordingly [Publishing a GeoServer Layer for use with Mapbox Styles](https://docs.geoserver.org/stable/en/user/styling/mbstyle/source.html):

"https://geoserver.something.com/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=<something>%3A<something>&STYLE=&TILEMATRIX=EPSG:3857:{z}&TILEMATRIXSET=EPSG:3857&FORMAT=application/vnd.mapbox-vector-tile&TILECOL={x}&TILEROW={y}"

I am able to run this URL in the browser with the appropriate z/x/y values.
But when I supply this style to MapboxGL.VectorSource - I get this error, please see screenshot below. Also, same error when zoom in.
Why do I get this error? Can anyone help? Does anyone have  similar error?
Is it possible to add the WMTS served from Geoserver to the map style as a layer on the map?

![IMG_0011](https://user-images.githubusercontent.com/71545170/207275792-6fc25a88-fadc-4dc8-858f-fe85c9a26e1e.PNG)
![IMG_0012](https://user-images.githubusercontent.com/71545170/207275801-3ad29aef-e0c1-438e-a064-e0a0659d3dbc.PNG)

**Comment by mfazekas** [comment]
Sorry we don't have time to look into old versions
