### ISSUE TITLE
Atmosphere, SkyLayer  and terrain all causing not found in UIManager errors

### ISSUE THREAD

**Issue by mrcameron999** [rnmapbox/maps#2494]
## Environment
- Dev OS: [Win11]
- Version ^10.0.0-beta.59
## Steps to reproduce
The following components are all causing errors. 
Atmosphere - **Invariant Violation: requireNativeComponent: "RCTMGLAtmosphere" was not found in the UIManager.**
SkyLayer - **Invariant Violation: requireNativeComponent: "RCTMGLSkyLayer" was not found in the UIManager.**
Terrain - **Invariant Violation: requireNativeComponent: "RCTMGLTerrain" was not found in the UIManager.**

I have the rest of MapBox working including drawing shapes and lines on the graph. I have googled but have not found anything related to this topic. I'm also using EXPO and followed all the installation steps. All other parts of Map Box seem to work apart from the terrain and 3d stuff.

Is this component working as expected?

```<MapboxGL.MapView scrollEnabled={true} styleURL='redacted' style={styles.map}>
          <MapboxGL.Camera ref={camera} />
          <RasterDemSource
          id="mapbox-dem"
          url="mapbox://mapbox.mapbox-terrain-dem-v1"
          tileSize={514}
          maxZoomLevel={14}
        >
            <Atmosphere
              style={{
                color: 'rgb(186, 210, 235)',
                highColor: 'rgb(36, 92, 223)',
                horizonBlend: 0.02,
                spaceColor: 'rgb(11, 11, 25)',
                starIntensity: 0.6,
              }}
            />
            <SkyLayer
              id="sky-layer"
              style={{
                skyType: 'atmosphere',
                skyAtmosphereSun: [0.0, 0.0],
                skyAtmosphereSunIntensity: 15.0,
              }}
            />
            <Terrain style={{ exaggeration: 1.5 }} />
          </RasterDemSource>
        </MapboxGL.MapView>```

**Comment by ArthurBriggs8888** [comment]
Same here in expo project. How can I fix this?
