### ISSUE TITLE
LocationManager: Choose between request always authorization and when in use

### ISSUE THREAD

**Issue by pablogdcr** [rnmapbox/maps#2499]
## Choose between always or WhenInUse location permission
Hi,

In [RCTMGLLocationModule](https://github.com/rnmapbox/maps/blob/main/ios/RCTMGL-v10/RCTMGLLocationModule.swift), the `start` function is requesting both always and whenInUse authorization.
It would be nice to be able to choose between whenInUse or always, depending on the use case.

We could add a prop to the UserLocation component, `listensToLocationInBackground` or similar, to enable background location if we need it.

In case of `listensToLocationInBackground` is false, we can then `stop` listening for the user location when the app is in the background, and `start` it again when opening it.

## Why
It is not possible to use the LocationManager if we only want to use the `WhenInUse` location permission.
I don't think that the default behavior should be requiring the always location permission.
Most of the time, having the location when the app is running is enough, it uses less battery, and is more respectful of the user's privacy.

**Comment by pablogdcr** [comment]
I've started a PR (#2501) with this change.

**Comment by jaltin** [comment]
Hi @pablogdcr.

I saw this issue and had a look at the PR and I have a related question:

In what situation do you need the location when the app is in the background?

I am asking this since we have an app that is **sometimes** using the location when the app is in the background.

We are allowing the user to enable tracing of their movement, and for this we need to get location updates even if the app is in the background, but only if the user has turned on tracing. If they haven't enabled tracing, we don't want to listen to background updates as it users CPU and battery resources unnecessarily.

We are using the package [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) for the location tracking as it is very resoruce efficient when the app is in the background compared to just plainly using the CLLocationManager as is done in the mapbox native library.

Will your PR changes not interfere with that, in that the location manager will be stopped in background if the requestsAlwaysUse flag is set to false?

**Comment by pablogdcr** [comment]
Hi @jaltin, don't know if I understood your question correctly, if requetsAlwaysUse is set to false (or not set, false being the default value), only the WhenInUse permission will be requested, and the locationManager will be stopped in the background, and restarted when the user reopens the app.

**Comment by jaltin** [comment]
Hi again @pablogdcr.

I will try to explain better my concern/question:

- I have a RN app that is using Mapbox maps.
- It is possible for my users to trace/track their movements while the app is in the background (e.g. like a running app or a fleet management app does).
- If the user has enabled tracing, then I need to receive location updates even if the app is in the background (I use [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) for this.
- If the user is not tracing, then I want to disable location updates when the app is in the background to save resources (CPU, battery, memory).

If I understand your PR correctly, then it means that:
- requetsAlwaysUse flag set to false will stop CLLocationManager when the app goes into the background.
- requetsAlwaysUse is set to true will force CLLocationManager to run in the background.

If my understanding is correct, then your PR will interfere with the user scenario I described above and block me from deciding when to have location updates in background, and when not to receive them. But perhaps I am misunderstanding this?

Also, if the location updates are coming in when the app is in the background, then there might be unnecessary resource usages (e.g. as is the case in this issue, where the user location is re-rendering in background https://github.com/rnmapbox/maps/issues/536).

So given my explanation above, that is why I was wondering why you need BG location updates. Perhaps you can explain that a bit more?

In my mind, a package like this should not get involved with the decision of if to receive location updates in the background or not, as this is a complex thing that will affect other plugins and app behavior. That is better left to packages like [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) (or any other that does the same job).

I hope my explanations make sense but ask more if you need further details.

**Comment by pablogdcr** [comment]
Thanks for the explanation.

In my app I'm not using background location, that's why I did this PR, to not require the AlwaysUse permission, and to stop the locationManager while the app is in the background if `requestsAlwaysUse` is `false`. I don't need a more complex location system, so using the UserLocation component with `requestsAlwaysUse` to `false` is enough.

Based on the code of the [UserLocation.js](https://github.com/rnmapbox/maps/blob/main/javascript/components/UserLocation.js) file, if you don't want Mapbox to handle the user location for you, you can still use the UserLocation component, but without the `onUpdate` prop, and with the default `renderMode` ("normal").

This way, you can use react-native-background-geolocation to handle the user location instead of Mapbox.

**Comment by mfazekas** [comment]
This seems to be addressed now
