### ISSUE TITLE
Issue after lib install

### ISSUE THREAD

**Issue by AlexandrBol** [rnmapbox/maps#2510]
## Environment
- Dev OS: macOS Ventura 13.0
- iOS16 
- @rnmapbox/maps@rnmapbox/maps#main": version "10.0.0-beta.62"

## Steps to reproduce

```sh   
react-native init sample --version react-native@0.70.6
cd sample
yarn add rnmapbox/maps#main 
yarn ios
```

After lib installation and runing project get next issue on start:

![Simulator Screen Shot - iPhone 14 - 2022-12-28 at 15 35 04](https://user-images.githubusercontent.com/26917977/209828099-8c32f65a-72b2-4981-ac62-94ab51406a79.png)

 BUNDLE  ./index.js 

error: node_modules/@rnmapbox/maps/javascript/components/PointAnnotation.tsx: unknown node of type "TSInstantiationExpression" with constructor "Object"
 BUNDLE  ./index.js 

error: node_modules/@rnmapbox/maps/javascript/components/PointAnnotation.tsx: unknown node of type "TSInstantiationExpression" with constructor "Object"

**Comment by saheem128** [comment]
Same problem

**Comment by AlexandrBol** [comment]
@saheem128 last stable version that works for me is `10.0.0-beta.39`

**Comment by saheem128** [comment]
@AlexandrBol I was able to avoid this error by including `@babel/preset-typescript` in the `babel.config.js` `presets` array.

**Comment by AlexandrBol** [comment]
@saheem128 also works for me, thanks!

**Comment by AlexandrBol** [comment]
1. run `yarn add @babel/preset-typescript --dev`
2. add `'@babel/preset-typescript'` to the `presets` array in the `babel.config.js`
