### ISSUE TITLE
[Bug]: Outdoor style enum URL

### ISSUE THREAD

**Issue by maartenweyns** [rnmapbox/maps#2517]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```javascript
import React from 'react';
import { MapView } from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView
        style={{flex: 1}}
        styleURL={MapboxGL.StyleURL.Outdoors}>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Mapbox reports an error:
```
Mapbox error {OnlineFileSourc}[General]: The resource `https://api.mapbox.com/styles/v1/mapbox/outdoors-v1` not found
```

### Expected behavior

The enum URL should resolve to `outdoors-v11`, not `outdoors-v1`

### Notes / preliminary analysis

Additioanlly, the [mapbox site](https://www.mapbox.com/maps/outdoors) resolves to a new version: v12

```
mapbox://styles/mapbox/outdoors-v12
```

**Comment by mfazekas** [comment]
@maartenweyns sound you're using the deprecated mapbox-gl or maplibre implementation. Please see install guides on how to use the v10 implementation
