### ISSUE TITLE
[Bug]: iOS PointAnnotation ignores anchor

### ISSUE THREAD

**Issue by nixolas1** [rnmapbox/maps#2519]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.62

### Standalone component to reproduce

```javascript
<MapboxGL.PointAnnotation
          key={"key"}
          id={"id1234"}
          coordinate={[lon, lat]}
          anchor={{y: 1, x: 0.5}}
          onSelected={() => {}}>
          <Icon width={40} height={40} />
</MapboxGL.PointAnnotation>
```

### Observed behavior and steps to reproduce

Add anchor, reload map, no change. Change anchor, no change.

### Expected behavior

Anchor should move pointannotation if it is still supported by it.

**Comment by mfazekas** [comment]
@nixolas1 pls add a full component

**Comment by nixolas1** [comment]
One mistake in the report: only iOS

Component, with two different anchors on the PointAnnotations. They should both be visible, but on iOS only Red is visible.
```
export default ({ }) => {
  return (
        <MapboxGL.MapView>
          <MapboxGL.Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
          <MapboxGL.PointAnnotation
            key={"test"}
            coordinate={[-74.00597, 40.71427]}
            id={"1"}
            anchor={{y: 1, x: 0.5}}>
            <View style={{backgroundColor: "red", height: 40, width: 20}}/>
          </MapboxGL.PointAnnotation>
          <MapboxGL.PointAnnotation
            key={"test2"}
            coordinate={[-74.00597, 40.71427]}
            id={"2"}
            anchor={{y: -1, x: 0.5}}>
            <View style={{backgroundColor: "blue", height: 40, width: 20}}/>
          </MapboxGL.PointAnnotation>
        </MapboxGL.MapView>
  );
};
```


How it should look: 
![image](https://user-images.githubusercontent.com/3536134/210745483-41e891b1-5984-48a8-9dda-a0f5dd38e4ae.png)

how it looks on ios
![Uploading image.png…]()

**Comment by nixolas1** [comment]
Awesome! Thank you
