### ISSUE TITLE
[Bug]: Getting error: MapLoad error Failed to load glyphs when using custom font

### ISSUE THREAD

**Issue by thomasgrivet** [rnmapbox/maps#2527]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.61

### Standalone component to reproduce

```
 <MapboxGL.SymbolLayer
                id="points"
                sourceID="source"
                style={{
                  textField: ['get', 'formattedRiderPrice'],
                  textFont: ['Euclid Circular A Bold', 'Arial Unicode MS Regular'],
                }}
            />
```

### Observed behavior and steps to reproduce

Hello! I added a custom font to my mapbox custom style in Studio, added the styleUrl to my MapView component (which displays the custom style nicely when not using custom font) and tried using the custom font in the textFont property of my SymbolLayer.
Using the custom font, my style won't load and I get the following error: 

`Mapbox error Map load failed: {type=glyphs, message=Failed to load glyphs: HTTP status code 404, begin=20384103955} {"level": "error", "message": "Map load failed: {type=glyphs, message=Failed to load glyphs: HTTP status code 404, begin=20384103955}", "tag": "RCTMGLMapView"}`

I don't have any issue when using fonts already given by Mapbox such as Open Sans, etc...

### Expected behavior

Style should load correctly and custom font should be displayed

### Additional links and references

<img width="349" alt="Screenshot 2023-01-05 at 16 21 39" src="https://user-images.githubusercontent.com/18561703/210815512-1e29208f-5116-40d9-a8c7-b80e5ffeecf1.png">

Please ping me if you need any other infos! Thanks for your time once again, really appreciate it

**Comment by mfazekas** [comment]
@thomasgrivet pls post a full example we can try

**Comment by thomasgrivet** [comment]
@mfazekas Thanks for the quick answer! here is a full test component:

```
import { MapboxGL } from '~commonComponents/MapboxGL/MapboxGL';

const CUSTOM_FONT = 'Your custom font name here';

export const WithCustomFontMapView = () => (
    <MapboxGL.MapView style={{ flex: 1 }} styleURL="mapbox://styles/[userId]/[styleId]">
        <MapboxGL.Camera centerCoordinate={[0, 0]} />
        <MapboxGL.ShapeSource
            id="source"
            shape={{
                type: 'FeatureCollection',
                features: [
                    {
                        type: 'Feature',
                        geometry: {
                            type: 'Point',
                            coordinates: [0, 0]
                        },
                        properties: {}
                    }
                ]
            }}
        >
            <MapboxGL.SymbolLayer
                sourceID="source"
                id="text"
                style={{
                    textColor: '#000000',
                    textField: 'hey there',
                    // If you remove the custom font, it works as expected.
                    textFont: [CUSTOM_FONT, 'Arial Unicode MS Regular'],
                    textSize: 14,
                    textAllowOverlap: true
                }}
            />
        </MapboxGL.ShapeSource>
    </MapboxGL.MapView>
);

```

**Comment by thomasgrivet** [comment]
@mfazekas Thanks for the answer!
Can I give you my account infos in DM along the custom font name? I used variables as to not publicly show my mapbox account's details.
