### ISSUE TITLE
[Bug]: Multiple typescript errors occur when project specific tsconfig contain stricter rules

### ISSUE THREAD

**Issue by mattijsf** [rnmapbox/maps#2528]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.62

### Standalone component to reproduce

Not relevant. See Steps to reproduce.

### Observed behavior and steps to reproduce

1. `npx react-native init MapboxV10TS --template react-native-template-typescript`
2. `cd MapboxV10TS`
3. `yarn add @rnmapbox/maps@10.0.0-beta.62`
4. `open App.tsx`
	- Add `import MapboxGL from "@rnmapbox/maps";`
	- Save
5. `npx tsc --noEmit` (observe that there are no errors)
6. `open tsconfig.json`
	- Add `"noUncheckedIndexedAccess": true` to `compilerOptions`
	- Save
7. `npx tsc --noEmit`:

```
Found 13 errors in 4 files.

Errors  Files
     8  node_modules/@rnmapbox/maps/javascript/components/Camera.tsx:384
     2  node_modules/@rnmapbox/maps/javascript/requestAndroidLocationPermissions.ts:8
     2  node_modules/@rnmapbox/maps/javascript/utils/BridgeValue.ts:68
     1  node_modules/@rnmapbox/maps/javascript/utils/deprecation.ts:36
```

### Expected behavior

Changes to project local typescript configuration should not impact files imported from `node_modules`

### Notes / preliminary analysis

Some might say to use `skipLibCheck: true` or to add an `exclude` section to `compilerOptions`. This will not work since due to:
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler

And the reason that these errors occur is because [index.d.ts is importing .ts[x]](https://github.com/rnmapbox/maps/blob/v10.0.0-beta.62/index.d.ts#L28-L63) files instead of definition files which causes the compiler to include them during compilation.

**Comment by mfazekas** [comment]
Should be fixed now
