### ISSUE TITLE
Expo / EAS build error: "module 'Mapbox' not found"

### ISSUE THREAD

**Issue by nickkuh** [rnmapbox/maps#2531]
I'm trying to add rnmapbox to an Expo Managed Workflow project. We're using EAS and Expo. 

I've followed the Expo install setup steps here:

https://github.com/rnmapbox/maps/blob/main/plugin/install.md

Then I'm attempting to get EAS to create a dev client for my iOS simulator. I kick off that process as follows:

`eas build --profile development-simulator --platform ios`

EAS manages to get most of the way through creating a development client for my simulator but it falls over when it gets to installing the MapBox specific cocoapods with the following error from EAS/FastLane:

```
› Compiling @rnmapbox/maps Pods/rnmapbox-maps » RNMBImageUtils.m
› Compiling @rnmapbox/maps Pods/rnmapbox-maps » RCTMGLVectorSourceManager.m
› Compiling @rnmapbox/maps Pods/rnmapbox-maps » RCTMGLVectorSource.m
› Compiling @rnmapbox/maps Pods/rnmapbox-maps » RCTMGLVectorLayer.m
(node_modules/@rnmapbox/maps/ios/RCTMGL/RCTMGLLayer.h:15:9)

  13 | @class RCTMGLMapView;
  14 | 
> 15 | @import Mapbox;
     |         ^ module 'Mapbox' not found
  16 | 
  17 | @interface RCTMGLLayer<T> : UIView
  ```

I'm wondering if I'm missing a step that's required. Any help much appreciated!

**Comment by mfazekas** [comment]
What is the value of `RNMapboxMapsImpl`?

**Comment by craigcoles** [comment]
@mfazekas Currently, the value of `RNMapboxMapsImpl` is simply `mapbox`

**Comment by nickkuh** [comment]
@mfazekas - why have you close this please? Do you have a resolution? Thanks

**Comment by nickkuh** [comment]
@mfazekas any update please?

**Comment by craigcoles** [comment]
Morning @mfazekas, is it possible to reopen the issue? We are still experiencing this issue and would love to help get to the bottom of it

**Comment by mfazekas** [comment]
Sorry folks it's a misconfiguration, as if  RNMapboxMapsImpl was set correctly to `mapbox` it should have been using the swift version of the code, but the error is points to the `maplibre` variant being used. 

But without describing exactly what you've done it's impossible to help.

**Comment by ste00martin** [comment]
I'm experiencing this same issue
