### ISSUE TITLE
Pod Install Fails: Value of type 'PointAnnotation' has no member 'isDraggable'

### ISSUE THREAD

**Issue by wen-kai** [rnmapbox/maps#2536]
## Environment
- Dev OS: OSX 13
- xcode 14

## Steps to reproduce

```sh   
react-native init sample --version react-native@0.70.5
cd sample
npm install rnmapbox/maps#main --save
npx pod-install
npx react-native run-ios
```

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/1305459/211442488-a8676279-5322-4c36-98a6-7d8b2ffb35a5.png">

**Comment by mfazekas** [comment]
@wen-kai are you sure you don't have RNMapboxMapsVersion set to an older version than 10.10?

**Comment by wen-kai** [comment]
that was it, thank you!
