### ISSUE TITLE
[Bug]: downloading multiple packs causes an issue

### ISSUE THREAD

**Issue by AlexandrBol** [rnmapbox/maps#2537]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.64

### Standalone component to reproduce

```javascript
import { Button, StyleSheet, View } from 'react-native';
import React from 'react';
import MapboxGL from '@rnmapbox/maps';
import { MAPBOX_TOKEN } from '@env';

export const MapDownload = () => {
  const packDownloading = async (
    minLongitude: number,
    maxLongitude: number,
    minLatitude: number,
    maxLatitude: number,
  ) => {
    await MapboxGL.setAccessToken(MAPBOX_TOKEN);
    await MapboxGL.offlineManager.createPack(
      {
        name: `test-world-${Date.now()}`,
        styleURL: MapboxGL.StyleURL.Street,
        minZoom: 0,
        maxZoom: 6,
        bounds: [
          [Number(minLongitude.toFixed(4)), Number(minLatitude.toFixed(4))],
          [Number(maxLongitude.toFixed(4)), Number(maxLatitude.toFixed(4))],
        ],
      },
      (pack, status) => console.log('pack, status', { pack }, status),
      (pack, err) =>
        console.log(
          'pack, err',
          { pack },
          err,
          Number(minLongitude.toFixed(4)),
          Number(minLatitude.toFixed(4)),
          Number(maxLongitude.toFixed(4)),
          Number(maxLatitude.toFixed(4)),
        ),
    );
  };

  const downloadWorld = async () => {
    for (let i = 0; i < 360; i = i + 10) {
      await packDownloading(i, i + 10, -90, 90);
    }
  };

  return (
    <View style={styles.container}>
      <Button title="Download world" onPress={downloadWorld} />
    </View>
  );
};

export default MapDownload;

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 32,
  },
  textStyle: {
    textAlign: 'center',
    marginBottom: 16,
  },
});

```

### Observed behavior and steps to reproduce

Continues issues [#2516](https://github.com/rnmapbox/maps/issues/2516) as completed via [#2533](https://github.com/rnmapbox/maps/pull/2533).

Try to run `downloadPacks` Press download world button
Expect => downloading packs one by one
Result firstly getting multiple error then download starts

Error:

> pack
: 
OfflinePack
pack
: 
bounds
: 
"{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Point\",\"coordinates\":[0,-90]}},{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Point\",\"coordinates\":[10,90]}}]}"
metadata
: 
"{\n  \"name\" : \"test-world-1673360389314\"\n}"

> message: "Failed to resolve tileset descriptors: Loading request canceled"
> name: "test-world-1673360389314"

### Expected behavior

Successful download

### Additional links and references

https://user-images.githubusercontent.com/26917977/211576573-ecfd90b3-16a3-4054-9f3e-23452f995f7b.mov

**Comment by mfazekas** [comment]
First using `Date.now()` as a key is not great as there is a slight chance that two key will have the same id and in that case the old load will get cancelled. Also I do get error like this, which could also explain the cancelations.:

```
  message: 'The tile region \'tw-1673371860767\' can\'t be loaded because it would increase the number of Maps tiles to 774, which is beyond the maximum allowed 750 tiles. Please contact Mapbox if your use case requires a larger region size.' }, 10, -90, 20, 90
```
