### ISSUE TITLE
[Bug]: Map zoom + movement issues

### ISSUE THREAD

**Issue by nixolas1** [rnmapbox/maps#2550]
### Mapbox Implementation

Mapbox

### Mapbox Version
not set

### Platform

Android

### `@rnmapbox/maps` version

^10.0.0-beta.64

### Standalone component to reproduce

```javascript

// completely default map component

import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

When zooming in with two fingers, then moving around, the movement is wrong (too fast). 
See video

Steps:

1. Zoom in with two fingers, and then without lifting them
2. Pan the map with the same two fingers
3. Map moves more than the finger movement

(Works fine on iOS!)

### Expected behavior

Map should move the same distance as the fingers, even after zooming in.

### Notes / preliminary analysis

Seems like the movement is based on the zoom distance at the beginning of the two-finger zoom/pan, instead of being updated to match the zoom level.

### Additional links and references

https://i.imgur.com/EUG1XUi.mp4

**Comment by nixolas1** [comment]
Also, text sometimes is rendered weirdly when zoomed out. Affects both my own `CircleLayer`s and `SymbolLayer`s, as well as actual map labels (like "Norway").
Not sure how to report that properly.

**Comment by mfazekas** [comment]
Thanks for the report. This sounds like an upstream issue, with mapbox. Sorry we don't have resources to look into, please try to report to upstream at: https://github.com/mapbox/mapbox-maps-android
