### ISSUE TITLE
[Bug]: MapView contentInset is not applied

### ISSUE THREAD

**Issue by veb-ioki** [rnmapbox/maps#2554]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.10.0

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.64

### Standalone component to reproduce

```javascript
import React from 'react';
import { Button } from 'react-native';
import {
  MapView,
  ShapeSource,
  SymbolLayer,
  CircleLayer,
  Camera,
} from '@rnmapbox/maps';

const styles = {
  mapView: { flex: 1 },
  circleLayer: {
    circleRadiusTransition: { duration: 5000, delay: 0 },
    circleColor: '#ff0000',
  },
};

const features = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: 'a-feature',
      properties: {
        icon: 'example',
        text: 'example-icon-and-label',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.00597, 40.71427],
      },
    },
  ],
};

class TempMapView extends React.Component {
  state = {
    radius: 20,
  };

  render() {
    const circleLayerStyle = {
      ...styles.circleLayer,
      ...{ circleRadius: this.state.radius },
    };

    return (
      <>
        <Button
          title="Grow"
          onPress={() => this.setState({ radius: this.state.radius + 20 })}
        />
        <MapView style={styles.mapView} contentInset={[0, 0, 200, 0]}>
          <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
          <ShapeSource id={'shape-source-id-0'} shape={features}>
            <CircleLayer id={'circle-layer'} style={circleLayerStyle} />
            <SymbolLayer
              id="symbol-id"
              style={{
                iconImage: ['get', 'icon'],
              }}
            />
          </ShapeSource>
        </MapView>
      </>
    );
  }
}

export default TempMapView;

```

### Observed behavior and steps to reproduce

Tested in the repo's example app by simply replacing the component code of `example/src/examples/V10/CameraAnimation.tsx` with the above and change the `conentInset` values attribute on `MapView`.
Shots are identical, despite differences in `contentInset` (hover over shot for values):
<p>
<img width="200" title="contentInset=[0, 0, 0, 0]" src="https://user-images.githubusercontent.com/64905645/214050873-c27b903e-43c4-4399-bc90-fcbbd56c04ec.png">
<img width="200" title="contentInset=[0, 200, 0, 0]" src="https://user-images.githubusercontent.com/64905645/214050875-2ffa444e-8c20-449a-bb7c-09393d569b2a.png">
</p>

### Expected behavior

The MapView content should move according to the `contentInset` values.

### Notes / preliminary analysis

Only thing I checked was logging if the `contenInset` values reach the MapView component:
`javascript/components/MapView.js` Lines 803-813
They do.

First tested with 10.0.0-beta.59, Mapbox 10.10.7.
No changes since.

**Comment by KiwiKilian** [comment]
@mfazekas is this prop still supposed to work or should it be removed? It only ever appears in the [Android Code](https://github.com/rnmapbox/maps/blob/main/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt#L200-L203). Was this once supported by the native SDK MapViews or was this always properietary to rnmapbox? Because I currently can't find any docs for v10 setting an inset in the native SDKs – only always padding on Camera options or functions. Am I missing something?

To fix a few of these padding/inset problems, we should decide how the combination of these props shall work.

- Should this prop `contentInset` still exist and should it always be a global `padding` added to everything? 
  - `UserLocation` puck, `Camera` `padding` (as prop as well when using `setCamera`, `fitBounds`), Ornaments?
- If not, is there any other global `padding`/`inset` supposed to exist? The `Camera` props currently are more some kind of imerpative way to change the camera, but setting a `padding` is not supposed to be always added when for example calling `setCamera` without a padding?

**Comment by mfazekas** [comment]
@KiwiKilian I don't really remember the exact details, but we had a lot of similar stuff in mapbox-gl-ios: edgePadding, contentInset, and there were quite a few issues. I'll try to think about what's the best way going ahead.

https://github.com/mapbox/mapbox-gl-native/issues/12818

**Comment by veb-ioki** [comment]
>@veb-ioki for now you could use padding on Camera to achieve mostly the same result. You have to always apply the same padding later on when changing with setCamera etc...

Thanks @KiwiKilian for clarification! We will try it out.

**Comment by veb-ioki** [comment]
**Update:**
Setting padding on Camera works on iOS ✅,
but has no effect on Android ❌ 

See also [this observation](https://github.com/rnmapbox/maps/issues/2317#issuecomment-1412067753) on `MapView` callbacks on Android not firing, while fine on iOS. 
Maybe it's related?

(Tested with version: "@rnmapbox/maps": "10.0.0-beta.65"
Really sorry I can't contribute much more. My native powers are very limited 😔)

**Comment by KiwiKilian** [comment]
@mfazekas 
> I don't really remember the exact details, but we had a lot of similar stuff in mapbox-gl-ios: edgePadding, contentInset, and there were quite a few issues. I'll try to think about what's the best way going ahead.

Did you yet have some time thinking about it? We will soon need the `UserPosition` with some kind of `contentInset`. So if we do have some concept, I could try working into that direction. Otherwise I would be trying to add a prop specific to `UserLocation`.

**Comment by dorthwein** [comment]
Adding to @KiwiKilian the use case for this seems to be mostly having the user location positioned at the bottom of the map (or side in landscape) for turn by turn navigation.  I know in v8 this was a constant battle for a long time.

**Comment by KiwiKilian** [comment]
@dorthwein see https://github.com/rnmapbox/maps/pull/2630

**Comment by dorthwein** [comment]
@KiwiKilian - not all heros wear capes - your the man! Thank you!  I look forward to giving this a go!

**Comment by KiwiKilian** [comment]
@veb-ioki for `setCamera` padding on Android see: https://github.com/rnmapbox/maps/pull/2669 – hopefully soon to be released.

**Comment by veb-ioki** [comment]
Thank you @KiwiKilian ... 👉 https://github.com/rnmapbox/maps/issues/2554#issuecomment-1450602239!! 🙇‍♀️
Will check it out ASAP

**Comment by KiwiKilian** [comment]
Make sure to [install from git `#main`](https://github.com/rnmapbox/maps#step-1---install-package) as it's not yet released in a beta version.

**Comment by veb-ioki** [comment]
Can confirm that it works like a charm now on android as well!
=> Closing as this got fixed with https://github.com/rnmapbox/maps/pull/2669

**Comment by KiwiKilian** [comment]
I would rather keep this open, because `contentInset` is still to be discussed.

**Comment by veb-ioki** [comment]
> I would rather keep this open, because `contentInset` is still to be discussed.

Oh, sorry! Of course.

**Comment by mfazekas** [comment]
@KiwiKilian sorry can we move to discussions instead? We can think about bringing the [viewport](https://docs.mapbox.com/android/maps/api/10.4.0/mapbox-maps-android/com.mapbox.maps.plugin.viewport/viewport.html) concept to rnmapbox in some form.

I think followPadding in Camera does fit into the current logic. So #2630 is good for now. Yes we'd not necessary need both the follow and non follow properties. The only use of that I can think of right now, if that until GPS signal is available you wan to display a different location.
