### ISSUE TITLE
[Bug]: Markers appear stuck on the screen when they are on a non visible part of the map and change shape

### ISSUE THREAD

**Issue by pablogdcr** [rnmapbox/maps#2562]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.64

### Standalone component to reproduce

```javascript
import React, { useState, useMemo } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import {
  MapView,
  MarkerView,
  Camera,
} from '@rnmapbox/maps';

const Map = () => {
  const [selectedMarkerId, setSelectedMarkerId] = useState(0);

  const markers = useMemo(() => (
    [{
      "id": 0,
      "lat": 41.393042,
      "lng": 2.1848,
    }, {
      "id": 1,
      "lat": 41.392747,
      "lng": 2.185167,
    }]
  ), [selectedMarkerId]);

  return (
    <MapView style={{flex: 1}} onPress={() => setSelectedMarkerId(undefined)}>
      <Camera centerCoordinate={[2.1848, 41.393042]} zoomLevel={14} />
      {markers.map((marker) => (
        <MarkerView
          key={marker.id}
          coordinate={[marker.lng, marker.lat]}
          allowOverlap
        >
          <Pressable onPress={() => setSelectedMarkerId(marker.id)}>
            <View style={marker.id === selectedMarkerId ? styles.selected : styles.notSelected} />
          </Pressable>
        </MarkerView>
      ))}
    </MapView>
  );
};

const styles = StyleSheet.create({
  selected: {
    height: 20,
    width: 20,
    borderRadius: 10,
    backgroundColor: 'red',
  },
  notSelected: {
    height: 30,
    width: 30,
    backgroundColor: 'blue',
  },
});

export default Map;
```

### Observed behavior and steps to reproduce

In the example above, I'm displaying a map with two markers.
When a marker is selected, its width and height change (as does its color).
When you press the map, the markers are deselected.

If you select a marker, move the map so the markers are no longer visible on the screen, then press the map to deselect the selected marker, both markers will appear on the side of the screen, detached from the map.

### Expected behavior

The makers must remain in their position on the map, and therefore not be visible on the screen.

### Additional links and references

https://user-images.githubusercontent.com/35684551/214818693-d743b8d2-2515-4085-96c2-8b96e916ecfd.mp4

**Comment by mfazekas** [comment]
@pablogdcr thanks much for the clear and easy to reproduce bug report, I have an alternative fix at #2589
