### ISSUE TITLE
[Bug]:  (Android) NullPointerException when quickly loading / unloading map

### ISSUE THREAD

**Issue by Arilith** [rnmapbox/maps#2563]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.64

### Standalone component to reproduce

```javascript
import { View, StyleSheet } from 'react-native'
import React, {  useEffect,  useRef, useState } from 'react'
import MapboxGL, {  MapView } from '@rnmapbox/maps';

export const MapScreen = () => {

  const [showMapTest, setShowMapTest] = useState(true);

  const Map = useRef<MapView>(null);
  const Camera = useRef<MapboxGL.Camera>(null);


  useEffect(() => {
    setInterval(() => {
      setShowMapTest(!showMapTest);
    }, 500);
  }, [])


  return (
      <View style={ styles.container }>
        {
            showMapTest &&
            <MapView styleURL='mapbox://styles/arilith/ckr9r509238t817mxz75lwbxt' style={styles.map} ref={Map} scaleBarEnabled={false}>
              <MapboxGL.Camera ref={ Camera } />
            </MapView>
        }
      </View>
  )
}


const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1
  }
});

```

### Observed behavior and steps to reproduce

Upon switching to and from a component that has a (partially?) loaded map, the following exception is thrown:

```js
java.lang.NullPointerException
  com.mapbox.rctmgl.components.camera.RCTMGLCamera$mCameraCallback$1.onAnimationEnd(RCTMGLCamera.kt:96)
  com.mapbox.rctmgl.components.camera.CameraUpdateItem$run$callback$1.onAnimationEnd(CameraUpdateItem.kt:61)
  android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
  android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1294)
  android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1079)
  android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
  android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
  android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
  android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
  android.view.Choreographer.doCallbacks(Choreographer.java:761)
  android.view.Choreographer.doFrame(Choreographer.java:693)
  android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
  android.os.Handler.handleCallback(Handler.java:873)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loop(Looper.java:214)
  android.app.ActivityThread.main(ActivityThread.java:7050)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

Please note that this only happens on Android, while on iOS this issue does **not** occur. It seems that the unmounting of the map creates some kind of problem if the map is asked to mount immediately after again.

The use case where I noticed this problem is:
User switches to map screen, switches away very quickly (before the map has finished fully initializing), and then opens the map screen again. The app will crash fully with the above error.

I've also seen this behavior happen in a non "react-navigation/tabs" navigator. Just a simple component mount / unmount also triggers this error. (For example someone presses a button to open a map sheet, closes it and pressed the button quickly again).

### Expected behavior

The expected behaviour is that the map does not throw the exception and unmounts/mounts correctly, just like it seems to do on iOS, where I haven't managed to recreate this bug in both an emulator and/or physical device.

### Notes / preliminary analysis

It seems like it's Android version / phone independent, I've had multiple people with different phones and releases of android have the bug happen. While testing on my S8+ running Android 9 pie, the problem also occurs. However, I have not managed to trigger it in my Android emulator (yet). It could simply be that the emulator is "too slow" to make this quick switch bug happen.

It also seems like that the problem is not related to the tab navigator for react native (which was a previous problem where the app would hang/crash after switching away from the maps tab for android). The problem also occurs in "generic" view mounts/unmounts.

### Additional links and references

As it occurs on my physical android device (sorry for no screen cap, old s8 didn't like it :()
https://user-images.githubusercontent.com/13538135/214840315-05ae0f34-dec2-43aa-b922-35a0995bcb47.mp4

As it should be on my physical iPhone (12 Pro Max)
https://user-images.githubusercontent.com/13538135/214839924-b298906d-2c7e-466d-bd0a-6b35003d4bf6.MP4

**Comment by mfazekas** [comment]
@Arilith can you change it to a component that reproduces the issue without user interaction? Like using setTimeout to hide/show the map?

**Comment by Arilith** [comment]
> @Arilith can you change it to a component that reproduces the issue without user interaction? Like using setTimeout to hide/show the map?

@mfazekas Updated the reproduction component. I tested it on my S8 and it triggered the crash.
