### ISSUE TITLE
[Bug]:  setCamera animaition issue

### ISSUE THREAD

**Issue by junleejaehyuk** [rnmapbox/maps#2567]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.0-beta.60

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

  const focusUser = useCallback(() => {
    if (setLocationValue) {
      camera.current?.setCamera({
        pitch: 30,
        heading: 0,
        zoomLevel: 12,
        animationMode: 'none',
        animationDuration: 0,
        centerCoordinate: [setLocationValue.lon, setLocationValue.lat],
      });
    }
  }, [setLocationValue]);         

  useEffect(() => {
    setTimeout(() => {
      focusUser();
    }, 2000);
  }, [focusUser]);

<MapboxGL.Camera
            followUserLocation={false}
            defaultSettings={{ zoomLevel: isIos ? 0 : 5, centerCoordinate: [127, 34] }}
            ref={camera}
            maxZoomLevel={20}
          />

### Observed behavior and steps to reproduce

After connecting the map, other buttons cannot be pressed until the animation of the setCamera function is finished in camera.

**Comment by mfazekas** [comment]
@junleejaehyuk thanks for the report and the sample code, but I don't understand what's the issue. What's are other buttons?
