### ISSUE TITLE
[Bug]:  Invalid displacement location error React Native

### ISSUE THREAD

**Issue by BrunoArrojado** [rnmapbox/maps#2579]
### Mapbox Implementation

Mapbox

### Mapbox Version

main

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.65

### Standalone component to reproduce

Created a Map component where I need the userLocation property enabled, nothing special there.

### Observed behavior and steps to reproduce

I was running an app using mapbox for some time, and since this weekend, after reinstalling npm the app after requesting the the location permission started to crash.

If I comment the mapbox code, it will work, can you please help?

![image](https://user-images.githubusercontent.com/29729658/216133163-1c044fb1-2f03-4624-93b1-9fb8a8d06eff.png)

### Expected behavior

Aplication running without no problem...

**Comment by mfazekas** [comment]
Please include example code.

**Comment by BrunoArrojado** [comment]
<SafeAreaView style={styles.safeAreaView}>
        <View style={styles.mapContainer}>
          <MapboxGL.MapView
            style={styles.map}
            styleURL={MapboxGL.StyleURL.Street}
            logoEnabled={true}
            localizeLabels={true}
            onPress={(feature) => { console.log('Coords:', JSON.stringify(feature.geometry)); setOcurrenceLocation(feature.geometry.coordinates) }}
          >
            <MapboxGL.UserLocation
              visible={true}
              showsUserHeadingIndicator={Platform.OS === 'ios'}
            />
            <MapboxGL.Camera
              zoomLevel={10}
              animationMode={'flyTo'}
              animationDuration={2000}
              followUserLocation={true}
            />
            {(ocurrenceLocation) &&
              renderAnnotations()}

          </MapboxGL.MapView>
     
      </View>
    </SafeAreaView >

**Comment by MartinGryner** [comment]
Had the same issue after upgrading expo to 47. Fixed by changing Mapbox implementation from maplibre to mapbox.
