### ISSUE TITLE
Unexpected token ','    

### ISSUE THREAD

**Issue by qeorqe-codes** [rnmapbox/maps#2597]
## Environment
- Dev OS: [Mac OS monterey]

## Steps to reproduce
Issue on IOS simulator.
Followed the installation guide from the docs. When I add an import statement (`import MapboxGL from '@rnmapbox/maps'`;) I get this error and I can not figure out why. 

`$RNMapboxMapsImpl` is set to  `'mapbox'` at the top of my podfile. I also added to my podfile folowing strings:
`pre_install do |installer|
   $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
   $RNMapboxMaps.post_install(installer)
  end`
Pods are being installed and app builds successfully but this is all I get. I definitely did not put extra ',' somewhere
<img width="321" alt="image" src="https://user-images.githubusercontent.com/93978839/217828479-db7abdca-8987-4c11-844b-83a31f42dfd7.png">

**Comment by mfazekas** [comment]
@qeorqe-codes sorry not enough info to reproduce closing. Most likely and old typescript/babel issue.

**Comment by alfredvaa** [comment]
I just got the same thing. With less even less info. Using Expo 47.
<img width="412" alt="image" src="https://user-images.githubusercontent.com/10890307/219849542-003eb566-e775-40d1-b50c-56a8a544c6a7.png">

**Comment by harishgupta01** [comment]
@alfredvaa @qeorqe-codes Did you guys got the solution for this ?

**Comment by alfredvaa** [comment]
@harishgupta01 no, i switched to react-native-maps instead.

**Comment by harishgupta01** [comment]
@alfredvaa Actually just now i found the solution. My react native app is written in JS but rnmapbox in typescript. After adding preset-typescript as below fixes the issue.
 
***Babel.config.js***
```
module.exports = {
  presets: ['@babel/preset-typescript', 'module:metro-react-native-babel-preset']
};

```


***package.json***
```
"devDependencies": {
    "@babel/core": "^7.16.12",
    "@babel/preset-typescript": "^7.22.15",
....
```
