### ISSUE TITLE
[Bug]: LongPress event on Android triggered by pressing a marker and then the map

### ISSUE THREAD

**Issue by pablogdcr** [rnmapbox/maps#2598]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.68

### Standalone component to reproduce

```javascript
import React, { useState, useMemo } from 'react';
import { Pressable, View } from 'react-native';
import {
  MapView,
  MarkerView,
  Camera,
} from '@rnmapbox/maps';

const Map = () => {
  const [selectedMarkerId, setSelectedMarkerId] = useState(0);

  const markers = useMemo(() => (
    [{
      "id": 0,
      "lat": 41.393042,
      "lng": 2.1848,
    }, {
      "id": 1,
      "lat": 41.393242,
      "lng": 2.1853,
    }, {
      "id": 2,
      "lat": 41.392747,
      "lng": 2.185167,
    }]
  ), []);

  return (
    <MapView style={{flex: 1}} onLongPress={() => console.log('Long Press')}>
      <Camera centerCoordinate={[2.1848, 41.393042]} zoomLevel={14} />
      {markers.map((marker) => (
        <MarkerView
          key={marker.id}
          coordinate={[marker.lng, marker.lat]}
        >
          <Pressable onPress={() => setSelectedMarkerId(marker.id)} >
            <View style={{ height: 30, width: 30, backgroundColor: marker.id ===  selectedMarkerId ? 'red' : 'blue'}} />
          </Pressable>
        </MarkerView>
      ))}
    </MapView>
  );
};

export default Map;
```

### Observed behavior and steps to reproduce

In the example above, we display 3 markers on a map.
The selected marker is red, and the others are blue.
On the MapView component, the onLongPress function is implemented and displays a message on the terminal.

If I press a marker (selected or not) and then press any other part of the map, the onLongPress event is triggered, and the message is displayed.

### Expected behavior

The onLongPress event shouldn't be triggered.

**Comment by mfazekas** [comment]
I've tried on emulator with beta70 and I could not reproduce it. `onLongPress` was written to console for long press on a map. I've clicked a blue marker it became red, then clicked on map but did not see the `onLongPress` in the console.
