### ISSUE TITLE
[Bug]: MapboxGL.MapboxV10 not getting set

### ISSUE THREAD

**Issue by jrobber** [rnmapbox/maps#2602]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.58

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

function BugReportExample: React.FC<MapViewProps> = (props) => {  {
   const mapRef = useRef<MapboxGL.MapView>()
  
  
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine} 
            onPress={e=> {
                   const markers = await mapRef.current.queryRenderedFeaturesInRect([], undefined, ['idStreetLayer'])
            }
}
          >
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  
}
```

### Observed behavior and steps to reproduce

When trying to get `queryRenderedFeaturesInRect` to work according to the docs I tried to pass in an empty array and got an error about empty arrays only in V10.

So I put some logs in and found that MapboxV10 is undefined.

`mapRef.current.queryRenderedFeaturesInRect([], undefined, ['home-layer'])`
Will fail because it doesn't think I'm on V10

### Expected behavior

MapboxV10 to be set so the supported V10 features work correctly

### Notes / preliminary analysis

I'm on expo 46.

app.json plugin setup:
```
  [
        "@rnmapbox/maps",
        {
          "RNMapboxMapsImpl": "mapbox",
          "RNMapboxMapsDownloadToken": "pk.ABC.XYZ"
        }
      ],
      ```
      
 I also tried following the manual iOS docs and putting the podfile instruction in, that did nothing different.
 
 When searching for MapboxV10 I can see it set in MGLModule.swift
 ```
 @objc(MGLModule)
class MGLModule : NSObject {
  static var accessToken : String?
    
  @objc
  func constantsToExport() -> [AnyHashable: Any]! {
    return [
      "MapboxV10":true,
      "StyleURL":
        [
```

**Comment by mfazekas** [comment]
Your expo config is wrong in some way causing RNMapbox to use the default MapLibre implementation
