### ISSUE TITLE
[Bug]: '@objc' instance method in extension of subclass of 'MapView' requires iOS 13.0.0

### ISSUE THREAD

**Issue by KirillRodichev** [rnmapbox/maps#2607]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.68

### Standalone component to reproduce

Don't think components are necessary, since the build fails

Poflie:
```
use_frameworks! :linkage => :static

$RNMapboxMapsImpl = 'mapbox'

if $RNMapboxMapsImpl == 'mapbox'
  platform :ios, '13.0'
else
  platform :ios, '12.4'
end

IS_CI = ENV['APPCENTER_BUILD_ID']

target '...' do

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
    ...
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)

    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
end

```

### Observed behavior and steps to reproduce

**OB:** 
<img width="346" alt="Screenshot 2023-02-15 at 16 23 21" src="https://user-images.githubusercontent.com/57504303/219088732-3dcdcf32-8be8-4b6f-9b80-870816da16b9.png">
<img width="1305" alt="Screenshot 2023-02-15 at 16 24 07" src="https://user-images.githubusercontent.com/57504303/219089009-8e3c4b9a-c94d-4c1e-8fd3-2a042e4aed0e.png">

### Expected behavior

**EB:** builds without errors

### Notes / preliminary analysis

After installation the build was failing. I tried
- specifying platform as you can see in Podfile
- removing BUILD_LIBRARY_FOR_DISTRIBUTION = 'YES'
- increasing project's minimum deployment to 13
- reinstalling pods

Once I was able to build, but the it started failing again with same errors.

**Comment by mfazekas** [comment]
@KirillRodichev  it does build in our example app, so likely it's an issue with your project setup. Can you reproduce in a branch new project started with `react-native create` ?!

**Comment by martinlAP** [comment]
Hello,

I have the same issue on React Native 0.71.8
@KirillRodichev Did you find a solution? 

I'm going to try to reproduce the issue with a blank project.
