### ISSUE TITLE
[Bug]: MarkerViews become 'unfixed' from their coordinate and float around the map

### ISSUE THREAD

**Issue by connorpmullins** [rnmapbox/maps#2608]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.59

### Standalone component to reproduce

```javascript
import MapboxGL, { Camera, MapView, RegionPayload } from "@rnmapbox/maps";

const Component = () =>  (
        <MapboxGL.MapView
          compassEnabled
          ref={mapRef}
          style={{ flex: 1, opacity: overlay ? 0 : 1 }}
          styleURL={styleUrl}
          projection="mercator"
          scaleBarEnabled={false}
          onRegionIsChanging={updatePins}
          onDidFinishLoadingMap={() => {
            setOverlay(false);
            updatePins();
          }}
          regionDidChangeDebounceTime={100}>
          <Camera
            ref={cameraRef}
            animationMode="flyTo"
            animationDuration={0}
            zoomLevel={7}
            centerCoordinate={
              userLocation
                ? [
                    parseInt(userLocation.longitude, 10),
                    parseInt(userLocation.latitude, 10),
                  ]
                : undefined
            }
          />
          {pins.length
            ? pins.map(({ waterbody, Pin }) => (
                <MapboxGL.MarkerView
                  key={waterbody.id}
                  allowOverlap
                  coordinate={[waterbody.lng, waterbody.lat]}
                  style={{ zIndex: waterbody.fishing_reports_count || 1 }}>
                  <Pressable onPress={() => onSelectMapPin(waterbody)}>
                    <Pin height={50} width={50} />
                  </Pressable>
                </MapboxGL.MarkerView>
              ))
            : null}
        </MapboxGL.MapView>
)
```

### Observed behavior and steps to reproduce

Here's a video of the behavior we encounter:
https://user-images.githubusercontent.com/24562987/219132205-d065db5a-fb9b-4ff8-bc4b-d14cec169291.mp4

As you can see above, on occasion, the MarkerViews we use become unfixed from their coordinates and remain at a fixed place on the screen until we move the map outside the bounds of where the pins should be displayed and they're un-rendered.

This is not something that is consistently reproducible, but does pop up with some consistency. I only included our Mapbox code because I figured the other component code wasn't related to the bug. Happy to post more code if helpful reproducing

### Expected behavior

The expected behavior is that MarkerViews remain pinned to their coordinates

### Notes / preliminary analysis

We're using the new mapbox implementation and encountering the above issue. Apologies if this has already been reported or resolved. The other MarkerView issues seemed to not be exactly what I'm encountering. 

One thing to note is that I am 10 patch versions behind the latest beta - I can't update from .59 -> .69 because we're on Expo 45 and you require Expo 47 for the latest beta.

In case it's pertinent, here's my code for generating and updating the data we render into MarkerViews:
```  
const updatePins = useCallback(
      async (props?: GeoJSON.Feature<GeoJSON.Point, RegionPayload>) => {
        let bounds: GeoJSON.Position[] | undefined;
        let zoom;
        if (props) {
          bounds = props.properties.visibleBounds;
          zoom = props.properties.zoomLevel;
        } else {
          bounds = await mapRef.current?.getVisibleBounds();
          zoom = await mapRef.current?.getZoom();
        }

        if (bounds && bounds.length && zoom) {
          const waterbodies = await callFetchPins({
            ...deriveBoundsFromPosition(bounds),
            zoom,
            limit: 20,
          });
          if (waterbodies) {
            const inViewFavs = favoriteWaterbodies.filter(
              ({ lat, lng }) =>
                lat <= bounds[0][1] &&
                lat >= bounds[1][1] &&
                lng <= bounds[0][0] &&
                lng >= bounds[1][0]
            );
            const mapPins = generateMapPins({
              waterbodies,
              favoriteWaterbodies: inViewFavs,
              selectedPin,
            });
            setPins(mapPins);
          }
        }
      },
    [favoriteWaterbodies, selectedPin]
  );
  ```
  
  Thank you for your time!

**Comment by mfazekas** [comment]
Can you try a more recent beta? https://github.com/rnmapbox/maps/pull/2589 was fixed since beta 59. So pls retest with latest beta (beta-69)
