### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by g-pex-aerian** [rnmapbox/maps#2612]
## New Feature
I appreciate this is not currently in development and as far as I can tell is not currently on the roadmap either however it's a feature I'm sure I am not alone in hoping it will be considered at some point in the future, especially as more libraries implement it.

## Why
For me personally, I maintain a number of React Native Apps and have began the update process and move to the new architecture where possible. One particular App could be switched over but for this one library not supporting it. Generally speaking I think it's common for the Map to be a core feature and as we use MapBox and have a custom set of Maps implemented and hosted on MapBox cloud, it's not possible for us to move to another provider.  

I'm opening this not with the expectation that it will speed up the process of supporting Fabric but at least to:

1. Highlight how much demand there is for this feature.
2. A place to both follow the conversation around this feature and hopefully get updates on when it might be supported.

Many thanks to those that are maintaining and improving this library by the way, it's very much appreciated.

**Comment by mfazekas** [comment]
Closing as Discussions is more appropriate for this.
