### ISSUE TITLE
[Bug]: Compass frozen, not rotating (v10 + Android)

### ISSUE THREAD

**Issue by jfaq89** [rnmapbox/maps#2614]
### Mapbox Implementation

Mapbox

### Mapbox Version

10

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.69

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView compassEnabled style={{flex: 1}} />
    );
  }
}
```

### Observed behavior and steps to reproduce

Compass is frozen no matter what I do.

### Expected behavior

Rotate the map and see compass rotating accordingly

### Notes / preliminary analysis

I did try the example App (see Video) and I got the same problem.

### Additional links and references

https://user-images.githubusercontent.com/39528995/219387467-ddf49f49-836d-4ce8-99be-4ad50decfec5.mp4

**Comment by mfazekas** [comment]
@jfaq89  how is it different than #2543 ?!

**Comment by jfaq89** [comment]
There is no relation to the navigation as far as I see. I did try navigating away and back and that didn't fix the problem in my case. It could be that the symptom is the same but the cause is different.

**Comment by mfazekas** [comment]
@jfaq89 I've checked and navigating away then back solved the issue. 

<img width="399" alt="image" src="https://user-images.githubusercontent.com/52435/221421561-55c983d6-980a-4ab0-896e-8fc7c2239a6e.png">
