### ISSUE TITLE
Expo Plugin doesn't support `RNMapboxMapsVersion`

### ISSUE THREAD

**Issue by KiwiKilian** [rnmapbox/maps#2618]
## New Feature
As far as I understand the plugin code, `RNMapboxMapsVersion` is currently not supported through the Expo plugin. Am I right?

## Why
In cases like #2613 it's desirable to change the Mapbox version beeing used instead of downgrading the rn package.

**Comment by KiwiKilian** [comment]
I'm also seeing this error during a local eas build.

```
[INSTALL_PODS] /build/node_modules/@rnmapbox/maps/rnmapbox-maps.podspec:91: warning: already initialized constant Pod::MapboxImplVersion
[INSTALL_PODS] /build/node_modules/@rnmapbox/maps/rnmapbox-maps.podspec:91: warning: previous definition of MapboxImplVersion was here
```

**Comment by Lurtroxx** [comment]
Is there any way to solve this? I am just seeing a black box for my mapbox map. I had the map working before, I'm not sure what I did to mess it up.

**Comment by KiwiKilian** [comment]
@Lurtroxx you are probably experiencing a different problem. Black box instead of the map ist mostly a missing access token.

**Comment by Lurtroxx** [comment]
@KiwiKilian !!! We have mapbox implementation working with expo managed project and development builds. 

In the App.tsx file you need the following code, and the import for MapboxGL at the top:

`
MapboxGL.setAccessToken(Constants.expoConfig?.extra?.mapbox.token);
`
and in your app.json file you will need the "Extra" section of expo config that matches the key you are using in the plugins section, or use .env for the token.

"extra": {
      "mapbox": {
        "token": "sk........."
      }
    },

I also reverted back 1 version on the mapbox 10.0 beta to 10.0.0-beta.68 not 69 (current)

**Comment by KiwiKilian** [comment]
Still, I'm talking about a different topic. I would like to conrol which **version** of the Mapbox SDKs are installed.

**Comment by mfazekas** [comment]
@KiwiKilian thanks, yep RNMapboxMapsVersion not there in expo plugin. It should be straightforward to add. PR welcome

https://github.com/rnmapbox/maps/blob/main/plugin/src/withMapbox.ts

**Comment by KiwiKilian** [comment]
Also it's only supported on Android?

**Comment by mfazekas** [comment]
It should be supported on iOS and Android as well

**Comment by mfazekas** [comment]
@KiwiKilian oh yep on android we provide hook to change the libraries, no way for just version
