### ISSUE TITLE
[Bug]: Type 'OfflineSwitch' has no member 'getApiData'

### ISSUE THREAD

**Issue by Jobjeuh** [rnmapbox/maps#2621]
### Mapbox Implementation

Mapbox GL

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

This is the class where it goes wrong on iOS:
```swift
public class OfflineSwitch {
    internal var internalOfflineSwitch: MapboxCommon.OfflineSwitch

    /// Returns the `OfflineSwitch` shared instance.
    public static var shared = {
        return OfflineSwitch()
    }()

    private init() {
        internalOfflineSwitch = MapboxCommon.OfflineSwitch.getApiData() // <--- Here is where the error occurs
    }

    /// Connects or disconnects the Mapbox stack. If set to `false`, current
    /// and new HTTP requests will fail with `HttpRequestError` with type
    /// `.connectionError`.
    public var isMapboxStackConnected: Bool {
        get {
            return internalOfflineSwitch.isMapboxStackConnected()
        }
        set {
            internalOfflineSwitch.setMapboxStackConnectedForConnected(newValue)
        }
    }
}
```

This is a snippet of the code in my app:
```javascript
<MapboxGL.MapView
    localizeLabels={true}
    rotateEnabled={false}
    logoEnabled={false}
    compassEnabled={true}
    zoomEnabled={true}
    pitchEnabled={true}
    style={styles.map}
    onTouchEnd={handleMapTouch}
>
            <MapboxGL.Camera ref={camera} />
            <MapboxGL.UserLocation
                    showsUserHeadingIndicator={false}
                    renderMode="native"
                    // TODO: Up later (10?)
                    minDisplacement={0}
                    visible={true}
                    onUpdate={e => handleLocationUpdate(e)}
            />
            <Route />
            <POIs />
</MapboxGL.MapView>
```
`Route` and `POIs` are not that special; they implement `MarkerView`s and `ShapeSource` 

### Observed behavior and steps to reproduce

I've followed the installation steps for both Android and iOS. It works fine on Android, but on iOS I get the above mentioned error message in XCode when trying to compile a build. This happens on both a Simulator, aswell as on a physical device.

I'm no expert with Swift or most of the native side of app development. So I don't know if I'm doing anything wrong somewhere else in the code?

### Expected behavior

After running `npx react-native run-ios (--device)` I expect it to compile with no errors

**Comment by mfazekas** [comment]
For me that line is `internalOfflineSwitch = MapboxCommon.OfflineSwitch.getInstance()` please remove your ios/Podfile.lock, and ios/Pods and do a pod install again.
