### ISSUE TITLE
[Bug]: Add custom headers not working in iOS

### ISSUE THREAD

**Issue by wmonecke** [rnmapbox/maps#2628]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

^10.0.0-beta.70

### Standalone component to reproduce

Calling these methods dont work on iOS

```javascript
MapboxGL.addCustomHeader(
  'authority',
  getValueForCurrentEnv('MAPBOX_AUTHORITY'),
);

MapboxGL.addCustomHeader(
  'Authorization',
  `Basic ${btoa(
    getValueForCurrentEnv('GEOSERVER_USER') +
      ':' +
      getValueForCurrentEnv('GEOSERVER_SECRET'),
  )}`,
);
```

**Comment by mfazekas** [comment]
@wmonecke pls expand your bug report, what doesn't work means, and how can we reproduce the issue?

**Comment by wmonecke** [comment]
@mfazekas I am adding an API key to the custom headers as shown above but getting a 401 meaning that they are not set.

I think I am bit confused because of this documentation:
[https://github.com/rnmapbox/maps/blob/main/docs/CustomHttpHeaders.md](https://github.com/rnmapbox/maps/blob/main/docs/CustomHttpHeaders.md)

Is the official way to add custom HTTP methods in Mapbox v10 to do it via a swizzle in iOS or should `MapboxGL.addCustomHeader` be working now?

**Comment by mfazekas** [comment]
Updated docs, hopefully it's clearer. For which request are you receiving 401? You can try to add breakpoints to onRequest and inDownload to check if headers are aded correctly. But looking at the code that should work just fine

**Comment by wmonecke** [comment]
Thank you for the prompt answer and doc update 🚀

I am receiving 401s for custom layers that need the API key set in the Mapbox header.
With the swizzle method, it worked fine and the layers loaded - with `MapboxGL.addCustomHeader` it doesn't.

Excuse my ignorance but I don't see Mapbox v10 exposing an `onRequest` or `inDownload` method. I checked `MapboxGL` or if this was a prop of `MapboxGL.MapView`. Where can I find these methods?
