### ISSUE TITLE
Handle iconHaloColor, iconHaloWidth and iconHaloBlur for SymbolLayer

### ISSUE THREAD

**Issue by pablogdcr** [rnmapbox/maps#2629]
## New Feature

It seems that those three styles aren't working on the v10 (`iconHaloColor`, `iconHaloWidth`, `iconHaloBlur`).

## Why
Today there is no way to put a halo on the symbol layers.

**Comment by mfazekas** [comment]
@pablogdcr pls post a complete example a describe what's not working, iconHaloColor, iconHaloWidth, and iconHaloBlur should be all implemented
