### ISSUE TITLE
[Bug]: Map is blank on my iPhone 13 mini OS 16.3.1 but works on my iPhone 6s OS 15.7.3

### ISSUE THREAD

**Issue by Abdulkhaaliq** [rnmapbox/maps#2632]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.54

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

MapboxGL.setAccessToken(
	"Mapbox access token",
);

const HomeScreen: React.FC = () => {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
       <MapboxGL.UserLocation visible />
		<View>
			<MapboxGL.ShapeSource
				cluster={false}
				id="car_parks"
				onPress={(e) => onMarkerPress(e, null, null)}
				shape={{
					type: "FeatureCollection",
					features: marker,
				}}>
				<MapboxGL.SymbolLayer
					sourceLayerID="symbolLayerSource"
					id="symbolLocationSymbols"
					filter={["!", ["has", "point_count"]]}
					style={{
						iconImage: require("../../../../assets/icon_transparent.png"),
						iconSize: 0.25,
						iconAllowOverlap: true,
					}}
				/>
			</MapboxGL.ShapeSource>
		</View>
      </MapView>
    );
}
```

### Observed behavior and steps to reproduce

Map loads perfectly on my iPhone 6s and iPhone 8 OS OS 16.3.1 but does not run on newer phones. I just get a blank screen. I am using an expo dev-client build so my app is managed with eas build

**Comment by mfazekas** [comment]
@Abdulkhaaliq  what is the plugin configuration? Please try with the latest version beta70

**Comment by Abdulkhaaliq** [comment]
` "plugins": [
      [
        "@rnmapbox/maps",
        {
          "RNMapboxMapsImpl": "mapbox",
          "RNMapboxMapsDownloadToken": "access token here"
        }
      ]
}`

I followed the docs on how to set it up to use mapbox implementation
