### ISSUE TITLE
[Bug]: MapboxGL.offlineManager.createPack is not working with custom style

### ISSUE THREAD

**Issue by anth0nieto** [rnmapbox/maps#2638]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.0-beta.64

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

```javascript
<MapboxGL.MapView
    ref={mapRef}
    style={style.mapContainer}
    styleURL={CUSTOM_STYLE_URL}
    compassEnabled
    compassViewPosition={3}
    regionDidChangeDebounceTime={1500}
    logoEnabled={false}
    attributionEnabled={false}
    scaleBarEnabled={false}
    onRegionDidChange={onRegionDidChange}
    onPress={presenter.onMapPress}
    testID="mapView"
    >
    <MapboxGL.Camera
	    ref={cameraRef}
	    zoomLevel={presenter.zoom}
	    animationMode="moveTo"
	    animationDuration={600}
	    centerCoordinate={presenter.centerCoordinates}
    />
    <MapboxGL.UserLocation showsUserHeadingIndicator />
    
    {renderExperiences( presenter )}
    </MapboxGL.MapView>
```

### Observed behavior and steps to reproduce

I made a function to download the map:

```
await MapboxGL.offlineManager.createPack(
	{
		name: this.packName,
		styleURL: CUSTOM_STYLE_URL,
		minZoom: 8,
		maxZoom: 16,
		bounds: this.selectedLocation.coordinatesBounds,
	},
	this.mapDownloadProgressListener,
	this.mapDownloadErrorListener,
);
```

the function is called when user press on download button. That button shows up when the map is already draw in the screen.

When the user is Offline, the map shows up but, not work properly beacuse the roads, trips, stations, all the details in the map they do not show well. It is as if the map is not downloading, and the reality is that it is not downloading because the errorListener is triggered.

### Expected behavior

The map should display well, in full detail when I am offline with the custom style.

### Notes / preliminary analysis

I believe that createPack does not support customs styles, or so I read on some sites.

**Comment by mfazekas** [comment]
@anth0nieto thanks for the report. Pls describe the correct versions  - 10.0.0-beta.64 is the @rnmapbox/maps version, what is your MapboxMaps version? Also please try with latest beta 70. Also please describe the error shown by errorListeners, and finally make a component which we can use to reproduce.

**Comment by JamesIde** [comment]
How does one consume an offline map? Is it through the styleURL?

**Comment by mfazekas** [comment]
@JamesIde if you have a pack created with same style url, as the map's styleURL, then mapbox should use that pack.

**Comment by midhun-sa** [comment]
> 

but when I turn off my net connection ... I am getting this error


 ERROR  Mapbox error Map load failed: {tile-id={x=5820, y=3838, z=13}, type=tile, message=Failed to load tile: Unable to resolve host "api.mapbox.com": No address associated with hostname, begin=72547879318, source-id=composite} {"level": "error", "message": "Map load failed: {tile-id={x=5820, y=3838, z=13}, type=tile, message=Failed to load tile: Unable to resolve host \"api.mapbox.com\": No address associated with hostname, begin=72547879318, source-id=composite}", "tag": "RCTMGLMapView"}

why is this coming?

**Comment by JamesIde** [comment]
@midhun-sa
Hey - I might be able to help as I believe I have solved it in my project
How are you creating your Mapbox.Mapview component? And how are you downloading your maps?

**Comment by anth0nieto** [comment]
Im downloading some p

> @anth0nieto thanks for the report. Pls describe the correct versions - 10.0.0-beta.64 is the @rnmapbox/maps version, what is your MapboxMaps version? Also please try with latest beta 70. Also please describe the error shown by errorListeners, and finally make a component which we can use to reproduce.


The error in ErrorListeners is 

`{"_metadata": null, "pack": {"bounds": "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Point\",\"coordinates\":[-154.72977783,20.40350508]}},{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Point\",\"coordinates\":[-156.04484719,18.79380124]}}]}", "metadata": "{
  \"name\" : \"BigPack\",
  \"styleURI\" : \"mapbox:\\/\\/styles\\/theamalgama\\/clf7dre09002u01nj9x696hhu\"
}"}}` the listeners no give more information. Only print that

**Comment by anth0nieto** [comment]
The version is the last one. `^10.0.0-beta.76`. But recently i dicovered that i was able to download some maps. But in some locations doesn't work.

With this params doesn't work:

```
await MapboxGL.offlineManager.createPack(
				{
					name: "BigPack",
					styleURL: "mapbox://styles/theamalgama/clf7dre09002u01nj9x696hhu",
					minZoom: 8,
					maxZoom: 16,
					bounds: [[-154.72977783, 20.40350508], [-156.04484719, 18.79380124]],
				},
				this.mapDownloadProgressListener,
				this.mapDownloadErrorListener,
```

but with this, works

```
await MapboxGL.offlineManager.createPack(
				{
					name: "BigPack",
					styleURL: "mapbox://styles/theamalgama/clf7dre09002u01nj9x696hhu",
					minZoom: 8,
					maxZoom: 16,
					bounds: [[-159.24283405355087, 22.284937595242525], [-159.8232784117509, 21.853928428098186]],
				},
				this.mapDownloadProgressListener,
				this.mapDownloadErrorListener,
				
```

I do not why. maybe is for the area. In the first case is more big than the second case. Are there some kind of limitation to download styles? I dont understand.

**Comment by midhun-sa** [comment]
@JamesIde 

This is how I download the map but, I also don't know how to use the downloaded file...



await MapboxGL.offlineManager.createPack(
      {
        name: 'offlinePack',
        styleURL: MapboxGL.StyleURL.Street,
        minZoom: 7,
        maxZoom: 16,
        bounds: [
          [11.2664, 75.7755],
          [11.2666, 75.7756],
        ],
      },
      progressListener,
      errorListener,
    );
  };


**and this is my map box component**


import {StyleSheet, Text, View} from 'react-native';
import React from 'react';


import CurrentLocationIcon from '../assets/images/CurrentLocationIcon';

import {useState} from 'react';

import MapboxGL from '@rnmapbox/maps';
import {useEffect} from 'react';

const MapBox = (props) => {
  const mapbox = React.createRef();
  const [isMapLoaded, setIsMapLoaded] = useState(false);

  useEffect(async () => {
    const offlinePacks = await MapboxGL.offlineManager.getPacks();
    console.log(offlinePacks[0].pack.bounds[0]);
    MapboxGL.initializeOfflinePacks;
    return () => {};
  }, []);

  return (
    <MapboxGL.MapView
      style={{...props.style}}
      ref={mapbox}
      centerCoordinate={[props.latitude, props.longitude]}
      showUserLocation={true}
      styleURL={MapboxGL.StyleURL.Street}>
      <MapboxGL.Camera
        zoomLevel={12}
        followUserLocation
        followZoomLevel={16}
        centerCoordinate={[props.longitude, props.latitude]}
      />

      <MapboxGL.PointAnnotation
        key="pointAnnotation"
        id="pointAnnotation"
        coordinate={[props.longitude, props.latitude]}
        anchor={{x: 0.5, y: 0.5}}>
        <CurrentLocationIcon />
      </MapboxGL.PointAnnotation>

     
    </MapboxGL.MapView>
  );
};

export default MapBox;

const styles = StyleSheet.create({});

**Comment by JamesIde** [comment]
I will confirm this with some tests later on in my own app, but I believe in an earlier issue @mfazekas said that Mapbox caches the downloaded packs and if the URL that you set in your offlineManager.createPack matches that of the URL passed in as styleURL, it will (somehow, magically), use/find the cached map for usage?

Also, @midhun-sa I reckon its worth using Mapbox instead of MapboxGL as technically the documentation is mostly referring to using 'Mapbox', but I'm unsure if theres any difference to be honest (very new to this). 

What I do know is that Mapbox (not MapboxGL) does not have an [inititialiseOfflinePacks ](https://github.com/rnmapbox/maps/blob/main/docs/OfflineManager.md) so your useEffect you have is probably not required.

**Comment by midhun-sa** [comment]
@JamesIde 
Thanks james...

**Comment by vienha** [comment]
i use rnmapbox version 10.1.31 and react-native version 0.75.4. When i call
          await MapboxGL.offlineManager.createPack(
				{
					name: "offlinePack",
					styleURL: "custom_style_url",
					minZoom: 0,
					maxZoom: 17,
					bounds: [ [105.517826, 20.90185],
							  [105.906464, 21.204365]],
				},
				this.progressListener,
				this.errorListener

I get status: 
{"completedResourceCount": 0, "completedResourceSize": 0, "erroredResourceCount": 0, "loadedResourceCount": 0, "loadedResourceSize": 0, "name": "offlinePack", "percentage": NaN, "requiredResourceCount": 0, "state": "complete"}.  no data downloaded. Please help me. Thanks.

**Comment by anth0nieto** [comment]
Try removingall the previous downloaded maps. Or cleaning the cache

**Comment by vienha** [comment]
@anth0nieto. I created a new package but still encountered the same issue.

**Comment by anth0nieto** [comment]
This is our code. 

```
private async deleteLocationsPacks() {
  const packs = await MapboxGL.offlineManager.getPacks();
  await Promise.all( packs.map( ( pack ) => MapboxGL.offlineManager.deletePack( pack.name ) ) );
}

private async createPack( location: Location, packName: string ) {
  try {
	return await MapboxGL.offlineManager.createPack(
          {
	          name: packName,
	          styleURL: location.mapStyle,
	          minZoom: 10,
	          maxZoom: 13.5,
	          bounds: location.coordinatesBounds,
          },
          this.mapDownloadProgressListener( location ),
          this.mapDownloadErrorListener( packName ),
          );
      } catch ( error ) {
	      throw new Error( "Error creating offline package" );
      }
}

private async downloadMap( location: Location ) {
  await this.deleteLocationsPacks();
  const packName = `${location.name}-Pack-Map`;
  MapboxGL.offlineManager.setTileCountLimit( 10000000000 );
  return this.createPack( location, packName );
}

```

In our case, we have uniques locations and uniques maps, we set the name of the each offline package with the location name and every time that we need to download a new map we run the `downloadMap()` method.

I don't know if this is the best approach but is working. If anybody knows another way, please let us know.

I hope this can work for you.
