### ISSUE TITLE
[Bug]: Android app crashes when when MapView is being unmounted

### ISSUE THREAD

**Issue by jmysliv** [rnmapbox/maps#2640]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.68

### Standalone component to reproduce

```js
function Component() {
  const [offline, setOffline] = useState(false);

 return (
  <View className="flex-1">
    {offline ? renderMapboxMapView() : renderSomethingElse()}
    <TouchableOpacity className="absolute z-50 b-0 l-0 w-[100] h-[100] bg-red" onPress={() => setOffline(!offline)}/>
  </View> 
)
}
```

### Observed behavior and steps to reproduce

I have a component that conditionally renders Mapbox `MapView` with some elements absolutely positioned on top of it, which are not rendered conditionally. When the MapView is being hidden the whole app crashes with the following stack trace:

![Screenshot 2023-02-28 at 19 54 39](https://user-images.githubusercontent.com/48885911/221952279-6e5b512e-d56d-4807-a2e6-8a9d79fddc31.png)

### Expected behavior

The app shouldn't crash, during toggling MapView.

**Comment by mfazekas** [comment]
@jmysliv  thanks for the report. I've tried this and could not reproduce. Pls attach a complete example so we can reproduce and fix

```jsx
import React, { useState } from 'react';
import { Button, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

const Map = () => {
  const [offline, setOffline] = useState(false);

  return (
    <View style={{ flex: 1 }}>
      <Button title="toggle" onPress={() => setOffline(!offline)} />
      {offline ? (
        <Mapbox.MapView style={{ flex: 1 }}>
          <Mapbox.Camera
            centerCoordinate={[2.162210168136397, 41.38882548578357]}
            zoomLevel={14}
          />
          <Mapbox.ShapeSource
            id="ss-source"
            shape={{
              type: 'FeatureCollection',
              features: [],
            }}
          >
            <Mapbox.SymbolLayer id="ss-symbol" style={{}} />
          </Mapbox.ShapeSource>
        </Mapbox.MapView>
      ) : (
        <View style={{ backgroundColor: 'red' }} />
      )}
    </View>
  );
};

export default Map;```
