### ISSUE TITLE
[Bug]: App crash when removing filter from SymbolLayer on Android

### ISSUE THREAD

**Issue by pablogdcr** [rnmapbox/maps#2649]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.71

### Standalone component to reproduce

```javascript
import React, { useMemo, useState } from 'react';
import MapboxGL from '@rnmapbox/maps';

const Map = () => {
  const shape = useMemo(() => ({
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        properties: { visible: true },
        geometry: {
          coordinates: [
            2.169586296739851,
            41.39450473274982
          ],
          type: "Point"
        }
      },
      {
        type: "Feature",
        properties: { visible: true },
        geometry: {
          coordinates: [
            2.162210168136397,
            41.38882548578357
          ],
          type: "Point"
        }
      },
      {
        type: "Feature",
        properties: {},
        geometry: {
          coordinates: [
            2.1707509486246295,
            41.38882548578357
          ],
          type: "Point"
        }
      },
      {
        type: "Feature",
        properties: {},
        geometry: {
          coordinates: [
            2.1752154475155407,
            41.38867985754251
          ],
          type: "Point"
        }
      }
    ]
  }), []);

  const [filter, setFilter] = useState(true);

  const toggleFilter = () => {
    setFilter(!filter);
  };

  return (
    <MapboxGL.MapView style={{flex: 1}} onLongPress={toggleFilter}>
      <MapboxGL.Camera centerCoordinate={[2.162210168136397, 41.38882548578357]} zoomLevel={14} />
      <MapboxGL.Images
        images={{
          marker: require('./assets/marker.png'),
        }}
      />
      <MapboxGL.ShapeSource id="markers" shape={shape}>
        <MapboxGL.SymbolLayer
          id="markers"
          style={{ iconImage: { uri: 'marker' } }}
          filter={filter ? ['==', 'visible', true] : undefined}
        />
      </MapboxGL.ShapeSource>
    </MapboxGL.MapView>
  );
};

export default Map;

```

### Observed behavior and steps to reproduce

In the example above, I display a map and a layer displaying markers.
This layer filters by default the markers that don't have the property `visible` set to true.
Doing a long press on the map deactivate/activate the filter on the SymbolLayer.

On IOS, it is working fine. On Android, it crashes when deactivating the filter with the following error:
```
Set layer property "filter" failed: filter value must be a non empty array
true
```

### Expected behavior

The app shouldn't crash, and the filters should be deactivated.

### Notes / preliminary analysis

The crash comes from `RCTLayer.kt`:

```kotlin
    fun setFilter(readableFilterArray: ReadableArray?) {
        val filterExpression = ExpressionParser.from(readableFilterArray)
        mFilter = filterExpression
        if (mLayer != null) {
            if (mFilter != null) {
                mHadFilter = true
                updateFilter(mFilter)
            } else if (mHadFilter) {
                updateFilter(literal(true)) // <== here
            }
        }
    }
```

I don't know how to fix is as I'm not able to find anything on the documentation about how to reset the filter of a SymbolLayer.

**Comment by pablogdcr** [comment]
As a workaround, this is what I do on my project:

```javascript
const noFilter = useMemo(() => (Platform.select({ ios: undefined, android: ['all'] })), []);

...

<MapboxGL.SymbolLayer
  ...
  filter={condition ? ['==', ['get', 'visible'], true] : noFilter}
/>          
```

**Comment by mfazekas** [comment]
See https://github.com/mapbox/mapbox-maps-android/issues/1923

**Comment by peterbodo** [comment]
> As a workaround, this is what I do on my project:
> 
> const noFilter = useMemo(() => Platform.select({ ios: undefined, android: ['all'] }), []);
> 
> ...
> 
> <MapboxGL.SymbolLayer
>   ...
>   filter={condition ? ['==', ['get', 'visible'], true] : noFilter}
> />

Now undefined is working on android, but on ios it cannot be reset to undefined if it had earlier any other array expression, changing the filter to undefined will not effect filter and will not through error, too.

If you initiate the layer with an array filterexpression, it is even worse. You cannot set a new filterexpression, because it will through the error:
```
 (NOBRIDGE) ERROR  Mapbox [error] updateLayer SymbolLayer.poi-scalerank4-l15 The data couldn’t be read because it isn’t in the correct format. [RootCodingKeys(stringValue: "filter", intValue: nil)] Expected to decode Array<Any> but found a number instead.
```

when the experssion is clearly an Array<Any>

"expo": "~52.0.38",
 "react-native": "0.76.7",
 "@rnmapbox/maps": "^10.1.35",
