### ISSUE TITLE
[Bug]: ShapeSource unable to take testID and style props

### ISSUE THREAD

**Issue by KarelMensah** [rnmapbox/maps#2654]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.72

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine} testID="shape-source-id" style={{opacity: 1}}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

The ShapeSource component is unable to take a testID prop or a style prop. In an editor, during compilation by tsc or when running tests with Jest an error is thrown about testID being an invalid prop type.

### Expected behavior

ShapeSource should allow testID and style props as in the previous version of the library.

### Notes / preliminary analysis

Simply adding a patch for the prop types that the ShapeSource takes fixes the issue, and the props are passed down correctly.

**Comment by mfazekas** [comment]
@KarelMensah thanks for the  report, yep we'll need ot add a BaseProps to all layers that has testID for example
