### ISSUE TITLE
drawing a direction route/navigation from one of coordinates to another

### ISSUE THREAD

**Issue by Emmybritt** [rnmapbox/maps#2655]
New Feature
I am requesting the addition of a new feature to RNMapbox that allows users to draw a direction route/navigation from one coordinates to another, i am using rnmapbox in my application and i am unable to draw a route/navigation direction, when i used the linelayer, it was just drawing a straight line from the a point to another which is not a good experience, i should be able to direct user to any point on the map.

Description
This feature will enable users to plot a course between two or more points on the map using the shortest and most efficient path. Users can specify their starting point and destination, and the feature will calculate the best possible route between the two. It will provide turn-by-turn directions, travel time estimates, and distance calculations.

This feature will be useful for users who want to navigate to a particular location using the shortest route possible, whether it's for personal or business purposes. For example, users can use this feature to plan their commute to work, navigate to a new restaurant, or explore a new city.

Why
The addition of this feature will enhance the functionality of RNMapbox, making it more versatile and useful for a wide range of applications. It will also increase the competitiveness of the library, as other popular mapping libraries such as Google Maps already have this feature.

In addition, this feature will improve the user experience by providing more accurate and efficient navigation. Users will be able to save time and avoid unnecessary detours and traffic jams.

Overall, the addition of this feature will provide significant value to users of RNMapbox, making it a more powerful and reliable mapping library.

**Comment by mfazekas** [comment]
@Emmybritt thanks for the request, this is a bit out of scope of this project. We could wrap mapbox navigation libs, but that would be another library.

**Comment by Emmybritt** [comment]
Ok but please can you suggest any library i can along side with rnmapbox to draw a route line that direct user from one coordinates to another showing the direction, because google map as this feature, or can you advise me on implementation wise, cause i am trying to do that on rnmapbox, but i am not seeing any thing like that.

> @Emmybritt thanks for the request, this is a bit out of scope of this project. We could wrap mapbox navigation libs, but that would be another library.

**Comment by ShivamJoker** [comment]
I am looking for the same.

**Comment by Emmybritt** [comment]
> I am looking for the same.

how i was able to solve this was that i used this api https://api.mapbox.com/directions/v5/mapbox/driving to get routes directions 

here is the function 


`
const getRouteDirection = async (
    startPoint: PointProp,
    endPoint: PointProp,
  ) => {
    const mapCoordinates = [...userCurrentMapCoordinates];
    if (endPoint.lat || endPoint.lng) {
      mapCoordinates[1] = {
        latitude: endPoint.lat,
        longitude: endPoint.lng,
      };
      setUserCurrentMapCordinates(mapCoordinates);
    }
    setFollowUserLocation(true);
    const url = 'https://api.mapbox.com/directions/v5/mapbox/driving';
    try {
      const directionResponse = await axios.get(
        `${url}/${startPoint.lng},${startPoint.lat};${endPoint.lng},${endPoint.lat}?alternatives=false&geometries=geojson&overview=simplified&steps=false&access_token=${MAPBOX_PK}`,
      );
      if (directionResponse.data?.code === 'Ok') {
        setDirectionCoordinate(
          directionResponse.data?.routes[0].geometry.coordinates,
        );
        // console.log(directionResponse.data?.routes[0].geometry.coordinates);
      } else {
      }
    } catch (error) {}
  };


it will return some response to navigate user, and then i set the data into the shapeSource

<MapboxGL.ShapeSource
      id={'routeSource'}
      lineMetrics={true}
      shape={{
        properties: {},
        type: 'Feature',
        geometry: {
          type: 'LineString',
          coordinates: routeDirectionCoords,
          // coordinates: [
          //   [3.371018, 6.509449],
          //   [3.372146, 6.508393],
          //   [3.372301, 6.508194],
          //   [3.376102, 6.509765],
          //   [3.375794, 6.510529],
          //   [3.377471, 6.511185],
          //   [3.375178, 6.516149],
          //   [3.371407, 6.517713],
          //   [3.36906, 6.516874],
          //   [3.367807, 6.519059],
          //   [3.367704, 6.522934],
          //   [3.36685, 6.562292],
          //   [3.366959, 6.567846],
          //   [3.367904, 6.571613],
          //   [3.362641, 6.57397],
          //   [3.358708, 6.583552],
          //   [3.361905, 6.584674],
          //   [3.363964, 6.586197],
          //   [3.361347, 6.589335],
          //   [3.361978, 6.589869],
          //   [3.362162, 6.589668],
          // ],
        },
      }}>
      <MapboxGL.LineLayer
        id="exampleLineLayer"
        style={{
          lineColor: '#42A2D9',
          lineCap: 'round',
          lineJoin: 'round',
          lineWidth: 7,
        }}
      />
    </MapboxGL.ShapeSource>
