### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vadim312** [rnmapbox/maps#2659]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.7.0

### Platform

Android

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

const BugReportExample = () => {
const renderBackdrop = useCallback(
      (props) => <SheetBackdrop {...props} backdropProps={backdropProps} />,
      [backdropProps],
    );

    const renderHandle = useCallback(() => <ModalHandler />, []);

return (
      <BottomSheet
        ref={ref}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
        keyboardBehavior="interactive"
        keyboardBlurBehavior="restore"
        backdropComponent={noBackdrop ? undefined : renderBackdrop}
        handleComponent={showHeader ? renderHandle : null}
        enablePanDownToClose={enablePanDownToClose}
      >
        <BottomSheetScrollView
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={false}
      >
<MapView
      style={styles.map}
      styleURL={CONFIG.MAPBOX_STYLE_URL}
      zoomEnabled={false}
      scrollEnabled={false}
      logoEnabled={false}
      compassEnabled={false}
      scaleBarEnabled={false}
      rotateEnabled={false}
      pitchEnabled={false}
      attributionEnabled={false}
    >
      <Camera
        followUserLocation={false}
        minZoomLevel={16}
        zoomLevel={16}
        centerCoordinate={[-122.32356, 34.565433]}
        animationDuration={0}
      />
      <MapboxGL.LineLayer id="traffic" style={trafficStyle} />
    </MapView>
      <Text>Testing...</Text>
<Text>Testing...</Text>
<Text>Testing...</Text>
<Text>Testing...</Text>
     </BottomSheetScrollView>
      </BottomSheet>
    );
}
```

### Observed behavior and steps to reproduce

After opened bottom sheet and scroll up, map goes beyond of scrollview on android only

### Expected behavior

Shouldn't be happening

### Notes / preliminary analysis

I didn't expected such issue.
Looks like it's `zIndex` issue but not sure

### Additional links and references

https://user-images.githubusercontent.com/75946509/223185804-731c9cc5-495c-43d3-b847-7f773d7e0dc3.mp4

**Comment by mfazekas** [comment]
@vadim312 we can't use this component, lots of undefined stuff like `ref`, `snapPoints` etc.

**Comment by vadim312** [comment]
> @vadim312 we can't use this component, lots of undefined stuff like `ref`, `snapPoints` etc.

sorry, let me change it

**Comment by vadim312** [comment]
> @vadim312 we can't use this component, lots of undefined stuff like `ref`, `snapPoints` etc.

if you find `undefined` if I missed, just ignore or replace proper value, but as you see attach video, it is bad experience

**Comment by mfazekas** [comment]
Please post a compact complete runnable example you tested yourself to reproduce the problem otherwise we won't even look. Thanks for the understanding.

**Comment by vadim312** [comment]
hey @mfazekas why you close it?
