### ISSUE TITLE
[Bug]: `followUserLocation` and `onRegionDidChange` not working as expected

### ISSUE THREAD

**Issue by sagarshakya** [rnmapbox/maps#2670]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.74

### Standalone component to reproduce
```
import React from 'react';
import {
  MapView,
  Camera,
UserLocation
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}} onRegionDidChange={() => console.log('onRegionDidChange')}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} followUserLocation />
        <UserLocation visible minDisplacement={100} />
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

https://user-images.githubusercontent.com/66957698/223635896-be24ec9b-ede2-473a-8d38-28ef34b7be00.mp4

When you have `followUserLocation` set to `true`, and `<UserLocation />` component is visible, the marker says stationery to the position it was before. 

`minDisplacement` value is doesn't have any affect. The marker moves constantly as with the location change. And with that `onRegionDidChange` is triggered every second.

### Expected behavior

1. The marker should update with the user location.
2. `minDisplacement` value should be have an affect on how often the marker moves with the change in user location. 
3. `onRegionDidChange` should be triggered based on `minDisplacement` value of the `<UserLocation />` component.

https://user-images.githubusercontent.com/66957698/223637301-738a2aea-3c5e-4b83-aac9-c159f2b65f36.mp4

**Comment by mfazekas** [comment]
@sagarshakya Thanks for the report, but please post a compact but complete component to reproduce. I don't see minDisplacement in the code you've provided.

Also note that onRegionDidChange (to be deprecated in favour of onMapIdle) has nothing to do with location tracking. It'll be called when mapbox has finished rendering.

**Comment by sagarshakya** [comment]
@mfazekas Apologies, a markdown error was causing the code to not display properly. I have updated it.

Regarding `onMapIdle`, on the docs, it actually says this `iOS, v10 only, deprecated will be removed in next version - please use onRegionDidChange`.

**Comment by sagarshakya** [comment]
When we have to make an API request while the user location is being tracked, it will be ideal to make that request every `x` distance travelled, instead of every small change in user location.

**Comment by mfazekas** [comment]
@sagarshakya for that please don't use onRegionDidChange, and minDisplacement, use `locationManager#addListener` or `UserLocation#onUpdate` and calculate distance with truft for example.
