### ISSUE TITLE
[Bug]: Android: `nativeAssetImages` from Images doesn't work anymore since v10.0.0-beta.73

### ISSUE THREAD

**Issue by pablogdcr** [rnmapbox/maps#2680]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.75

### Standalone component to reproduce

```javascript
import React, { useMemo } from 'react';
import {
  MapView,
  ShapeSource,
  SymbolLayer,
  Camera,
  Images,
} from '@rnmapbox/maps';

const Map = () => {
  const point: GeoJSON.Feature = useMemo(() => ({
    type: 'Feature',
    properties: {},
    geometry: {
      type: 'Point',
      coordinates: [-74.00597, 40.71427],
    },
  }), []);

  return (
    <MapView style={{flex: 1}}>
      <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
      <Images
        nativeAssetImages={['myImage']}
        onImageMissing={console.warn}
      />
      <ShapeSource id="point-source" shape={point}>
        <SymbolLayer id="point-layer" />
      </ShapeSource>
    </MapView>
  );
};

export default Map;
```

### Observed behavior and steps to reproduce

In the example above, I try to load an image from the native assets.

The images are stored in `android/app/src/main/res/drawable` and is named 'myImage.png';

With the v10.0.0-beta.72, everything works as expected.

Since the v10.0.0-beta.73, `onImageMissing` is called, and the SymbolLayer is not able to display the image anymore.

### Expected behavior

No error should be triggered and the image should be displayed.

### Notes / preliminary analysis

This bug is caused by https://github.com/rnmapbox/maps/pull/2650

**Comment by mfazekas** [comment]
Should be fixed by: https://github.com/rnmapbox/maps/commit/c1b6f8cfa69d6b5a99d3866f515aff3df772accb
