### ISSUE TITLE
Remove MapLibre support

### ISSUE THREAD

**Issue by KiwiKilian** [rnmapbox/maps#2683]
MapLibre has successfully onboarded a fork into their realms: https://github.com/maplibre/maplibre-react-native – awesome 🎉!

Can we begin to remove the MapLibre support from the main branch?

**Comment by mfazekas** [comment]
@KiwiKilian the plan is to deprecate MapLibre and Mapbox GL implementations in 10.0 releases. We'll remove them once we've released a 10.0 final.

**Comment by KiwiKilian** [comment]
Could we remove the MapLibre GitHub actions workflows already? They fail on every PR. Or would this be the same for the Mapbox actions workflows?

**Comment by mfazekas** [comment]
Not sure what's going on there. It does pass on main, but I do see that it regularly fails to check out cocoapods.

One issue is that Mapbox v10 uses Metal, so it cannot run on GitHub action vm-s, while MapLibre can. Not super usefull, but that's it. 

https://github.com/rnmapbox/maps/actions/runs/4376624293/jobs/7659059478

**Comment by KiwiKilian** [comment]
So I guess it's not actually the Metal problem, but rather `MAPBOX_DOWNLOAD_TOKEN` not beeing exposed to non maintainers. Probably because changes could expose that secret.

**Comment by mfazekas** [comment]
So there is 3 separate issues:

1. [Metal is not supported on macOS images](https://github.com/actions/runner-images/discussions/6138) therefore we cannot run our detox tests with v10 version of mapbox
2. MAPBOX_DOWNLOAD_TOKEN is not available for PR-s from forks, so contributors PR-s will not run any Mapbox compile/detox tests
3. MAPBOX_DOWNLOAD_TOKEN is not available for PR-s from forks, but we still add it to .netrc, that causes cocoapod install issue even for MapLibre. Should be addressed by #2689
