### ISSUE TITLE
[Bug]: Invalid bundle structure error when submitting a release with Xcode

### ISSUE THREAD

**Issue by hernanmateo** [rnmapbox/maps#2690]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.76

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

After archiving without apparently any error (on iOS) I'm receiving the following error when I'm trying to submit the release to the apple store:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1542900/224578788-e9ceb27a-464b-4d05-be33-bdd634d8f734.png">

It seems that it is adding two executables (Turf and MapboxMaps) when archiving

<img width="166" alt="image" src="https://user-images.githubusercontent.com/1542900/224578194-9bc02a94-98ea-4d29-86fb-e41c7dd90aed.png">

### Expected behavior

Archive a valid bundle to upload to the apple store connect

**Comment by mfazekas** [comment]
@hernanmateo can you reproduce with a fresh project created with `react-native init`?

Also you can try set ` $RNMapboxMapsSwiftPackageManager` to `manual`, and then you can add the mapbox libs the way it works for you. Either with SwiftPackageManager or cocoa pods.

**Comment by hernanmateo** [comment]
Yes I can reproduce the same problem with a fresh project created with react-native init. The ipa generated also has the two not permitted binaries

<img width="206" alt="image" src="https://user-images.githubusercontent.com/1542900/224662181-9f9df0d8-070c-440e-a391-acb4a0f564b4.png">

I tried to downgrade to v8 facing the same problem, but in this case the not permitted binary is the MapboxMobileEvents package. I'm on a M1 with Ventura 13.0 and Xcode 14.0.1.

I'm trying to set it manually with no success at the moment.

**Comment by mfazekas** [comment]
@hernanmateo for future reference what was the issue?

**Comment by hernanmateo** [comment]
I'm not 100% sure. But the game changer for me was the re-location of **$RNMapboxMaps.post_install(installer)** to the last line of the post_install block. After cleaning everything (build folder, pods...) and restarted xcode it started archiving correctly.

**After**

````ruby
post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )    
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
````

**Before**

````ruby

post_install do |installer|    
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )    
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    $RNMapboxMaps.post_install(installer)  
end
````

**Comment by herbertvuijk** [comment]
Thanks for posting the possible solution. @hernanmateo  I have the same problem. Your fix unfortunately didn't work. I'm lost 2 days now on this problem. It started from nowhere. It always worked just fine. Any other ideas?

**Comment by hernanmateo** [comment]
Hello, unfortunately, I still don't know the origin of this error, but it has happened to me more times, and I've managed to fix it. I think it's related to some issue with the deep cache of CocoaPods that gets corrupted at some point due to a misconfiguration in the Podfile and doesn't recover. So, clearing the cache, deintegrating pods, and even restarting Xcode (and the computer!) helps resolve it. I know it's not the best advice, but I don't have another solution. If you want, post the Podfile, and I can compare it for you.
