### ISSUE TITLE
[Bug]: queryRenderedFeaturesInRect not working properly in iOS but Android is working fine

### ISSUE THREAD

**Issue by somasekharkakarla** [rnmapbox/maps#2699]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

[rnmapbox/maps#main](github:rnmapbox/maps#main)

### Standalone component to reproduce

 "react": "17.0.2",
 "react-native": "0.66.0",
"Android": 13
"iOS": 16.0.2
"Xocde":14.2

### Observed behavior and steps to reproduce

I am using queryRenderedFeaturesInRect to find the features i touched. Filter is working fine in android but in iOS it not working properly. i am attaching log videos for iOS and android. In iOS, it not filtering or it randomly picking up a same feature even we select other features.

Android:

https://user-images.githubusercontent.com/65530762/225072920-c30bd1d7-4f36-4f54-94a2-bb8ed83592c8.mov

iOS:

https://user-images.githubusercontent.com/65530762/225073027-a6a57dbe-aedc-427c-9eb7-09a5ff90db59.mov

### Expected behavior

As code repo is same. Expected android and ios same behaviour

Please reply ASPS.

Thank you

**Comment by mfazekas** [comment]
@somasekharkakarla pls include a sample component, so we can reproduce and fix the issue

**Comment by somasekharkakarla** [comment]
Hi @mfazekas ,

Here is the repo link https://github.com/somasekharkakarla/mapbox_test

Please check. Reply ASAP.

**Comment by mfazekas** [comment]
@somasekharkakarla sorry I don't understand this issue. First the filter is null in the code example:
https://github.com/somasekharkakarla/mapbox_test/blob/6757515f633e92f5d315371414e185a10866ab35/App.tsx#L67-L76

I don't understand what I should see on those videos, how do I see that some feature is ok and the other isn't?

Also your RNMapboxMapsImpl so you're using a deprecated Maplibre implementation, we don't support.

**Comment by somasekharkakarla** [comment]
Hi @mfazekas ,

when click on feature i am using `queryRenderedFeaturesInRect` to query for those layers here the method https://github.com/somasekharkakarla/mapbox_test/blob/6757515f633e92f5d315371414e185a10866ab35/App.tsx#L67-L76

when i am running in android, queryRenderedFeaturesInRect is returning the feature but not in ios. Please run on android and ios devices. click on feature and see logs.
