### ISSUE TITLE
[Bug]: PointAnnotation onDragEnd app crash (IOS)

### ISSUE THREAD

**Issue by 0xcD3v** [rnmapbox/maps#2712]
### Mapbox Implementation

Mapbox

### Mapbox Version

10

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

```javascript
import React from 'react';
import MapboxGL
} from '@rnmapbox/maps';


class BugReportExample extends React.Component {

  const cameraRef = useRef(null);
  const location = useState(location);

  render() {
    return (
              <MapboxGL.MapView
            style={{width: '100%', height: '100%'}}
            logoEnabled={false}
            scaleBarEnabled={false}>

            <MapboxGL.Camera
              ref={cameraRef}
              animationMode="none"
              zoomLevel={1}
            />
    
          
            {location ? (
              <MapboxGL.PointAnnotation
                draggable={true}
                onDragEnd={feature => {
                  console.log(feature);
                  setLocation({
                    latitude: feature.geometry.coordinates[1],
                    longitude: feature.geometry.coordinates[0],
                  });
                }}
                coordinate={[location.longitude, location.latitude]}
              >
             <View style={{
                height: 30,
                width: 30,
                backgroundColor: '#00cccc',
                borderRadius: 50,
                borderColor: '#fff',
                borderWidth: 3
                }} />
      
              </MapboxGL.PointAnnotation >
            ) : null}


          </MapboxGL.MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

When i click on the displayed pointAnnotation the app simply crash. i'm testing on simulator

**Comment by mfazekas** [comment]
@0xcD3v pls make this component complete. `location`, `cameraRef` is not defined

**Comment by 0xcD3v** [comment]
> @0xcD3v pls make this component complete. `location`, `cameraRef` is not defined

thanks for the reply, those variables are declared i just forgot to put them here, i have and api call to get a location then it will show the pointAnnotation on the map without problems, but when i click on the pointAnnotation the app crashes

**Comment by 0xcD3v** [comment]
i created a new project to test, and happens the same.

import React, {useState} from 'react';
import { StyleSheet, View ,Text} from 'react-native';
import Mapbox from '@rnmapbox/maps';

const App = () => {

  const [location,setLocation] = useState(null);

  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <Mapbox.MapView style={styles.map} >
              <Mapbox.PointAnnotation
                draggable={true}
                onDragEnd={feature => {
                  console.log(feature);
                  setLocation({
                    latitude: feature.geometry.coordinates[1],
                    longitude: feature.geometry.coordinates[0],
                  });
                }}
                coordinate={ [
                  -1.510311133796023,
                  53.816142903704616
                        ]}
              >
             <View style={{
                height: 30,
                width: 30,
                backgroundColor: '#00cccc',
                borderRadius: 50,
                borderColor: '#fff',
                borderWidth: 3
                }} />
              </Mapbox.PointAnnotation>
        </Mapbox.MapView>
      </View>
    </View>
  );
}

**Comment by 0xcD3v** [comment]
I think am using the latest version.

my package.json:

<img width="537" alt="Screenshot 2023-03-18 at 11 34 00" src="https://user-images.githubusercontent.com/128076064/226103684-e02ebba3-7333-4d16-977a-aa859291fe24.png">

build.gradle

<img width="633" alt="Screenshot 2023-03-18 at 11 40 27" src="https://user-images.githubusercontent.com/128076064/226103693-236c9425-6c37-4825-92d7-99793f2461dd.png">

installed via yarn with yarn add "rnmapbox/maps#main"

**Comment by mfazekas** [comment]
Your example still doesn't compiles as style is missing, this is a working repro

```jsx
import React, { useState } from 'react';
import { StyleSheet, View, Text } from 'react-native';
import Mapbox from '@rnmapbox/maps';

const App = () => {
  const [location, setLocation] = useState(null);

  return (
    <Mapbox.MapView style={{ flex: 1 }}>
      <Mapbox.Camera
        centerCoordinate={[-1.510311133796023, 53.816142903704616]}
        zoomLevel={14}
      />
      <Mapbox.PointAnnotation
        draggable={true}
        onDragEnd={(feature) => {
          console.log(feature);
          setLocation({
            latitude: feature.geometry.coordinates[1],
            longitude: feature.geometry.coordinates[0],
          });
        }}
        coordinate={[-1.510311133796023, 53.816142903704616]}
      >
        <View
          style={{
            height: 30,
            width: 30,
            backgroundColor: '#00cccc',
            borderRadius: 50,
            borderColor: '#fff',
            borderWidth: 3,
          }}
        />
      </Mapbox.PointAnnotation>
    </Mapbox.MapView>
  );
};
export default App;
```

**Comment by mfazekas** [comment]
The issue is that your point annotation has no `id` but it's a required attribute.

**Comment by 0xcD3v** [comment]
> The issue is that your point annotation has no `id` but it's a required attribute.

That resolved the issue! 
Much appreciated
