### ISSUE TITLE
[Bug]: Pressing on the user location icon does not fire the map view press function

### ISSUE THREAD

**Issue by lmalvasia** [rnmapbox/maps#2715]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.68

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  UserLocation
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}} onPress={(data) => { console.log(data) }}>
        <MapboxGL.UserLocation
          onPress={() => { console.log('Pressing user location') }}
          showsUserHeadingIndicator
        />
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

I'm trying to add a couple of markers/point annotations to the map when the user clicks on any place. The problem happens when the user clicks on the user location icon. In this case, the user location onPress function is called instead of the mapview onPress.

### Expected behavior

The MapView on press function should be also called?

**Comment by mfazekas** [comment]
@lmalvasia  you can try using the native user location indicator, or you can try using the onPress on UserLocation. I think this is the desired behaviour.
