### ISSUE TITLE
pod install fails with $RNMapboxMapsImpl = 'mapbox'

### ISSUE THREAD

**Issue by Stophface** [rnmapbox/maps#2722]
## Environment
- Dev OS: 13.12.1

## Steps to reproduce
I installed `v10`  with `yarn add rnmapbox/maps#main` and updated my Podfile as per [instructions](https://github.com/rnmapbox/maps/blob/main/ios/install.md).
But, as soon as I add this line `$RNMapboxMapsImpl = 'mapbox'`  and I do a `pod install`, I get

```
[!] Error installing MapboxCommon
[!] /usr/bin/curl -f -L -o /var/folders/09/fk50bt0s7sdct3833mjq06sh0000gp/T/d20230320-4581-1hxxt8j/file.zip https://api.mapbox.com/downloads/v2/mapbox-common/releases/ios/packages/23.3.2/MapboxCommon.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    39    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
```

I am adding the line here

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
$RNMapboxMapsImpl = 'mapbox'

target 'Foo' do
  config = use_native_modules!
  ...
```

When I remove the line `$RNMapboxMapsImpl = 'mapbox'`, `pod install`  runns without throwing an error.

**Comment by spiritof91** [comment]
https://docs.mapbox.com/ios/maps/guides/install/#configure-credentials

**Comment by muhammedesadkaya** [comment]
you must create your secret file for your secret key.

`touch ~/.netrc
echo "machine api.mapbox.com" > ~/.netrc
echo "login mapbox" >> ~/.netrc
echo "password <YOUR_KEY>" >> ~/.netrc`

then pod install.

**Comment by Stophface** [comment]
@muhammedesadkaya Sorry for bothering again... I am trying to update from v8 to v10, and when I do a `pod install` I get 

> Warning: Duplicate Mapbox dependency found, it's consumed by both SwiftPackageManager and CocoaPods

Now, when I try to build the project I get

> Missing package product 'Mapbox'
> failed downloading 'https://github.com/maplibre/maplibre-gl-native/releases/download/ios-v5.12.1/Mapbox-5.12.1.zip' which is required by binary target 'Mapbox': Operation cancelled
> fatalError


Do you have any ideas what might cause this?

**Comment by muhammedesadkaya** [comment]
@Stophface follow these steps; https://dev.to/ajmal_hasan/react-native-mapbox-v10-installation-7ga

**Comment by Stophface** [comment]
@muhammedesadkaya I did all that, still the same error.

**Comment by alexander0205** [comment]
> @santhosh-umapathi-appymango
> 
> ```
> netrc_path=~/.netrc
> 
> if [ ! -e "$netrc_path" ]; then
>     touch $netrc_path
> fi
> 
> new_login='mapbox'
> # your download token
> new_password=$MAPBOX_DOWNLOAD_TOKEN
> 
> machine_name='api.mapbox.com'
> 
> # remove the old credentials for the api.mapbox.com
> temp_file="$(mktemp)"
> sed "/^machine ${machine_name}/,/^$/d" ${netrc_path} > "$temp_file" && mv "$temp_file" ${netrc_path}
> 
> # add the new credentials for the api.mapbox.com
> echo "\n" >> ${netrc_path}
> echo "machine ${machine_name}" >> ${netrc_path}
> echo "login ${new_login}" >> ${netrc_path}
> echo "password ${new_password}" >> ${netrc_path}
> ```

It works but not with default token in case is required generate a new token with some credentials.
