### ISSUE TITLE
[Bug]: onCameraChanged and onMapIdle not working on iOS

### ISSUE THREAD

**Issue by muhammedesadkaya** [rnmapbox/maps#2723]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

@rnmapbox/maps

### Standalone component to reproduce

```js
import React, { useState, useEffect, useRef } from 'react';
import { View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

export default function MyMap(props) {
  const mapRef = useRef(null);
  const mapCameraRef = useRef(null);

  const [userCoordinate, setUserCoordinate] = useState({ latitude: 37.4226711, longitude: -122.0849872 });

  useEffect(() => {
    Mapbox.setWellKnownTileServer(Mapbox.TileServers.Mapbox);
  }, []);

  const onCameraChanged = () => {
    console.log("onCameraChanged");
  };

  const onMapIdle = (event) => {
    console.log("onMapIdle");
  };

  return (
    <View style={{ flex: 1 }}>
      <Mapbox.MapView
        ref={mapRef}
        style={{ flex: 1}}
        onCameraChanged={onCameraChanged}
        onMapIdle={onMapIdle}
        styleURL={Mapbox.StyleURL.Street}
      >
        <Mapbox.Camera
          ref={mapCameraRef}
          zoomLevel={15}
          centerCoordinate={[userCoordinate.longitude, userCoordinate.latitude]}
          animationMode='flyTo'
          animationDuration={1200}
        />
        <Mapbox.UserLocation />
      </Mapbox.MapView>
    </View>
  );
}
```

### Observed behavior and steps to reproduce

 Don't get any errors or warnings when using onCameraChanged and onMapIdle on iOS but it's not working. Also both function works well on Android. When I change both function to "onCameraChanged -> onRegionIsChanging" and "onMapIdle -> onRegionDidChange" works well but fires warning like crazy.

**Warning examples;**

- onRegionIsChanging is deprecated and will be removed in next beta - please use onCameraChanged 
- onRegionDidChange is deprecated and will be removed in next beta - please use onMapIdle

What should I do? One not giving warning but not working, other one works but gives warning like crazy.

Thanks.

**Comment by buraksecer** [comment]
+1

**Comment by muhammedesadkaya** [comment]
@mfazekas I did "yarn install" and my problem solved. Thanks!!
