### ISSUE TITLE
Missing package product 'Mapbox' && failed downloading MapLibre upon updating from v8 to v10

### ISSUE THREAD

**Issue by Stophface** [rnmapbox/maps#2725]
## Environment
- Dev OS: 13.12.1

## Steps to reproduce
I am trying to update from v8 to v10. I removed the v8 version with `yarn` and removed the references to the old v8 version in the Podfile manually. I followed the installation instructions, edited my Podfile to add the new v10 versionas well as added a secret token like explained [here](https://docs.mapbox.com/ios/maps/guides/install/#configure-credentials). When I now do a `pod install` I get 

> Warning: Duplicate Mapbox dependency found, it's consumed by both SwiftPackageManager and CocoaPods

Now, when I try to build the project I get

> Missing package product 'Mapbox'
> failed downloading 'https://github.com/maplibre/maplibre-gl-native/releases/download/ios-v5.12.1/Mapbox-5.12.1.zip' which is required by binary target 'Mapbox': Operation cancelled
> fatalError

The fail comes very early, roughly five seconds after clicking the build button... Where is coming the warning after the `pod install`  from and what is stopping it from compiling?

**Comment by Stophface** [comment]
@mfazekas I supsected that. I "searched" already in XCode for the reference, but I did not find it. I am not sure where to look. Can you pin point me into the right direction?

**Comment by mfazekas** [comment]
Open the project, then click the project, then project, then look for package dependencies
![image](https://user-images.githubusercontent.com/52435/226540708-67b834c9-71db-4919-a4cc-04e65c44928c.png)

**Comment by Stophface** [comment]
@mfazekas Thanks, that resolved the error above. Now I am getting a new one...

```
error: SyntaxError: /.../node_modules/@rnmapbox/maps/src/components/ShapeSource.tsx: Unexpected token (152:36)

  150 |  */
  151 | export class ShapeSource extends NativeBridgeComponent(
> 152 |   AbstractSource<Props, NativeProps>,
      |                                     ^
  153 |   NATIVE_MODULE_NAME,
  154 | ) {
  155 |   static NATIVE_ASSETS_KEY = 'assets';
```

Any ideas what might be the problem here? I use the `<ShapeSource />`  component like this

```
<Mapbox.ShapeSource>
    <Mapbox.SymbolLayer />
</Mapbox.ShapeSource>
```

**Comment by mfazekas** [comment]
@Stophface see https://github.com/rnmapbox/maps/issues/2423#issuecomment-1342579105

**Comment by Stophface** [comment]
@mfazekas Again, thanks for your reply but still no luck... The error changed, to 

```
error: node_modules/@rnmapbox/maps/src/components/ShapeSource.tsx: /.../node_modules/@rnmapbox/maps/src/components/ShapeSource.tsx: Unknown node type: "TSInstantiationExpression"
```

though. This is my setup. I cannot go further down with `babel/core`, otherwise some other libraries do not work. When I downgrade to `"@babel/core": "7.19.1",` as suggested in the comment you linked, I get an error from another library (react-native gesture handler). 


```
// package.json
"dependencies": {
    "@rnmapbox/maps": "rnmapbox/maps#main",
    ....
    },
  "devDependencies": {
    "@babel/core": "^7.x.x",
    "@babel/plugin-proposal-decorators": "^7.17.9",
    "@babel/preset-typescript": "^7.12.17",
    "@babel/runtime": "^7.12.5",
...
```

```
// babel.config.js
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    '@babel/preset-typescript',
  ],
  plugins: [
    'react-native-reanimated/plugin',
    ['@babel/plugin-proposal-decorators', {legacy: true}],
  ],
};
```
