### ISSUE TITLE
[Bug]: MapView missing exported type

### ISSUE THREAD

**Issue by Kaijonsson** [rnmapbox/maps#2732]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.0-beta.80

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.80

### Standalone component to reproduce

import {MAPBOX_ACCESS_TOKEN} from '@env';
import {View} from '@farmo/ui';
import MapboxGL, {MapViewProps} from '@rnmapbox/maps';
import React from 'react';

void MapboxGL.setAccessToken(MAPBOX_ACCESS_TOKEN);

export type MapProps = {
  children?: React.ReactNode;
} & MapViewProps;
const Map = ({...props}: MapProps) => {
  return (
    <View flex>
      <MapboxGL.MapView {...props}>{children}</MapboxGL.MapView>
    </View>
  );
};

export default Map;

### Observed behavior and steps to reproduce

Mapbox does not export types for the MapView component any longer. Like the example we import MapViewProps in order to forward props to our custom component. But that type dissapeared when we updated the package. Now we get type errors all over since the type is wrong (doesn't exist).

### Expected behavior

I expect to be able to import the types of the MapBox components.

**Comment by mfazekas** [comment]
@Kaijonsson for now please use `React.ComponentProps` to extract props type. Ideally we'll add back MapViewProps as a deprecated export and the recommended this instead:

```tsx
type MapViewProps = React.ComponentProps<typeof MapView>;
```
