### ISSUE TITLE
[Bug]: compassEnabled is not optional

### ISSUE THREAD

**Issue by Kaijonsson** [rnmapbox/maps#2733]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.0-beta.80

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.80

### Standalone component to reproduce

```
import {MAPBOX_ACCESS_TOKEN} from '@env';
import {View} from '@farmo/ui';
import MapboxGL, {MapView} from '@rnmapbox/maps';
import React from 'react';

void MapboxGL.setAccessToken(MAPBOX_ACCESS_TOKEN);

type MapViewProps = React.ComponentProps<typeof MapView>;
export type MapProps = {
  children?: React.ReactNode;
} & MapViewProps;
const Map = ({children, ...props}: MapProps) => {
  return (
    <View flex>
      <MapboxGL.MapView {...props}>{children}</MapboxGL.MapView>
    </View>
  );
};

export default Map;

const MapBlock = () => {
  return <Map />
};

```

### Observed behavior and steps to reproduce

Feels like a bug that compassEnabled isn't optional. I have omitted it myself for now in the project i'm working on.

**Comment by mfazekas** [comment]
@Kaijonsson thanks much, can you pls submit a PR, making compassEnabled optional?
