### ISSUE TITLE
Mapview with custom styleJson offline

### ISSUE THREAD

**Issue by AlessandroAries** [rnmapbox/maps#2741]
Hello peeps! I have a problem when trying to use a `MapView` while being offline. I don't understand what I am doing wrong. 
I use version `10.0.0-rc.1`. I use a `MapView` with a custom `styleJson` prop to display some images looking like the following, where CUSTOM_URL is pointing to our own server to fetch these image tiles:
```
layers: [
      {
        id: 'plan',
        source: 'custom',
        type: 'raster',
      },
    ],
    sources: {
      custom: {
        tileSize: 256,
        tiles: [
         `CUSTOM_URL/tile/{z}/{x}/{y}`
        ],
        type: 'raster',
      },
    },
    version: 1,
  };
```
Now I want to only make these tiles available for offline usage so the user can still see them and zoom in on them while being offline. I create a pack upfront using ` MapboxGL.offlineManager.createPack` with options: 
```
{
 bounds: [
      [180, 85.051129],
      [-180, -85.051129],
    ],
    maxZoom: 3,
    minZoom: 0,
    name: id,
    styleURL: customURL2
}
```
where `customURL2` is pointing to an endpoint on our own server again which returns the exact style json as used in the `styleJson` of the `MapView`.
When create the pack,  turn off network and show my `MapView` it gives me errors like this on Android:
`Failed to load tile: Unable to resolve host "SOME_URL": No address associated with hostname`
and on iOS `Mapbox error MapLoad error Failed to load tile`. Note that the online flow using this approach shows our tiles correctly and even if I opened the `MapView` with these tiles before, turn off network and open it again it shows the tiles correctly, so I assume it has to with how I create the pack or something.
I hope someone is able to help me with this!

**Comment by mfazekas** [comment]
@AlessandroAries thanks much for the bug report. 
Have you tried to use the same styleURL, both for offline a MapVIew?

I'm 99.9% that it's an upstream behaviour so not much we (rnmapbox community) can do about that
