### ISSUE TITLE
[Bug]: v10 Android addView crash

### ISSUE THREAD

**Issue by sweatherall** [rnmapbox/maps#2747]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-rc.5

### Standalone component to reproduce

TODO
```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

![Screenshot_20230328-121917](https://user-images.githubusercontent.com/4127588/228307542-568bb088-570f-40e9-a1ea-1cb645efd279.png)

### Expected behavior

Adds/removes views without crashing

### Notes / preliminary analysis

Only happening on Android. 
Happens when switching states within app, so most likely there are items getting removed/added to the map.
**This error does not happen on version** `10.0.0-beta.73`.

**Comment by mfazekas** [comment]
@sweatherall pls add reproduction, otherwise we cannot look into it.

This would happen if you added a view, as child to map view? Something like this, but even with this I cannot reproduce the issue?

You should also recede a warning:

![image](https://user-images.githubusercontent.com/52435/228320039-0b15d1b9-b037-4397-86b4-f1dca3be5498.png)


```jsx
import React from 'react';
import { View } from 'react-native';
import { MapView, ShapeSource, LineLayer, Camera } from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{ flex: 1 }}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
        <View>
          <View
            style={{
              borderColor: 'green',
              borderWidth: 2,
              width: 20,
              height: 20,
            }}
          />
          <View
            style={{
              borderColor: 'red',
              borderWidth: 2,
              width: 20,
              height: 20,
            }}
          />
          <ShapeSource id="idStreetLayer2" shape={aLine}>
            <LineLayer id="idStreetLayer2" />
          </ShapeSource>
        </View>
      </MapView>
    );
  }
}

export default BugReportExample;
```

**Comment by sweatherall** [comment]
Thank you for the response.
I found that the issue was that we had some `MarkerView`s that were wrapped in a react-native `View` - once I removed the `View` wrapper from around the `MarkerView` component - this crash no longer happened.
This must have been ok with previous versions of rnmapbox - but I'm happy to close this issue since it has a reasonable fix on our end.
