### ISSUE TITLE
[Bug]: Camera padding still applied after .fitBounds is done animating

### ISSUE THREAD

**Issue by filipstefansson** [rnmapbox/maps#2749]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

v10.0.0-rc.5

### Standalone component to reproduce

```javascript
import { Camera, MapView, PointAnnotation } from '@rnmapbox/maps';
import { useRef, useState } from 'react';
import { Button, StyleSheet, View } from 'react-native';

const Screen = () => {
  const [markers, setMarkers] = useState([]);
  const [center, setCenter] = useState();
  const ref = useRef();

  const fitBounds = () => {
    const bounds = getBoundingBoxCorners(markers);
    // after this, markers are no longer added to the center of the map
    ref?.current?.fitBounds(bounds.sw, bounds.ne, [200, 60, 60, 0], 200);
  };

  return (
    <View style={{ flex: 1, position: 'relative' }}>
      <MapView
        style={{ flex: 1 }}
        onMapIdle={(event) => {
          setCenter(event.properties.center);
        }}
      >
        <Camera ref={ref} />
        {markers.map((marker, index) => {
          return (
            <PointAnnotation
              coordinate={marker}
              id={`${index}`}
              key={`${index}`}
            >
              <View style={styles.annotation} />
            </PointAnnotation>
          );
        })}
      </MapView>
      <View style={styles.center} />
      <View style={styles.buttons}>
        <View style={styles.button}>
          <Button
            title="Add marker to center"
            color="white"
            onPress={() => {
              setMarkers((prevMarkers) => [...prevMarkers, center]);
            }}
          />
        </View>
        <View style={styles.button}>
          <Button title="Fit bounds" color="white" onPress={fitBounds} />
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  center: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    right: 0,
    bottom: 0,
    backgroundColor: 'red',
    width: 10,
    height: 10,
    marginTop: -5,
    marginLeft: -5,
  },
  annotation: {
    backgroundColor: 'blue',
    width: 10,
    height: 10,
    marginTop: -5,
    marginLeft: -5,
  },
  buttons: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
  },
  button: {
    marginTop: 4,
    backgroundColor: 'red',
  },
});

function getBoundingBoxCorners(coordinates) {
  let minLat = coordinates[0][0];
  let minLng = coordinates[0][1];
  let maxLat = coordinates[0][0];
  let maxLng = coordinates[0][1];

  for (const coordinate of coordinates) {
    const [lat, lng] = coordinate;
    minLat = Math.min(minLat, lat);
    minLng = Math.min(minLng, lng);
    maxLat = Math.max(maxLat, lat);
    maxLng = Math.max(maxLng, lng);
  }

  const sw = [minLat, minLng];
  const ne = [maxLat, maxLng];

  return { sw, ne };
}

export default Screen;
```

### Observed behavior and steps to reproduce

Before calling `.fitBounds` on a camera ref, the `onMapIdle` and similar methods reports the center (`event.properties.center`) to be at the center of the `Map` component. 

After you call `.fitBounds` with a padding like in the example (`[200, 60, 60, 0]`), that padding is saved after the animation is done, so the camera center is no longer the map center. See attached video of the example code I included.

https://user-images.githubusercontent.com/472270/228761774-b777958a-b781-4b81-8f48-78c9d928a79c.MP4

### Expected behavior

Maybe the padding should be reset after the animation is done, or to whatever the value was before `.fitBounds` was called? If the way it works now is the expected behavior, how would we animate to a position on the map but with padding? 

A use case for this is for example when you want to animate to an area and show some content at the bottom of the screen, but you still want to whole area to be visible on the map.

### Notes / preliminary analysis

My guess is that calling `.fitBounds` sets the padding property permantently on the Camera.

### Additional links and references

See comment below: https://github.com/rnmapbox/maps/issues/2749#issuecomment-1490127955

**Comment by filipstefansson** [comment]
After some more research I think maybe this is the expected behaviour. I found this issue for Mapbox GL JS:
https://github.com/mapbox/mapbox-gl-js/issues/6736 which pointed to a method called `cameraForBounds` that let's you calculate bounds that you then can apply to a camera.

I found this in the iOS docs that I think does the same thing:
https://docs.mapbox.com/ios/maps/api/10.3.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC6camera3for7padding7bearing5pitchAA13CameraOptionsVSaySo22CLLocationCoordinate2DVG_So12UIEdgeInsetsVSdSgAPtF

and a recommendation to use it here: https://github.com/mapbox/mapbox-maps-ios/issues/1142#issuecomment-1047902749

I'm happy to try to try to add this as a method to `MapView` if you think it's relevant. Maybe something like:

```ts
mapViewRef.getCameraForCoordinates(Position[], padding: number[], bearing?: Number, pitch?: Number): CameraStop
```

**Comment by filipstefansson** [comment]
> After all I would mostly prefer to stay as close as possible to native/SDK behavior and don't add to much around this topic on the RN side.

@KiwiKilian I agree, that makes sense. Exposing [camera(for:padding:bearing:pitch:)](https://docs.mapbox.com/ios/maps/api/10.3.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC6camera3for7padding7bearing5pitchAA13CameraOptionsVSaySo22CLLocationCoordinate2DVG_So12UIEdgeInsetsVSdSgAPtF) would stay true to that statement and solve the problem, right?

**Comment by KiwiKilian** [comment]
From my point of view it would by nice to have such methods also available through RN.

**Comment by filipstefansson** [comment]
Awesome. I'll start on it next week.

**Comment by mfazekas** [comment]
@filipstefansson thanks much, I've closed the issue as it's works as intended.
