### ISSUE TITLE
[Bug]: `onTouchEnd` from MapView isn't working anymore on iOS

### ISSUE THREAD

**Issue by pablogdcr** [rnmapbox/maps#2753]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.12.0

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-rc.5

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView
        style={{flex: 1}}
        onTouchStart={() => console.log('Touch Start')}
        onTouchCancel={() => console.log('Touch Cancel')}
        onTouchEnd={() => console.log('Touch End')}
      >
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Interacting with the map triggers the `onTouchStart` event, but it is immediately followed by `onTouchCancel`, preventing handling of `onTouchEnd`.

This issue occurs after upgrading to version 10.0.0-rc.2 (which upgrades mapbox-maps version to 10.12.0) and persists in the latest version 10.0.0-rc.5

### Expected behavior

`onTouchCancel` shouldn't be triggered, and `onTouchEnd` must be triggered when releasing the finger from the screen.

### Notes / preliminary analysis

Seems to be related to the upgrade of mapbox-maps to 10.12.0. As a workaround, I call my `onTouchEnd` function in `onMapIdle`. but there is a delay between the end of the touch and the `onMapIdle` function call.

**Comment by mfazekas** [comment]
@pablogdcr thanks much for the report. What is the use-case?

We do have  onPress and onLongPress supported but the mentioned onTouchStart, onTouchCancel, onTouchEnd events are working as is. It would be complicated to synchronise rn gesture and mapbox gesture system.

**Comment by mfazekas** [comment]
@pablogdcr btw I also could not reproduce the issue in simulator.

**Comment by petermm** [comment]
fwiw, I'm seeing same issue, and could replicate bug example above - RN 0.70.8 if that matters..

**Comment by devoren** [comment]
same issue on real device iphone

**Comment by devoren** [comment]
> @pablogdcr thanks much for the report. What is the use-case?
> 
> We do have onPress and onLongPress supported but the mentioned onTouchStart, onTouchCancel, onTouchEnd events are working as is. It would be complicated to synchronise rn gesture and mapbox gesture system.

Hi I have tested it inside NavigationContainer without any gesture handler and stacks but it doesn't work.
