### ISSUE TITLE
Not able to migrate form mapboxGL to rnmapbox V10

### ISSUE THREAD

**Issue by viswakarmalovekush** [rnmapbox/maps#2778]
## Environment
- Dev OS: [e.g. OSX 13.1, Mac OS M1 ]

## Steps to reproduce

Hi,
Currently I am using  "@react-native-mapbox-gl/maps": "8.2.1", library for map in react-native application, and it is working fine.
Now I want to update this library to new one that is **@rnmapbox/maps** . I install everything based on the document guideline given in the url https://github.com/rnmapbox/maps but it is giving so many errors.

Also I was not using typeScript with the project , so I added typeScript as well but after that also giving errors and installation is not happened successfully .

My Project cong versions:

  "react": "17.0.2",
  "react-native": "0.66.5",
  
 
 
 Error Log:
 
 
 
 
 
 Recrawled this watch 101 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/lovekush.viswakarmaonsolve.com/Documents/Workspace/alerts' ; watchman watch-project '/Users/lovekush.viswakarmaonsolve.com/Documents/Workspace/alerts'`

 BUNDLE  ./index.js 

error: SyntaxError: /Users/lovekush.viswakarmaonsolve.com/Documents/Workspace/alerts/node_modules/@rnmapbox/maps/src/components/Style.tsx: Missing initializer in const declaration. (73:50)

  71 | function asLayerComponent(layer: MapboxJSONLayer) {
  72 |   type GenericProps = { key?: string; id: string };
> 73 |   const LayerComponent: typeof React.PureComponent<GenericProps> | null =
     |                                                   ^
  74 |     getLayerComponentType(layer) as typeof React.PureComponent<GenericProps>;
  75 |   if (!LayerComponent) {
  76 |     return null;
  
  
  
<img width="370" alt="Screenshot 2023-04-06 at 1 21 59 PM" src="https://user-images.githubusercontent.com/8572582/230311084-df25c8a6-65de-46be-8b48-c28e62617260.png">

<img width="576" alt="Screenshot 2023-04-06 at 1 21 52 PM" src="https://user-images.githubusercontent.com/8572582/230311199-53effe85-bf30-4002-bfe1-6f22784b73d1.png">

```

**Comment by mfazekas** [comment]
Sorry this is not a bug report, as I won't be able to reproduce with a new project.

Please see this:
https://github.com/rnmapbox/maps/issues/2264#issuecomment-1371841235
