### ISSUE TITLE
[Bug]: The `in` filter doesn't work as expected

### ISSUE THREAD

**Issue by ikarasz** [rnmapbox/maps#2779]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.7.0

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.10

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
  VectorSource,
  FillLayer,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
        <VectorSource
          id="countries-source"
          url="mapbox://mapbox.country-boundaries-v1"
        >
          <FillLayer
            id="countries-layer"
            sourceID="countries-source"
            sourceLayerID="country_boundaries"
            style={{
              fillColor: '#6E599F',
            }}
            filter={['in', 'worldview', 'US']}
          />
        </VectorSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Observed behavior: When the worldview is an array the filter doesn't match. Even if the specified value is contained in the array.

For example, if you replace the 'US' with 'CN' then it will display the layer but if it is an array the layer won't be drawn. In nutshell, the 'in' expression works as '=='.

### Expected behavior

The example above should draw a layer above China.

**Comment by mfazekas** [comment]
@ikarasz I don't completely understand can you elaborate? Have you tried the same expression in mapbox-gl-js? Does it work there? 

Shouldn't it be `['in','US',['get','worldview']]`



https://docs.mapbox.com/help/glossary/worldview/

**Comment by ikarasz** [comment]
@mfazekas I think China is a good test case.
China is highlighted with `['in', 'worldview', 'CN']` but not highlighted with `['in', 'CN', ['get', 'worldview']]` so I suppose the second is not the proper approach however, that would make sense to me.
And no, I haven't tested it with mapbox-gl-js. I am pretty new to mapbox so I am a bit lost with all the different libraries.

[This mapbox example](https://docs.mapbox.com/mapbox-gl-js/example/toggle-worldviews/) works with match, which doesn't work for me in rnmapbox either.
[This one](https://docs.mapbox.com/help/glossary/worldview/) suggests using the approach that you mentioned but still doesn't work in my case.

Unfortunately, I have no idea how to debug this issue. If you could give me some hints then I would try it.

**Comment by ikarasz** [comment]
You were right, the problem is not with the library. The filter doesn't work as described [here](https://docs.mapbox.com/help/glossary/worldview/#filtering-data). It seems like you cannot combine `in` with `==`
So instead of:
```js
[
  "any",
  ["==", "all", ["get", "worldview"]],
  ["in", "US", ["get", "worldview"]]
]
```
We need:
```js
[
  "any",
  ["in", "all", ["get", "worldview"]],
  ["in", "US", ["get", "worldview"]]
]
```
