### ISSUE TITLE
[Bug]: There is no Style component

### ISSUE THREAD

**Issue by yuriydrobniy** [rnmapbox/maps#2783]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.10.0

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.61

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
  Style,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Style json={.....} />
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

import does not contain the described [here](https://github.com/rnmapbox/maps/blob/main/docs/Style.md) Style component

### Expected behavior

the Style component should be present

**Comment by mfazekas** [comment]
@yuriydrobniy can you try an RC version? It should be there :

https://github.com/rnmapbox/maps/blob/366eee40af9f1c439706d6104b964e0f25fd7b28/src/Mapbox.ts#L57
