### ISSUE TITLE
impossible to launch app after install

### ISSUE THREAD

**Issue by Survivor2302** [rnmapbox/maps#2786]
When i install the module witn npm install or yarn add, when i launch my app i got the error :

> Task :rnmapbox_maps:compileDebugRenderscript NO-SOURCE
> Task :rnmapbox_maps:generateDebugResValues FAILED

and the build fail

**Comment by mfazekas** [comment]
@Survivor2302 hi sorry we don't provide Support. See https://github.com/rnmapbox/maps/wiki/Support For more info.
