### ISSUE TITLE
[Bug]: Re-rendering a VectorSource with a different key keeps previous cached tiles, causing flickering.

### ISSUE THREAD

**Issue by wmonecke** [rnmapbox/maps#2787]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.70

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const Map = () => {
  const [forceRerenderNumber, setForceRerenderNumber] = useState(0);
  const { data: webSocketUpdates } = useFetchZoneStatusUpdatesQuery();

  useEffect(() => {
    const refetchTiles = async () => {
      await MapboxGL.offlineManager.invalidatePack('evacuation_zone_layer');
      await MapboxGL.offlineManager.invalidateAmbientCache();

      setTimeout(() => {
        setForceRerenderNumber((prev) => prev + 1);
      }, CacheTimeoutPeriod + 1000);

      setTimeout(
        () => setForceRerenderNumber((prev) => prev + 1),
        CacheTimeoutPeriod + 3000,
      );
    };

    if (UpdateEvacZonesIds.includes(webSocketUpdates?.layerToUpdate ?? '')) {
      refetchTiles();
    }
    
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [webSocketUpdates]);

    return (
      <MapView style={{flex: 1}}>
         <MapboxGL.VectorSource
              key={forceRerenderKey}
              id="evacuation_zone_layer"
              tileUrlTemplates={buildTileTemplatesURLs('evacuation_zone')}
           >
           <MapboxGL.FillLayer
                id="evacuation_zone"
                layerIndex={LayerIndexes.ZoneFill}
                style={{
                  fillColor: ['get', 'color'],
                  fillOpacity: 0.4,
                  fillOutlineColor: '#232323',
                }}
                sourceID="evacuation_zone_layer"
                sourceLayerID="evacuation_zone"
              />
          </MapboxGL.VectorSource>
      </MapView>
    );
}
```

### Observed behavior and steps to reproduce

The fill layer gets cached and conflicts with the newly fetched tiles. As you zoom in and out the color changes. The actual color should be **red** but it switches from purple to red. This is happening in both iOS and Android.

**Is there any way to discard all previously cached tiles to make sure this doesn't happen?**

https://user-images.githubusercontent.com/24256469/231426288-a1cd9586-4a4e-4956-9804-b65b15260358.MP4

### Expected behavior

The layer to stay red.

**Comment by mfazekas** [comment]
@wmonecke Thanks for the report, in the code `forceRerenderKey` is not defined, please make your example complete

**Comment by wmonecke** [comment]
@mfazekas Updated the code. The `forceRerenderKey` is simply a number that gets increased to force a rerender of the component.

**Comment by mfazekas** [comment]
@wmonecke it's still not something we can run, even more undefined things. Please post a complete component that we can  run.

Also why does the color change? Did the url changed in vector source? Or just the url content? In the later case try changing the url too.

**Comment by wmonecke** [comment]
The `tileUrlTemplates` stays the same between re-renders. The color should NOT change, that is the bug I am trying to report. The tileUrlTemplates should be fetching the new tiles which would be the color **red** and only **red**.

I can't really post our server tile URL because of sensitive data.
I cannot provide a fully working example because that would need env keys.

@mfazekas  I am just trying to show that the previously shown tiles are somehow interfering with the newly fetched ones.
I don't think this issue should be closed though 😅

**Comment by wmonecke** [comment]
@mfazekas Could we reopen this issue, please? This functionality is critical to our organisation.

**Comment by mfazekas** [comment]
@wmonecke Sorry we do close issues if there is not enough info to reproduce it. This is an issue list for reproducible bugs, sorry. We do still accept PR-s, fixes.

Unfortunately we don't have resources to provide free [support](https://github.com/rnmapbox/maps/wiki/Support).

**Comment by wmonecke** [comment]
Will dig into the code and submit a potential PR for this issue. Thank you for the prompt response!

**Comment by Dakuan** [comment]
we are finding that changing the url of the VectorSource just makes the fill / line layers just vanish rather than getting updated

**Comment by wmonecke** [comment]
Can you try unmounting the VectorSource then remounting it with the updated
url?

A bit hacky but it's what is working.
