### ISSUE TITLE
[Bug]: TypeError: MapboxGLOfflineManager.resetDatabase / .invalidateAmbientCache is not a function

### ISSUE THREAD

**Issue by wmonecke** [rnmapbox/maps#2797]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.70

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
  offlineManager
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  componentDidMount() {
    offlineManager.resetDatabase() // throws type error
    offlineManager.invalidateAmbientCache() // also throws type error
  }

  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

offlineManager.resetDatabase throws an error when it should be deleting the DB

### Expected behavior

fn call should delete DB.

**Comment by wmonecke** [comment]
@mfazekas This is still an issue with  "@rnmapbox/maps": "10.0.3-beta.0".

**Comment by mfazekas** [comment]
@wmonecke sorry thought it's an android error reopening. `invalidateAmbientCache` is not implemented on v10. What is the use case?

**Comment by wmonecke** [comment]
@mfazekas This goes back to [another issue](https://github.com/rnmapbox/maps/issues/2787) I opened recently.

When you unmount and remount a Layer on the web, the Layer then fetches fresh tiles. However, on mobile, this is not the case. When a Layer remounts it fetches from the cache apparently. We want to invalidate the cache between the unmount and remount of the layer.

**Comment by mfazekas** [comment]
On v10 we cannot implement invalidateAmbientCache, it now logs a warning about that. Added a new v10 only method MapView.clearData, but I don't think it helps your use case. If you know the source you're referring to has changed, the best way is to use a different url. (Like adding and extra query param like `http://bar.com/data?ts=1234`)

**Comment by wmonecke** [comment]
`clearData` will wipe the cache?

I just tried the extra query param approach and it partially works. It appears there is still some cache conflict when cold-starting the app. Maybe `clearData` could help solve that?

**Comment by sampathkumarch** [comment]
how to clear the data from  ambient cache can you give some example code
