### ISSUE TITLE
[Bug]: TypeError: Cannot read property 'EventTypes' of null, js engine: hermes

### ISSUE THREAD

**Issue by pathetic** [rnmapbox/maps#2798]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```javascript
import React from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

Mapbox.setAccessToken('<YOUR_ACCESSTOKEN>');

const App = () => {
  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <Mapbox.MapView style={styles.map} />
      </View>
    </View>
  );
}

export default App;

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    height: 300,
    width: 300,
  },
  map: {
    flex: 1
  }
});
```

### Observed behavior and steps to reproduce

When I am trying to start the app I am getting 2 errors
› Reloading apps
Android Bundling complete 1217ms
 ERROR  TypeError: Cannot read property 'EventTypes' of null, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### Expected behavior

Should start the app with no errors

**Comment by mfazekas** [comment]
Sorry we don't offer free [support](https://github.com/rnmapbox/maps/wiki/Support) for this package. Please check our setup guides to make sure that you've integrated the library correctly. Also check out this [tutorial](https://dev.to/ajmal_hasan/react-native-mapbox-v10-installation-7ga)

**Comment by TayyabMir056** [comment]
Hey @pathetic Were you able to solve the error?

**Comment by pathetic** [comment]
Yeah, I did

**Comment by TayyabMir056** [comment]
@pathetic Could you please share the steps to solve this? I'm facing the same issue. Thanks.

**Comment by pathetic** [comment]
https://youtu.be/C6b-TXFtJDs

Follow this video, also after adding an expo plugin make sure to rebuild the app.
This is what was causing the issue in the first place.
