### ISSUE TITLE
[Bug]: Can't install the app on an iPhone physical device

### ISSUE THREAD

**Issue by thibaultitautomotive** [rnmapbox/maps#2810]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.2

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

I can't install my app via Xcode

### Notes / preliminary analysis

Unable to install "MyApp"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
User Info: {
    DVTErrorCreationDateKey = "2023-04-19 18:45:51 +0000";
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}

Could not inspect the application package.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
User Info: {
    DVTRadarComponentKey = 282703;
    MobileDeviceErrorCode = "(0xE8000051)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000117c0c2bc DTDKCreateNSErrorFromAMDErrorCode + 300
	1   DTDeviceKitBase                     0x0000000117c403c0 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 136
	2   DVTFoundation                       0x00000001070520e0 DVTInvokeWithStrongOwnership + 76
	3   DTDeviceKitBase                     0x0000000117c40144 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1196
	4   IDEiOSSupportCore                   0x0000000125e47c34 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.147 + 2328
	5   DVTFoundation                       0x000000010715c99c __DVT_CALLING_CLIENT_BLOCK__ + 16
	6   DVTFoundation                       0x000000010715d408 __DVTDispatchAsync_block_invoke + 152
	7   libdispatch.dylib                   0x00000001955325f0 _dispatch_call_block_and_release + 32
	8   libdispatch.dylib                   0x00000001955341b4 _dispatch_client_callout + 20
	9   libdispatch.dylib                   0x000000019553b8a8 _dispatch_lane_serial_drain + 668
	10  libdispatch.dylib                   0x000000019553c404 _dispatch_lane_invoke + 392
	11  libdispatch.dylib                   0x0000000195546c98 _dispatch_workloop_worker_thread + 648
	12  libsystem_pthread.dylib             0x00000001956f4360 _pthread_wqthread + 288
	13  libsystem_pthread.dylib             0x00000001956f3080 start_wqthread + 8
);
}

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone11,8";
    "device_osBuild" = "14.5 (18E199)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 18246;
    "operation_errorCode" = "-402653103";
    "operation_errorDomain" = "com.apple.dt.MobileDeviceErrorDomain";
    "operation_errorWorker" = IDEInstalliPhoneLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 1;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_runnable_type" = 2;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos16.2";
    "sdk_osVersion" = "16.2";
    "sdk_variant" = iphoneos;
}

System Information

macOS Version 12.5.1 (Build 21G83)
Xcode 14.2 (21534) (Build 14C18)
Timestamp: 2023-04-19T20:45:51+02:00

**Comment by thibaultitautomotive** [comment]
<img width="276" alt="Capture d’écran 2023-04-19 à 20 46 01" src="https://user-images.githubusercontent.com/97880904/233171953-77db4bc1-9779-4b45-86c8-60c129fd8f84.png">

**Comment by herbertvuijk** [comment]
What was the issue? I'm having the same
