### ISSUE TITLE
followuserlolation not working after zooming

### ISSUE THREAD

**Issue by PentamapRainer** [rnmapbox/maps#2813]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.2

### Standalone component to reproduce

```javascript
import React from 'react';
import Mapbox from '@rnmapbox/maps';

class Map extends React.Component {
    return (
      <Mapbox.MapView 
        style={{flex:1, }}
      >
        <Mapbox.Camera 
          followUserLocation
        />
        <Mapbox.UserLocation
            visible={true}
          /> 
      </Mapbox.MapView>
    );
}
```

### Observed behavior and steps to reproduce

When zooming, the user location is not following any more.

### Expected behavior

When zooming, the user location should be still following.

### Notes / preliminary analysis

https://user-images.githubusercontent.com/6825724/233954202-a360390b-d409-4243-b98c-429e82e02cb3.mov

**Comment by mfazekas** [comment]
@PentamapRainer this is how mapbox works by default any user interaction removes followUserLocation. We'll need better api so this can be customised better. But it's a feature request not a bug report
