### ISSUE TITLE
[Android] Cannot zoom, drag, rotate the map. Touch gestures don't work. Is there any solution for me?

### ISSUE THREAD

**Issue by SonDN-DDS** [rnmapbox/maps#2823]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.12.1

### Platform

Android

### `@rnmapbox/maps` version

main

### Standalone component to reproduce

```javascript
i  return (
    <View style={{flex: 1}}>
      <Mapbox.MapView
        style={{flex: 1}}
        styleURL={Mapbox.StyleURL.Street}
        zoomEnabled
        rotateEnabled
        scrollEnabled>
        <Mapbox.Camera
          zoomLevel={13}
          animationMode={'flyTo'}
          animationDuration={1100}
          centerCoordinate={[
            locationRoute?.coords.longitude ?? 0,
            locationRoute?.coords.latitude ?? 0,
          ]}
        />
        <Mapbox.UserLocation
          animated
          androidRenderMode="gps"
          requestsAlwaysUse
          showsUserHeadingIndicator
        />
        {listMarker &&
          listMarker.map((item, index) => {
            return (
              <Mapbox.PointAnnotation
                key={index.toString()}
                id={index.toString()}
                onSelected={() => console.log('123')}
                coordinate={[item.long, item.lat]}>
                <AnnotationContent customisedName={item.title} />
              </Mapbox.PointAnnotation>
            );
          })}
      </Mapbox.MapView>
      <View style={{position: 'absolute', top: insets.top, right: 16}}>
        <AppIcons
          iconType={AppConstant.ICON_TYPE.AntIcon}
          name="closecircle"
          size={30}
          color={Colors.blue}
          onPress={() => navigation.goBack()}
        />
      </View>
    </View>
  );
```

### Observed behavior and steps to reproduce

[Android] Cannot zoom, drag, rotate the map. Touch gestures don't work. Is there any solution for me?

**Comment by JamesIde** [comment]
As trivial as it sounds, did you try rebuilding your app? Sometimes the touch gestures stop completely after too many hot reloads/refreshes.

**Comment by SonDN-DDS** [comment]
@JamesIde i tried rebuilding so many times, but it doesn't work

**Comment by mfazekas** [comment]
@SonDN-DDS pls include a complete example, the current one missing variables like listMarker. etc.

**Comment by SonDN-DDS** [comment]
@mfazekas when i add TouchableWithouthFeedback wrapper, scroll function works however rotate and zoom function not working 
my code : 

import React, {FC, useEffect} from 'react';
import {useIsFocused, useNavigation, useRoute} from '@react-navigation/native';
import {NavigationProp, RouterProp} from '../../navigation';
import {TimeKeepDataProps} from '../../models/types';
import {
  StyleSheet,
  View,
  Text,
  PermissionsAndroid,
  TouchableWithoutFeedback,
} from 'react-native';
import {Colors} from '../../assets';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {AppIcons} from '../../components/common/AppIcons';
import {AppConstant} from '../../const';
import {MAPBOX_ACCESS_TOKEN} from '@env';
import MapboxGL, {
  MapView,
  Camera,
  UserLocation,
  PointAnnotation,
  MarkerView,
} from '@rnmapbox/maps';

MapboxGL.setAccessToken(MAPBOX_ACCESS_TOKEN);

const MapCoordinate = () => {
  const navigation = useNavigation<NavigationProp>();
  const route = useRoute<RouterProp<'MAP_COORDINATE'>>();
  const isFocus = useIsFocused();
  const insets = useSafeAreaInsets();

  const locationRoute = route.params?.location;
  const listMarker: TimeKeepDataProps[] = route.params?.listMaker;

  const requestLocationPermission = async () => {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can use the location');
      } else {
        console.log('location permission denied');
      }
    } catch (err) {
      console.warn(err);
    }
  };

  useEffect(() => {
    if (isFocus) {
      requestLocationPermission();
    }
  }, [isFocus]);

  const AnnotationContent: FC<AnnotationContentProps> = ({customisedName}) => {
    return (
      <View style={styles.container}>
        <View style={styles.textContainer}>
          <Text style={styles.text}>{customisedName}</Text>
        </View>
        <AppIcons
          iconType={AppConstant.ICON_TYPE.AweIcons5}
          name="map-marker-alt"
          size={30}
          color={Colors.red}
        />
      </View>
    );
  };

  return (
    <>
      <TouchableWithoutFeedback
        style={{flex: 1, justifyContent: 'center'}}
        touchSoundDisabled={false}>
        <MapView
          style={{flex: 1}}
          styleURL={MapboxGL.StyleURL.Street}
          zoomEnabled={true}
          rotateEnabled={true}
          scrollEnabled={true}
          onPress={() => console.log('222')}>
          <Camera
            zoomLevel={12}
            animationMode={'flyTo'}
            animationDuration={1100}
            centerCoordinate={[
              locationRoute?.coords.longitude ?? 0,
              locationRoute?.coords.latitude ?? 0,
            ]}
          />
          <UserLocation
            visible={true}
            animated
            androidRenderMode="gps"
            requestsAlwaysUse={true}
            showsUserHeadingIndicator={true}
          />
          {listMarker &&
            listMarker.map((item, index) => {
              return (
                <PointAnnotation
                  key={index.toString()}
                  id={(index + 1).toString()}
                  onSelected={() => console.log('123')}
                  coordinate={[item.long, item.lat]}>
                  <AnnotationContent customisedName={item.title} />
                </PointAnnotation>
              );
            })}
        </MapView>
      </TouchableWithoutFeedback>
      <View style={{position: 'absolute', top: insets.top, right: 16}}>
        <AppIcons
          iconType={AppConstant.ICON_TYPE.AntIcon}
          name="closecircle"
          size={30}
          color={Colors.blue}
          onPress={() => navigation.goBack()}
        />
      </View>
    </>
  );
};
const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    width: 100,
    backgroundColor: 'transparent',
  },
  textContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  text: {
    textAlign: 'center',
    paddingHorizontal: 5,
  },
  icon: {
    paddingTop: 5,
  },
});

interface AnnotationContentProps {
  customisedName: string;
}

export default MapCoordinate;

**Comment by SonDN-DDS** [comment]
import React, {FC, useEffect} from 'react';
import {useIsFocused, useNavigation, useRoute} from '@react-navigation/native';
import {NavigationProp, RouterProp} from '../../navigation';
import {TimeKeepDataProps} from '../../models/types';
import {
  StyleSheet,
  View,
  Text,
  PermissionsAndroid,
  TouchableWithoutFeedback,
} from 'react-native';
import {Colors} from '../../assets';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {AppIcons} from '../../components/common/AppIcons';
import {AppConstant} from '../../const';
import {MAPBOX_ACCESS_TOKEN} from '@env';
import MapboxGL, {
  MapView,
  Camera,
  UserLocation,
  PointAnnotation,
  MarkerView,
} from '@rnmapbox/maps';

MapboxGL.setAccessToken(MAPBOX_ACCESS_TOKEN);

const MapCoordinate = () => {
  const navigation = useNavigation<NavigationProp>();
  const route = useRoute<RouterProp<'MAP_COORDINATE'>>();
  const isFocus = useIsFocused();
  const insets = useSafeAreaInsets();

  const locationRoute = route.params?.location;
  const listMarker: TimeKeepDataProps[] = route.params?.listMaker;

  const requestLocationPermission = async () => {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can use the location');
      } else {
        console.log('location permission denied');
      }
    } catch (err) {
      console.warn(err);
    }
  };

  useEffect(() => {
    if (isFocus) {
      requestLocationPermission();
    }
  }, [isFocus]);

  const AnnotationContent: FC<AnnotationContentProps> = ({customisedName}) => {
    return (
      <View style={styles.container}>
        <View style={styles.textContainer}>
          <Text style={styles.text}>{customisedName}</Text>
        </View>
        <AppIcons
          iconType={AppConstant.ICON_TYPE.AweIcons5}
          name="map-marker-alt"
          size={30}
          color={Colors.red}
        />
      </View>
    );
  };

  return (
    <>
      <TouchableWithoutFeedback
        style={{flex: 1, justifyContent: 'center'}}
        touchSoundDisabled={false}>
        <MapView
          style={{flex: 1}}
          styleURL={MapboxGL.StyleURL.Street}
          zoomEnabled={true}
          rotateEnabled={true}
          scrollEnabled={true}
          onPress={() => console.log('222')}>
          <Camera
            zoomLevel={12}
            animationMode={'flyTo'}
            animationDuration={1100}
            centerCoordinate={[
              locationRoute?.coords.longitude ?? 0,
              locationRoute?.coords.latitude ?? 0,
            ]}
          />
          <UserLocation
            visible={true}
            animated
            androidRenderMode="gps"
            requestsAlwaysUse={true}
            showsUserHeadingIndicator={true}
          />
          {listMarker &&
            listMarker.map((item, index) => {
              return (
                <PointAnnotation
                  key={index.toString()}
                  id={(index + 1).toString()}
                  onSelected={() => console.log('123')}
                  coordinate={[item.long, item.lat]}>
                  <AnnotationContent customisedName={item.title} />
                </PointAnnotation>
              );
            })}
        </MapView>
      </TouchableWithoutFeedback>
      <View style={{position: 'absolute', top: insets.top, right: 16}}>
        <AppIcons
          iconType={AppConstant.ICON_TYPE.AntIcon}
          name="closecircle"
          size={30}
          color={Colors.blue}
          onPress={() => navigation.goBack()}
        />
      </View>
    </>
  );
};
const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    width: 100,
    backgroundColor: 'transparent',
  },
  textContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  text: {
    textAlign: 'center',
    paddingHorizontal: 5,
  },
  icon: {
    paddingTop: 5,
  },
});

interface AnnotationContentProps {
  customisedName: string;
}

export default MapCoordinate;

**Comment by JamesIde** [comment]
Any reason why TouchableWithoutFeedback instead of Pressable? The docs https://reactnative.dev/docs/touchablewithoutfeedback say it shouldn't be used unless theres a really good reason to.

**Comment by shamilkotta** [comment]
@SonDN-DDS  have you figured it out, I am also facing same issue in android. @rnmapbox/maps version 10.0.15
