### ISSUE TITLE
Cannot build app for arm64 devi ce

### ISSUE THREAD

**Issue by Stophface** [rnmapbox/maps#2828]
## Environment
Dev OS: 13.12.1
rnmapbox: 8.6.0-beta.0

## Steps to reproduce

I am getting the following error (`Command PhaseScriptExecution failed with a nonzero exit code`) when I try to archive the App for arm64 (getting ready for production).

> rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
> Command PhaseScriptExecution failed with a nonzero exit code

Upon investigation, I found out that this error preceeds the actual error thrown by XCode. It has something to do with `MapboxMobileEvents.framework` 

> Stripped /Users/.../Library/Developer/Xcode/DerivedData/...-booakraqsfcnpmerohyuverblmeu/Build/Intermediates.noindex/ArchiveIntermediates/.../InstallationBuildProductsLocation/Applications/....app/Frameworks/Mapbox.framework/Mapbox of architectures: i386 x86_64 armv7
> Code Signing /Users/.../Library/Developer/Xcode/DerivedData/...-booakraqsfcnpmerohyuverblmeu/Build/Intermediates.noindex/ArchiveIntermediates/.../InstallationBuildProductsLocation/Applications/....app/Frameworks/Mapbox.framework with Identity Apple Development: jodelkraeh@protonmail.com (7QVUJM89KY)
> /usr/bin/codesign --force --sign 87D485685916DD996401EDB822E33EE71FAA5D2B  --preserve-metadata=identifier,entitlements '/Users/.../Library/Developer/Xcode/DerivedData/...-booakraqsfcnpmerohyuverblmeu/Build/Intermediates.noindex/ArchiveIntermediates/.../InstallationBuildProductsLocation/Applications/....app/Frameworks/Mapbox.framework'
> Symlinked...
> rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/MapboxMobileEvents.framework" "/Users/.../Library/Developer/Xcode/DerivedData/...-booakraqsfcnpmerohyuverblmeu/Build/Intermediates.noindex/ArchiveIntermediates/.../InstallationBuildProductsLocation/Applications/....app/Frameworks"
building file list ... rsync: link_stat "/Users/.../projects/.../ios/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/MapboxMobileEvents.framework" failed: No such file or directory (2)
done

I am not sure what is causing this... Why does it have trouble finding `MapboxMobileEvents.framework`.? 

I am also getting some weird behaviour around Mapbox with `pod`: Upon `pod deintegrate` I get

>  Showing Recent Issues
mkdir -p /Users/.../Library/Developer/Xcode/DerivedData/...-booakraqsfcnpmerohyuverblmeu/Build/Intermediates.noindex/ArchiveIntermediates/.../BuildProductsPath/Release-iphoneos/....app/Frameworks

> rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/.../projects/.../ios/Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework" "/Users/.../Library/Developer/Xcode/DerivedData/...-booakraqsfcnpmerohyuverblmeu/Build/Intermediates.noindex/ArchiveIntermediates/.../InstallationBuildProductsLocation/Applications/....app/Frameworks"

This is my `podfile`

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target '...' do
  config = use_native_modules!
    # If you're using autolinking, this line might not be needed
    pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'

    # NOTE: Do not remove, needed to keep WatermelonDB compiling:
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true

    # react-native-fs
    pod 'RNFS', :path => '../node_modules/react-native-fs'

    # NOTE: This is required as of v0.23
    pod 'simdjson', path: '../node_modules/@nozbe/simdjson'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target '...Tests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    # react-native-mapbox-gl
    $RNMBGL.pre_install(installer)
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.157.0' })

  post_install do |installer|
    react_native_post_install(installer)
    # react-native-mapbox-gl
    $RNMBGL.post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

However, it finishes. I then run `pod install` which does not throw anything.

**Comment by mfazekas** [comment]
@Stophface sorry why are you using 8.6? GitHub issues is only for 10.0-version, and we also only accept bugs with instructions to reproduce. Sorry we don't have [support](https://github.com/rnmapbox/maps/wiki/Support) as it's a community project.

**Comment by Stophface** [comment]
@mfazekas Because I cannot upgrade to v10 because of https://github.com/rnmapbox/maps/issues/2725#issuecomment-1481973177.
