### ISSUE TITLE
[Bug]: MarkerView adding touchable views inside doesnot worki

### ISSUE THREAD

**Issue by pasalnp** [rnmapbox/maps#2834]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.4

### Platform

iOS

### `@rnmapbox/maps` version

10.0.4

### Standalone component to reproduce

```
const BugReportExample = ()=> {

    return (
    <MapboxGL.Camera
       animationMode={'flyTo'}
       animationDuration={100}
        zoomLevel={14} 
        centerCoordinate={adjustCoordinate} />
      <MapboxGL.MarkerView
        // centerCoordinate={coordinate}
        key="pointAnnotation"
        id="pointAnnotation"
        // draggable
        // onDragEnd={(data)=>{console.log("drag end",data);}}
        coordinate={coordinate}
      >
        <TouchableOpacity 
        onPress={clickHandle}
        >
        <View
          style={
            {
           
              display:'flex',
              flexDirection:'row'
            }
          }
        >
                

          <Text style={{fontSize:Fonts.verysmall,color:Colors.white,fontWeight:Fonts.bolder}}> Place name</Text> 
        </View>
        </TouchableOpacity>
      </MapboxGL.MarkerView>
    );
  }
```

### Observed behavior and steps to reproduce

clicking on marker in the map does nothing

### Expected behavior

clicking touchable opacity should work

**Comment by mfazekas** [comment]
`adjustCoordinate` `clickHandle` and `coordinate` is not defined. Also please add imports and not sure what's `Fonts`

**Comment by Epick362** [comment]
Hi, I am encountering this aswell in my application. Here is my code that worked on version before v10.

The <TouchableOpacity> shows a touch event (it fades for a second) but no `onPress` is logged.

```tsx
// This is in map
<MapboxGL.MarkerView coordinate={coordinates} anchor={{ x: 0.5, y: 1 }}>
  <BasicMarker element={element} style={style} onPress={onPress} />
</MapboxGL.MarkerView>

// BasicMarker.tsx
export const BasicMarker = ({ element, onPress, style }: Props) => {
  const onPressMarker = () => {
    console.log('onPress', onPress)
    onPress && onPress(element)
  }

  const markerDimensions: { width: number; height: number } = {
    width: 30,
    height: 40,
  }

  return (
    <TouchableOpacity
      onPress={onPressMarker}
      style={{ backgroundColor: 'transparent', ...markerDimensions, ...style }}>
      <Svg
        height={markerDimensions.height}
        width={markerDimensions.width}
        viewBox={`0 0 ${markerDimensions.width} ${markerDimensions.height}`}>
        <Path
          d="M15.6,1c-7.7,0-14,6.3-14,14c0,10.5,14,26,14,26s14-15.5,14-26C29.6,7.3,23.3,1,15.6,1z"
          fill={element.markerConfig.markerColor}
          stroke={element.markerConfig.outlineColor}
          strokeWidth={element.markerConfig.outlineWidth}
        />
      </Svg>

      <Icon
        name={element.markerConfig.icon}
        style={{
          position: 'absolute',
          top: 8,
          left: 10,
          color: element.markerConfig.iconColor,
        }}
        solid
      />
    </TouchableOpacity>
  )
  ```

**Comment by MichaelDanielTom** [comment]
> Hi, I am encountering this aswell in my application. Here is my code that worked on version before v10.
> 
> The shows a touch event (it fades for a second) but no `onPress` is logged.
> 
> ```tsx
> // This is in map
> <MapboxGL.MarkerView coordinate={coordinates} anchor={{ x: 0.5, y: 1 }}>
>   <BasicMarker element={element} style={style} onPress={onPress} />
> </MapboxGL.MarkerView>
> 
> // BasicMarker.tsx
> export const BasicMarker = ({ element, onPress, style }: Props) => {
>   const onPressMarker = () => {
>     console.log('onPress', onPress)
>     onPress && onPress(element)
>   }
> 
>   const markerDimensions: { width: number; height: number } = {
>     width: 30,
>     height: 40,
>   }
> 
>   return (
>     <TouchableOpacity
>       onPress={onPressMarker}
>       style={{ backgroundColor: 'transparent', ...markerDimensions, ...style }}>
>       <Svg
>         height={markerDimensions.height}
>         width={markerDimensions.width}
>         viewBox={`0 0 ${markerDimensions.width} ${markerDimensions.height}`}>
>         <Path
>           d="M15.6,1c-7.7,0-14,6.3-14,14c0,10.5,14,26,14,26s14-15.5,14-26C29.6,7.3,23.3,1,15.6,1z"
>           fill={element.markerConfig.markerColor}
>           stroke={element.markerConfig.outlineColor}
>           strokeWidth={element.markerConfig.outlineWidth}
>         />
>       </Svg>
> 
>       <Icon
>         name={element.markerConfig.icon}
>         style={{
>           position: 'absolute',
>           top: 8,
>           left: 10,
>           color: element.markerConfig.iconColor,
>         }}
>         solid
>       />
>     </TouchableOpacity>
>   )
> ```

I'm getting the same behavior with code that was working before the v10 upgrade - it still shows the touch event for a few frames before fading and never calling any onPress callbacks.

**Comment by Epick362** [comment]
@MichaelDanielTom did you also upgrade your React Native version recently by any chance? I created a new issue #2880 but it seems to not be reproducible by maintainer.

**Comment by ovsiannykov** [comment]
I have this problem too. Is have it solution?

**Comment by JClackett** [comment]
Yeah definitely also having the same issue, so weirdly the onPress stops working after I've rendered the Carousel component from https://github.com/dohooo/react-native-reanimated-carousel

My guess is that something in either this package or the Carousel one is hijacking the onPress events or something, I literally have no idea how that works but I can replicate it 100% of the time if I render this Carousel somewhere in my app.

**Comment by Ajmal0197** [comment]
```
import {TapGestureHandler} from 'react-native-gesture-handler';

      <TapGestureHandler onActivated={handleTap}>
        <View style={styles.shadowWrapper1}>{CustomMarkerSwitch()}</View>
      </TapGestureHandler>
```

**Comment by MichaelDanielTom** [comment]
> 

Perhaps this means that it's an issue with reanimated (or possibly just reanimated 2) modifying something natively? For us, onPress events are also not working (onPressIn works fine), and we use Reanimated fairly heavily in our app. It also kind of reminds me of [this issue](https://github.com/software-mansion/react-native-reanimated/issues/2704) in reanimated, although I'm not sure if it's related yet.

**Comment by trungledangAxonActive** [comment]
> Solution:
> 
> ```
>   const doubleTapRef = useRef();
> 
> 
> 
>     <MarkerView ...>
>       <TapGestureHandler
>         waitFor={doubleTapRef}
>         onActivated={() => {
>           console.log("SINGLE TAP");
>         }}
>       >
>         <TapGestureHandler
>           maxDelayMs={250}
>           ref={doubleTapRef}
>           numberOfTaps={2}
>           onActivated={() => {
>             console.log("DOUBLE TAP");
>           }}
>         >
>           <Animated.View
>             style={{ width: 100, height: 100, backgroundColor: "red" }}
>           />
>         </TapGestureHandler>
>       </TapGestureHandler>
>     </MarkerView>
> ```
Thanks @Ajmal0197  
It works for me.
