### ISSUE TITLE
[Bug]: MapboxGL.UserLocation heading is not rotating 

### ISSUE THREAD

**Issue by somasekharkakarla** [rnmapbox/maps#2835]
### Mapbox Implementation

Mapbox

### Mapbox Version

rnmapbox/maps#main

### Platform

Android

### `@rnmapbox/maps` version

rnmapbox/maps#main

### Standalone component to reproduce

```javascript

<MapboxGL.UserLocation
        visible={true}
        showsUserHeadingIndicator={true}
        renderMode={'normal'}
      />
```

### Observed behavior and steps to reproduce

![Screenshot_20230502-200027](https://user-images.githubusercontent.com/65530762/235721956-83848638-154a-41d7-8f4b-8a843962c6e5.png)

I am using pixel 7 pro.  User location head is not at all rotating with phone direction

### Expected behavior

Should rotate along with phone direction

**Comment by ayberkanilatsiz** [comment]
Same on prod. It was working but now not working.

**Comment by ZanPerse** [comment]
this is working on 10.0.0-rc.11

**Comment by ZanPerse** [comment]
useEffect(() => {
    MapboxGL.locationManager.start();
    return () => {
      MapboxGL.locationManager.stop();
    };
  }, []);

add this and its should be working

**Comment by ayberkanilatsiz** [comment]
I fixed the issue. My token expired. I generated new token it fixed 👍🏼👍🏼

**Comment by mfazekas** [comment]
Pls reopen if the issue still happens with 10.1
