### ISSUE TITLE
[Bug]: iOS - followUserLocation not working

### ISSUE THREAD

**Issue by whiteHatCip** [rnmapbox/maps#2838]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.12.2

### Platform

iOS

### `@rnmapbox/maps` version

10.0.4

### Standalone component to reproduce
```
import React, {useCallback, useEffect} from 'react';
import MapboxGL, {UserTrackingMode} from '@rnmapbox/maps';

import {
  useGetCenterCoords,
  useGetCurrentCoords,
  useLocationState,
  useMapSnapState,
  useMapState,
} from 'hooks';
import {isAndroid} from '@utils';
import {Coordinate, LogManager} from 'model';

const animationDuration = 500;

const MapCamera: React.FC = () => {
  const centerCoords = useGetCenterCoords();
  const currentCoords = useGetCurrentCoords();
  const {followUserLocation, permissionGranted} = useLocationState();
  const {moveCamera} = useMapState();
  const {shouldTakeSnapshot} = useMapSnapState();
  const camera = React.createRef<MapboxGL.Camera>();

  const moveTo = useCallback(
    (coords: Coordinate, zoom?: number | null, animDuration?: number) => {
      const {latitude, longitude} = coords;
      const destZoom = zoom === null ? undefined : zoom ?? 16.35;
      LogManager.log('moveTo', {coords, zoom, destZoom});
      camera.current?.setCamera({
        centerCoordinate: [longitude, latitude],
        zoomLevel: destZoom,
        animationDuration: animDuration ?? animationDuration,
        animationMode: isAndroid ? 'moveTo' : undefined,
      });
    },
    [camera],
  );

  useEffect(() => {
    if (!moveCamera) {
      return;
    }
    if (centerCoords != null && moveCamera) {
      moveTo(centerCoords);
    }
  }, [
    centerCoords,
    moveCamera,
    moveTo,
    shouldTakeSnapshot,
    followUserLocation,
  ]);

  useEffect(() => {
    if (!isAndroid) {
      return;
    }
    if (!followUserLocation) {
      return;
    }
    if (currentCoords != null && moveCamera === true) {
      moveTo(currentCoords);
    }
  }, [currentCoords, followUserLocation, moveCamera, moveTo]);

  const shouldFollowUserLocation = () => {
    if (!permissionGranted) {
      return false;
    }
    return followUserLocation;
  };

  return (
    <MapboxGL.Camera
      ref={camera}
      followUserLocation={shouldFollowUserLocation()}
      followUserMode={UserTrackingMode.Follow}
      animationMode="none"
      animationDuration={0}
    />
  );
};

export {MapCamera};
```

### Observed behavior and steps to reproduce

The map would load and start animating towards user's location, but, after updating some redux state that caused the map to re-render, the map camera's animation would stop, and even by turning off and on the value used for `followUserLocation` prop would not make any difference. Even setting followUserLocation to true statically would not work.

### Expected behavior

The map should move towards the user's current location anytime the followUserlocation prop is set to true, no matter what.

### Notes / preliminary analysis

I did some testing, version by version since beta 76, up to beta 80, and then, lastly, using version 10.0.4.
In beta 76, everything was working fine and the followUserLocation was properly responding to the prop value changes.
Starting from beta 77, with [this](https://github.com/rnmapbox/maps/commit/e29c776ed81e42b46f285544939066426f724004) commit (integrated in beta 77), the followUserLocation updates were not causing the camera to move the map to user's current location.
Manually applying a patch that reverted the commit's changes, I was able to restore functionality.
Then I tried with a later version, specifically beta 80, and it was not working anymore.
Again, to restore the camera's functionality, I had to revert the changes in [this](https://github.com/rnmapbox/maps/commit/74d09ef24c1f9f6b0d039c8e94e10d19f12b1869#diff-1ecadd3f6b728d722b496cd815446fb9b264ec24f18c709800adfd7648040d23) commit for the `ios/RCTMGL-v10/RCTMGLLocationModule.swift` file.
Creating a patch that reverts these two code changes, I am now able to get back my application in a working state as expected.

I don't understand exactly why these two commits were needed, but they broke my application and I was wondering if it could be possible that there might be something wrong that should be fixed, so that the code in version 10.0.4 can keep its current implementation, but allowing a proper handling of my scenario.

I don't think I can provide a minimal reproduction component because of the complexity of the structure and the fact that there's the redux state that gets updated and it's really impossible for me to provide a minimum reproducible example.

Anyway I think it could be already a good insight knowing which changes that were integrated in beta 77 and beta 80 that broke my application.

Of course I am available for discussion on my specific use case, also privately, to try to sort this problem out.

**Comment by ZanPerse** [comment]
hey why dont u use this 

 ```
<MapboxGL.UserLocation
          onUpdate={loc => {
            if (followUser) {
              updateCamera(
                loc.coords.longitude,
                loc.coords.latitude,
                loc.coords.heading,
              );
            }
          }}
          requestsAlwaysUse
          showsUserHeadingIndicator
    />
 const updateCamera = (lng: number, lat: number) => {
    camera.current?.flyTo([lng, lat]);
  };
```
thats how i did it but i not able to set heading for some reason i hope this helps u

**Comment by mfazekas** [comment]
@whiteHatCip Sorry but it's unlikely that we'll be able to fix the issue without being able to reproduce it.
