### ISSUE TITLE
[Bug]: Ios `resetDatabase` crashes the app

### ISSUE THREAD

**Issue by jmysliv** [rnmapbox/maps#2842]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.3

### Standalone component to reproduce

```javascript
await MapboxGL.offlineManager.resetDatabase()
```

### Observed behavior and steps to reproduce

When called, the following error is thrown:

<img width="344" alt="Screenshot 2023-05-08 at 13 45 28" src="https://user-images.githubusercontent.com/48885911/236815973-4f8635e8-f927-4d70-9f43-88c31b19186a.png">

### Expected behavior

Function should work without an error.

**Comment by mfazekas** [comment]
It was merged with this PR https://github.com/rnmapbox/maps/commit/565a539f1afe162caa9e2528201a7edb377b2a69 so please try a later 10.0.4 release
