### ISSUE TITLE
[Bug]: contentInset of MapView doesn't work anymore

### ISSUE THREAD

**Issue by vadim312** [rnmapbox/maps#2843]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.7.0

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class MapViewBugContentInset extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}} contentInset={[0, 0, 200, 200]}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

While `contentInset` props is passed into MapView, edges should be moved but no any effect after put or not.

### Expected behavior

While `contentInset` props is passed into MapView, edges should be moved but no any effect after put or not.

**Comment by mfazekas** [comment]
@vadim312 thanks for the report. ContentInset is deprecated in v10 I'll update the docs/issue warning. Please use padding on Camera instead.
