### ISSUE TITLE
[Bug]: RasterSource not displaying multiple tileUrlTemplates

### ISSUE THREAD

**Issue by connorpmullins** [rnmapbox/maps#2855]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.6

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps'; 

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
        <MapboxGL.MapView
          styleURL={styleUrl}
          projection="mercator"
          regionDidChangeDebounceTime={100}>
          <RasterSource
            id="provider"
            key="provider"
            tileUrlTemplates={[vegetationSource, contourSource]}>
            <RasterLayer
              id="contour"
              sourceID="provider"
              style={{
                rasterSaturation: 0,
                rasterBrightnessMin: -0.5,
                rasterBrightnessMax: 1,
              }}
            />
            <RasterLayer
              id="vegetation"
              sourceID="provider"
              style={{
                rasterSaturation: 0,
                rasterBrightnessMin: -0.5,
                rasterBrightnessMax: 1,
              }}
            />
          </RasterSource>
        </MapboxGL.MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

The issue I am experiencing is that when I pass multiple `tileUrlTemplates` to RasterSource, only the first url is displayed. 
I've confirmed both layers work. I took images of that below. Whichever URL is in the 0th position in the array is the layer that gets displayed.

![image](https://github.com/rnmapbox/maps/assets/24562987/e3307654-5f7b-403e-8417-745684d31368)
![image](https://github.com/rnmapbox/maps/assets/24562987/bccec875-64e5-4f45-ac68-0ab9c777b6b6)

### Expected behavior

I expect both (or N number of) layers to be displayed when I pass multiple urls to `tileUrlTemplates` and render multiple RasterLayer components inside the parent RasterSource

### Notes / preliminary analysis

Debugging efforts:
- Try different orders of layers
- Play around with the `id`, `sourceID`, and `sourceLayerID` values
- Change the `rasterOpacity` value in the `style` property on child RasterLayers to confirm that the first layer isn't blocking children

How I got the feature to work (feels like this is not the intended solution):
```
<MapboxGL.MapView
          ref={mapRef}
          styleURL={styleUrl}
          projection="mercator">
          <RasterSource
            id="source1"
            key="source1"
            tileUrlTemplates={[contourSource]}>
            <RasterLayer
              id="contour"
              sourceID="source1"
              style={{
                rasterOpacity: 0.5,
                rasterSaturation: 0,
                rasterBrightnessMin: -0.5,
                rasterBrightnessMax: 1,
              }}
            />
          </RasterSource>
          <RasterSource id="source2" key="source2" tileUrlTemplates={[depthSource]}>
            <RasterLayer
              id="depth"
              sourceID="source2"
              style={{
                rasterOpacity: 0.5,
                rasterSaturation: 0,
                rasterBrightnessMin: -0.5,
                rasterBrightnessMax: 1,
              }}
            />
          </RasterSource>
        </MapboxGL.MapView>
```
![image](https://github.com/rnmapbox/maps/assets/24562987/02db5198-083f-4d88-b49c-972249d99bb3)

What I'm wondering is why multiple sources need to be created when `tileUrlTemplates` accepts an array of strings rather than a single string?

I'm sorry if I'm misunderstanding something basic or wasting time. This is just a tough concept for me to wrap my head around.

Thank you in advance.

**Comment by mfazekas** [comment]
@connorpmullins pls fix the example so we can reproduce the issue. Please also include source url-s. Otherwise it's extra work for us even to reproduce the issue. Thanks for the understanding.
