### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by thatop007** [rnmapbox/maps#2857]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.11.1

### Platform

iOS

### `@rnmapbox/maps` version

10.0.6

### Observed behavior and steps to reproduce

Hi 
I have followed the v10 setup steps: https://github.com/rnmapbox/maps/blob/main/README-v10.md
when I attempt to sign my app on code magic, I get the following error on the Set up code "signing settings on Xcode project" step:

```
Configure code signing settings
Searching for files matching /Users/builder/Library/MobileDevice/Provisioning Profiles/*.mobileprovision
Searching for files matching /Users/builder/Library/MobileDevice/Provisioning Profiles/*.provisionprofile
List available code signing certificates in keychain /Users/builder/Library/codemagic-cli-tools/keychains/11-05-23_q2jyl2j7.keychain-db
Searching for files matching /Users/builder/clone/**/*.xcodeproj
Failed to set code signing settings for node_modules/@rnmapbox/maps/ios/RCTMGL.xcodeproj


Build failed :|
Step 13 script `Set up code signing settings on Xcode project` exited with status code 1
```

Using these packages: 
"react-native": "0.68.2",
"@rnmapbox/maps": "10.0.6"

we use the code magic cli for the provisioning profile.

locally my project builds fine for ios and android, just an issue with code magic ios signing. Please let me know if you require any more info. 

### Expected behavior

My signing profile should not fail if it does not have an xcode dependency 

### Additional links and references

<img width="1440" alt="image" src="https://github.com/rnmapbox/maps/assets/91869074/11664acf-6b58-4fa1-87a4-cf365d58797c">

**Comment by mfazekas** [comment]
@thatop007 I'm not sure what codemagic.io is. So the .xcodeproj is a placeholder project, and not real Xcode project. That might confuse codemagic.io. you might just remove that before doing code sign as a workaround, or use `patch-package` or similar.

https://github.com/rnmapbox/maps/blob/main/ios/RCTMGL.xcodeproj/project.pbxproj
