### ISSUE TITLE
@rnmapbox (Mapbox Version 10)  is not fabric(New Architecture of react-native) compatible yet

### ISSUE THREAD

**Issue by UdayVinaik** [rnmapbox/maps#2859]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.11.1

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0

### Standalone component to reproduce

There is no error in building the app but getting following error on runtime:

`Invalid react tag, could not find RCTMGLMapView

+[RCTMGLSwiftLog error:file:line:]
    RCTMGLMapViewManager.swift:33
$s13rnmapbox_maps14RCTMGLLogErroryySS_SSSutF
$s13rnmapbox_maps20RCTMGLMapViewManagerC07withMapD0_4name8rejecter2fnySo8NSNumberC_SSySSSg_AJs5Error_pSgtcyAA0cD0CctFySo12RCTUIManagerCSg_SDyAISo6UIViewCGSgtcfU_
$s13rnmapbox_maps20RCTMGLMapViewManagerC07withMapD0_4name8rejecter2fnySo8NSNumberC_SSySSSg_AJs5Error_pSgtcyAA0cD0CctFySo12RCTUIManagerCSg_SDyAISo6UIViewCGSgtcfU_TA
$sSo12RCTUIManagerCSgSDySo8NSNumberCSo6UIViewCGSgIeggg_ACSo12NSDictionaryCSgIeyByy_TR
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.498
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
`

### Observed behavior and steps to reproduce

Also on UI I see following message:

`Unimplemented component: <MGLMapView>`

**Comment by mfazekas** [comment]
@UdayVinaik see #2106
