### ISSUE TITLE
[Bug]: Image stretchX / stretchY not working with <View/>

### ISSUE THREAD

**Issue by ryanpwaldon** [rnmapbox/maps#2862]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.11.1

### Platform

iOS

### `@rnmapbox/maps` version

10.0.6

### Standalone component to reproduce

```typescript
import { View } from 'react-native'
import Mapbox from '@rnmapbox/maps'
import { type SymbolLayerStyleProps } from '@rnmapbox/maps/src/utils/MapboxStyles'

const feature = {
  type: 'Feature',
  properties: {
    id: 'clgnqq4xc00v4bpxv7hs9m5kt',
    name: 'Soldiers Beach',
    point: {
      lng: 151.564602,
      lat: -33.291277,
    },
  },
  geometry: {
    type: 'Point',
    coordinates: [151.564602, -33.291277],
  },
} satisfies GeoJSON.Feature

const featureCollection = {
  type: 'FeatureCollection',
  features: [feature],
} satisfies GeoJSON.FeatureCollection

export default function Map() {
  return (
    <View style={{ width: '100%', height: '100%' }}>
      <Mapbox.MapView style={{ width: '100%', height: '100%' }}>
        <Mapbox.Camera animationMode="moveTo" centerCoordinate={feature.geometry.coordinates} zoomLevel={14} />
        <Mapbox.ShapeSource id="source" shape={featureCollection}>
          <Mapbox.SymbolLayer
            id="layer"
            style={
              {
                iconImage: 'badge',
                textField: ['get', 'name'],
                iconTextFit: 'both',
              } as SymbolLayerStyleProps
            }
          />
        </Mapbox.ShapeSource>
        <Mapbox.Images>
          <Mapbox.Image name="badge" stretchX={[[2, 22]]}>
            <View style={{ width: 24, height: 24, borderWidth: 2, borderColor: 'gray', backgroundColor: 'white' }} />
          </Mapbox.Image>
        </Mapbox.Images>
      </Mapbox.MapView>
    </View>
  )
}
```

### Observed behavior and steps to reproduce

`stretchX` / `stretchY` are not working with images created with native `<View/>` elements.

### Expected behavior

Image should stretch according to the `stretchX` prop (image border should not be distorted).

### Notes / preliminary analysis

![IMG_4659](https://github.com/rnmapbox/maps/assets/12480362/e3245255-baa5-46af-b989-c62da602438f)

**Comment by mfazekas** [comment]
@ryanpwaldon thanks much for the report. I could reproduce the issue can you try the fix at: https://github.com/rnmapbox/maps/pull/2863 

`yarn add rnmapbox/maps#mfazekas/image-stretch`

**Comment by ryanpwaldon** [comment]
Thanks for the quick response!

I just tried, but I'm having issues with pnpm... 🤦

Will try again tomorrow.

**Comment by ryanpwaldon** [comment]
Sorry Miklós – still having issues with my environment (only when installing rnmapbox directly from github / locally), but I assume you're happy with it, will test in the next release! Also, thanks for this feature, it's a game changer 🎉

**Comment by mfazekas** [comment]
publishing  v10.0.7-rc.0 to npm. It was half part working for me, the end was not stretched but the start was. I've double checked and it seems that we've passed down the

**Comment by ryanpwaldon** [comment]
Ahh, I see. Same here – left side is stretched, right side is not.

I believe `stretchX` is applying a multiple of 3 to its calculations (possibly related to device pixel ratio?).

Following along from my original example:

If we use a stretchX value of [[6, 66]] `[[borderWidth * 3, (width * 3) - borderWidth * 3]]`, like so:

```ts
<Mapbox.Image name="badge" stretchX={[[6, 66]]}>
    <View style={{ width: 24, height: 24, borderWidth: 2, borderColor: 'gray', backgroundColor: 'white' }} />
</Mapbox.Image>
```

It works as expected.

(There's still some blurring of the border, but I believe this is a separate issue).

**Comment by mfazekas** [comment]
@ryanpwaldon thanks much. I haven't thought of the scale factor. It's there on android, but wasn't aware on iOS. I think it should be fixed so it's the same unit as used by RN.

**Comment by ryanpwaldon** [comment]
That sounds like a good option :)

**Comment by mfazekas** [comment]
Changed v10.0.7-rc.1, so scales the stretch values
