### ISSUE TITLE
[Bug]: RCTMGL Images - SDF Icon differences from iOS to Android

### ISSUE THREAD

**Issue by sm-lgv** [rnmapbox/maps#2869]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.6

### Standalone component to reproduce

```Javascript
//The code here is what's relevant to replication, drop in a map component. 
<MapboxGL.Images
  images={{
    shop: {
      //Using url here is accepted on iOS, but will cause a crash on Android. Using uri loses the sdf aspect.
      url: 'https://docs.mapbox.com/help/data/shop-15.png',
      scale: 1.0,
      sdf: true,
    }
  }}
  onImageMissing={(e) => { console.log("onimagemissing", e) }}
/>

<MapboxGL.ShapeSource
  id={`pinMarkerShapeSource`}
  shape={{
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        id: `pin-collection`,
        properties: {
          icon: 'shop',
          color: 'red',
        },
        geometry: {
          type: 'Point',
          coordinates: [-77.049916, 38.914451],
        },
      },
    ],
  }}
  hitbox={{ width: 5, height: 5 }}
  cluster={false}
>
  <MapboxGL.SymbolLayer
    id={`pinMarkerSymbolLayer`}
    style={{
      iconImage: ['get', 'icon'],
      iconColor: ['get', 'color'],
      textField: ['get', 'name'],
      iconHaloColor: 'white',
      iconHaloWidth: 0.85,
      iconTextFit: 'both',
      iconAllowOverlap: true,
      iconSize: 0.4
    }}
  />
</MapboxGL.ShapeSource>
```

### Observed behavior and steps to reproduce

After implementing SDF Icons with MapboxGL.Images, differences were noticed between iOS and Android. Android was not working with the same structure of data as iOS and initially, and was crashing due to the use of url. Noting the structure I used is accepted in the TypeScript code as [ImageEntryData](https://github.com/rnmapbox/maps/blob/0ee5c3ff34a1eb4d30baeeef2456c5776483cd2b/src/components/Images.tsx#LL54C1-L63C3).

```
 ERROR  Your app just crashed. See the error below.
java.lang.RuntimeException: An error occurred while executing doInBackground()
  android.os.AsyncTask$4.done(AsyncTask.java:399)
  java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
  java.util.concurrent.FutureTask.setException(FutureTask.java:252)
  java.util.concurrent.FutureTask.run(FutureTask.java:271)
  android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.lang.Thread.run(Thread.java:919)
Caused by java.lang.NullPointerException: uri must not be null
```

Going to look at this file appears to show a [direct extraction of the uri token](https://github.com/rnmapbox/maps/blob/0ee5c3ff34a1eb4d30baeeef2456c5776483cd2b/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/utils/DownloadMapImageTask.kt#L49) which leads me to believe the Android code is expecting something more along the lines of the [ImageURISource structure](https://github.com/rnmapbox/maps/blob/63b95c86b269ebeebec4c49bfd916490da17374e/src/components/Images.tsx#L5).

Attempting to use uri resulted in a map that displayed the SDF icons as their base image, the black and fuzzy pngs that previewers will show.

iOS using ImageEntryData:
![Screenshot 2023-05-18 at 3 10 18 PM](https://github.com/rnmapbox/maps/assets/127074381/eb0bc965-7505-4c84-bf5c-030f126de7fe)

And Android with uri instead of url, but the rest of the structure remaining the same:
<img width="173" alt="Screenshot 2023-05-18 at 3 13 43 PM" src="https://github.com/rnmapbox/maps/assets/127074381/7323deb8-5457-4e03-868c-18d33b002b43">

### Notes / preliminary analysis

Looking around, it appears that the Swift code called to get remote images looks for ImageEntryData values to support sdf files: https://github.com/rnmapbox/maps/blob/0ee5c3ff34a1eb4d30baeeef2456c5776483cd2b/ios/RCTMGL-v10/RCTMGLUtils.swift#L32-L39

While the Android fetch code appears to pass it around to a [background task](https://github.com/rnmapbox/maps/blob/63b95c86b269ebeebec4c49bfd916490da17374e/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/utils/DownloadMapImageTask.kt#L43) that I don't see directly referencing the same structure data, although I'm not entirely sure of the intended path here. The only area I directly see the sdf value being used is in the [addBitmapImage](https://github.com/rnmapbox/maps/blob/63b95c86b269ebeebec4c49bfd916490da17374e/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImages.kt#L30C2-L42) function which only seems to only have sdf non-false if [UpdateImage](https://github.com/rnmapbox/maps/blob/63b95c86b269ebeebec4c49bfd916490da17374e/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImages.kt#L247-L252) gets sdf true passed in, I'm guessing this may not be happening as expected - or I'm missing the obvious.

**Comment by sm-lgv** [comment]
Can confirm the root cause, for testing purposes changing this to true: https://github.com/rnmapbox/maps/blob/63b95c86b269ebeebec4c49bfd916490da17374e/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImages.kt#L37

Will produce this result:
<img width="699" alt="Screenshot 2023-05-30 at 10 02 37 AM" src="https://github.com/rnmapbox/maps/assets/127074381/8534cbda-6921-44a3-8786-3973f3e33a50">

Obviously not the fix, but does indicate the value isn't being passed in, presumably from the lack of:
https://github.com/rnmapbox/maps/blob/63b95c86b269ebeebec4c49bfd916490da17374e/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/utils/ImageEntry.java#L3-L25

**Comment by mfazekas** [comment]
@sm-lgv yes your analysis is right we haven't passed sdf, stretchX, etc around when downloading simple images.
#2891 should address this

**Comment by mfazekas** [comment]
Full component I've used to repro:
```jsx
import React from 'react';
import MapboxGL from '@rnmapbox/maps';
import { View } from 'react-native';

export default function BugReportExample() {
  //The code here is what's relevant to replication, drop in a map component.
  return (
    <View style={{ flex: 1 }}>
      <MapboxGL.MapView style={{ flex: 1 }}>
        <MapboxGL.Camera
          centerCoordinate={[-77.049916, 38.914451]}
          zoomLevel={18}
        />

        <MapboxGL.Images
          images={{
            shop: {
              //Using url here is accepted on iOS, but will cause a crash on Android. Using uri loses the sdf aspect.
        
              url: 'https://docs.mapbox.com/help/data/shop-15.png',
              scale: 1.0,
              sdf: true,
            },
          }}
          onImageMissing={(e) => {
            console.log('onimagemissing', e);
          }}
        />

        <MapboxGL.ShapeSource
          id={'pinMarkerShapeSource'}
          shape={{
            type: 'FeatureCollection',
            features: [
              {
                type: 'Feature',
                id: 'pin-collection',
                properties: {
                  icon: 'shop',
                  color: 'red',
                },
                geometry: {
                  type: 'Point',
                  coordinates: [-77.049916, 38.914451],
                },
              },
            ],
          }}
          hitbox={{ width: 5, height: 5 }}
          cluster={false}
        >
          <MapboxGL.SymbolLayer
            id={'pinMarkerSymbolLayer'}
            style={{
              iconImage: ['get', 'icon'],
              iconColor: ['get', 'color'],
              textField: ['get', 'name'],
              iconHaloColor: 'white',
              iconHaloWidth: 0.85,
              iconTextFit: 'both',
              iconAllowOverlap: true,
              iconSize: 0.4,
            }}
          />
        </MapboxGL.ShapeSource>
      </MapboxGL.MapView>
    </View>
  );
}

```

**Comment by sm-lgv** [comment]
> @sm-lgv yes your analysis is right we haven't passed sdf, stretchX, etc around when downloading simple images. #2891 should address this

Thank you for the help, apologies as I don't know any Java so I was working pretty slowly through the issue today haha. Much appreciated.
