### ISSUE TITLE
.netrc file doesn't work  ||  IOS PODS INSTALL 401 ERROR

### ISSUE THREAD

**Issue by ovsiannykov** [rnmapbox/maps#2877]
# Pod is not installed and writes 401 error
## Environment
- Dev OS: [e.g. MAC OS 13.4, IOS 16]

When I try to install pods, and create `.netrc` file as mentioned here as mentioned [here](https://dev.to/ajmal_hasan/react-native-mapbox-v10-installation-7ga) it doesn't work. You can see it in the screenshot 

Token is right and android work correctly

<img width="1413" alt="Screenshot 2023-05-22 at 14 38 58" src="https://github.com/rnmapbox/maps/assets/93041689/cee091e9-350f-48bd-b500-ab04ff3efabf">

**Comment by KiwiKilian** [comment]
`.netrc` musst be placed in your user directory (`~/.netrc`, in your case `/Users/mykhailovsiannykov/.netrc´), which is also noted in the linked tutorial. Not somewhere in the project directory. Please remove your screenshot, because your secret is not properly blurred.

**Comment by ovsiannykov** [comment]
> `.netrc` musst be placed in your user directory (`~/.netrc`, in your case `/Users/mykhailovsiannykov/.netrc´), which is also noted in the linked tutorial. Not somewhere in the project directory. Please remove your screenshot, because your secret is not properly blurred.

Thank you very much! It's worked for me
