### ISSUE TITLE
[Bug]: `PointAnnotation` with `Image` is transparent on cold start

### ISSUE THREAD

**Issue by KiwiKilian** [rnmapbox/maps#2893]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```tsx
import { Camera, MapView, PointAnnotation } from '@rnmapbox/maps';
import React, { useRef, useState } from 'react';
import { Button, Image, View } from 'react-native';

import pinIcon from '../assets/pin.png';

const styles = {
  mapView: { flex: 1 },
};

const ANNOTATION_WIDTH = 42;
const ANNOTATION_HEIGHT = 68;

const BugReportExample = () => {
  const pointAnnotation = useRef<PointAnnotation>(null);
  const [showAnnotation, setShowAnnotation] = useState(false);

  return (
    <>
      <Button
        title="Show Annotation"
        onPress={() => {
          setShowAnnotation(true);
        }}
      />
      <MapView style={styles.mapView}>
        <Camera
          defaultSettings={{
            centerCoordinate: [-74.00597, 40.71427],
            zoomLevel: 12,
          }}
        />

        {showAnnotation && (
          <PointAnnotation
            id="annotation"
            coordinate={[-74.00597, 40.71427]}
            ref={pointAnnotation}
          >
            <View
              style={{ width: ANNOTATION_WIDTH, height: ANNOTATION_HEIGHT }}
            >
              <Image
                source={pinIcon}
                style={{ width: ANNOTATION_WIDTH, height: ANNOTATION_HEIGHT }}
                // fadeDuration={0}
                onLoad={() => {
                  console.log('onLoad');

                  pointAnnotation.current?.refresh();
                }}
              />
            </View>
          </PointAnnotation>
        )}
      </MapView>
    </>
  );
};

export default BugReportExample;
```

### Observed behavior and steps to reproduce

First, force quit the app. No start the app, open the example and press the "Show Annotation" button. The image in the annotation is rendere with alpha.

<img src="https://github.com/rnmapbox/maps/assets/18724559/f22ffa68-0bf2-465f-8751-9a87df21f5b6" width="200" />

### Expected behavior

The image should be rendered opaque. It works on consecutive renders, for example re-enter the screen and press the button again.

<img src="https://github.com/rnmapbox/maps/assets/18724559/9d9efb88-706d-4115-91b8-7dd870709bc5" width="200" />

### Notes / preliminary analysis

This is due to the default `fadeDuration`. On an cold app start this fade is applied and the bitmap for `PointAnnotation` is generated during the fade. Uncomment the `fadeDuration` line to fix it. I'm not sure if this is fixable from the plugins side – otherwise we should just update the docs/`PointAnnotation` example to always use `fadeDuration={0}`.

**Comment by mfazekas** [comment]
@KiwiKilian Thanks, much. Good point. Not sure if there is much we can do. I don't think we can detect when child has finished rerendereing. 
Adding fadeDuration={0} would be the best solution IMO.
