### ISSUE TITLE
[Bug]: Export more types from the package

### ISSUE THREAD

**Issue by pranshuchittora** [rnmapbox/maps#2897]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.7.0

### Standalone component to reproduce

```javascript
import { RegionPayload } from '@rnmapbox/maps';
```

### Observed behavior and steps to reproduce

Try to import the following type. 

### Expected behavior

The type has already been exported at the module level and it should be exported at the package level too.

### Notes / preliminary analysis

The type `RegionPayload` has already been exported from the `MapView`
https://github.com/rnmapbox/maps/blob/main/src/components/MapView.tsx#L60

But the same has not been exported at the package level 
https://github.com/rnmapbox/maps/blob/main/src/Mapbox.ts#L10

**Comment by mfazekas** [comment]
@pranshuchittora good point in the meantime you can use something like this to extract:

```tsx
type RegionPayload = Parameters<NonNullable<ComponentProps<typeof MapView>['onRegionWillChange']>>[0];
```

**Comment by pranshuchittora** [comment]
Thanks @mfazekas for the blazing fast reply ⚡ 
I am open to raising a PR for the same. 

So currently I am migrating from v8 to v10. And I feel there are some other types that are also not exported like camera etc. 
Let me know if you want to me to combine the other type exports with the same PR.

Happy Friday :)

**Comment by bjeske-snap** [comment]
> Thanks @mfazekas for the blazing fast reply ⚡ I am open to raising a PR for the same.
> 
> So currently I am migrating from v8 to v10. And I feel there are some other types that are also not exported like camera etc. Let me know if you want to me to combine the other type exports with the same PR.
> 
> Happy Friday :)

I think this might be causing issues. I am looking at upgrading a project to v10 but I get this error when trying to use Camera:
/node_modules/@rnmapbox/maps/src/Mapbox.ts: Unexpected token, expected "," (5:7)

**Comment by bjeske-snap** [comment]
> Hey @bjeske-snap
> Can you pls share the code snippet for more context.

It's actually happening even without importing anything, I commented out this:
`<Mapbox.Camera
          zoomLevel={11}
          centerCoordinate={startingPoint}
          animationMode={'flyTo'}
          animationDuration={0}
          ref={mapCameraRef}
        />`
<img width="426" alt="Screen Shot 2023-06-07 at 1 43 26 PM" src="https://github.com/rnmapbox/maps/assets/135865347/e1c74d80-422c-4b40-8c88-1046ae389b99">

**Comment by vikalinic** [comment]
> `export { Camera, UserTrackingMode, // type CameraPadding, // type CameraAnimationMode, // type CameraBounds, } from './components/Camera';`
> 
> Also if I comment out these lines in the Mapbox.ts file in node_modules, it then throws this error: <img alt="Screen Shot 2023-06-07 at 1 48 50 PM" width="432" src="https://user-images.githubusercontent.com/135865347/244154305-93372ab8-3f0c-43b6-aa51-7318c6751239.png">

Also getting this error after upgrade to V10 in 10.6 and 10.8

**Comment by tk63135** [comment]
Hi All - I am encountering the Unexpected token error above.  Our app is running react-native: 0.63.5, rnmapbox/maps: 10.0.15.  Has anyone found a resolution for the above?

**Comment by mfazekas** [comment]
Valid bug, but not planned do to [lack of resources](https://github.com/rnmapbox/maps/wiki/Limited-resources). Closing as not planned.
