### ISSUE TITLE
[Bug]: PointAnotation under others markers - can't setup zIndex'es

### ISSUE THREAD

**Issue by ovsiannykov** [rnmapbox/maps#2904]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.7-rc.0

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.7-rc.0

### Standalone component to reproduce

How can i setup PointAnotation & MarkerView zIndex?

<img width="361" alt="Screenshot 2023-06-12 at 16 09 37" src="https://github.com/rnmapbox/maps/assets/93041689/ad04962b-4a66-488a-8b06-c4402d27a7ec">

**Comment by mfazekas** [comment]
See https://github.com/rnmapbox/maps/blob/main/docs/Annotations.md
