### ISSUE TITLE
[Bug]: `setConnected` is undefined

### ISSUE THREAD

**Issue by jmysliv** [rnmapbox/maps#2908]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.6

### Standalone component to reproduce

```javascript
import React, { useEffect } from 'react';
import MapboxGL, {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

function BugReportExample {
    useEffect(() => {
        MapboxGL.setConnected(false);
    }, []);

    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );

}
```

### Observed behavior and steps to reproduce

The following error appears:

`undefined is not a function`

### Expected behavior

The function should run without the error.

**Comment by mfazekas** [comment]
We don't have setConnected implemented for v10/android. 


https://docs.mapbox.com/android/maps/api/10.14.0/mapbox-maps-android/com.mapbox.common/-offline-switch/
https://docs.mapbox.com/ios/maps/api/10.14.0/Classes/OfflineSwitch.html

====
https://github.com/mapbox/mapbox-maps-android/issues/206

There is a changelog entry:

```
* Introducing NetworkConnectivity API (offline switch). If setting setMapboxStackConnected(false), the Reachability API will report NotReachable, http requests are being blocked and if running, cancelled.
```

~But I don't see anything like that in current version - ah~ renamed to OfflineSwitch

https://github.com/mapbox/mapbox-maps-android/blob/49397adcd04443fcbd403b8763b56952ce362fbb/app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt#L90

**Comment by jmysliv** [comment]
@mfazekas thanks for your reply. Do you have in your roadmap to implement it then?

**Comment by mfazekas** [comment]
Valid bug, but not planned do to [lack of resources](https://github.com/rnmapbox/maps/wiki/Limited-resources). Closing as not planned.

**Comment by made4udhilip** [comment]
OMG, Then have to remove Mapbox offline from the project, RN offline mapbox no more use when its don't have this feature. As it alway create error, Mapbox will search through network for new tiles (online) when user zoom the offline map.  we can declare RN Mapbox offline is not supported anymore.  People who are trying mapbox offline feature don't waste time here, its no more supported as mentioned by @mfazekas
