### ISSUE TITLE
[BUG]: offlineManager.invalidatePack is not implemented

### ISSUE THREAD

**Issue by chris-gaona** [rnmapbox/maps#2910]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.7

### Standalone component to reproduce

```javascript
import React from 'react';
import {StyleSheet, View} from 'react-native';
import MapboxGL from '@rnmapbox/maps';

const styles = StyleSheet.create({
    mapView: {flex: 1},
});

class BugExample extends React.Component {
    async componentDidMount() {
        console.log('>>>>>>>>>>start creating pack', );
        await MapboxGL.offlineManager.createPack(
            {
                name: 'field-1', // any
                bounds: [[32.23782523101579, 46.39912398458027], [33.43887899585923, 47.041693870480955]], // any LARGE area
                styleURL: MapboxGL.StyleURL.Street,
                minZoom: 10,
                maxZoom: 12,
            },
            (pack, status) => {
                console.log('>>>>>>>>>>pack progress', pack.name, status.percentage, status.completedTileCount);
                if (status.state === 'completed') {
                    MapboxGL.offlineManager.deletePack('field-1');
                    // throws error where deletePack is not a function (android only)
                }
            },
            (pack, error) => {
                console.log('>>>>>>>>>>pack error', pack.name, error);
            },
        );

        // always shows a single pack without metadata nor identifier (name)
        console.log(MapboxGL.offlineManager.getPacks());

        // HERE's where the error is thrown
        await MapboxGL.offlineManager.invalidatePack('field-1')
    }

    render() {
        return (
            <View style={styles.mapView}>
                <MapboxGL.MapView
                    ref={(c) => (this._map = c)}
                    onPress={this.onPress}
                    style={styles.mapView}
                >
                    <MapboxGL.Camera
                        zoomLevel={10}
                        centerCoordinate={[33.43887899585923, 47.041693870480955]}
                    />
                </MapboxGL.MapView>
            </View>
        );
    }
}

export default BugExample;
```

### Observed behavior and steps to reproduce

Example of the error thrown below:

<img width="794" alt="Screenshot 2023-06-14 at 4 45 26 PM" src="https://github.com/rnmapbox/maps/assets/14164974/2fb7947e-b7cc-48a8-9917-ea31d2555aa1">

### Expected behavior

await Mapbox.offlineManager.invalidatePack(packName) should be implemented.

### Notes / preliminary analysis

await Mapbox.offlineManager.invalidatePack(packName) is not implemented and throws a JS function is undefined error.

**Comment by mfazekas** [comment]
@chris-gaona Thanks for the report, It's not yet implemented for v10. I think we can use TileStore.removeTileRegion

https://docs.mapbox.com/ios/maps/guides/offline/#delete-style-packs-and-regions

**Comment by sampathkumarch** [comment]
Hi ,
While using

:MapboxGL.offlineManager.createPack()

 Am able to downloading the maps like I gave multiple map boundaries and along with multiple names .  After that app memory size was increased then I want to delete few offline maps so am using this one 

MapboxGL.offlineManager.deletePack('field-1')  

using whatever i used names for create  offline map  , but name only deleting   along with data was not deleted , while check the app memory still  same size is there .

So I want how to delete the offline map from the app ambient cache memory

**Comment by mfazekas** [comment]
Valid bug, but not planned do to [lack of resources](https://github.com/rnmapbox/maps/wiki/Limited-resources). Closing as not planned.

**Comment by petertoth-dev** [comment]
@mfazekas Still not? Why is it documented then?? I have no idea why people start projects then abandon them... if they didn't start someone else might've done a better job :/
