### ISSUE TITLE
[Bug]: onCameraChanged crashes iOS

### ISSUE THREAD

**Issue by Renszit** [rnmapbox/maps#2921]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.8

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView onCameraChanged={()=> console.log('anything')} style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

using onCameraChanged on latest update on iOS crashes the app with a native crash. 

### Expected behavior

No crash

### Notes / preliminary analysis

 _No response_

### Additional links and references

stacktrace: 
[crash.txt](https://github.com/rnmapbox/maps/files/11801107/crash.txt)

**Comment by olofholmlund** [comment]
Also getting this error on latest version
```
[CoreFoundation] *** Terminating app due to uncaught exception
'NSInvalidArgumentException', reason: '-[rnmapbox_maps.RCTMGLCameraChanged
coalescingKey]: unrecognized selector sent to instance 0x600003324b80'
```

**Comment by mfazekas** [comment]
@Renszit thanks for the report, I wasn't able to reproduce in our example app Example app.

What is the react-native version?!

**Comment by RyanTG** [comment]
I am experiencing this as well with 10.0.8. Class component, iOS. No crash in Android. RN version is `0.71.8` (using Expo)

**Comment by jfaq89** [comment]
I got the same exact error on Android when using the following versions:
        "@rnmapbox/maps": "10.0.9-rc.0",
        "react-native": "0.71.6",
