### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fsixpro** [rnmapbox/maps#2925]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.9-rc.0

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

I keep getting an error screen with the message `com.facebook.react.common.javascriptexception unexpected token ";"` each time I tried to run it on Android however, once I uninstall mapbox the app will work fine, but once I install it again I will see the error screen

### Expected behavior

the app should work without error screen

**Comment by mfazekas** [comment]
@fsixpro looks like a project setup issue. I'm pretty sure it works with a new project created with react-native init.
Sorry we don't have resources to troubleshoot your project setup. Most likely babel/typescript/preset are not currect. Please search or issues for similar stuff.
