### ISSUE TITLE
[Bug]: MapboxGl.Images not loading in Android

### ISSUE THREAD

**Issue by matifriaz** [rnmapbox/maps#2927]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.8

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

This issue is still occurring. I am on 10.0.8. Here's the code for loading the images 
<MapboxGl.Images images={{ 'field-pin': { uri: 'https://ricult-development.s3-ap-southeast-1.amazonaws.com/map-pin.png', }, 'field-pin-light': { uri: 'https://ricult-development.s3-ap-southeast-1.amazonaws.com/map-red-pin.png', }, }} />

**Comment by marvinernst-cognitio** [comment]
Got the same isssue.  if I use the following code the app crahes instantly
 ` 
<MapboxGL.Images
          images={{
            marker: {
              uri: BASE_URL + data.symbol.path,
            },
          }}
        /> `

**Comment by matifriaz** [comment]
It’s working fine with IOS but on Android it sometimes show the image and and sometimes not

**Comment by Stettho** [comment]
Also bumped into the crash on Android. Ended up with the following code:

```
Platform.OS === 'android'
    ? {[key]: uri}
    : {
        [key]: {uri},
      };
```

**Comment by mfazekas** [comment]
Pls add a repro component, thanks!

**Comment by sabarikobagapau** [comment]
same issue not working with url in android only please help
