### ISSUE TITLE
@rnmapbox/maps installation error in react-native-expo project

### ISSUE THREAD

**Issue by asiflhr** [rnmapbox/maps#2935]
## Environment
- Dev OS: [Win11]

## Steps to reproduce

I've installed @rnmapbox/maps in my react-native-expo project by using this guide: [https://github.com/rnmapbox/maps/blob/main/plugin/install.md](url), but getting error: "Cannot read property 'EventTypes' of null. 

```Note: I've added screenshots below``` 

![Screenshot 2023-06-26 173948](https://github.com/rnmapbox/maps/assets/26629776/9f7166d0-8235-4c43-96fa-9a83251f32a0)
![Screenshot 2023-06-26 173920](https://github.com/rnmapbox/maps/assets/26629776/b7e055b0-79f6-4b7f-938b-18ba31b41d95)

**Comment by cmaart** [comment]
Anyone solved this? Same error happening to me
