### ISSUE TITLE
[Bug]: MapboxGl.Images not loading in Android only

### ISSUE THREAD

**Issue by sabarikobagapau** [rnmapbox/maps#2939]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.8

### Standalone component to reproduce

```javascript
import React from 'react';
import MapboxGL from '@rnmapbox/maps'



class BugReportExample extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
    mapBoxsource:[{
                                type: 'Feature',
                                geometry: {
                                  type: 'Point',
                                  coordinates: [80.234,87.8888]
                                },
                                properties: {
                                  id: 'a',
                                  markerImage: 'https://reactnative.dev/img/tiny_logo.png',
                                  data: 'sampleData',
                                },
                              }]
                          }}
  render() {
    return (
  <MapboxGL.MapView style={{flex:1}}
                styleURL={this.state.customMapStyle === '' || this.state.customMapStyle === ' ' ? MapboxGL.StyleURL.Satellite : this.state.customMapStyle}
                logoEnabled={false}
                onDidFinishLoadingMap={this.onDidFinishLoadingStyle}
                scaleBarEnabled ={false}
                attributionEnabled = {false}
              >
            <MapboxGL.Camera
            container= 'map'
            zoomLevel={this.state.mapZoomLevel}
            styleURL={MapboxGL.StyleURL.Satellite}
            animationMode='moveTo'
            centerCoordinate={this.state.coords}
                        />
             {this.state.mapBoxsource &&
              this.state.mapBoxsource.length > 0 && (
                <MapboxGL.Images
                  images={this.state.images}
                  onImageMissing={(url) => {
                    this.setState({
                      images: {
                        ...this.state.images,
                        [url]: { uri: url },
                      },
                    })
                  }}
                />
                          )}
                        {this.state.mapBoxsource &&
              this.state.mapBoxsource.length > 0 && (
                <MapboxGL.ShapeSource
                  id={'allLightMarkers'}
                  shape={{
                    type: 'FeatureCollection',
                    features: this.state.mapBoxsource,
                  }}
                  onPress={(e) => {
                    this.navigateAssetdetailScreen(e)
                  }}
                >
                  <MapboxGL.SymbolLayer
                    id="markersLevel1"
                    style={{
                      iconImage: ['get', 'markerImage'],
                      iconSize: 1.0,
                      iconAllowOverlap: true,
                    }}
                  />
                </MapboxGL.ShapeSource>
              )} 
              </MapboxGL.MapView>    );
  }
}
```

### Observed behavior and steps to reproduce

Loading perfectly in IOS but  not in Android local image fine but i want to work in url images also above mapboxsource is my sample data

**Comment by sabarikobagapau** [comment]
> ## Lint failed 😭
> Please fix the errors in your code example - [More info](https://github.com/rnmapbox/maps/wiki/ErrorInExamplesInIssue).:
> 
> ```
> error: 'item' is not defined (no-undef) at example.jsx:15:48:
>   13 |                                 geometry: {
>   14 |                                   type: 'Point',
> > 15 |                                   coordinates: item.geometry.coordinates,
>      |                                                ^
>   16 |                                 },
>   17 |                                 properties: {
>   18 |                                   id: 'a' + i,
> 
> 
> error: 'i' is not defined (no-undef) at example.jsx:18:45:
>   16 |                                 },
>   17 |                                 properties: {
> > 18 |                                   id: 'a' + i,
>      |                                             ^
>   19 |                                   markerImage: 'https://reactnative.dev/img/tiny_logo.png',
>   20 |                                   data: item,
>   21 |                                 },
> 
> 
> error: 'item' is not defined (no-undef) at example.jsx:20:41:
>   18 |                                   id: 'a' + i,
>   19 |                                   markerImage: 'https://reactnative.dev/img/tiny_logo.png',
> > 20 |                                   data: item,
>      |                                         ^
>   21 |                                 },
>   22 |                               }]
>   23 |                           }}
> 
> 
> 3 errors found.```
> ```

**Comment by mfazekas** [comment]
@sabarikobagapau  thank much for the bug report. I'm getting the following error when running the example. Pls fix, so I can try to reproduce the issue.

![image](https://github.com/rnmapbox/maps/assets/52435/aa6528e2-e1a7-47e1-87a0-30cc6b03f0b6)

**Comment by brdar** [comment]
Try setting scale=1
https://github.com/rnmapbox/maps/pull/2928

**Comment by sabarikobagapau** [comment]
Hi @brdar please help i am unable load huge assets with url please provide sample example above working fine in ios not in android please provide full example with huge assets loading like 3k to 5k

**Comment by mfazekas** [comment]
https://github.com/rnmapbox/maps/pull/2928 was fixed, and I cannot run this component to verify that this was the same issue or not. So closing this.
