### ISSUE TITLE
[Bug]: logs for existing and non existing id not found misleading - ShapeSource|UserLocation on style change

### ISSUE THREAD

**Issue by FrederickEngelhardt** [rnmapbox/maps#2944]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.14.0

### Platform

iOS

### `@rnmapbox/maps` version

10.0.9-rc.1

### Standalone component to reproduce

```typescript
import React, { useMemo, useState } from 'react'
import { View, TouchableOpacity, Text } from 'react-native'
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
  StyleURL,
  UserLocation,
} from '@rnmapbox/maps'
const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
}

const styles = [StyleURL.Dark, StyleURL.Light]
const SourceIdIssuesIOS = () => {
  const [mapboxStyleIndex, setMapboxStyleIndex] = useState(0)

  const selectedStyle = useMemo(
    () => styles[mapboxStyleIndex],
    [mapboxStyleIndex],
  )

  const incrementStyle = () => {
    let nextIndex = mapboxStyleIndex + 1

    if (nextIndex >= styles.length) {
      nextIndex = 0
    }

    setMapboxStyleIndex(nextIndex)
  }

  return (
    <View style={{ flex: 1 }}>
      <MapView styleJSON={selectedStyle} style={{ flex: 1 }}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id='idStreetLayer' shape={aLine} existing={false}>
          <LineLayer id='idStreetLayer' existing={true} />
        </ShapeSource>
        <UserLocation />
      </MapView>
      <TouchableOpacity
        style={{
          position: 'absolute',
          right: 50,
          top: 50,
          width: 100,
          height: 100,
          borderRadius: 50,
          backgroundColor: 'orange',
          alignItems: 'center',
          justifyContent: 'center',
        }}
        onPress={() => incrementStyle()}
      >
        <Text>Swap Style</Text>
      </TouchableOpacity>
    </View>
  )
}

export default SourceIdIssuesIOS
```

### Observed behavior and steps to reproduce

You will need to enable location permissions to test the locations component.

1. Load the map. (Add token etc).
2. Click the large orange button
3. see the logs message output.

Example
```
 WARN  Mapbox warning Warning source with id:idStreetLayer referred to existing source but `existing` attibute was missing. https://github.com/rnmapbox/maps/wiki/Deprecated-ExistingSourceLayer {"level": "warning", "message": "Warning source with id:idStreetLayer referred to existing source but `existing` attibute was missing. https://github.com/rnmapbox/maps/wiki/Deprecated-ExistingSourceLayer"}
 WARN  Mapbox warning Warning source with id:mapboxUserLocation referred to existing source but `existing` attibute was missing. https://github.com/rnmapbox/maps/wiki/Deprecated-ExistingSourceLayer {"level": "warning", "message": "Warning source with id:mapboxUserLocation referred to existing source but `existing` attibute was missing. https://github.com/rnmapbox/maps/wiki/Deprecated-ExistingSourceLayer"}
```

iOS will spam the Logger with warnings about shape sources and UserLocation ids not having the correct properties

- If the `existing` property is `true` it will warn it cannot find the property
- if the `existing` property is `false` it will still warn that the key is not set and it's looking for a value.

FYI this issue is **per source** so if you have defined a bunch of layers you will most likely will only trigger the error per source id you reference. If you have duplicate layers it will not trigger the same log for that id.

Current log workarounds:
- Look at a solution using https://github.com/rnmapbox/maps/blob/main/docs/Logger.md
- Silence all logs `LogBox.ignoreAllLogs()`
- Remove the native code on iOS that fires off all these logs

Section that is causing issues + patch to remove it.
node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLSource.swift
```diff
--- a/node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLSource.swift
+++ b/node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLSource.swift
@@ -71,14 +71,8 @@ class RCTMGLSource : RCTMGLInteractiveElement {
     self.map = map
 
     if style.sourceExists(withId: self.id) {
-      if (!existing) {
-        Logger.log(level: .warn, message: "Warning source with id:\(optional: id) referred to existing source but `existing` attibute was missing. https://github.com/rnmapbox/maps/wiki/Deprecated-ExistingSourceLayer")
-      }
       self.source = try! style.source(withId: self.id)
     } else {
-      if (existing) {
-        Logger.log(level: .warn, message: "Warning source with id:\(optional: id) marked as existing, but could not find in style, source identifiers: \(style.allSourceIdentifiers.map { [$0.id, $0.type.rawValue] })")
-      }
       let source = self.makeSource()
       self.ownsSource = true
       self.source = source

```

### Expected behavior

ShapeSource and UserLocation when re-rendering do not trigger any warnings when existing is false on the shapesource and the shapelayer is set as false

Setting the value to existing={false} should hide all these logs.

There should be an option to silence these logs with a filter. These logs show up right at the bottom of the screen making it hard to test buttons that are near the logbox area that trigger re-renders for layers with `id` values.

### Notes / preliminary analysis

Looks like this is only an iOS issue for now. Android seems to not show any logs when re-rendering sources or layers with ids.

**Comment by mfazekas** [comment]
@FrederickEngelhardt thanks much for the bug report, the root of the issue was that on style change sources were readedded twice once from here:
https://github.com/rnmapbox/maps/blob/6f2c74e803bb88c373ca7ba8644e7aeccbe5e60f/ios/RCTMGL-v10/RCTMGLMapView.swift#L355-L357

and once from here:
https://github.com/rnmapbox/maps/blob/6f2c74e803bb88c373ca7ba8644e7aeccbe5e60f/ios/RCTMGL-v10/RCTMGLMapView.swift#L559-L562

I've fixed this by using the same thing we do on android, we only have a single features array and we add stuff from there if it's not already added.
