### ISSUE TITLE
[Bug][Reopen]: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)

### ISSUE THREAD

**Issue by brdar** [rnmapbox/maps#2952]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.9-rc.1

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
Images
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <Images nativeAssetImages={[{name: 'point'}]} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

add png image `point.png` to android `res/drawable` directory and reference it with images.
Image usage (rendering) is not required, loading source alone causes the crash.

Tested on emulators: "pixel_3a_API_34_extension_level_7_arm64-v8a" and on API_33

Please refer to this closed issue:
https://github.com/rnmapbox/maps/issues/2948

### Expected behavior

Icons should be rendered without crash.

We hold our images as native resources and reference them using URI.
This used to work before `@react-native-mapbox-gl/maps": "^8.6.0-beta.0`

### Notes / preliminary analysis

If image sources are are added like this:
`<Images nativeAssetImages={['point']} />`
image gets loaded but colors are inconsistent, sometimes with black background, sometimes look fine...

### Additional links and references

Please refer ti this closed issue:
https://github.com/rnmapbox/maps/issues/2948

**Comment by brdar** [comment]
See this pr, setting scale=1 seems to resolve crash.
https://github.com/rnmapbox/maps/pull/2928

**Comment by mfazekas** [comment]
Thanks much I could reproduce
