### ISSUE TITLE
Development build for iOS simulator fails with expo app on apple silicon mac

### ISSUE THREAD

**Issue by philiplindberg** [rnmapbox/maps#2956]
When trying to run an expo app on the iOS simulator with `@rnmapbox/maps` installed (and the associated expo config plugin configured), the build fails with a `no such module 'ExpoModulesCore'` error.

I believe this is because the expo config plugin sets `arm64` as an excluded architecture (in [maps/plugin/src/withMapbox.ts](https://github.com/rnmapbox/maps/blob/685e5361008bcd3ed209720323244c83b58df8ee/plugin/src/withMapbox.ts#L201)), which makes development builds for the simulator fail on apple silicon macs (documented in [this issue](https://github.com/facebook/react-native/issues/32704#issuecomment-1174458011)). Development builds seem to work fine on physical iOS devices, and production builds seem to work for both the simulator and physical iOS devices.

## Environment
- Dev OS: macOS 13.4.1
- Xcode: 14.3.1

## Steps to reproduce
```sh
git clone https://github.com/philiplindberg/rnmapbox-repro
cd rnmapbox-repro
# replace MAPBOX_DOWNLOAD_TOKEN in app.json with valid mapbox download token
# replace MAPBOX_ACCESS_TOKEN in App.tsx with valid mapbox access token
yarn
yarn ios
```

Results in xcodebuild error: `no such module 'ExpoModulesCore'`

## Component to reproduce
```ts
import React from 'react'
import Mapbox, { MapView } from '@rnmapbox/maps'

Mapbox.setAccessToken('MAPBOX_ACCESS_TOKEN')

export default function App() {
  return (
    <MapView style={{ flex: 1 }} />
  )
}
```

## Workaround
My current workaround is to patch `maps/plugin/build/withMapbox.js` as follows:

```
diff --git a/plugin/build/withMapbox.js b/plugin/build/withMapbox.js
index 07d50e3208c4b2391ad8bc10346f9b5d42316f75..5fb51dfdda4f94530e28d601c32045529a875d57 100644
--- a/plugin/build/withMapbox.js
+++ b/plugin/build/withMapbox.js
@@ -269,7 +269,7 @@ const withMapboxAndroid = (config, { RNMapboxMapsImpl, RNMapboxMapsDownloadToken
     return config;
 };
 const withMapbox = (config, { RNMapboxMapsImpl, RNMapboxMapsVersion, RNMapboxMapsDownloadToken }) => {
-    config = withExcludedSimulatorArchitectures(config);
+    // config = withExcludedSimulatorArchitectures(config);
     config = withMapboxAndroid(config, {
         RNMapboxMapsImpl,
         RNMapboxMapsVersion,
```

**Comment by mfazekas** [comment]
@philiplindberg thank much I guess we can remove that part from the expo plugin. It was added with: https://github.com/rnmapbox/maps/pull/1490

@KiwiKilian what do you think?

**Comment by KiwiKilian** [comment]
I'm on vacation for at least another week and can't confirm. But we definitely made dev builds on Apple Silicon and ran in the simulator.
