### ISSUE TITLE
[Bug]: Android Error including RasterSource from GeoServer with credentials

### ISSUE THREAD

**Issue by PentamapFlorian** [rnmapbox/maps#2957]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.9-rc.1

### Standalone component to reproduce

```javascript
import React from 'react';
import Mapbox from '@rnmapbox/maps';

const Map = () => {

  return (

      <Mapbox.MapView 
        styleURL={"myStyleURL"}
        style={{
          flex:1,
        }}
      >
          <Mapbox.RasterSource 
              id="id"
              name="name"
              tileUrlTemplates={["https://username:password@mygeoserver.com/myWorkspace/wms?service=WMS&version=1.1.0&request=GetMap&layers=myWorkspace%3AmyLayer&bbox={bbox-epsg-3857}&width=512&height=512&srs=EPSG:3857&styles=&format=image/png&transparent=true"]}
              tileSize={256}
          >
            <Mapbox.RasterLayer
              id="baseLayer"
            />
          </Mapbox.RasterSource>
        
      </Mapbox.MapView>

  );
}

export default Map
```

### Observed behavior and steps to reproduce

I try to include a RasterLayer with RasterSource from GeoServer. It is working as expected when I remove "username:password@" from my url and do not restrict GeoServer access. However that is not an option for me. 

The restricted layer returns following error:
E  'Mapbox error', 'Map load failed: {tile-id={x=139, y=89, z=8}, type=tile, message=Failed to load tile: HTTP status code 401, begin=36147304550, source-id=at}', { level: 'error',
                                                                                                      tag: 'RCTMGLMapView',
                                                                                                      message: 'Map load failed: {tile-id={x=139, y=89, z=8}, type=tile, message=Failed to load tile: HTTP status code 401, begin=36147304550, source-id=id}' }

It works as expected on iOS devices.

### Expected behavior

WMS TileLayer shows up on mapbox map.

### Notes / preliminary analysis

I tried to include a transformRequest to Mapbox.Map without success. Propably a configuration issue.

 transformRequest={(url, resourceType) => {
          if (resourceType === 'Source' && url.startsWith('https://username:password')) {
            return {
              url: url,
              //headers: { 'Authorization': 'username:password' }
              credentials: 'username:password'
            }
          }
        }}

**Comment by mfazekas** [comment]
@PentamapFlorian thanks for the report. Unfortunately we cannot accept bug reports that doesn't contain standalone component to reproduce the issue. Yours has placeholder in styleURL and username/password. Sorry we don't offer free [support](https://github.com/rnmapbox/maps/wiki/Support) for this package. 

I don't think we have `trasformRequest`, we do have `CustomHttpHeaders` but I'm don't think that covers your usecase as that adds headers to every request.
