### ISSUE TITLE
[Bug]: Camera followUserLocation={true} possible interaction with UserLocation at app start 

### ISSUE THREAD

**Issue by Tiropz** [rnmapbox/maps#2980]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.10

### Standalone component to reproduce

```javascript
import React, {
  useState, useRef
} from 'react';
import Mapbox, { MarkerView, PointAnnotation, UserLocationRenderMode, UserTrackingMode, ShapeSource, Images, LineLayer, ImageSource, UserLocation, MapView, MapState, Camera } from '@rnmapbox/maps';
import { StyleSheet } from 'react-native';



const Bug = () => {


  const camera = useRef<Camera>(null);
  const map = useRef<MapView>(null);
  const [followingUser, setFollowingUser] = useState(true);
  const [customStyle, setCustomStyle] = useState(`mapbox://styles/tiropz/clgvdgisx007g01quecyz9yb1?fresh=true&t=${new Date().getTime()}`); // THIS STYLE IS THE STANDARD STREET STYLE
  const [zoom, setZoom] = useState(17);

  const onCameraChanged = async () => {
    const currentZoom = await map.current?.getZoom();
    if (currentZoom != zoom) {
      setZoom(currentZoom)
    }
  }

    return (
      <Mapbox.MapView
        ref={map}
        styleURL={customStyle}
        style={styles.mapContainer}
        scaleBarEnabled={false}
        logoEnabled={false}
        compassEnabled={true}
        compassFadeWhenNorth={false}
        onDidFinishLoadingStyle={() => console.log("loaded style")}
        onMapIdle={() => console.log("IDDDDLEE")}
        onDidFinishLoadingMap={() => console.log("finish")}
        attributionEnabled={false}
        onCameraChanged={onCameraChanged}
      >
        <Camera ref={camera}
          followUserLocation={followingUser}
          followUserMode={UserTrackingMode.Follow}
          animationMode={'flyTo'}
          followZoomLevel={17}
        />
        <UserLocation
          androidRenderMode={'gps'}
          renderMode={UserLocationRenderMode.Normal}
          showsUserHeadingIndicator={true}
          visible={true}
          onUpdate={() => console.log("render")}
          requestsAlwaysUse={true}
          minDisplacement={3}
          animated={true}
        />
      </Mapbox.MapView>
    );
  }

const styles = StyleSheet.create({
  mapContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
});

export default Bug;
```

### Observed behavior and steps to reproduce

The map will load and I can move it around and the UserLocation is displayed correctly but the Camera won't be centered on the user position and be center on some random point in Africa ( (0,0) maybe ?). Then the UserLocation will update, calling onUpdate, and the camera will then be centered on the user. Sometimes this flow can take up to 1 min or more.

Link to a video that I hope you can access, showing the issue :
https://github.com/Tiropz/Tiropz/blob/main/363439962_6464920006907379_8923571196012967067_n.mp4

@mfazekas suggested that this behaviour may come from the delay to get the first gps position but in the logs i can see the following pattern : 
```
LOG  render
 LOG  render
 LOG  loaded style
 LOG  finish
 LOG  IDDDDLEE
 LOG  render
 LOG  IDDDDLEE
```
which indicates that the userlocation is updated early on. Note that after the sequence : IDDDDLEE, render, IDDDDLEE the view centers on the user as expected

### Expected behavior

The expected behaviour is to have the camera be centered on user location when the map finishes loading, or to take a finite amount of time but not up to several minutes.

### Notes / preliminary analysis

If I remove the UserLocation element, I do not have this problem anymore. The camera will be centered on the user coordinates and follow the user but the userlocation won't be displayed anymore : https://github.com/Tiropz/Tiropz/blob/main/363446150_6014967741942168_3887937087368391008_n.mp4

If I set followingUser to false, it will juste show me the whole globe, with the UserLocation still being displayed correctly of course.

The current found workaround which supports my hypothesis that this is not a GPS issue is that the following workaround works : 

 ```
const [showUser, setShowUser] = useState(false); 

<Mapbox.MapView
        ref={map}
        styleURL={customStyle}
        style={styles.mapContainer}
        onMapIdle={() => {
          setShowUser(true);
      }}
      >
     <Camera ref={camera}
          followUserLocation={followingUser}
          followUserMode={UserTrackingMode.Follow}
          animationMode={'flyTo'}
          followZoomLevel={17}
        />
     {showUser && (<UserLocation
          androidRenderMode={'gps'}
          renderMode={UserLocationRenderMode.Normal}
          showsUserHeadingIndicator={true}
          visible={true}
          onUpdate={() => console.log("render")}
          requestsAlwaysUse={true}
          minDisplacement={3}
          animated={true}
        />)}

</MarkerView>
```

This is my first ever GitHub Bug report so if something is not clear or up to any standards, please inform me and I will adapt. 

Thank you for your time 

### Additional links and references

/

**Comment by mfazekas** [comment]
Have you tried the code you've posted in your example? It's having hooks outside of a functional component, so I don't think you've tried it.
Please note that I'm mostly spending my free time on this project, and I'd appreciate if you'd post code example that you've tried before posting, thanks for the understanding.

```
 ERROR  Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem., js engine: hermes

```

**Comment by Tiropz** [comment]
> Have you tried the code you've posted in your example? It's having hooks outside of a functional component, so I don't think you've tried it. Please note that I'm mostly spending my free time on this project, and I'd appreciate if you'd post code example that you've tried before posting, thanks for the understanding.
> 
> ```
>  ERROR  Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem., js engine: hermes
> ```

Sorry for that ! I was trying to make it fit the template and correct the errors pointed out by the bot, but I didn't tried it in a new file. The code that I've posted now has been tested in a standalone .tsx file. 
Again sorry for the mistake I'm still learning how to do bug reports and thank you for your time

**Comment by mfazekas** [comment]
@Tiropz thanks much for the updated component I was able to reproduce the issue, the only change I've needed is use a standard style url, as I do not have permission to read yours. 

I've submitted a PR for iOS.

```tsx
import React, { useState, useRef } from 'react';
import Mapbox, {
  MarkerView,
  PointAnnotation,
  UserLocationRenderMode,
  UserTrackingMode,
  ShapeSource,
  Images,
  LineLayer,
  ImageSource,
  UserLocation,
  MapView,
  MapState,
  Camera,
} from '@rnmapbox/maps';
import { StyleSheet } from 'react-native';

const Bug = () => {
  const camera = useRef<Camera>(null);
  const map = useRef<MapView>(null);
  const [followingUser, setFollowingUser] = useState(true);
  const [customStyle, setCustomStyle] = useState(
    `mapbox://styles/mapbox/streets-v12?fresh=true&t=${new Date().getTime()}`,
  ); // THIS STYLE IS THE STANDARD STREET STYLE
  const [zoom, setZoom] = useState(17);

  const onCameraChanged = async () => {
    const currentZoom = await map.current?.getZoom();
    if (currentZoom != zoom) {
      setZoom(currentZoom);
    }
  };

  return (
    <Mapbox.MapView
      ref={map}
      styleURL={customStyle}
      style={styles.mapContainer}
      scaleBarEnabled={false}
      logoEnabled={false}
      compassEnabled={true}
      compassFadeWhenNorth={false}
      onDidFinishLoadingStyle={() => console.log('loaded style')}
      onMapIdle={() => console.log('IDDDDLEE')}
      onDidFinishLoadingMap={() => console.log('finish')}
      attributionEnabled={false}
      onCameraChanged={onCameraChanged}
    >
      <Camera
        ref={camera}
        followUserLocation={followingUser}
        followUserMode={UserTrackingMode.Follow}
        animationMode={'flyTo'}
        followZoomLevel={17}
      />
      {false && <UserLocation renderMode={UserLocationRenderMode.Native} />}
      {true && (
        <UserLocation
          androidRenderMode={'gps'}
          renderMode={UserLocationRenderMode.Normal}
          showsUserHeadingIndicator={true}
          visible={true}
          onUpdate={() => console.log('on update')}
          requestsAlwaysUse={true}
          minDisplacement={3}
          animated={true}
        />
      )}
    </Mapbox.MapView>
  );
};

const styles = StyleSheet.create({
  mapContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
});

export default Bug;
```

**Comment by mfazekas** [comment]
Not sure if this is still an issue pls try with 10.1

**Comment by Tiropz** [comment]
> Not sure if this is still an issue pls try with 10.1

Hello @mfazekas, I have upgraded to 10.1 and i'm not facing the issue right now. Thank you

**Comment by FrancMihani** [comment]
Still the same issue, is there any workaround?
