### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token, expected ',' in @rnmapbox/maps module's Mapbox.ts

### ISSUE THREAD

**Issue by orlenko-dmitry** [rnmapbox/maps#2998]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.0.11

### Platform

Android

### `@rnmapbox/maps` version

10.0.11

### Standalone component to reproduce

```javascript
import React from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

Mapbox.setAccessToken('<YOUR_ACCESSTOKEN>');

const App = () => {
  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <Mapbox.MapView style={styles.map} />
      </View>
    </View>
  );
}

export default App;

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    height: 300,
    width: 300,
  },
  map: {
    flex: 1
  }
});
```

### Observed behavior and steps to reproduce

SyntaxError: C:\WORK\plotlot\plotlot-25398\android\node_modules\@rnmapbox\maps\src\Mapbox.ts: Unexpected token, expected "," (5:7)

  3 |   Camera,
  4 |   UserTrackingMode,
> 5 |   type CameraPadding,
    |        ^
  6 |   type CameraAnimationMode,
  7 |   type CameraBounds,
  8 | } from './components/Camera';

### Additional links and references

With the same issue has faced here in the article: [https://stackoverflow.com/questions/76782028/syntaxerror-unexpected-token-expected-in-rnmapbox-maps-modules-mapbox-ts](url)

**Comment by mfazekas** [comment]
I'm sorry but this an issue tracker and your submission sound more like a question. Gitter or StackOverflow might be a better place to ask such questions.  

This looks like a setup issue, but you've not included steps to reproduce, from `react-native init`. If you fail to reproduce in a new project then compare the new project with your project setup.

Please understand that the project is run by volunteers in their own free time, and we need to focus our attention to be able to move forward.
