### ISSUE TITLE
[Bug]: SyntaxError in Mapbox.ts

### ISSUE THREAD

**Issue by brankoEISI** [rnmapbox/maps#3003]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

```javascript
import React from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

Mapbox.setAccessToken('<YOUR_ACCESSTOKEN>');

const App = () => {
  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <Mapbox.MapView style={styles.map} />
      </View>
    </View>
  );
}

export default App;

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    height: 300,
    width: 300,
  },
  map: {
    flex: 1
  }
});
```

### Observed behavior and steps to reproduce

<img width="567" alt="Screenshot 2023-08-17 at 2 14 05 PM" src="https://github.com/rnmapbox/maps/assets/9456563/b94d5efe-e389-4175-95d1-38cdc150d21c">

### Additional links and references

Issue also noted by this StackOverflow user https://stackoverflow.com/questions/76782028/syntaxerror-unexpected-token-expected-in-rnmapbox-maps-modules-mapbox-ts

**Comment by sahil16r** [comment]
@brankoEISI I'm facing the same issue...

**Comment by mfazekas** [comment]
Something is wrong in you setup, most likely old rn version, and you need to update babel presets to support typescript. 

See: #2998, #2423

https://github.com/rnmapbox/maps/issues/2423#issuecomment-1342579105

**Comment by sahil16r** [comment]
@mfazekas I have made the suggested changes but now I'm getting a different error

`"dependencies": {
    "@rnmapbox/maps": "^10.0.15",
    "react": "17.0.2",
    "react-native": "0.65.1",
  },
  "devDependencies": {
    "@babel/core": "^7.17.9",
    "@babel/preset-typescript": "^7.17.9",
    "@babel/runtime": "^7.17.9",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "^27.5.1",
  }`
  
  
![Screenshot_1697706613](https://github.com/rnmapbox/maps/assets/131645484/5e66dd5f-f608-4bc1-b7aa-eda733363497)
