### ISSUE TITLE
[Bug]: inconsistent iconSize between iOS and Android

### ISSUE THREAD

**Issue by paulschreiber** [rnmapbox/maps#3009]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.11

### Standalone component to reproduce

```js
import React from 'react';
import {
  Images,
  MapView,
  ShapeSource,
  SymbolLayer,
  Camera,
} from '@rnmapbox/maps';

const styles = {
  mapView: { flex: 1 },
  iconLayer: {
    iconSize: 3.0,
    iconImage: 'example'
  },
};

const features = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: 'a-feature',
      geometry: {
        type: 'Point',
        coordinates: [-74.00597, 40.71427],
      },
    },
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={styles.mapView}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <Images images={{ example: require('../assets/example.png') }} />
        <ShapeSource id={'shape-source-id-0'} shape={features}>
          <SymbolLayer
            id="symbol-id"
            style={styles.iconLayer}
          />
        </ShapeSource>
      </MapView>
    );
  }
}

export default BugReportExample;
```

### Observed behavior and steps to reproduce

Images on iOS are are ≈2.5x larger than on Android:
<img width="677" alt="image" src="https://github.com/rnmapbox/maps/assets/86784/8015ee6c-07bb-4fe2-8813-18c9732fe00a">

<img width="561" alt="image" src="https://github.com/rnmapbox/maps/assets/86784/cc20ba49-3c89-4656-a7b5-55e212159428">

### Expected behavior

Same size on both device types.

### Notes / preliminary analysis

React 18.2.0
React Native 0.72.4
@rnmapbox/maps 10.0.11

### Additional links and references

Previous related bug: https://github.com/rnmapbox/maps/issues/68

**Comment by shrouxm** [comment]
note from paul's teammate: we haven't been able to determine yet whether this is a bug in our code which generates the icon image per platform, or a bug in rnmapbox's icon scaling, so if this can't be reproduced it should be safe to close out

**Comment by andrei-tofan** [comment]
We are having the same problem, please write an update if it was a bug in your code.

**Comment by shrouxm** [comment]
update: current best guess is that it is due to `rnmapbox` ignoring the `scale` attribute of `ImageURISource`s passed into `Mapbox.Images`'s `images` argument on Android only. in our case we couldn't avoid using the `scale` attribute due to the way our vector icon library generates images, so we are trying to work around by multiplying the size of the icon on Android only by `PixelRatio.get()`. will update again if this resolves on all platforms once it gets pushed to more users' devices.

**Comment by JasonSanford** [comment]
I'm seeing something similar, but with the built-in user heading icon. On iOS in the dev client the image is the proper size, but when built for production the image looks about 3x too big.

## Dev Client

![IMG_2503](https://github.com/rnmapbox/maps/assets/220341/6dff1569-81ac-4081-be9a-b22640efb6cd)

## Production Build

![IMG_2504](https://github.com/rnmapbox/maps/assets/220341/48597fed-0255-4c2c-a705-aefe98811a3c)

**Comment by Vednus** [comment]
It's really strange for me. Only certain icons are different sizes, some are rendered the same size regardless of platform. Tried resizing the inconsistent one, but didn't seem to resolve it.

**Comment by snazarkoo** [comment]
Hey, I think a potential fix could be done here [`android/src/main/java-v10/com/mapbox/rctmgl/components/images/RCTMGLImages.kt`](https://github.com/rnmapbox/maps/blob/0814c940b5324b323659ef103abd00267fa023fa/android/src/main/java/com/rnmapbox/rnmbx/components/images/RNMBXImages.kt#L37)
We might need to replace `(1.0/((160.0/bitmap.density)) * scale).toFloat()` , with `scale.toFloat`.  Tested it on 2 devices with different ratio sizes. Works well on my end

**Comment by mfazekas** [comment]
I think those are the factors:
1.) Image DPI (a 200x200 image with 144 DPI should be half the size on the map than a 200x200 image with 77 DPI)
2.) Screen scaling (I think this mostly affects android). Device density can go from 160 DPI/MDPI => XXXHDPI aka 640DPI)
3.) Debug/release version, in debug version the image is coming from metro bundler and I think it's an url, wile in release it's from the disk, and has different structure.

**Comment by snazarkoo** [comment]
Thanks, as I understood, in your fixes for old versions the scale is passed directly to sdk methods without modifying. So what scale RN picks depends on what is available in file system (@, @2x, @3x), that image will be created. 

In release mode, the asset looks like this
`{ NativeMap: {"__packager_asset":true,"width":29,"uri":"packages_native_src_assets_map_route_bridge_unsafe","height":29,"scale":2} }`

Hence, in both cases (debug, prod) the scale property is available and the value is the same. And it's correct as on my device pixelRatio is 1.5 and the image was picked @2x.

**Comment by mfazekas** [comment]
So I've tried the example in the bug report, and for me it was the same size.

![image](https://github.com/rnmapbox/maps/assets/52435/a658ff09-5724-4bdf-ac09-3ff9f4764fd3)

![image](https://github.com/rnmapbox/maps/assets/52435/59600d6a-2213-4885-b304-ab96a626d7dd)

This was in debug build and using the example in the example repo:

![](https://github.com/rnmapbox/maps/blob/main/example/src/assets/example.png)

**Comment by mfazekas** [comment]
So if anyone have issue with icon size, please write a clear description:
1.) Prod or Debug version
2.) Exact image (was it a multi scale image with `@2x etc version)
3.) Exact images declaration (was scale property used?)
4.) Android device denisity

Screenshots on both platform.


Ideally you can also add a circle layer above the icons, to see how it compares with the desired size:

With the example.png as it's 44x44 pixel sized. 

I've just added a CircleLayer to verify it's correct size on both platforms:

```jsx
        <ShapeSource id={'shape-source-id-0'} shape={features}>
          <SymbolLayer id="symbol-id" style={styles.iconLayer} />
          <CircleLayer
            id="circel-layer"
            style={{
              circleRadius: 3 * (44.0 / 2),
              circleOpacity: 0.4,
              circleStrokeColor: 'green',
              circleStrokeWidth: 2,
            }}
          />
        </ShapeSource>
```

android:
![image](https://github.com/rnmapbox/maps/assets/52435/ef3f5712-3f99-47e1-bf91-2060c1a1e9b8)

iOS:
![image](https://github.com/rnmapbox/maps/assets/52435/8eaa752d-4cad-4dd7-a294-f3b7b9d59538)

**Comment by mfazekas** [comment]
The issues should have been fixed `10.1.0-beta.10`, can you pls confirm?

**Comment by snazarkoo** [comment]
Thanks @mfazekas. It works as expected in debug, but not in prod
1. Device density 1.5;
2. Image for testing scale-test-icon. It should be an image with different resolutions @2, @3 in assets folder.

Note: The size of image looks the same as with this workaround https://github.com/rnmapbox/maps/issues/3009#issuecomment-1739935698

Prod
![Screenshot 2023-10-12 at 13 04 44](https://github.com/rnmapbox/maps/assets/10786814/741053d2-3d9c-4399-b859-cf407032fdcd)
Debug
![Screenshot 2023-10-12 at 13 05 03](https://github.com/rnmapbox/maps/assets/10786814/a5a88ff6-bfc3-49e0-91ce-5c64f695e9bc)

**Comment by mfazekas** [comment]
@snazarkoo can you test `10.1.0-beta.11` the production now uses the same Fresco pipeline for prod as used for debug

**Comment by orca-nazar** [comment]
@mfazekas Perfect, icons are properly sized. Thanks for your work

**Comment by Noitham** [comment]
Hello, I'm having this exact issue, but the other way around. 
The icons look oversized on the iOS production builds only.
Using - `"@rnmapbox/maps": "10.1.3"`.

**Comment by Noitham** [comment]
Hey @JasonSanford , did you find a solution for your issue?

I'm still experiencing the issue on version "10.1.3" (magnified HeadingIcon & some SymbolLayers).
