### ISSUE TITLE
[Bug]:  fatal error: module map file '/Users/g2g/Library/Developer/Xcode/DerivedData/G2G-czvkihrnjujimzfgabajunpbjfrn/Build/Products/Debug-iphonesimulator/rnmapbox-maps/rnmapbox_maps.modulemap' not found

### ISSUE THREAD

**Issue by bilalyaqoob** [rnmapbox/maps#3043]
### Mapbox Implementation

Mapbox

### Mapbox Version

*

### Platform

iOS

### `@rnmapbox/maps` version

10.0.4

### Standalone component to reproduce

I tried to build the project on mac m1  and it is not building the project but on mac air 2019 it is building successfully without any error.

**Macbook on which it is running**
```
System:    OS: macOS 13.0.1     Shell: 5.8.1 - /bin/zsh  Binaries:    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node    Yarn: 3.3.0 - /usr/local/bin/yarn    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm    Watchman: 2022.12.12.00 - /usr/local/bin/watchman  Managers:    CocoaPods: 1.11.3 - /Users/macbookair2019/.rbenv/shims/pod  SDKs:    iOS SDK:      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1    Android SDK: Not Found  IDEs:    Android Studio: 2021.3 AI-213.7172.25.2113.9123335    Xcode: 14.2/14C18 - /usr/bin/xcodebuild  Languages:    Java: 11.0.18 - /usr/bin/javac    Python: Not Found  npmPackages:    @react-native-community/cli: Not Found    react: 16.13.1 => 16.13.1     react-native: 0.63.5 => 0.63.5     react-native-macos: Not Found  npmGlobalPackages:    react-native: Not Found
```

### Observed behavior and steps to reproduce

*

### Expected behavior

have to run on macbook m1

### Notes / preliminary analysis

*

### Additional links and references

*

**Comment by mfazekas** [comment]
The project does build on ARM machines as well. Have you tried a new rn project, from `react-native init` etc.

**Comment by bilalyaqoob** [comment]
yes i built a new project and it worked.
