### ISSUE TITLE
Mapbox styles When i add custom style url it give blank screen on borders of custom style url

### ISSUE THREAD

**Issue by sabarikobagapau** [rnmapbox/maps#3078]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.15

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView  style={{flex: 1}}
              styleURL= {'mapbox://styles/*********************'}

>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

![Screenshot 2023-09-27 at 10 35 33 AM](https://github.com/rnmapbox/maps/assets/96055758/42f304ee-ead5-4f67-bd48-f477a664e06c)
![Screenshot 2023-09-27 at 10 35 21 AM](https://github.com/rnmapbox/maps/assets/96055758/1a2e061c-c598-4116-8814-c1607630c521)

### Expected behavior

when i use satelite style its working fine but i use default style url it renders like above screen shote both platforms and tested  it physical devices also please help

**Comment by mfazekas** [comment]
Sorry we don't offer free [support](https://github.com/rnmapbox/maps/wiki/Support) for this package. I can't repro your issue, because you haven't included full style url. 

Try to look into the device logs, to see if there is any related mapbox lines.

**Comment by sabarikobagapau** [comment]
@mfazekas  hi this is log from device when i load it  comes **"Map load failed: {tile-id={x=383483, y=235906, z=19}, type=tile, message=Failed to load tile: Unable t
![Screenshot 2023-09-28 at 10 12 49 AM](https://github.com/rnmapbox/maps/assets/96055758/f9ff7704-cb5b-46f0-aca3-0407aeede2ab)
o resolve host "[api.mapbox.com](http://api.mapbox.com/)": No address associated with hostname, begin=595628096, source-id=mapbox://aerosimple.asim_20_g}"**

**Comment by sabarikobagapau** [comment]
Hi @mfazekas please help with this i debug it devices logs it comes like this. **"Map load failed: {tile-id={x=383483, y=235906, z=19}, type=tile, message=Failed to load tile: Unable to resolve host "[api.mapbox.com](http://api.mapbox.com/)": No address associated with hostname, begin=595628096, source-id=mapbox://*******.asim_20_g}"**
![Screenshot 2023-09-28 at 10 12 49 AM](https://github.com/rnmapbox/maps/assets/96055758/37320f32-b9e4-43d3-bd57-397f52a7aecf)

**Comment by mfazekas** [comment]
Seems to me an environment error not a mapbox one.  I usually see unable to resolve api.mapbox.com, when my laptop changed wifi and android emulator stuck with the old one. Restarting the machine helps in those cases.

**Comment by sabarikobagapau** [comment]
Hi @mfazekas when i use custom style url it occurs only otherwise woking fine in both environements

**Comment by sabarikobagapau** [comment]
mapbox://styles/aerosimple/clmyyud9802u301qu2yadcuco.  this is the mapstyle url
