### ISSUE TITLE
[Bug]: Project Fails to Load When Mapbox is imported Expo 49

### ISSUE THREAD

**Issue by AdzeB** [rnmapbox/maps#3106]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.15

### Standalone component to reproduce

```javascript
import React from 'react';
import Mapbox from "@rnmapbox/maps";

Mapbox.setAccessToken(
  "pk.-9g"
);

const Main = () => {
    return (
       <Mapbox.MapView style={{ flex: 1 }} />
    );
}
```

### Observed behavior and steps to reproduce

- Install the latest version of the library using bunx expo install @rnmapbox/maps
- Up the plugin in the `app.json` file
- Import library in my main.js file
- Updated My dev client version 
- `bun expo start --dev-client -c` to start my dev client
- It just stops running at the splash screen
- I get this error after
None of these files exist:
  * node_modules/@rnmapbox/maps/src/MGLModule(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  * node_modules/@rnmapbox/maps/src/MGLModule/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
> 1 | export * from './MGLModule';

### Expected behavior

- Should render the map view.

**Comment by mfazekas** [comment]
@AdzeB 

`node_modules/@rnmapbox/maps/src/MGLModule.ts` should be there. Also you'll need to rebuild with your client. 

I'm closing this as we don't have resources to provide free support.

**Comment by AdzeB** [comment]
I have rebuilt my dev client twice, trying for the 3rd time now.

**Comment by AdzeB** [comment]
Solved the issue. If you are using Bun, create a `bunfig.toml` file and set `install.peer = false`
