### ISSUE TITLE
[Bug]: Point annotations generating error in v11

### ISSUE THREAD

**Issue by balloman** [rnmapbox/maps#3121]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.0.0-beta.4

### Platform

iOS

### `@rnmapbox/maps` version

10.1.0-beta.11

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
  PointAnnotation
} from '@rnmapbox/maps';
import { View } from 'react-native';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <PointAnnotation id="someId" coordinate={[-74,40.71]}>
         <View style={{ backgroundColor: "red", width: 30, height: 30 }} />
        </PointAnnotation>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Using code like this generates the error `Mapbox error MapLoad error Source RNMBX-mapview-point-annotations_drag is not in style {"level": "error", "message": "MapLoad error Source RNMBX-mapview-point-annotations_drag is not in style"}`

### Expected behavior

There is no error.

### Notes / preliminary analysis

It seems additionally, that the onselect prop does not work also, at least I can't get it to respond to any touches at all. The new updates to v11 on iOS do mention the use of a new drag handler, so this might be the root of the issue.

### Additional links and references

https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Documentation.docc/Migrate%20to%20v11.md#24-map-content-gesture-system

**Comment by balloman** [comment]
Any updates?

**Comment by balloman** [comment]
@mfazekas Have you figured out anything? I've spent a few days investigating and haven't figured this error out

**Comment by mfazekas** [comment]
@balloman sorry didn't have time look. Sounds like an upstream issue

**Comment by mfazekas** [comment]
I've reported the error as https://github.com/mapbox/mapbox-maps-ios/issues/2058 to upstream, but could not reproduce in the native mapbox app.

**Comment by mfazekas** [comment]
Also https://github.com/mapbox/mapbox-maps-ios/issues/2059 that causes the issue with tap handlers

**Comment by Infinity1high** [comment]
Seems the issue still exists on ios in the last version 10.1.9.  using v11  `MapLoad error Source RNMBX-mapview-point-annotations_drag is not in style`

**Comment by Ritik5Prasad** [comment]
Any fixes ??

**Comment by valn1** [comment]
i tried the latest version and still does not fix the issue @mfazekas 
is there any patch we can apply to fix it temporarily?

**Comment by mfazekas** [comment]
@valn1 the bugreprot had two issues one the log issue was not fixed, the other unselect should be fixed. 

As a workaround for the log issue you should be able to filter this one out with Logging callbacks.

**Comment by talesborn** [comment]
Any news
I updated to the version released two days ago, but there is still no solution for this problem

**Comment by gabrielsalvi** [comment]
Any workaround on this problem?? I'm using the last released version

**Comment by markfaust123** [comment]
updates?

**Comment by RemiHin** [comment]
still running in to this issue, im on 10.1.18

**Comment by mfazekas** [comment]
Pls see https://github.com/rnmapbox/maps/issues/3121#issuecomment-1930752480

**Comment by number1hustler** [comment]
I am also seeing this issue
