### ISSUE TITLE
[Bug]: completedTileCount is not set in offlineManager

### ISSUE THREAD

**Issue by rebebop** [rnmapbox/maps#3143]
### Mapbox Implementation

Mapbox

### Mapbox Version

defualt

### Platform

iOS

### `@rnmapbox/maps` version

10.0.1

### Standalone component to reproduce

```javascript
// not relevant
```

### Observed behavior and steps to reproduce

You can try to get the `status.completedTileCount` (from type `OfflinePackStatus` when doing `createPack` but it is always undefined. I do not see it being set anywhere in the code, you can easily do a github search for `completedTileCount` and see that it is only ever defined in the `OfflinePackStatus` type or in examples.

### Expected behavior

The `completedTileCount` property to be set correctly

**Comment by tischenkoa** [comment]
completedTileCount is not set because are count on the number of **Tile Pack** in v10 (https://docs.mapbox.com/android/maps/guides/offline/#tile-store-disk-quota)
