### ISSUE TITLE
[Bug]: Getting blank map screen on IOS v10

### ISSUE THREAD

**Issue by danialseikh34** [rnmapbox/maps#3146]
### Mapbox Implementation

Mapbox

### Mapbox Version

mapbox

### Platform

iOS

### `@rnmapbox/maps` version

10.15.0

### Standalone component to reproduce

```
```
![maps-screen](https://github.com/rnmapbox/maps/assets/138012661/59c70cfc-f0de-4e00-9362-b04cb2cdfe2b)

### Observed behavior and steps to reproduce

After installation @rnmapbox/maps getting white screen instead of maps with this error [Mapbox] [Error, maps-ios/MapView]: No suitable Metal simulator can be found.

**Comment by conor909** [comment]
Same issue here, I've looked at the source code and the component doenst seem to do anything with the styleUrl prop

**Comment by danialseikh34** [comment]
Do you find any solution ?

**Comment by conor909** [comment]
The props get passed directly to a native component so I've no idea

**Comment by conor909** [comment]
@danialseikh34 did you set up an access token with `DOWNLOADS:READ` scope?

**Comment by danialseikh34** [comment]
yes

**Comment by conor909** [comment]
@danialseikh34 did you set it in the app.config plugins and use `mapbox` for `RNMapboxMapsImpl`?
```
      [
        '@rnmapbox/maps',
        {
          RNMapboxMapsImpl: 'mapbox',
          RNMapboxMapsDownloadToken: process.env.MAPBOX_SECRET_SCOPE_TOKEN
        }
      ]
```

**Comment by danialseikh34** [comment]
yes
