### ISSUE TITLE
[Bug]: followUserLocation is always true when onUserTrackingModeChange is called on iOS

### ISSUE THREAD

**Issue by andrei-tofan** [rnmapbox/maps#3154]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS

### `@rnmapbox/maps` version

10.1.0-beta.17

### Standalone component to reproduce

```javascript
// Tested with this example screen: https://github.com/rnmapbox/maps/blob/main/example/src/examples/UserLocation/UserLocationRenderMode.tsx

// Added the following code in the `onUserTrackingModeChange`
// console.log(`onUserTrackingModeChange(${JSON.stringify({followUserLocation: payload.followUserLocation, followUserMode: payload.followUserMode})})`);
```

### Observed behavior and steps to reproduce

The property `payload.followUserLocation` is always `true`, see the video in the link below:
https://drive.google.com/file/d/10T3L6sbjN1GsKUKSXnPppeaT4sOZRBiq/view?usp=sharing

### Expected behavior

When I set programmatically the `followUserLocation` property to `false`, the `onUserTrackingModeChange` callback should be called with a payload with the `followUserLocation` set to `false`.

**Comment by mfazekas** [comment]
Pls check `ViewPort onStatusChanged` this will replace onUserTrackingModeChanged
