### ISSUE TITLE
[Bug]: showAttribution method doesn't work. 

### ISSUE THREAD

**Issue by Streudal** [rnmapbox/maps#3165]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.15

### Standalone component to reproduce

```typescript
import React, { useCallback, useRef } from 'react';
import { Pressable, Text, View } from 'react-native';
import { MapView } from '@rnmapbox/maps';

function BrokenAttributionMapExample() {
  const mapRef = useRef<MapView>(null);

  const showAttribution = useCallback(async () => {
    await mapRef.current?.showAttribution(); // this doesn't work
  }, [mapRef]);

  return (
    <>
      <MapView
        ref={mapRef}
        attributionEnabled={false}
        logoEnabled={false}
        style={{ flex: 1 }}
      >
      </MapView>
      <View
        style={{
          position: 'absolute',
          right: 4,
          bottom: 90,
          zIndex: 50
        }}
      >
        <Pressable
          onPress={showAttribution}
        >
          <Text>
            Show Attribution Stuff
          </Text>
        </Pressable>
      </View>
    </>
  );
}
```

### Observed behavior and steps to reproduce

Using the built in `showAttribution` method that you can retrieve from the maps reference doesn't work.

![image](https://github.com/rnmapbox/maps/assets/35472790/0312e6b8-d908-437e-bf71-69be09a0ec82)

### Expected behavior

Expected this to just to work just like the built in one since it was documented in the [docs: showAttribution](https://github.com/rnmapbox/maps/blob/02173ce636267116b4a4bc1bd89f78127e0c8c4e/docs/MapView.md?plain=1#L723).

### Notes / preliminary analysis

Just wanted to use a custom button for the attribution since the positioning was not consistent with the built in position methods on the MapView across iOS/Android devices and differences between phones & tablets between the 2 different OSs as well.

Noticed that there was an open issue about this some time ago ([1409](https://github.com/rnmapbox/maps/issues/1409)) and it seems to be the same problem.

**Comment by mfazekas** [comment]
We don't have that implemented in v10 sdk and there is no api for it, so it's not trivial to implement. I'll remove the code for now, we'll read if there is an implementation

https://github.com/rnmapbox/maps/commit/6b7520fff56916d5f4766beb21b887a37817c8b9

In v10 on iOS that is implemented by the attributionDialogManager, on android AttributionViewPlugin and onClick could be used if accessible.
