### ISSUE TITLE
[Bug]: App crash due to nil unwrapping in gestureSettings on MapView

### ISSUE THREAD

**Issue by ysainson** [rnmapbox/maps#3183]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.0.0-rc.1

### Platform

iOS

### `@rnmapbox/maps` version

10.1.0-beta.20

### Standalone component to reproduce

```tsx
import * as React from "react";

import { Platform, StyleSheet } from "react-native";
import Mapbox, { StyleImport } from "@rnmapbox/maps";

interface MapViewProps {}

const MapView = (props: MapViewProps) => {
  const {} = props;

  // refs
  const mapRef = React.useRef<Mapbox.MapView>(null);

  // render
  return (
    <Mapbox.MapView
      ref={mapRef}
      // zoomEnable={true} // same behavior
      gestureSettings={{
        rotateEnabled: false,
      }}
      style={{ flex: 1 }}
      styleURL="mapbox://styles/mapbox/standard-beta"
    >
      <StyleImport
        id="basemap"
        existing
        config={{
          lightPreset: "dusk",
          // @ts-ignore
          showRoadLabels: false,
          // @ts-ignore
          showPlaceLabels: false,
          // @ts-ignore
          showTransitLabels: false,
          // @ts-ignore
          showPointOfInterestLabels: false,
        }}
      />
    </Mapbox.MapView>
  );
};

export default MapView;
```

### Observed behavior and steps to reproduce

When attempting to set the `gestureSettings` property (or `zoomEnabled`) on `Mapbox.MapView`, the application crashes. The crash occurs when unwrapping an optional value in the `setReactGestureSettings` method, as indicated by the runtime error `'Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value'.` This issue can be reproduced by initializing a MapView with the gestureSettings prop.

**With `gestureSettings` property:**

<img width="738" alt="image" src="https://github.com/rnmapbox/maps/assets/37186269/5b62ad34-a649-4edb-8b3e-a2b885e3fbc1"><br>

**With `zoomEnabled` property:**

<img width="729" alt="image" src="https://github.com/rnmapbox/maps/assets/37186269/903b6d17-fb03-4a29-b302-f7044c4c9b75">

### Expected behavior

The expected behavior is for the app to run without crashing when setting the `gestureSettings` property (or `zoomEnabled`).

**Comment by mfazekas** [comment]
Should be fixed in `10.1.0-beta.21`

**Comment by erwanlpfr** [comment]
Hello !

I have exactly the same issue with `10.1.0-beta.21` with `zoomEnabled`.
It crashes with the same screnshots and stacktrace than the previous post.

![image](https://github.com/rnmapbox/maps/assets/113348625/4555b7e6-ba68-4b09-8540-46dc1addbb91)

Thank you!

**Comment by mfazekas** [comment]
@erwanlpfr pls use equivalent settings in gestureSettings, I'll fix this issue later. And will probably also deprecate `zoomEnabled` and recommend to use `gestureSettings` instead.

**Comment by ysainson** [comment]
Thanks, @mfazekas! `10.1.0-beta.21` has fixed the problem.
