### ISSUE TITLE
UserLocation not working on android

### ISSUE THREAD

**Issue by lvothnrv** [rnmapbox/maps#3192]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.15

### Standalone component to reproduce

```javascript
import React from 'react';
import MapboxGL, {UserLocation} from '@rnmapbox/maps';

import {StyleSheet, StatusBar, View} from 'react-native';

MapboxGL.setAccessToken('...');

const PerimeterStep = () => {
  return (
    <View style={styles.flex1}>
      <StatusBar barStyle="light-content" animated={true} />
      <MapboxGL.MapView
        style={styles.flex1}
        styleURL={'mapbox://styles/.../...'}
        logoEnabled={false}
        attributionEnabled={false}>
        <UserLocation />
      </MapboxGL.MapView>
    </View>
  );
};

export default PerimeterStep;

const styles = StyleSheet.create({
  flex1: {
    flex: 1,
  },
});

```

### Expected behavior

I was on version 10.0.0-beta.70 it worked but now it doesn't work anymore so I switched to the latest version but the same thing doesn't work..

**Comment by AntonioA-D-C** [comment]
Having this exact same error, UserLocation crashes the app

**Comment by Cdingram** [comment]
Yup mine crashes too

**Comment by Cdingram** [comment]
FYI, I was able to make it work by using "<Mapbox.UserLocation renderMode="native" />" instead of just "<Mapbox.UserLocation />"

**Comment by Cdingram** [comment]
Interesting I’m using Mapbox not MapboxGL from the import, not sure if that makes a difference.

**Comment by mfazekas** [comment]
> Interesting I’m using Mapbox not MapboxGL from the import, not sure if that makes a difference.
@Cdingram it shouldn't make a difference.

For those it's crashing pls post the exception and backtrace.
