### ISSUE TITLE
[Bug]: java.lang.NullPointerException: anchor shouldn't be null

### ISSUE THREAD

**Issue by AdzeB** [rnmapbox/maps#3231]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.0.0

### Platform

Android

### `@rnmapbox/maps` version

v10.1.0-rc.0

### Standalone component to reproduce

```javascript
import React, { useState } from 'react';
import Mapbox, { MapView, StyleImport, Camera, MarkerView } from '@rnmapbox/maps';
import LottieView from "lottie-react-native";

const MapScreen = () => {
  const [defaultCoordinate, setDefaultCoordinate] = useState([
    28.047304, -26.204103,
  ]);

  const renderMarker = () => {
    return (
      <LottieView
        source={require("../../assets/lotties/marker_2.json")}
        autoPlay
        loop
        style={{
          width: 60,
          height: 40,
        }}
      />
    );
  };

  return (
    <MapView
      style={{ flex: 1 }}
      styleURL={"mapbox://styles/mapbox/standard-beta"}
    >
      <StyleImport
        id="basemap"
        existing
        config={{
          lightPreset: "day",
        }}
      />
      <Camera
        zoomLevel={8}
        animationMode="moveTo"
        animationDuration={2000}
        maxZoomLevel={20}
        centerCoordinate={defaultCoordinate}
      />
      <MarkerView
        id="userLocationMarker"
        key="userLocationMarker"
        allowOverlap={true}
        coordinate={defaultCoordinate}
      >
        {renderMarker()}
      </MarkerView>
    </MapView>
  );
}
```

### Observed behavior and steps to reproduce

On my Android emulator, I get the following error, but on my IOS simulator everything works as it should

```bash
 ERROR  Your app just crashed. See the error below.
java.lang.NullPointerException: anchor shouldn't be null
  com.mapbox.maps.ViewAnnotationAnchorConfig$Builder.build(ViewAnnotationAnchorConfig.java:127)
  com.rnmapbox.rnmbx.v11compat.annotation.AnnotationKt.offsets(Annotation.kt:25)
  com.rnmapbox.rnmbx.components.annotation.RNMBXMarkerView.getOptions(RNMBXMarkerView.kt:177)
  com.rnmapbox.rnmbx.components.annotation.RNMBXMarkerView.add(RNMBXMarkerView.kt:117)
  com.rnmapbox.rnmbx.components.annotation.RNMBXMarkerView.addToMap(RNMBXMarkerView.kt:79)
  com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.addFeaturesToMap(RNMBXMapView.kt:567)
  com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.styleLoaded(RNMBXMapView.kt:331)
  com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.access$styleLoaded(RNMBXMapView.kt:198)
  com.rnmapbox.rnmbx.components.mapview.RNMBXMapView$applyStyleURL$2.onStyleLoaded(RNMBXMapView.kt:720)
  com.mapbox.maps.StyleObserver.run(StyleObserver.kt:96)
  android.os.MessageQueue.nativePollOnce(Native Method)
  android.os.MessageQueue.next(MessageQueue.java:335)
  android.os.Looper.loopOnce(Looper.java:161)
  android.os.Looper.loop(Looper.java:288)
  android.app.ActivityThread.main(ActivityThread.java:7872)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Expected behavior

Should render Mapbox Map version 11 like IOS does

### Additional links and references

My app.json

```json
"@rnmapbox/maps",
        {
          "RNMapboxMapsImpl": "mapbox",
          "RNMapboxMapsDownloadToken": "sk.",
          "RNMapboxMapsVersion": "11.0.0"
        }
```

**Comment by AdzeB** [comment]
@mfazekas I have updated the sample, and with my defaultCoordinate state

**Comment by AdzeB** [comment]
@mfazekas   
 Apologies no,  but it's when I add the marker, everything works as it should with no marker. Lint was just giving me issues; hence I had to remove certain part  
  
\`\`\`javascript

import React, { useState } from 'react';  
import Mapbox, { MapView, StyleImport, Camera, MarkerView } from '@rnmapbox/maps';

const MapScreen = () => {  
 const \[defaultCoordinate, setDefaultCoordinate\] = useState(\[  
   28.047304, -26.204103,  
 \]);

 return (  
   \<MapView  
     style={{ flex: 1 }}  
     styleURL={"mapbox://styles/mapbox/standard-beta"}  
   >  
     \<StyleImport  
       id="basemap"  
       existing  
       config={{  
         lightPreset: "day",  
       }}  
     />  
     \<Camera  
       zoomLevel={8}  
       animationMode="moveTo"  
       animationDuration={2000}  
       maxZoomLevel={20}  
       centerCoordinate={defaultCoordinate}  
     />  
     \<MarkerView  
       id="userLocationMarker"  
       key="userLocationMarker"  
       allowOverlap={true}  
       coordinate={defaultCoordinate}  
     />  
   \</MapView>  
 );  
}  
  
  
\`\`\`

**Comment by ysainson** [comment]
Encountering the same issue in beta 23 when using `MarkerView` on Android. Explicitly setting the `anchor` does not resolve the problem.

**Comment by mfazekas** [comment]
@AdzeB thanks I could reproduce the issue. While the fix for this is trivial, but on v11 there Is another issue with marker views.

**Comment by MichaelDanielTom** [comment]
Can confirm that this is reproducible in the [`MarkerView.js`](https://github.com/rnmapbox/maps/blob/main/example/src/examples/Annotations/MarkerView.js) example in the example project, which crashes immediately upon navigating to the screen, which you can get to by pressing `Annotations` and then `MarkerView` in the example app. This is with version `10.1.0-rc.0` and with the settings in `example/android/gradle.properties` being the same as is in main (`RNMBX11=true` and `newArchEnabled=false`)

**Comment by AdzeB** [comment]
Thanks @mfazekas, I will test it on my end later today
