### ISSUE TITLE
Expo installation instructions fail with error: "Setting $RNMapboxMapsImpl is now required"

### ISSUE THREAD

**Issue by wvteijlingen** [rnmapbox/maps#3234]
## Environment
- Dev OS: macOS 14.1.2

## Steps to reproduce

1. Follow the exact instructions at: https://github.com/rnmapbox/maps/blob/main/plugin/install.md#plugin-configuration
2. Run `npx expo run:ios`

The error message is quite cryptic, and the provided URL (https://github.com/rnmapbox/maps/wiki/Deprecated-RNMapboxImpl-Unset#ios) isn't very clear on how to fix this either. It just refers the the iOS installation instructions for a bare iOS workflow.

## Result

```sh
npx expo run:ios
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: 
[!] Invalid `rnmapbox-maps.podspec` file: Setting $RNMapboxMapsImpl is now required - https://github.com/rnmapbox/maps/wiki/Deprecated-RNMapboxImpl-Unset#ios.

 #  from <project_dir>/node_modules/@rnmapbox/maps/rnmapbox-maps.podspec:88
 #  -------------------------------------------
 #  unless $RNMapboxMapsImpl
 >    raise "Setting $RNMapboxMapsImpl is now required - https://github.com/rnmapbox/maps/wiki/Deprecated-RNMapboxImpl-Unset#ios"
 #  end
 #  -------------------------------------------
.

 #  from <project_dir>/WandelApp/ios/Podfile:52
 #  -------------------------------------------
 #    use_expo_modules!
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

**Comment by wvteijlingen** [comment]
> No code example found in issue body - [More info](https://github.com/rnmapbox/maps/wiki/ErrorInExamplesInIssue)

Not sure what code I am supposed in include here. The issue is with the installation procedure.

**Comment by hamsterhomka** [comment]
Same problem. Why Isn't the need to pass another parameter ```RNMapboxMapsImpl: 'mapbox'``` even mentioned in the guide for the expo plugin? And even after passing it I am still getting an error

```
import MapboxMaps
 ^ compiling for iOS 11.0, but module 'MapboxMaps' has a minimum deployment target of iOS 12.0: 
```


<img width="1109" alt="image" src="https://github.com/rnmapbox/maps/assets/6339290/648dd5dd-7b04-47aa-8ab3-4b3b64e83cda">

I am using expo SDK 49 and my deploymentTarget is 13.0

**Comment by Ladvace** [comment]
Same problem here:

![image](https://github.com/rnmapbox/maps/assets/31326058/62a6288c-050f-4943-a4f1-3aa8da1c382b)

**Comment by maxkudla** [comment]
> Same problem. Why Isn't the need to pass another parameter `RNMapboxMapsImpl: 'mapbox'` even mentioned in the guide for the expo plugin? And even after passing it I am still getting an error
> 
> ```
> import MapboxMaps
>  ^ compiling for iOS 11.0, but module 'MapboxMaps' has a minimum deployment target of iOS 12.0: 
> ```
> 
> <img alt="image" width="1109" src="https://private-user-images.githubusercontent.com/6339290/287992587-648dd5dd-7b04-47aa-8ab3-4b3b64e83cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NjE1NzUsIm5iZiI6MTcwMTk2MTI3NSwicGF0aCI6Ii82MzM5MjkwLzI4Nzk5MjU4Ny02NDhkZDVkZC03YjA0LTQ3YWEtOGFiMy00YjNiNjRlODNjZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMTUwMTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjY0MTQ3ODYxNTQwN2RkZTIyZTJiYTcwZDQxMjc4MmRkNDY2NWQzNDI2MTdhMzU0NmVmMDA0MjJmZjcwNTUwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aQ5LN-gCSfa1y9D1nOsTjEY6g3voHRXdCT54FfDPQ5Y">
> I am using expo SDK 49 and my deploymentTarget is 13.0

Have u fixed an issue?

**Comment by Ladvace** [comment]
adding this in ios > Podfile fixed the problem for me

```
$RNMapboxMapsImpl = 'mapbox' <--- you need to add this
target 'your_project_name' do
```

**Comment by hamsterhomka** [comment]
> > Same problem. Why Isn't the need to pass another parameter `RNMapboxMapsImpl: 'mapbox'` even mentioned in the guide for the expo plugin? And even after passing it I am still getting an error
> > ```
> > import MapboxMaps
> >  ^ compiling for iOS 11.0, but module 'MapboxMaps' has a minimum deployment target of iOS 12.0: 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="1109" src="https://private-user-images.githubusercontent.com/6339290/287992587-648dd5dd-7b04-47aa-8ab3-4b3b64e83cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NjE1NzUsIm5iZiI6MTcwMTk2MTI3NSwicGF0aCI6Ii82MzM5MjkwLzI4Nzk5MjU4Ny02NDhkZDVkZC03YjA0LTQ3YWEtOGFiMy00YjNiNjRlODNjZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMTUwMTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjY0MTQ3ODYxNTQwN2RkZTIyZTJiYTcwZDQxMjc4MmRkNDY2NWQzNDI2MTdhMzU0NmVmMDA0MjJmZjcwNTUwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aQ5LN-gCSfa1y9D1nOsTjEY6g3voHRXdCT54FfDPQ5Y">
> > I am using expo SDK 49 and my deploymentTarget is 13.0
> 
> Have u fixed an issue?

Yes, I did. You must pass this into expo plugin

```
[
    '@rnmapbox/maps',
    {
      RNMapboxMapsImpl: 'mapbox',
      RNMapboxMapsVersion: '10.16.2',
      RNMapboxMapsDownloadToken:
        'sk.your-key',
    },
],
```

**Comment by mfazekas** [comment]
So the issue is that #main documents the instructions with 10.1 which is only `rc` so you'd need to use `expo install @rnmapbox/maps@next` instead of `expo install @rnmapbox/maps`

This was fixed in the install instructions at:
https://rnmapbox.github.io/docs/install

And we're now just referring to it.
https://github.com/rnmapbox/maps#installation

**Comment by wvteijlingen** [comment]
@mfazekas I just created a new clean expo project and followed the instructions you linked. However, I'm now running into a different error:

> iOS Bundling failed 621ms
> error: App.tsx: Cannot find module '@rnmapbox/babel-plugin-maps'
> Require stack:
> - /Users/<redacted>/node_modules/@babel/core/lib/config/files/plugins.js
> - /Users/<redacted>/node_modules/@babel/core/lib/config/files/index.js
> - /Users/<redacted>/node_modules/@babel/core/lib/index.js
> - /Users/<redacted>/node_modules/metro-transform-worker/src/index.js
> - /Users/<redacted>/node_modules/metro/src/DeltaBundler/Worker.flow.js
> - /Users/<redacted>/node_modules/metro/src/DeltaBundler/Worker.js
> - /Users/<redacted>/node_modules/jest-worker/build/workers/processChild.js
> - If you want to resolve "@rnmapbox/maps", use "module:@rnmapbox/maps"

**Comment by mfazekas** [comment]
@wvteijlingen what is you config file? Do you have also added `...` from the docs, it's not supposed to be added

**Comment by wvteijlingen** [comment]
It's as follows:

```javascript
// babel.config.js

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        "@rnmapbox/maps",
        {
          "RNMapboxMapsDownloadToken": "xxx"
        }
      ]
    ]
  };
};
```

```javascript
// package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@rnmapbox/maps": "^10.1.3",
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "expo-splash-screen": "~0.20.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

**Comment by mfazekas** [comment]
> I didn't add the ellipsis. Basically what I did is create a fresh Expo project using `create-expo-app`, and then added rnmapbox using the installation instructions.
> 

Not exactly - the install instructions doesn't mention adding adding anything your `babel.config.js`. 
https://rnmapbox.github.io/docs/install#plugin-configuration

**Comment by wvteijlingen** [comment]
Aah you're right, I misread that, my mistake! I fixed it, but another issue pops up though:

> ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

**Comment by mfazekas** [comment]
> Aah you're right, I misread that, my mistake! I fixed it, but another issue pops up though:
> 
> > ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

See https://rnmapbox.github.io/docs/install?rebuild=expo#rebuild
