### ISSUE TITLE
[Bug]: Android: SIGSEGV crash after updating rnmapbox version

### ISSUE THREAD

**Issue by bradstiff** [rnmapbox/maps#3237]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.15

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView />
    );
  }
}
```

### Observed behavior and steps to reproduce

After updating rnmapbox version from 10.0.0-rc.13 to 10.0.15, opening any screen with a mapbox map causes the app to immediately crash with the following stack trace:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 18821 >>> com.xovation.weski <<<

backtrace:
  #00  pc 0x00000000000f8000  [anon:stack_and_tls:18821]
  #01  pc 0x00000000000e8238  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
  #02  pc 0x00000000000e7e6c  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
  #03  pc 0x00000000000e3f50  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
  #04  pc 0x00000000000e3da4  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libc++_shared.so (__gxx_personality_v0+224) (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
  #05  pc 0x0000000000143d4c  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #06  pc 0x0000000000144254  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #07  pc 0x0000000000180aec  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #08  pc 0x00000000001a67cc  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #09  pc 0x000000000028e914  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #10  pc 0x000000000028eec8  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #11  pc 0x000000000028f83c  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #12  pc 0x000000000019896c  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #13  pc 0x00000000001a9854  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (mapbox::common::platform::processTask(std::__ndk1::function<void ()> const&)+32) (BuildId: f2ed5d81095e1796)
  #14  pc 0x000000000019add0  /data/app/~~1cmB8bMYMLeAeaTLpYvN2w==/com.xovation.weski-8cBK0YxjolLvsDxLYFU2QA==/split_config.arm64_v8a.apk!libmapbox-common.so (BuildId: f2ed5d81095e1796)
  #15  pc 0x00000000000c9ccc  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #16  pc 0x000000000005db00  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

### Expected behavior

App should not crash.

### Notes / preliminary analysis

I upgraded from 10.0.0-rc.13 to 10.0.15.

I upgraded RN from 0.71.6 to 0.72.7.

No code changes were made.

I released a beta version with these changes to the Play Store, and updated the version on my phone. Now, opening any screen with a Mapbox map causes the app to crash. I tried clearing the Cache and it still crashes. I tried changing the code to simply render a MapView with no style, props, handlers or content, and it still crashes.

The only thing that stops the crashing is uninstalling and reinstalling the app.

So it seems like some data has been cached by Mapbox that is not compatible with the latest version.

Is there a programmatic way to clear cached data?

**Comment by bradstiff** [comment]
It looks like I need to try the following:

`await Mapbox.offlineManager.clearAmbientCache();`

I will try this as soon as I am able to access a broken device, and will report back.

**Comment by bradstiff** [comment]
I have narrowed down the problem, but am at a loss as to how to fix.

First, `Mapbox.offlineManager.invalidateAmbientCache()` is deprecated (docs should be updated to reflect this). So I tried `Mapbox.offlineManager.resetDatabase()`. Unfortunately, the issue persists.

I then uinstalled the app, installed the version that used rnmapbox v10.0.0-rc.13, and browsed some maps (to seed the database). I then updated to the 10.0.15 version, and the issue did not resurface.

This surprised me, so I uninstalled again, installed a much older version that used rnmapbox v10.0.0-beta.68, browed some maps, and updated to the version that has rnmapbox v10.0.15. The issue resurfaced. 

So it seems to be an issue with cached data stored by version 10.0.0-beta.68 that is supported by version 10.0.0-rc.13, but not compatible with version 10.0.15.

Since resetDatabase doesn't help, I'm not sure how to fix it.

Any ideas?

**Comment by bradstiff** [comment]
I had to set the access token before calling resetDatabase, otherwise the app would crash. 

I see that a [recent commit from a few days ago](https://github.com/rnmapbox/maps/pull/3218) sets the access token on the tile store.

But I am using v10.0.15 which does not set the access token. Since offlineManager.resetDatabase is the first method I am calling (after Mapbox.setAccessToken), could that be why resetDatabase doesn't work?

**Comment by mfazekas** [comment]
@bradstiff We also have https://rnmapbox.github.io/docs/components/MapView#cleardata but it's on MapView so might be too late.

In v11 it's static so we could make it a static method there.

https://docs.mapbox.com/android/maps/api/11.0.0/mapbox-maps-android/com.mapbox.maps/-mapbox-map/-companion/clear-data.html?query=fun%20clearData(callback:%20AsyncOperationResultCallback)

You can also give it a try with [10.1.*-rc ](https://github.com/rnmapbox/maps/releases/tag/v10.1.0-rc.0)

You can also look into logcat messages. 

Also you can use the `RNMapboxMapsImpl` to change mapbox versions.

https://github.com/rnmapbox/maps/blob/v10.0/android/install.md#using-non-default-mapbox-version

**Comment by bradstiff** [comment]
Thanks. I can't render a Mapview at all without crashing, so clearData won't work.

I'll try v10.1.

I have looked very closely at logcat. I don't see anything that gives me any ideas. I do notice that around the same time as the crash, the entry below appears a few ms prior. It is not the same process ID as the app, so I don't think much of it. But it is strange that it is there every time.

`2023-12-04 23:08:17.471 19325-19325 chromium                pid-19325                            E  [19325:19325:20231204,230817.471087:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)
`

One thing I forgot to mention: in Crashlytics, the reported RAM at the time of the crash is always very low, e.g., a few hundred MB. Essentially, RAM goes from normal, e.g., 2GB+, down to a few hundred MB just before the crash. As I said earlier, the crash occurs even rendering an empty Mapview, e.g., the memory drawdown I am describing has nothing to do with the map I'm trying to render.

**Comment by mfazekas** [comment]
@bradstiff in 10.1.0 I've also implemented clearData static method. But you might need to use 11.0 Mapbox to use it as native android  10.* requires a MapView instance to call clearData.

**Comment by bradstiff** [comment]
I upgraded to 10.1.0-rc.2 and it appears the problem went away.

I'm still concerned about what it could have been. 

Fresh installs worked fine. Only specific upgrades had the issue.
