### ISSUE TITLE
Failed to build Android rnmapbox package for RN 0.73.0.

### ISSUE THREAD

**Issue by yuriydrobniy** [rnmapbox/maps#3250]
## Environment
- Dev OS: OSX M1
- @rnmapbox/maps version: 10.0.15
- React Native version: 0.73.0

## Steps to reproduce

```
yarn android
```
Output:
```
> Task :rnmapbox_maps:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
```

**Comment by mfazekas** [comment]
@yuriydrobniy Thanks for the repot, pls use https://github.com/rnmapbox/maps/releases/tag/v10.1.0-rc.4, that should work with 0.73

**Comment by yuriydrobniy** [comment]
@mfazekas thanks it works
