### ISSUE TITLE
[Bug]: IllegalArgumentException   java.lang.Enum in valueOf

### ISSUE THREAD

**Issue by jakub-oone** [rnmapbox/maps#3255]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.16.2

### Platform

Android

### `@rnmapbox/maps` version

10.0.15

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Sentry is catching this error:
No enum constant com.mapbox.maps.extension.style.layers.properties.generated.LineJoin.MİTER

<img width="1083" alt="Screenshot 2023-12-08 at 16 49 03" src="https://github.com/rnmapbox/maps/assets/55842861/37fe6765-2690-49f3-8b57-66919e37ce3c">
<img width="858" alt="Screenshot 2023-12-08 at 16 51 04" src="https://github.com/rnmapbox/maps/assets/55842861/29cf2835-3ee8-4df7-a58e-3157dc015e8d">

**Comment by mfazekas** [comment]
Sorry we don't offer free [support](https://github.com/rnmapbox/maps/wiki/Support) for this package. 

Note the I is a special character in  MİTER it's either in your source code or might be coming from an expression evaluation
