### ISSUE TITLE
[Bug]: Android crashes upon launch with error: Exception in HostObject::get for prop 'RNMBXLocationModule': com.mapbox.common.location.IncompatibleGooglePlayServicesLocationVersion: Incompatible Google Play Services location version found. Please check https://docs.mapbox.com/android/maps/guides/user-location/ for more details.

### ISSUE THREAD

**Issue by manfredxu99** [rnmapbox/maps#3266]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.15

### Standalone component to reproduce

I haven't changed anything recently and started getting this error. Do I need to specify a particular version of play location services?

`com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get for prop 'RNMBXLocationModule': com.mapbox.common.location.IncompatibleGooglePlayServicesLocationVersion: Incompatible Google Play Services location version found. Please check https://docs.mapbox.com/android/maps/guides/user-location/ for more details. You can add <meta-data android:name="com.mapbox.maps.location.gms.SKIP_IF_INVALID_VERSION" android:value="true"/> to your AndroidManifest to skip it and use Android platform location APIs., js engine: hermes`

### Observed behavior and steps to reproduce

Open app, app crashes

### Expected behavior

App does not crash

**Comment by simvi** [comment]
Same here

**Comment by mfazekas** [comment]
1.) We've recently release `10.1` is that the version you're using now?
2.) What is your mapbox version? 
3.) What is your react-native version, are you using expo or react-native
3.) Have you tried to adding the mentioned tag to Manifest

See also
https://github.com/mapbox/mapbox-maps-android/issues/1752

**Comment by simvi** [comment]
Well I just add `<meta-data android:name="com.mapbox.maps.location.gms.SKIP_IF_INVALID_VERSION" android:value="true"/>` and it works again.
But I don't understand why is that append just today
