### ISSUE TITLE
kotlin 1.9.0: npm package build fails

### ISSUE THREAD

**Issue by petriaarnio** [rnmapbox/maps#3267]
## Environment
- Dev OS: macOS 13.5.2
- @rnmapbox/maps version: 10.1.1
- React Native version: 0.72.4

## Steps to reproduce
1. npm install @rnmapbox/maps
2. npm run android

Error:
e: file:///Users/xxx/work/mobile/mobile_app/node_modules/@rnmapbox/maps/android/src/main/java/com/rnmapbox/rnmbx/components/AbstractEventEmitter.kt:53:5 'addEventEmitters' overrides nothing

**Comment by mfazekas** [comment]
It's interesting as according to https://github.com/facebook/react-native/blame/746ad378c7efe3ee2f4926ab30e5401407f8b3ba/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManager.java#L242

superclass of AbstractEventEmitter - ViewManager in react-native had the 

```
  protected void addEventEmitters(@NonNull ThemedReactContext reactContext, @NonNull T view) {}
```

Unchanged for for years.
So not sure why the compiler error.

**Comment by petriaarnio** [comment]
Yes, this is strange.
I tried the same with "vanilla" project and it compiles ok.
So my project has something which causes the compilation error. Just hard to figure out what it is.

**Comment by mfazekas** [comment]
My 2 tips, is either your react-native version.  - check content of ViewManager.java. Or your kotlin settings in your Gradle files?

**Comment by mfazekas** [comment]
I'm closing this as this sound project specific then.

**Comment by rayjackson13** [comment]
I ran into the exact same issue on my project.

Environment:
- React Native: 0.72.4
- @rnmapbox/maps: 10.1.15
- kotlinVersion: 1.9.0
- Gradle: 8.0.1

Downgrading Kotlin version to 1.8.0 helped resolve this:
```
buildscript {
    ext {
       ...
        kotlinVersion = '1.8.0'
    }
    ...
    dependencies {
       ...
        classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0')
     }
}
```

Hope this helps :)

**Comment by petriaarnio** [comment]
I got this working after upgraded react-native to version 0.73.1
They also switched to Kotlin.

**Comment by robin-pham** [comment]
Proposed a PR fix that worked for me, should be an easy patch if anyone else needs to implement it ASAP. Got the inspiration from https://github.com/invertase/react-native-google-mobile-ads/issues/511

**Comment by MinskLeo** [comment]
Any progress there? The fix is easy to apply, but would be good to have working lib release without applying additional patch.

**Comment by petriaarnio** [comment]
Like I mentioned earlier, the problem disappeared with the latest React native version.

**Comment by andreirat** [comment]
I just encountered a similar issue, Android build fails after mapbox upgrade: 

"react-native": "0.72.14",
"@rnmapbox/maps": "^10.1.21",


`> Task :rnmapbox_maps:compileReleaseKotlin
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/runner/.gradle/caches/transforms-3/49101a29b9e4fb48ee2b093f44617f88/transformed/jetified-kotlinx-coroutines-android-1.8.0.jar!/META-INF/kotlinx-coroutines-android.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
e: /Users/runner/.gradle/caches/transforms-3/7fc092dbf0c43219afef390baa06b7b3/transformed/jetified-kotlin-stdlib-1.9.21.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
e: /Users/runner/.gradle/caches/transforms-3/7fc092dbf0c43219afef390baa06b7b3/transformed/jetified-kotlin-stdlib-1.9.21.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
e: /Users/runner/.gradle/caches/transforms-3/7fc092dbf0c43219afef390baa06b7b3/transformed/jetified-kotlin-stdlib-1.9.21.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
e: /Users/runner/.gradle/caches/transforms-3/9134c1c30b1a5b9ad37dd095f699d011/transformed/jetified-kotlinx-coroutines-core-jvm-1.8.0.jar!/META-INF/kotlinx-coroutines-core.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.`

**Comment by mfazekas** [comment]
@andreirat That is a bit different issue. See https://github.com/rnmapbox/maps/pull/3465/files

You might be able to work around that using 
```
kotlinxCoroutinesCoreVersion = 1.6.4
kotlinxCoroutinesAndroidVersion = 1.6.4
```

Add this to your andorid/build.gradle file after  `kotlinVersion = 1.6...` in `buildscript { ext {`

**Comment by andreirat** [comment]
> @andreirat That is a bit different issue. See https://github.com/rnmapbox/maps/pull/3465/files
> 
> You might be able to work around that using
> 
> ```
> kotlinxCoroutinesCoreVersion = 1.6.4
> kotlinxCoroutinesAndroidVersion = 1.6.4
> ```
> 
> Add this to your andorid/build.gradle file after `kotlinVersion = 1.6...` in `buildscript { ext {`

@mfazekas already did that, but it would break other packages we are using. It worked with RN version 0.72.4.

**Comment by andreirat** [comment]
@mfazekas 

- datadog
- react-native-screens
- mapbox still throws this

```
The class is loaded from /Users/andreirat/.gradle/caches/transforms-3/5d727cf8e0ce4b87b50c99126e24b794/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: /Users/andreirat/projects/Rodeo/rodeo/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (16, 10): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from /Users/andreirat/.gradle/caches/transforms-3/5d727cf8e0ce4b87b50c99126e24b794/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: /Users/andreirat/projects/Rodeo/rodeo/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (20, 5): Unresolved reference:
```

**Comment by andreirat** [comment]
@mfazekas downgraded to `"@rnmapbox/maps": "10.1.17",` and the build works. I wonder if this version covers all the Apple Privacy warnings?

**Comment by disersoft-code** [comment]
I had the same issue that @andreirat,  Environment:

- React Native: 0.72.6
- @rnmapbox/maps: 10.1.21
- kotlinVersion: 1.9.0

and downgraded to @rnmapbox/maps: 10.1.17, and it works
