### ISSUE TITLE
Expo build failed on Android :  Could not resolve com.mapbox.maps:android:10.16.2

### ISSUE THREAD

**Issue by TheUncharted** [rnmapbox/maps#3285]
## Environment
- Dev Win 11
- @rnmapbox/maps version: 10.1.2 
- Expo version: 49.0.0

## Steps to reproduce
Its not really an error from rnmapbox when I upgraded rnmapbox to the latest version, I was working mostly on ios so I didn't notice immediately for Android : it seems this version can not be found in the repo maven 

![image](https://github.com/rnmapbox/maps/assets/24917492/07f57850-4cf2-42fa-82ee-d5ddf460e1c8)

**Comment by mfazekas** [comment]
@TheUncharted it's likely an issue with the mapbox token. See the 401 errors.

**Comment by TheUncharted** [comment]
ah thanks I didnt see it
