### ISSUE TITLE
[Bug]: Layers drawn incorrectly at certain zoom levels

### ISSUE THREAD

**Issue by MorganTrudeau** [rnmapbox/maps#3286]
### Mapbox Implementation

Maplibre

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.65

### Standalone component to reproduce

```javascript
import React from "react";
import MapboxGL, {
  CircleLayerStyle,
  FillLayerStyle,
  LineLayerStyle,
  MapView,
} from "@rnmapbox/maps";

const GeofenceMap = () => {
  return (
    <MapView style={{ flex: 1 }}>
      <MapboxGL.Camera zoomLevel={13} centerCoordinate={[-122.702, 49.145]} />
      <MapboxGL.ShapeSource
        id="geofenceShape"
        shape={{
          type: "Feature",
          properties: {},
          geometry: {
            type: "Polygon",
            coordinates: [
              [
                [-122.70851985540335, 49.14128712757946],
                [-122.70851985540335, 49.16212739894851],
                [-122.69309519870549, 49.16212739894851],
                [-122.69309519870549, 49.14128712757946],
              ],
            ],
          },
        }}
      >
        <MapboxGL.FillLayer id="fill" style={layerStyles.fill} />
        <MapboxGL.LineLayer id="line" style={layerStyles.line} />
        <MapboxGL.CircleLayer id="circle" style={layerStyles.circle} />
      </MapboxGL.ShapeSource>
    </MapView>
  );
};

const layerStyles = {
  fill: {
    fillAntialias: true,
    fillColor: "red",
    fillOutlineColor: "red",
    fillOpacity: 0.1,
  },
  line: { lineWidth: 3, lineColor: "red" },
  circle: {
    circleColor: "red",
  },
};

export default GeofenceMap;
```

### Observed behavior and steps to reproduce

1. Render this component.
2. Observe the layer is cut off on the right.
3. Zoom out and observe the layer is drawn correctly.

### Expected behavior

I expect layers to be drawn correctly at all zoom levels.

### Cut off layer
<img src="https://github.com/rnmapbox/maps/assets/28589416/4683f9ad-8962-498c-b606-4e16ffcc22b9" width="200" />

### Correctly drawn layer
<img src="https://github.com/rnmapbox/maps/assets/28589416/6a530083-23a7-433d-8f73-9c7f286ab135" width="200" />

**Comment by mfazekas** [comment]
@MorganTrudeau thanks for the report, pls try with the latest version. 10.1 both with 10.6.3 RNMapbox and 11.0.0

**Comment by mfazekas** [comment]
Oh I see it's a maplibre issue. Sorry for maplire please use the maplibrare react native libraries
