### ISSUE TITLE
Mapbox V11: MapboxMobileEvents uninstalls when following documentation for V11 setup. Anyone else facing this?

### ISSUE THREAD

**Issue by shahbek** [rnmapbox/maps#3289]
## Environment
- Dev OS: [e.g. OSX 11.0.1, Win10]
- @rnmapbox/maps version: [eg. 10.0.15] 
- React Native version: [eg. 0.72.6]
- Expo version: [eg. 49.0.0]

## Steps to reproduce

```sh   
react-native init sample --version react-native@0.60.5
cd sample
npm install rnmapbox/maps#main --save
# or released version `npm install @rnmapbox/maps@8.0.0-rc1 --save`
react-native run-android
```

**Comment by mfazekas** [comment]
Your issue doesn't contain detailed description on what have you done, neither a detailed description on what have you experienced.
