### ISSUE TITLE
iOS v11 setting $RNMapboxMapsVersion

### ISSUE THREAD

**Issue by dpyeates** [rnmapbox/maps#3296]
[https://rnmapbox.github.io/docs/install?v11-insructions=ios#using-v11](https://rnmapbox.github.io/docs/install?v11-insructions=ios#using-v11)

The installation instructions for iOS to use v11 shows the following:

`$RNMapboxMapsVersion = '= 11.0.0'`

Is this a typo? I'm assuming it should be:

`$RNMapboxMapsVersion = '11.0.0'`

**Comment by mfazekas** [comment]
Not really on cocoa pods it's a version constraints. So can be `>= 11.0.0` etc. I think also works without an operator too.
