### ISSUE TITLE
Fresh project, can't build android...

### ISSUE THREAD

**Issue by 5PK** [rnmapbox/maps#3306]
## Environment
- Dev OS: OSX 11.0.1
- @rnmapbox/maps version: 10.1.3
- React Native version: 0.72.6
- Expo version: 49.0.15

## Steps to reproduce

1. ` npx create-expo-app my-app `
2. `cd my-app`
3. `npx expo install @rnmapbox/maps`
4. ` npx expo prebuild`
5. `npx expo run:android `

Error

```
Could not determine the dependencies of task ':rnmapbox_maps:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':rnmapbox_maps:debugCompileClasspath'.
   > Could not find com.mapbox.maps:android:10.1.3.
     Required by:
         project :rnmapbox_maps

```

Not sure why this is happening...on ios it works fine.

**Comment by 5PK** [comment]
https://api.mapbox.com/downloads/v2/releases/maven

pinging this with my download token gives this in postman

`{
    "message": "Not Found"
}`

What gives???

**Comment by mfazekas** [comment]
1. I'm sorry not much we can do about that. You can report it to upstream - mapbox android. But most likely an issue with the way you setup your credentials, or the credentatials itself. 

For `curl https://api.mapbox.com/downloads/v2/releases/maven` I'm also getting 404, but it's 401 without correct access token


```
curl  https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.jar
```

This should work with correct credentials
```
curl -u mapbox:sk.* https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.jar
```
