### ISSUE TITLE
[Bug]: Console Warning: MapIdle Not Supported During Jest Testing

### ISSUE THREAD

**Issue by sairus2k** [rnmapbox/maps#3314]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.1.3

### Standalone component to reproduce

```javascript
import React from 'react';
import { MapView } from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView onMapIdle={console.log} />
    );
  }
}
```

### Observed behavior and steps to reproduce

I'm currently experiencing an issue during my Jest testing process where I receive a console warning stating: "rnmapbox maps: MapIdle is not supported".

Preliminary analysis indicates that the issue might be arising due to the absence of the `MapIdle` event type in the `setup-jest.js` file.

Here's the detailed warning message:
```
  console.warn
    rnmapbox maps: MapIdle is not supported

      at warn (node_modules/@rnmapbox/maps/src/components/MapView.tsx:584:23)
      at MapView.addIfHasHandler [as _setHandledMapChangedEvents] (node_modules/@rnmapbox/maps/src/components/MapView.tsx:611:7)
      at MapView._setHandledMapChangedEvents [as componentDidMount] (node_modules/@rnmapbox/maps/src/components/MapView.tsx:559:10)
      ...
```

### Expected behavior

No warning, because `onMapIdle` works as expected.

**Comment by mfazekas** [comment]
@sairus2k thanks much for the report:

The warning is coming from here:

https://github.com/rnmapbox/maps/blob/cd7ee2c40f94d8b9517ec7a4e886275f83124ad9/src/components/MapView.tsx#L578-L586


And it seems that MapIdle is missing from here:

https://github.com/rnmapbox/maps/blob/cd7ee2c40f94d8b9517ec7a4e886275f83124ad9/setup-jest.js#L40-L55

Would you like to do a PR addressing it?!
