### ISSUE TITLE
Could not find com.mapbox.maps:android:10.16.2

### ISSUE THREAD

**Issue by batuhanors** [rnmapbox/maps#3316]
- Dev OS: MacOS Sonoma 
- @rnmapbox/maps version: 10.1.3
- React Native version: 0.73.1

I installed rnmapbox/maps version 10.1.3 and did everything that the docs says.
my android/build.gradle file:
`buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        kotlinVersion = "1.8.0"
    }
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be mapbox (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
}

apply plugin: "com.facebook.react.rootproject"`
and I set the authentication configs on my gradle.properties file.
The project seems to work well on iOS. However, when I try to run on android, I get the following error:

> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mapbox.maps:android:10.16.2.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/maps/android/10.16.2/android-10.16.2.pom
       - https://repo.maven.apache.org/maven2/com/mapbox/maps/android/10.16.2/android-10.16.2.pom
       - file:/Users/batuhanors/Documents/work/mangocarapp/node_modules/jsc-android/dist/com/mapbox/maps/android/10.16.2/android-10.16.2.pom
       - https://dl.google.com/dl/android/maven2/com/mapbox/maps/android/10.16.2/android-10.16.2.pom
       - https://www.jitpack.io/com/mapbox/maps/android/10.16.2/android-10.16.2.pom
     Required by:
         project :app > project :rnmapbox_maps
   > Could not find com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
       - https://repo.maven.apache.org/maven2/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
       - file:/Users/batuhanors/Documents/work/mangocarapp/node_modules/jsc-android/dist/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
       - https://dl.google.com/dl/android/maven2/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
       - https://www.jitpack.io/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
     Required by:
         project :app > project :rnmapbox_maps

**Comment by mfazekas** [comment]
Sounds like an issue with MAPBOX_DOWNLOADS_TOKEN, is that defined? Is that the correct token?

https://rnmapbox.github.io/docs/install?rebuild=android&configure-module=android#verify-mapbox_downloads_token-in-gradleproperties
