### ISSUE TITLE
[Bug]: Camera component bounds prop not working properly

### ISSUE THREAD

**Issue by andresev** [rnmapbox/maps#3327]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.1.5

### Platform

iOS

### `@rnmapbox/maps` version

10.0.13

### Standalone component to reproduce

```javascript
import React, {useEffect, useRef, useState} from 'react';
import {View, ViewStyle, ViewProps} from 'react-native';
import Mapbox, {
  PointAnnotation,
  Camera,
  LineLayer,
  ShapeSource,
  MapView,
} from '@rnmapbox/maps';
//@ts-ignore
import turfBbox from '@turf/bbox';

interface AppMapRideProps extends ViewProps {
  coordinates: any;
  isRideCard?: boolean;
}
...
export const AppMapRide = ({coordinates}: AppMapRideProps) => {
  const [coordBounds, setCoordBounds] = useState([]);
  const CameraRef = useRef<Camera>(null);
  const MapviewRef = useRef<MapView>(null);

// Gets bound coordinates from ne, sw bbox
    const bbox = turfBbox({
      type: 'LineString',
      coordinates: coordinates,
    });

  useEffect(() => {
    setCoordBounds([
      ...coordBounds,
      [bbox[0], bbox[1]],
      [bbox[2], bbox[3]],
    ]);
  }, [coordinates]);

  return (
    <Mapbox.MapView
      ref={MapviewRef}
      style={$mapview}
      logoEnabled={false}
      scaleBarEnabled={false}
      zoomEnabled={false}
      scrollEnabled={false}
      pitchEnabled={false}
      projection="mercator">
      <ShapeSource
        id="coordinateRideShape"
        shape={{type: 'Polygon', coordinates: [coordinates]}}>
        <LineLayer
          id="rideLineLayer"
          sourceID="polygonSource"
          layerIndex={50}
          existing
          style={{
            lineColor: colors.palette.primary500,
            lineWidth: 3,
          }}
        />
      </ShapeSource>
      <Camera
        ref={CameraRef}
        bounds={{
          ne: coordBounds[0],
          sw: coordBounds[1],
        }}
        padding={{
          paddingBottom: -50,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 10,
        }}
        allowUpdates={false}
        animationDuration={0}
        animationMode="none"
      />
    </Mapbox.MapView>
  );
};

const $mapview: ViewStyle = {
  height: '100%',
  width: '100%',
};

const $coordPoint: ViewStyle = {
  height: 10,
  width: 10,
  backgroundColor: colors.palette.neutral100,
  borderRadius: 5,
  borderColor: colors.palette.primary600,
  borderWidth: 2,
};

```

### Observed behavior and steps to reproduce

Spin up a map with the newest Mapbox and setup the Camera component to give bounds of a polygon (NE and SW). See if it works.

### Expected behavior

- This is the result I was getting before I updated pods for the Camera component bounds prop.
![Simulator Screenshot - iPhone 15 Pro - 2024-01-17 at 11 19 00](https://github.com/rnmapbox/maps/assets/22423891/d2c71dfe-db2c-47ce-9961-e2afc3275ee3)

- This is the result after pods were updated to MapboxMaps 10.16.4.
![Simulator Screenshot - iPhone 14 Pro - 2024-01-12 at 10 34 23](https://github.com/rnmapbox/maps/assets/22423891/54821c23-2a2b-497e-bbe3-29f7a2786160)

Bounds were not working properly and I did try to see what could've caused the problem but then I ended up downgrading Mapbox version and it's now working.

Reporting a bug if there's any for bounds prop. .

**Comment by swey** [comment]
Can confirm this. This happens on iOS only.

If the bounds are set after the map is loaded (`onDidFinishLoadingMap`), everything is fine (but of course with a visual jump).

**Comment by Gys** [comment]
This issue should not have closed for a minor technicality. It is very valid. I had the same and the solution of @swey works. Thanks!
