### ISSUE TITLE
[Bug]: After updating to latest mapbox, suddenly getting errors when running app

### ISSUE THREAD

**Issue by salvinoto** [rnmapbox/maps#3339]
### Mapbox Implementation

Mapbox

### Mapbox Version

latest

### Platform

iOS

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

import Mapbox from '@rnmapbox/maps';
import * as Device from 'expo-device';
import * as Location from 'expo-location';
import { Database } from 'lib/database.types';
import React, { useEffect } from 'react';
import { StyleSheet, View, Appearance, Platform } from 'react-native';
import { mapState } from 'store/store';
import { BathroomsInView } from 'utils/privy';

Mapbox.setAccessToken(
  'pk.eyJ1Ijoic2Fsdmlub3RvIiwiYSI6ImNqdW12ZXVpcTBmdHI0M3Bna2traG1zYXEifQ.Jq6Nu3b805TU4ZjpBfhXZA'
);

export const Map = () => {
  const [colorScheme, setColorScheme] = React.useState(Appearance.getColorScheme());
  const [bathrooms, setBathrooms] = React.useState<
    Database['public']['Functions']['bathrooms_in_view']['Returns']
  >([]);
  const [zoomLevel, setZoomLevel] = React.useState(0);
  const [userLocation, setUserLocation] = React.useState<[number, number]>([0, 0]);
  const [isDragging, setIsDragging] = React.useState(false);
  const map = React.useRef<Mapbox.MapView | null>(null);
  const camera = React.useRef<Mapbox.Camera>(null);

  // Light/Darkmode listener
  useEffect(() => {
    Appearance.addChangeListener(({ colorScheme }) => setColorScheme(colorScheme));
  }, []);

  // Fetch bathrooms in view to populate map
  useEffect(() => {
    async function getBathrooms() {
      const bathrooms = await BathroomsInView();
      if (bathrooms !== null) {
        setBathrooms(bathrooms);
      }
      // console.log(bathrooms);
    }
    getBathrooms();
  }, []);

  useEffect(() => {
    // console.log(restroomsGeoJSON);
  }, [bathrooms]); // Dependency array

  // Fetch user's current location
  useEffect(() => {
    async function getLocation() {
      if (Platform.OS === 'android' && !Device.isDevice) {
        console.log(
          'Oops, this will not work on Snack in an Android Emulator. Try it on your device!'
        );
        return;
      }
      const { status } = await Location.requestForegroundPermissionsAsync();
      if (status !== 'granted') {
        console.log('Permission to access location was denied');
        return;
      }
      const location = await Location.getCurrentPositionAsync({});
      setUserLocation([location.coords.latitude, location.coords.longitude]);
    }
    getLocation();
    console.log(userLocation);
  }, []);

  const isDarkMode = colorScheme === 'dark';

  const handleRegionChange = React.useMemo(() => {
    return async (state: {
      properties: {
        center: GeoJSON.Position;
        bounds: {
          ne: GeoJSON.Position;
          sw: GeoJSON.Position;
        };
        zoom: number;
        heading: number;
        pitch: number;
      };
      gestures: {
        isGestureActive: boolean;
      };
      timestamp?: number;
    }) => {
      // Perform asynchronous operations here
      const zoomLevel = state.properties.zoom;
      setZoomLevel(zoomLevel);

      // Calculate the bounding box
      mapState.min_lat = state.properties.bounds.sw[1];
      mapState.max_lat = state.properties.bounds.ne[1];
      mapState.min_long = state.properties.bounds.sw[0];
      mapState.max_long = state.properties.bounds.ne[0];

      const bathrooms = await BathroomsInView();
      if (bathrooms !== null) {
        setBathrooms(bathrooms);
      }
    };
  }, []);

  const restroomsGeoJSON: GeoJSON.FeatureCollection = {
    type: 'FeatureCollection',
    features: bathrooms.map((restroom, index) => ({
      type: 'Feature',
      id: index.toString(),
      properties: {
        ...restroom,
        title: restroom.name, // Make sure 'title' is a property in the 'properties' object
      },
      geometry: {
        type: 'Point',
        coordinates: [restroom.long, restroom.lat],
      },
    })),
  };

  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <Mapbox.MapView
          style={styles.map}
          logoEnabled={false}
          compassEnabled
          styleURL={
            isDarkMode
              ? 'mapbox://styles/salvinoto/clo6hwg2n00ks01qx5k2k3slm'
              : 'mapbox://styles/salvinoto/clo8xe5uf00nw01o3b8cjbm97'
          }
          scaleBarEnabled={false}
          onMapIdle={handleRegionChange}
        />
        {/* <Mapbox.Camera followUserLocation followZoomLevel={14} centerCoordinate={userLocation} /> */}
        <Mapbox.UserLocation visible />
        {/* ShapeSource for plotting bathrooms on map */}
        <Mapbox.ShapeSource
          id="restroomSource"
          shape={restroomsGeoJSON}
          cluster
          clusterRadius={50}
          clusterMaxZoomLevel={14}
          onPress={async (e) => {
            const feature = e.features[0];
            if (feature.properties?.cluster && 'coordinates' in feature.geometry) {
              const currentZoomLevel = map ? await map.current?.getZoom() : 0;
              if (
                Array.isArray(feature.geometry.coordinates) &&
                typeof feature.geometry.coordinates[0] === 'number'
              ) {
                camera?.current?.setCamera({
                  centerCoordinate: feature.geometry.coordinates as [number, number],
                  zoomLevel: currentZoomLevel! + 2,
                });
              }
            } else if (feature.properties) {
              // TODO: Open modal
              //   setRestroomDetails(feature.properties as IRestroomAPI);
            }
          }}>
          <Mapbox.Images
            images={{
              doorClosed: require('../assets/images/map/door-closed-blue.png'),
            }}
          />
          <Mapbox.SymbolLayer
            id="restroomLayer"
            sourceID="restroomSource"
            filter={['!', ['has', 'point_count']]}
            style={{
              iconImage: 'doorClosed',
              iconSize: 0.25, // Set the size of the icon
              iconAllowOverlap: true,
              textField: '{title}', // Replace with the property name from your data
              textFont: ['DIN Offc Pro Medium', 'Arial Unicode MS Bold'],
              textSize: 12,
              textTransform: 'uppercase',
              textLetterSpacing: 0.1,
              textOffset: [1.5, 0],
              textColor: '#3498db', // Set the color of the text
              textHaloColor: '#FFFFFF', // Set the color of the text's halo
              textHaloWidth: 2, // Set the width of the text's halo
              textAnchor: 'left', // Anchor the text to the top
              textJustify: 'center', // Justify the text automatically
            }}
          />
          <Mapbox.CircleLayer
            id="clusteredPoints"
            sourceID="restroomSource"
            belowLayerID="restroomLayer"
            filter={['has', 'point_count']}
            style={{
              circleColor: [
                'step',
                ['get', 'point_count'],
                '#51bbd6',
                100,
                '#f1f075',
                750,
                '#f28cb1',
              ],
              circleRadius: ['step', ['get', 'point_count'], 20, 100, 30, 750, 40],
              circleOpacity: 0.7,
            }}
          />
          <Mapbox.SymbolLayer
            id="clusterCount"
            sourceID="restroomSource"
            filter={['has', 'point_count']}
            style={{
              textField: '{point_count_abbreviated}',
              textSize: 12,
              textTransform: 'uppercase',
              textAllowOverlap: true,
              textColor: '#FFFFFF', // Set the color of the text
              textFont: ['DIN Offc Pro Medium', 'Arial Unicode MS Bold'],
            }}
          />
        </Mapbox.ShapeSource>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    ...StyleSheet.absoluteFillObject,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});

### Observed behavior and steps to reproduce

After updating to latest mapbox I am getting these errors when trying to run in iOS simulator:

 ERROR  TypeError: 0, _expoModulesCore.requireOptionalNativeModule is not a function (it is undefined), js engine: hermes
 ERROR  TypeError: 0, _expoModulesCore.requireOptionalNativeModule is not a function (it is undefined), js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

I have modified nothing else other than upgrading the the latest version map box and installling with pods. How can I resolve this issue?

**Comment by salvinoto** [comment]
I have no code to show it just broke when updating

**Comment by mfazekas** [comment]
Maybe you've upgraded expo too by mistake. Try creating a new app then compare or move the old stuff over. Sorry it's not something we can help with
