### ISSUE TITLE
iOS Pod error even after following setup

### ISSUE THREAD

**Issue by gsk143** [rnmapbox/maps#3360]
## Environment
- MacOS  13.2.1
- @rnmapbox/maps version: 10.1.10 
- React Native version: 0.73.3
## Steps to reproduce
Create a bare RN project and add the following pod file
```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

$RNMapboxMapsVersion = '= 11.0.0'

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyMobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end


  target 'MyMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    $RNMapboxMaps.post_install(installer)
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

```
<img width="1285" alt="Screenshot 2024-02-07 at 11 14 54 AM" src="https://github.com/rnmapbox/maps/assets/60306998/b51c0130-1eab-4fd3-b6f3-e03c6fa8687e">

I have also taken your example code and tried to run it. I am not gettting 404 error and curl shows the output but I get different issue. Any help is appreciated thanks
<img width="1283" alt="Screenshot 2024-02-07 at 11 22 06 AM" src="https://github.com/rnmapbox/maps/assets/60306998/925e6264-0a33-4ebe-b24e-e9ce546f370a">

**Comment by mfazekas** [comment]
401 means unauthorised, so you have not properly configured your credentials

See `Configure Credentials` step https://rnmapbox.github.io/docs/install and  https://rnmapbox.github.io/docs/install#verify-netrc

**Comment by gsk143** [comment]
Hi @mfazekas sorry for raising again but I did follow the setup as said and I can see I did create the ~/.netrc file and even ran chmod -R 0600 ~/.netrc to give the permissions. In the token as well I set **Downloads:Read** but still I am getting this error. Is there something wrong I am doing?

**Comment by gsk143** [comment]
After some digging I found the issue is due https://github.com/curl/curl/issues/3455 so if anyone facing this issue, update your curl by following https://everything.curl.dev/install/macos. Hope this helps.
