### ISSUE TITLE
[Bug]: ERROR Mapbox error setWellKnownTileServer is deprecated and will be removed {"level": "error", "message": "setWellKnownTileServer is deprecated and will be removed", "tag": "RNMBXModule"}

### ISSUE THREAD

**Issue by kodeandoec** [rnmapbox/maps#3367]
### Mapbox Implementation

Mapbox

### Mapbox Version

"@rnmapbox/maps": "^10.1.8",

### Platform

Android

### `@rnmapbox/maps` version

"@rnmapbox/maps": "^10.1.8",

### Standalone component to reproduce

<Mapbox.MapView 
        style={StyleSheet.absoluteFill}
        logoEnabled={false}
        attributionEnabled={false}
        scaleBarEnabled={false}
        onLayout={load}
      >
        <Mapbox.UserLocation
          showsUserHeadingIndicator={true}
          visible={true}
          animated={true}
        />
        <Mapbox.Camera
          ref={cameraRef}
          zoomLevel={16}
          centerCoordinate={[ lonActual, latActual ]}
          animationMode={'flyTo'}
          animationDuration={3000}
        />
        {}
      </Mapbox.MapView>

### Observed behavior and steps to reproduce

<img width="1041" alt="Captura de pantalla 2024-02-08 a la(s) 10 40 24" src="https://github.com/rnmapbox/maps/assets/73835732/1c9fbf08-44fe-470b-9ea7-911ebb70680b">

### Expected behavior

<img width="1041" alt="Captura de pantalla 2024-02-08 a la(s) 10 40 24" src="https://github.com/rnmapbox/maps/assets/73835732/1c9fbf08-44fe-470b-9ea7-911ebb70680b">

### Notes / preliminary analysis

<img width="1041" alt="Captura de pantalla 2024-02-08 a la(s) 10 40 24" src="https://github.com/rnmapbox/maps/assets/73835732/1c9fbf08-44fe-470b-9ea7-911ebb70680b">

### Additional links and references

<img width="1041" alt="Captura de pantalla 2024-02-08 a la(s) 10 40 24" src="https://github.com/rnmapbox/maps/assets/73835732/1c9fbf08-44fe-470b-9ea7-911ebb70680b">

**Comment by get-Friday** [comment]
To fix remove `Mapbox.setWellKnownTileServer('Mapbox');` from your code
