### ISSUE TITLE
[Bug]: Camera.zoomTo not working

### ISSUE THREAD

**Issue by g4rb4g3** [rnmapbox/maps#3389]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.1.0

### React Native Version

0.72.6

### Platform

iOS

### `@rnmapbox/maps` version

10.1.13

### Standalone component to reproduce

MapboxGL.Camera.zoomTo seems to be broken, it tries to call setCamera without centerCoordinate and without bounds which are required in RNMBXCamera.swift

https://github.com/rnmapbox/maps/blob/main/ios/RNMBX/RNMBXCamera.swift#L402
https://github.com/rnmapbox/maps/blob/main/ios/RNMBX/RNMBXCamera.swift#L425

With both props missing the camera check will make it return without zooming.
https://github.com/rnmapbox/maps/blob/main/ios/RNMBX/RNMBXCamera.swift#L464

### Observed behavior and steps to reproduce

Nothing is happening when calling zoomTo

### Expected behavior

zooming should work

**Comment by g4rb4g3** [comment]
@mfazekas Sorry for not providing an example but from the information I provided it should be pretty easy to understand what is not working. Could you still check it please? Thanks!

**Comment by anis-18** [comment]
Also not working for me

**Comment by anis-18** [comment]
Any fix for this issue ???

**Comment by cyrilmarceau** [comment]
Same problem on iOS with version 11.0.0

**Comment by illlama** [comment]
I'm getting same issue too.

**Comment by efstathiosntonas** [comment]
Any updates on this one? It's still an issue on `10.1.24`
