### ISSUE TITLE
[Upstream Bug]: Camera centers incorrectly around bounds with padding

### ISSUE THREAD

**Issue by naftalibeder** [rnmapbox/maps#3394]
This is a placeholder issue to track an upstream bug. See https://github.com/mapbox/mapbox-maps-ios/issues/2134.

**Comment by naftalibeder** [comment]
@mfazekas I'm not sure how to keep this open without adding the full issue template, but I don't think that really applies here.

**Comment by mfazekas** [comment]
> I'm not sure how to keep this open without adding the full issue template, but I don't think that really applies here. 

The bot only requires a rn component to reproduce the issue. I think that applies here as well.
