### ISSUE TITLE
[Bug]: Map is not usable in a (horizontal) ScrollView on Android

### ISSUE THREAD

**Issue by mattijsf** [rnmapbox/maps#3420]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.16.4

### React Native Version

0.73.5

### Platform

Android

### `@rnmapbox/maps` version

10.1.19

### Standalone component to reproduce

```tsx
import MapboxGL from "@rnmapbox/maps"
import React, { useMemo } from "react"
import { ScrollView, Text, View, ViewStyle, useWindowDimensions } from "react-native"

const MapboxScrollViewBug = () => {
  const { width: windowWidth } = useWindowDimensions()

  const pageContainer = useMemo((): ViewStyle => ({
      width: windowWidth,
      alignItems: "center",
      justifyContent: "space-around",
    }),
    [windowWidth]
  )

  return (
    <ScrollView
      horizontal
      pagingEnabled
      nestedScrollEnabled
      directionalLockEnabled
      showsHorizontalScrollIndicator={false}
      showsVerticalScrollIndicator={false}
      style={{ flex: 1 }}
    >
      <View style={[pageContainer, { backgroundColor: "aqua" }]}>
        <MapboxGL.MapView style={{ width: "100%", height: "50%" }} />
        <Text>Slide 1</Text>
      </View>
      <View style={[pageContainer, { backgroundColor: "beige" }]}>
        <Text>Slide 2</Text>
      </View>
      <View style={[pageContainer, { backgroundColor: "coral" }]}>
        <Text>Slide 3</Text>
      </View>
    </ScrollView>
  )
}

export default MapboxScrollViewBug
```````

### Observed behavior and steps to reproduce

When dragging the map within a ScrollView on Android the gesture is being recognized by the ScrollView and as a result interaction with the map is not possible. 

<img src="https://github.com/rnmapbox/maps/assets/706368/33d49866-e1aa-4741-b6d6-029298b86fbb" />

### Expected behavior

When dragging the map within a ScrollView I expect the MapView to take ownership of the gesture and prevent the Scrollview from responding to the pan gesture.

### Notes / preliminary analysis

- Only On Android
- Also tried wrapping with [NativeViewGestureHandler](https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-handlers/nativeview-gh)
- Using react-native-gesture-handler's [ScrollView](https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-handlers/about-handlers/#using-native-components)
- Only to happen in the direction of the Scrollview. So panning vertically in a horizontal ScrollView is recognized by the MapView and the map starts panning, as soon as you transition this gesture towards a horizontal one (within the same gesture) the ScrollView takes over (not showcased in the video though)

### Additional links and references

Test project also available at: https://github.com/mattijsf/mapbox-scrollview-test/

**Comment by mattijsf** [comment]
Ouch that bot is very strict on Typescript / eslint-disable notations 😅

**Comment by mfazekas** [comment]
> Ouch that bot is very strict on not allowing Typescript / eslint-disable notations 😅

Code is here, feel free to open PR with improvements:
https://github.com/rnmapbox/maps/tree/main/scripts/actions/lint-code-example-in-issues

**Comment by mattijsf** [comment]
> > Ouch that bot is very strict on not allowing Typescript / eslint-disable notations 😅
> 
> Code is here, feel free to open PR with improvements: [`main`/scripts/actions/lint-code-example-in-issues](https://github.com/rnmapbox/maps/tree/main/scripts/actions/lint-code-example-in-issues?rgh-link-date=2024-03-11T11%3A22%3A23Z)

Regarding the bot, I looked at the script and discovered that the bot was not checking typescript because I wrote the snippet in a \```javascript block instead of \```typescript

**Comment by mattijsf** [comment]
I just added `requestDisallowInterceptTouchEvent` and it seems to work great now on Android. It's even documented, I missed it. Sorry.
