### ISSUE TITLE
[Bug]: TypeScript style props exports not working properly

### ISSUE THREAD

**Issue by EmilJunker** [rnmapbox/maps#3428]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### React Native Version

0.73.6

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.1.19

### Standalone component to reproduce

```tsx
// Note: Your linter doesn't allow me to import from node_modules, so I commented out the corresponding lines.
// Please just uncomment them and you will be able to reproduce the bug.

import type { SymbolLayerStyle as StyleImportVariantA } from '@rnmapbox/maps';
import { SymbolLayerStyle as StyleImportVariantB } from '@rnmapbox/maps';
// import { SymbolLayerStyle as StyleImportVariantC } from './node_modules/@rnmapbox/maps/src/Mapbox';

export const styleA: StyleImportVariantA = {
    iconAnchor: 'foo',
};

export const styleB: StyleImportVariantB = {
    iconAnchor: 'foo',
};

// export const styleC: StyleImportVariantC = {
//     iconAnchor: 'foo',
// };
```

### Observed behavior and steps to reproduce

Observe that only the third import variant works properly and shows a type warning when I try to assign an invalid value "foo" as `iconAnchor`.
When I import the `SymbolLayerStyle` type directly from `@rnmapbox/maps`, it does not work properly (note the absence of any type warnings).

![image](https://github.com/rnmapbox/maps/assets/19289477/6e4f0168-2280-4765-8df2-19255cad0bd4)

### Expected behavior

Importing `SymbolLayerStyle` from `@rnmapbox/maps` should work properly.

**Comment by mfazekas** [comment]
We don't export those, as you can use `ComponentProps` to extract from SymbolLayer, and don't import from NodeModules as that is unsupported.

```tsx
import React, { ComponentProps } from 'react';
import { SymbolLayer } from '@rnmapbox/maps';
type SymboLayerStyle = ComponentProps<typeof SymbolLayer>['style'];
```

**Comment by EmilJunker** [comment]
@mfazekas Thank you for the hint, I was not aware of `ComponentProps`. However, even after implementing your suggestion, it still doesn't work correctly for me. I can still assign random values to the variable of type SymboLayerStyle without getting any type warnings:

```ts
import { ComponentProps } from 'react';
import { SymbolLayer } from '@rnmapbox/maps';

type SymboLayerStyle = ComponentProps<typeof SymbolLayer>['style'];

export const styles: SymboLayerStyle = {
    foo: 'bar',
};
```

![image](https://github.com/rnmapbox/maps/assets/19289477/b5ff2659-66ee-4969-a9fc-bc6573819cc6)

Am I doing something wrong or is this an issue with @rnmapbox/maps?

**Comment by giladgray** [comment]
it would be ideal if you could just export the original Props interfaces. `React.ComponentProps` is a poor substitute for access to the original, especially if the original is composed of several interfaces (like a CommonProps and then some specific ones). the former `react-native-mapbox-gl/maps` library exported all the props and it was really nice. 

please consider exporting them.
