### ISSUE TITLE
Support for iOS 12.4 with Mapbox Maps SDK v11

### ISSUE THREAD

**Issue by hexadecy** [rnmapbox/maps#3432]
## Issue

[!] The platform of the target `RNMapboxGLExample` (iOS 12.4) may not be compatible with `rnmapbox-maps (10.1.19)` which has a minimum requirement of iOS 13.0.

## Solution
Can we lower the requirement in the podspec file to iOS 12.4?
We have some users on iPad Air that can't update past iOS 12.5.7.
It compiles and the example runs well with React-Native 0.72.12
The minimum requirement for Mapbox Maps SDK v11 is 12.0, but React-Native 0.69.x-0.72.x needs at least 12.4.

## Environment
- Dev OS: macOS 14.4
- Apple M1 Pro
- Xcode 15.3
- @rnmapbox/maps version: 10.1.19
- React Native version: 0.72.12

## Steps to reproduce
- Example with react-native 0.72.12
- target ios 12.4
- no automaticPodsInstallation
- $RNMapboxMapsVersion = '= 11.1.0'

```sh
cd example
yarn
RNMBX11=1 yarn pod:install
```

**Comment by mfazekas** [comment]
https://github.com/rnmapbox/maps/blob/8c80033e6411debb84d6ee679185b73d40f5da9d/rnmapbox-maps.podspec#L226

Can you make PR for this?

**Comment by hexadecy** [comment]
Yeah sure and I will add some fixes for the Example project.
