### ISSUE TITLE
[Bug]: Execution failed for task ':rnmapbox_maps:compileDebugKotlin'

### ISSUE THREAD

**Issue by fixer4013** [rnmapbox/maps#3480]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.17.0

### React Native Version

0.72.7

### Platform

Android

### `@rnmapbox/maps` version

10.1.21

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Good day, in an attempt to run my project on android after updating to the 10.1.21 version, I get this error rnmapbox_maps:compileDebugKotlin: failed. I was wondering what the workaround fix for this might be. From what I can see the latest update is related to the PrivacyInfo files for the IOS build where I have no issues, but android does not seem to like them.

```
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (324, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (328, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (332, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (336, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (340, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (344, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (348, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (352, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (356, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (360, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (364, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (368, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (372, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (376, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (380, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (384, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (388, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt: (392, 5): Unresolved reference: TODO
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/style.kt: (7, 63): Unresolved reference: HashMap
e: /Users/martinyankov/immotech/immotech-app/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/style.kt: (8, 12): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/martinyankov/.gradle/caches/transforms-3/29b84db2cdfda5f4957ed70faa28c917/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 28s
error Failed to install the app.
info Run CLI with --verbose flag for more details.
martinyankov@Martins-Mac-mini immotech-app % 
```

**Comment by OverStackedLab** [comment]
This is what I'm running and its working:

```
// android/build.gradle
ext {
  ...
   kotlinVersion = '1.8.0'
}
...
dependencies {
  ...
    classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0')
 }
```

"@rnmapbox/maps": "^10.1.21",

**Comment by Syed-Anas-Ahmed** [comment]
I created a bare Expo project and just installed the @rnmapbox/maps package and setup the download key. Upon running the dev build (npx expo run:android), it's still throwing this error.

Mapbox Version: 10.1.30
RN Version: 0.74.5

My build.gradle file looks like this

```// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '34.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '23')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '34')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '34')
        kotlinVersion = findProperty('android.kotlinVersion') ?: '1.9.23'

        ndkVersion = "26.1.10909125"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle')
        classpath('com.facebook.react:react-native-gradle-plugin')
        classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')
    }
}

apply plugin: "com.facebook.react.rootproject"

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(['node', '--print', "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), '../android'))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(['node', '--print', "require.resolve('jsc-android/package.json', { paths: [require.resolve('react-native/package.json')] })"].execute(null, rootDir).text.trim(), '../dist'))
        }

        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}
// @generated begin @rnmapbox/maps-v2-maven - expo prebuild (DO NOT MODIFY) sync-32f1b7024bb5099f2805443b1960a3233ccde124

allprojects {
  repositories {
    maven {
      url 'https://api.mapbox.com/downloads/v2/releases/maven'
      authentication { basic(BasicAuthentication) }
      credentials {
        username = 'mapbox'
        password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
      }
    }
  }
}

// @generated end @rnmapbox/maps-v2-maven```

**Comment by syedmumersajjad** [comment]
Mac User:
https://docs.expo.dev/troubleshooting/clear-cache-macos-linux/

Windows
https://docs.expo.dev/troubleshooting/clear-cache-windows/

**Comment by tdavis10** [comment]
> I created a bare Expo project and just installed the @rnmapbox/maps package and setup the download key. Upon running the dev build (npx expo run:android), it's still throwing this error.
> 
> Mapbox Version: 10.1.30 RN Version: 0.74.5
> 
> My build.gradle file looks like this
> 
> ```
> 
> buildscript {
>     ext {
>         buildToolsVersion = findProperty('android.buildToolsVersion') ?: '34.0.0'
>         minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '23')
>         compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '34')
>         targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '34')
>         kotlinVersion = findProperty('android.kotlinVersion') ?: '1.9.23'
> 
>         ndkVersion = "26.1.10909125"
>     }
>     repositories {
>         google()
>         mavenCentral()
>     }
>     dependencies {
>         classpath('com.android.tools.build:gradle')
>         classpath('com.facebook.react:react-native-gradle-plugin')
>         classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')
>     }
> }
> 
> apply plugin: "com.facebook.react.rootproject"
> 
> allprojects {
>     repositories {
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url(new File(['node', '--print', "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), '../android'))
>         }
>         maven {
>             // Android JSC is installed from npm
>             url(new File(['node', '--print', "require.resolve('jsc-android/package.json', { paths: [require.resolve('react-native/package.json')] })"].execute(null, rootDir).text.trim(), '../dist'))
>         }
> 
>         google()
>         mavenCentral()
>         maven { url 'https://www.jitpack.io' }
>     }
> }
> // @generated begin @rnmapbox/maps-v2-maven - expo prebuild (DO NOT MODIFY) sync-32f1b7024bb5099f2805443b1960a3233ccde124
> 
> allprojects {
>   repositories {
>     maven {
>       url 'https://api.mapbox.com/downloads/v2/releases/maven'
>       authentication { basic(BasicAuthentication) }
>       credentials {
>         username = 'mapbox'
>         password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
>       }
>     }
>   }
> }
> 
> // @generated end @rnmapbox/maps-v2-maven```
> ```

@Syed-Anas-Ahmed Did you ever figure this out? i have the same versioning as you and running into the same error

**Comment by Syed-Anas-Ahmed** [comment]
Downgraded to 10.1.29 and it works

**Comment by SaleemMaini** [comment]
I tried all the mentioned solutions in this discussion and nothing worked. still have the same error.
versions
"react-native": "0.74.5"
"@rnmapbox/maps": "^10.1.21"
"RNMapboxMapsVersion": "10.17.0",

**Comment by Syed-Anas-Ahmed** [comment]
> I tried all the mentioned solutions in this discussion and nothing worked. still have the same error.
> versions
> "react-native": "0.74.5"
> "@rnmapbox/maps": "^10.1.21"
> "RNMapboxMapsVersion": "10.17.0",

Is 10.1.29 not working too?

**Comment by SaleemMaini** [comment]
> > I tried all the mentioned solutions in this discussion and nothing worked. still have the same error.
> > versions
> > "react-native": "0.74.5"
> > "@rnmapbox/maps": "^10.1.21"
> > "RNMapboxMapsVersion": "10.17.0",
> 
> Is 10.1.29 not working too?

yes I tried it also didn't work

**Comment by SaleemMaini** [comment]
finally it's worked on 10.1.31-rc.1

**Comment by brunobarretta** [comment]
Upgrade to 10.1.31 and it works

**Comment by Xx-Parks-xX** [comment]
Oh thanks, upgrading to 10.1.31 works for me also

**Comment by fionhua** [comment]
果然，升级到 10.1.31 也对我有用

**Comment by ramchandru97** [comment]
buildscript {
    ext {
        buildToolsVersion = "34.0.0" // Changed to stable build tools version
        minSdkVersion = 24
        compileSdkVersion = 34 // Set to stable compileSdkVersion
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = '1.9.0' // Updated to 1.9.0 as per requirement
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.0.2") // Added specific version for stability
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = 'mapbox'
                password = project.findProperty('MAPBOX_DOWNLOADS_TOKEN') ?: ""
            }
        }
    }
}

apply plugin: "com.facebook.react.rootproject"


  "dependencies": {
    "@rnmapbox/maps": "^10.1.31",
    "react": "18.3.1",
    "react-native": "0.76.0"
  },
  
  still i'm getting same issue => > Task :rnmapbox_maps:compileDebugKotlin FAILED

**Comment by twinedo** [comment]
> buildscript { ext { buildToolsVersion = "34.0.0" // Changed to stable build tools version minSdkVersion = 24 compileSdkVersion = 34 // Set to stable compileSdkVersion targetSdkVersion = 34 ndkVersion = "26.1.10909125" kotlinVersion = '1.9.0' // Updated to 1.9.0 as per requirement } repositories { google() mavenCentral() } dependencies { classpath("com.android.tools.build:gradle:8.0.2") // Added specific version for stability classpath("com.facebook.react:react-native-gradle-plugin") classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion") } }
> 
> allprojects { repositories { google() mavenCentral() maven { url 'https://api.mapbox.com/downloads/v2/releases/maven' authentication { basic(BasicAuthentication) } credentials { username = 'mapbox' password = project.findProperty('MAPBOX_DOWNLOADS_TOKEN') ?: "" } } } }
> 
> apply plugin: "com.facebook.react.rootproject"
> 
> "dependencies": { "@rnmapbox/maps": "^10.1.31", "react": "18.3.1", "react-native": "0.76.0" },
> 
> still i'm getting same issue => > Task :rnmapbox_maps:compileDebugKotlin FAILED

hey, still getting the `Task :rnmapbox_maps:compileDebugKotlin FAILED` issue ??

**Comment by twinedo** [comment]
> > > buildscript { ext { buildToolsVersion = "34.0.0" // Changed to stable build tools version minSdkVersion = 24 compileSdkVersion = 34 // Set to stable compileSdkVersion targetSdkVersion = 34 ndkVersion = "26.1.10909125" kotlinVersion = '1.9.0' // Updated to 1.9.0 as per requirement } repositories { google() mavenCentral() } dependencies { classpath("com.android.tools.build:gradle:8.0.2") // Added specific version for stability classpath("com.facebook.react:react-native-gradle-plugin") classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion") } }
> > > allprojects { repositories { google() mavenCentral() maven { url 'https://api.mapbox.com/downloads/v2/releases/maven' authentication { basic(BasicAuthentication) } credentials { username = 'mapbox' password = project.findProperty('MAPBOX_DOWNLOADS_TOKEN') ?: "" } } } }
> > > apply plugin: "com.facebook.react.rootproject"
> > > "dependencies": { "@rnmapbox/maps": "^10.1.31", "react": "18.3.1", "react-native": "0.76.0" },
> > > still i'm getting same issue => > Task :rnmapbox_maps:compileDebugKotlin FAILED
> > 
> > 
> > hey, still getting the `Task :rnmapbox_maps:compileDebugKotlin FAILED` issue ?? please tell me when you pass the issue
> 
> for me it works on "@rnmapbox/maps": "^10.1.33"

hey, can you share your kotlin version, buildTools, ndk etc
i tried those versions but still got error

**Comment by SmitChavan24** [comment]
> buildscript { ext { buildToolsVersion = "34.0.0" // Changed to stable build tools version minSdkVersion = 24 compileSdkVersion = 34 // Set to stable compileSdkVersion targetSdkVersion = 34 ndkVersion = "26.1.10909125" kotlinVersion = '1.9.0' // Updated to 1.9.0 as per requirement } repositories { google() mavenCentral() } dependencies { classpath("com.android.tools.build:gradle:8.0.2") // Added specific version for stability classpath("com.facebook.react:react-native-gradle-plugin") classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion") } }
> 
> allprojects { repositories { google() mavenCentral() maven { url 'https://api.mapbox.com/downloads/v2/releases/maven' authentication { basic(BasicAuthentication) } credentials { username = 'mapbox' password = project.findProperty('MAPBOX_DOWNLOADS_TOKEN') ?: "" } } } }
> 
> apply plugin: "com.facebook.react.rootproject"
> 
> "dependencies": { "@rnmapbox/maps": "^10.1.31", "react": "18.3.1", "react-native": "0.76.0" },
> 
> still i'm getting same issue => > Task :rnmapbox_maps:compileDebugKotlin FAILED

I am experiencing same issue after upgrading react-native, kotlinVersion = "1.9.24"

**Comment by allthetime** [comment]
Fresh install of latest versions today gives this issue. Tried playing with kotlinVersions, nothing helps so far. 

kotlinVersion = "2.0.21"
"@rnmapbox/maps": "^10.1.37"
"react-native": "0.78.0"

**Comment by Akifcan** [comment]
> > Fresh install of latest versions today gives this issue. Tried playing with kotlinVersions, nothing helps so far.
> > kotlinVersion = "2.0.21" "@rnmapbox/maps": "^10.1.37" "react-native": "0.78.0"
> 
> I have same error with similar versions, you solved it? kotlinVersion = "2.0.21" "@rnmapbox/maps": "^10.1.37" "react-native": "0.78.1"

Same for me, same environments

**Comment by generic-delta** [comment]
Same issue on mine as well

kotlinVersion = "2.0.21"
"@rnmapbox/maps": "^10.1.38"
"react-native": "0.78.2"

**Comment by ajdelaf** [comment]
Glad to see I'm not alone, but sad to see nobody's happened across a solution yet.

Getting `app:processDebugMainManifest FAILED` with versions:

kotlinVersion = "2.0.21"
"@rnmapbox/maps": "^10.1.38"
"react-native": "0.79.2"

**Comment by abbasKareem** [comment]
any updates ?!

**Comment by kakajann** [comment]
The issue still there

**Comment by UchihaVeha** [comment]
Got the same error on a just-started Expo project

**Comment by generic-delta** [comment]
> Glad to see I'm not alone, but disappointed to see the issue has been closed without a proper solution.
> 
> Getting `app:processDebugMainManifest FAILED` with versions:
> 
> kotlinVersion = "2.0.21" "@rnmapbox/maps": "^10.1.38" "react-native": "0.79.2"

For those whose still encountering this issue install this patch from [baralmanish](https://github.com/rnmapbox/maps/issues/3753#issuecomment-2809089587)

**Comment by gusow** [comment]
This worked for me!

**Comment by UchihaVeha** [comment]
> > Glad to see I'm not alone, but disappointed to see the issue has been closed without a proper solution.
> > Getting `app:processDebugMainManifest FAILED` with versions:
> > kotlinVersion = "2.0.21" "@rnmapbox/maps": "^10.1.38" "react-native": "0.79.2"
> 
> For those whose still encountering this issue install this patch from [baralmanish](https://github.com/rnmapbox/maps/issues/3753#issuecomment-2809089587)

It doesn't help me. Still get error: "Execution failed for task ':rnmapbox_maps:compileDebugKotlin'."

**Comment by generic-delta** [comment]
> > > Glad to see I'm not alone, but disappointed to see the issue has been closed without a proper solution.
> > > Getting `app:processDebugMainManifest FAILED` with versions:
> > > kotlinVersion = "2.0.21" "@rnmapbox/maps": "^10.1.38" "react-native": "0.79.2"
> > 
> > 
> > For those whose still encountering this issue install this patch from [baralmanish](https://github.com/rnmapbox/maps/issues/3753#issuecomment-2809089587)
> 
> It doesn't help me. Still get error: "Execution failed for task ':rnmapbox_maps:compileDebugKotlin'."
> 
> `"expo": "~53.0.9", "react-native": "0.79.2", "@rnmapbox/maps": "^10.1.38",`

You can try to do a clean build for android and clear cache metro, uninstall partially installed app in the emulator as well if there is any.

**Comment by sanjanaynvsdl** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

I just initialized an Expo app and installed rnmapbox, but I'm still facing issues. I've tried all the working versions mentioned in the discussion. Can someone help me out?

**Comment by mazumate** [comment]
Issue persists

**Comment by rhasve** [comment]
finally!

**Comment by VARN0R** [comment]
Same issue(
  "react-native": "0.79.2",
"@rnmapbox/maps": "^10.1.38",

```
> Configure project :react-native-reanimated
Android gradle plugin: 8.8.2
Gradle: 8.13

> Task :rnmapbox_maps:compileDebugKotlin FAILED
e: file:///C:/Users/vladi/OneDrive/Desktop/find-route/node_modules/@rnmapbox/maps/android/src/main/java/com/rnmapbox/rnmbx/components/images/RNMBXImagesManager.kt:252:29 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'com.facebook.react.bridge.ReadableArray?'
```

**Comment by VARN0R** [comment]
> Same issue( "react-native": "0.79.2", "@rnmapbox/maps": "^10.1.38",
> 
> ```
> > Configure project :react-native-reanimated
> Android gradle plugin: 8.8.2
> Gradle: 8.13
> 
> > Task :rnmapbox_maps:compileDebugKotlin FAILED
> e: file:///C:/Users/vladi/OneDrive/Desktop/find-route/node_modules/@rnmapbox/maps/android/src/main/java/com/rnmapbox/rnmbx/components/images/RNMBXImagesManager.kt:252:29 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'com.facebook.react.bridge.ReadableArray?'
> ```

I was able to find a solution here: https://github.com/rnmapbox/maps/issues/3753#issuecomment-2809089587

**Comment by VARN0R** [comment]
> Issue persists

Check here:  https://github.com/rnmapbox/maps/issues/3753#issuecomment-2809089587

**Comment by ghost** [comment]
I downgraded it from : @rnmapbox/[maps@10.1.39
to: @rnmapbox/[maps@10.1.38
and it works for me

**Comment by ilovepreet** [comment]
Any one please provide me zip file?
This is urgent

**Comment by facuescobar** [comment]
Having this error too,
I can't find the right configuration to get this compiled on Android.


``` 
 "@rnmapbox/maps": "^10.1.38",
 "react-native": "0.77.2",
 "react": "18.3.1",
```

```
buildscript {
    ext {
        buildToolsVersion = "35.0.0"
        minSdkVersion = 24
        compileSdkVersion = 35
        targetSdkVersion = 34
        ndkVersion = "27.1.12297006"
        kotlinVersion = "2.0.21"
    }
```

```
> Task :rnmapbox_maps:compileDebugKotlin FAILED
472 actionable tasks: 56 executed, 416 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/.../node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: file:///Users/.../node_modules/@rnmapbox/maps/android/src/main/lifecycle-compat/v25/com/rnmapbox/rnmbx/components/mapview/LifecycleCompat.kt:8:27 Unresolved reference 'ViewTreeLifecycleOwner'.
e: file:///Users/.../node_modules/@rnmapbox/maps/android/src/main/lifecycle-compat/v25/com/rnmapbox/rnmbx/components/mapview/LifecycleCompat.kt:22:30 Class '<anonymous>' is not abstract and does not implement abstract member 'lifecycle'.
e: file:///Users/.../node_modules/@rnmapbox/maps/android/src/main/lifecycle-compat/v25/com/rnmapbox/rnmbx/components/mapview/LifecycleCompat.kt:38:17 'getLifecycle' overrides nothing.
e: file:///Users/.../node_modules/@rnmapbox/maps/android/src/main/lifecycle-compat/v25/com/rnmapbox/rnmbx/components/mapview/LifecycleCompat.kt:43:13 Unresolved reference 'ViewTreeLifecycleOwner'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 7s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installLocalDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/.../node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: file:///Users/.../node_modules/@rnmapbox/maps/android/src/main/lifecycle-compat/v25/com/rnmapbox/rnmbx/components/mapview/LifecycleCompat.kt:8:27 Unresolved reference 'ViewTreeLifecycleOwner'.
e: file:///Users/.../node_modules/@rnmapbox/maps/android/src/main/lifecycle-compat/v25/com/rnmapbox/rnmbx/components/mapview/LifecycleCompat.kt:22:30 Class '<anonymous>' is not abstract and does not implement abstract member 'lifecycle'.
e: file:///Users/.../node_modules/@rnmapbox/maps/android/src/main/lifecycle-compat/v25/com/rnmapbox/rnmbx/components/mapview/LifecycleCompat.kt:38:17 'getLifecycle' overrides nothing.
e: file:///Users/.../node_modules/@rnmapbox/maps/android/src/main/lifecycle-compat/v25/com/rnmapbox/rnmbx/components/mapview/LifecycleCompat.kt:43:13 Unresolved reference 'ViewTreeLifecycleOwner'. FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 7s.
info Run CLI with --verbose flag for more details.
```

**Comment by usamahatzs** [comment]
**Any** one please provide solution 

"@rnmapbox/maps": "^10.1.38",
    "react-native": "0.80.0",



> Task :rnmapbox_maps:compileDebugKotlin FAILED

> Task :app:buildCMakeDebug[arm64-v8a]
C/C++: ninja: Entering directory `/Users/apple/Desktop/vectorApp/android/app/.cxx/Debug/394g54q2/arm64-v8a'
C/C++: In file included from /Users/apple/Desktop/vectorApp/node_modules/@rnmapbox/maps/android/build/generated/source/codegen/jni/react/renderer/components/rnmapbox_maps_specs/rnmapbox_maps_specsJSI-generated.cpp:10:
C/C++: /Users/apple/Desktop/vectorApp/node_modules/@rnmapbox/maps/android/build/generated/source/codegen/jni/react/renderer/components/rnmapbox_maps_specs/rnmapbox_maps_specsJSI.h:239:22: warning: 'facebook::react::NativeRNMBXChangeLineOffsetsShapeAnimatorModuleCxxSpecJSI::create' hides overloaded virtual function [-Woverloaded-virtual]
C/C++:   239 |   virtual jsi::Value create(jsi::Runtime &rt, int tag, jsi::Array coordinates, double startOffset, double endOffset) = 0;
C/C++:       |                      ^
C/C++: /Users/apple/.gradle/caches/8.14.1/transforms/89ee2d71482aa90a74abf94579aa4b78/transformed/react-android-0.80.0-debug/prefab/modules/reactnative/include/ReactCommon/TurboModule.h:125:22: note: hidden overloaded virtual function 'facebook::react::TurboModule::create' declared here: different number of parameters (2 vs 5)
C/C++:   125 |   virtual jsi::Value create(
C/C++:       |                      ^
C/C++: In file included from /Users/apple/Desktop/vectorApp/node_modules/@rnmapbox/maps/android/build/generated/source/codegen/jni/react/renderer/components/rnmapbox_maps_specs/rnmapbox_maps_specsJSI-generated.cpp:10:
C/C++: /Users/apple/Desktop/vectorApp/node_modules/@rnmapbox/maps/android/build/generated/source/codegen/jni/react/renderer/components/rnmapbox_maps_specs/rnmapbox_maps_specsJSI.h:535:22: warning: 'facebook::react::NativeRNMBXMovePointShapeAnimatorModuleCxxSpecJSI::create' hides overloaded virtual function [-Woverloaded-virtual]
C/C++:   535 |   virtual jsi::Value create(jsi::Runtime &rt, int tag, jsi::Array coordinate) = 0;
C/C++:       |                      ^
C/C++: /Users/apple/.gradle/caches/8.14.1/transforms/89ee2d71482aa90a74abf94579aa4b78/transformed/react-android-0.80.0-debug/prefab/modules/reactnative/include/ReactCommon/TurboModule.h:125:22: note: hidden overloaded virtual function 'facebook::react::TurboModule::create' declared here: different number of parameters (2 vs 3)
C/C++:   125 |   virtual jsi::Value create(
C/C++:       |                      ^
C/C++: 2 warnings generated.

[Incubating] Problems report is available at: file:///Users/apple/Desktop/vectorApp/android/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.14.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
73 actionable tasks: 73 executed

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

e: file:///Users/apple/Desktop/vectorApp/node_modules/@rnmapbox/maps/android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXMarkerViewManager.kt:42:64 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'ReadableArray?'.
e: file:///Users/apple/Desktop/vectorApp/node_modules/@rnmapbox/maps/android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXMarkerViewManager.kt:42:84 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'ReadableArray?'.

**Comment by KarthikRaju391** [comment]
Having the same issue. I am on react native 0.80.1 and mapbox version 10.1.38

**Comment by usamahatzs** [comment]
move 0.79.1 the mapbox working fine

**Comment by ghost** [comment]
Has anybody here found a solution?... basically after version @rnmapbox/maps@10.1.36 the builds failed...
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'

**Comment by JoeBoulton** [comment]
10.1.41 works for me

**Comment by Alvi24** [comment]
still an issue
`
 "@rnmapbox/maps": "^10.2.6",
 "react-native": "0.81.5",
`
