### ISSUE TITLE
I Have Problem with Android  Unsupported top level event type "topRct.mapbox.map.change" dispatched

### ISSUE THREAD

**Issue by mactung** [rnmapbox/maps#3493]
## Environment
- Dev OS: OSX 
- @rnmapbox/maps version:  10.1.21
- React Native version: 0.74

![Screenshot 2024-05-18 at 11 07 37](https://github.com/rnmapbox/maps/assets/55038228/3a9b8fac-0eb4-4972-af5c-18768afc9b6f)

It alway show this message.. and i can't do anything.
I placed MapView Into a Screen in BottomTabBar By React Native Navigation

And i don't have any problem On IOS with same code.

**Comment by mfazekas** [comment]
Please add a component reproducing the issue

**Comment by mactung** [comment]
please give me a example.
![Screenshot 2024-05-18 at 16 10 02](https://github.com/rnmapbox/maps/assets/55038228/e31931cb-201e-423d-978c-515a8f58cb21)
This is my code

**Comment by mactung** [comment]
> Please add a component reproducing the issue

i really don't understand what is to do next. Please explain that. Tks

**Comment by mfazekas** [comment]
> i really don't understand what is to do next. Please explain that. Tks

See https://stackoverflow.com/help/minimal-reproducible-example, write a simplified example that reproduces an issue and either include the code, or add a link to a GitHub repository.

**Comment by adishare** [comment]
I encountered the same problem when using React Native with the new architecture.
I was able to resolve it by disabling the new architecture. To do this, I modified the newArchEnabled property in android/gradle.properties @mactung . idk why this issue closed @mfazekas 

@rnmapbox/maps version: 10.1.28
React Native version: 0.74.3

**Comment by mfazekas** [comment]
@adishare please post an reproducible example I can copy paste into our example project and run. Screenshot of part of your code is not enough.

**Comment by robin-pham** [comment]
Here's a reproducible example: https://github.com/robin-pham/rnmapbox-event-name-reproduction I only configured it for the android build just to be speedy.

<img width="413" alt="Screenshot 2024-08-06 at 11 40 23 AM" src="https://github.com/user-attachments/assets/94f9875c-da5d-4cfc-850a-b177cfb544ee">


It's new architecture related, and the 'topRct' prefix is related to https://github.com/facebook/react-native/pull/42586 that normalizes event names. Otherwise I'm unsure of the code paths related to why rnmapbox's events aren't registered.

**Comment by ChrisBindy** [comment]
@mactung Did you ever find a solution to this problem? As im currently facing it myself.

**Comment by opesto** [comment]
I am also having the same issue with react-native: 0.75.2 and @rnmapbox/maps: 10.1.30. Any solutions yet?

**Comment by mactung** [comment]
> @mactung Did you ever find a solution to this problem? As im currently facing it myself.
HI mate, i had move my project to flutter. Everything be find on flutter now. :)
