### ISSUE TITLE
[Bug]: Archiving Freezes in Xcode at same exact spot.

### ISSUE THREAD

**Issue by salvinoto** [rnmapbox/maps#3513]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### React Native Version

0.74.2

### Platform

iOS

### `@rnmapbox/maps` version

10.1.24

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

When archiving for iOS t send to testflight/appstore, it freezes when 

### Expected behavior

The project should archive normally for deployment to appstore/ testflight, it freezes when buildtarget is MapBoxCoreMaps. Everything is up to date and compatible. Project compiles successfully when just using build option or simulating it. 
<img width="964" alt="Screenshot 2024-06-08 at 5 14 57 PM" src="https://github.com/rnmapbox/maps/assets/54959187/c3aff4a0-357d-4b00-99c2-f073e2ce78ed">

**Comment by mfazekas** [comment]
Closing as sounds like a project specific issue
