### ISSUE TITLE
[Bug]:  iOS crash with Thread 1: Assertion failed: the object is inited but there are still waiters

### ISSUE THREAD

**Issue by efstathiosntonas** [rnmapbox/maps#3528]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.0.0

### React Native Version

0.74.2

### Platform

iOS

### `@rnmapbox/maps` version

10.1.26

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

After upgrading to 10.1.26 it throws: 

`Thread 1: Assertion failed: the object is inited but there are still waiters`

![Screenshot 2024-06-14 at 09 37 17](https://github.com/rnmapbox/maps/assets/717975/37928cdb-4ac9-4ca0-acef-f225591e1871)

related [PR](https://github.com/rnmapbox/maps/pull/3523)

let me know if you need full trace

**Comment by mfazekas** [comment]
@efstathiosntonas thanks are you using new arch on iOS?

**Comment by efstathiosntonas** [comment]
@mfazekas Hi, no, I'm on Paper

**Comment by mfazekas** [comment]
@efstathiosntonas I'm not able to reproduce the issue:

Your stack trace 
<img width="401" alt="image" src="https://github.com/rnmapbox/maps/assets/52435/904f0633-1ccd-468a-877b-4bd374727c23">


Looks like infinite recursion. 

On the other hand I do see that we reenter addToMap and probably I'm not handling it correctly:
https://github.com/rnmapbox/maps/blob/0bcf8bb158d4fc313b9b9957791c6d63659af2fe/ios/RNMBX/RNMBXMapView.swift#L273

**Comment by efstathiosntonas** [comment]
@mfazekas thanks for the update, this is my component, it works fine on `10.1.25`: https://gist.github.com/efstathiosntonas/0e382aa2d05294585d0ca13ce099eefa

**Comment by mfazekas** [comment]
@efstathiosntonas can you try the main branch it should be fixed there

**Comment by efstathiosntonas** [comment]
@mfazekas works as a charm, thank your for the fast fix! keep it up!
