### ISSUE TITLE
[Bug]: 3D (terrain) not working on iOS

### ISSUE THREAD

**Issue by nemoneph** [rnmapbox/maps#3567]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.4.0

### React Native Version

0.74.2

### Platform

iOS

### `@rnmapbox/maps` version

10.1.23

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Mapbox
} from '@rnmapbox/maps';



class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
       <Mapbox.RasterDemSource
          id="mapbox-dem"
          url="mapbox://mapbox.mapbox-terrain-dem-v1"
          tileSize={514}
          maxZoomLevel={18}
        >
          <Mapbox.Terrain sourceID="mapbox-dem" style={{ exaggeration: 2 }} />
        </Mapbox.RasterDemSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

This is working fine on Android, but on iOS the terrain / 3D is flat (it's does nothing)

### Expected behavior

The terrain should show elevation terrain / 3D

**Comment by GBPeters** [comment]
Experiencing this too. Where's the upvote button? 😂
