### ISSUE TITLE
[Bug]: filter property doesn't work on VectorSource

### ISSUE THREAD

**Issue by petertoth-dev** [rnmapbox/maps#3575]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### React Native Version

0.72.9

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.1.27

### Standalone component to reproduce

-

### Observed behavior and steps to reproduce

When I try to add an expression to the source (I need to filter it otherwise the clusters will appear wrong), I get an error, that the filter prop doesn't exist.

### Expected behavior

filter prop should work, and accept an expression:
https://docs.mapbox.com/style-spec/reference/sources/#geojson-filter

### Additional links and references

https://docs.mapbox.com/style-spec/reference/sources/#geojson-filter

**Comment by peterbodo** [comment]
There is no property filter on Sources. You can apply on Layers.

**Comment by petertoth-dev** [comment]
@peterbodo https://docs.mapbox.com/style-spec/reference/sources/#geojson-filter

**Comment by peterbodo** [comment]
In rnmapbox, there is no such property
@petertoth-dev 
https://rnmapbox.github.io/docs/components/VectorSource

**Comment by petertoth-dev** [comment]
@peterbodo Yes, and this why I opened this issue for :) Not sure what are you trying to tell me here.

**Comment by peterbodo** [comment]
@petertoth-dev RNMapbox only aims to implement features what the Mapbox sdks implement and those have no filter on sources. 

https://docs.mapbox.com/android/maps/api/11.11.0/mapbox-maps-android/com.mapbox.maps.extension.style.sources.generated/-vector-source/

On the to other hand, the problem you raised is completely solvable by adding filter to your layer(s).

**Comment by petertoth-dev** [comment]
@peterbodo 
Now it's clear thx for linking the right docs, however my problem is completely not solvable since the values of the clusters will be wrong. I need to filter my sources and reload manually to get the right values for the clusters.
