### ISSUE TITLE
Unexpected CFBundleExecutable Key for MapboxMaps framework.

### ISSUE THREAD

**Issue by stardevrk** [rnmapbox/maps#3578]
## Environment
- Dev OS: MacOS Sonoma 14.4
- @rnmapbox/maps version: 10.0.15
- React Native version: 0.71.1
- Xcode version: 15.3

## Steps to reproduce
App works fine on the simulator and the physical device. Actually I had to set the Info.plist files manually for `Turf` and `MapboxMaps` frameworks in Xcode. Xcode could not run the app because there was no info.plist files for those frameworks. So app works good on both of the simulator and the physical device.
But now when I upload the app to the testflight, I got this error.

![Screenshot 2024-07-29 at 3 11 50 PM](https://github.com/user-attachments/assets/ca1725a6-a046-405a-8ba8-f4eec968b6a1)

Here is the Turf.plist file

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>${PODS_DEVELOPMENT_LANGUAGE}</string>
  <key>CFBundleIdentifier</key>
  <string>${PRODUCT_BUNDLE_IDENTIFIER}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${PRODUCT_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>BNDL</string>
  <key>CFBundleShortVersionString</key>
  <string>2.8.0</string>
  <key>CFBundleExecutable</key>
	<string>Turf</string>
  <key>CFBundleSignature</key>
  <string>????</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>NSPrincipalClass</key>
  <string></string>
</dict>
</plist>
```

And here is the MapboxMaps plist file.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>${PODS_DEVELOPMENT_LANGUAGE}</string>
  <key>CFBundleIdentifier</key>
  <string>${PRODUCT_BUNDLE_IDENTIFIER}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${PRODUCT_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>BNDL</string>
  <key>CFBundleShortVersionString</key>
  <string>10.18.2</string>
  <key>CFBundleExecutable</key>
  <string>MapboxMaps</string>
  <key>CFBundleSignature</key>
  <string>????</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>NSPrincipalClass</key>
  <string></string>
</dict>
</plist>

```

Please give me the hint, if you can see this issue.

**Comment by mfazekas** [comment]
What is your cocoa pods version? 

See also https://github.com/rnmapbox/maps/issues/2690

**Comment by stardevrk** [comment]
> What is your cocoa pods version?
> 
> See also #2690

My pod version is 1.15.2. 

I have tried:
- Pod cache clean
- Pod deintegrate
- Pod install again

But this solution didn't fix my issue.

**Comment by stardevrk** [comment]
> > What is your cocoa pods version?
> > See also #2690
> 
> My pod version is 1.15.2. And my xcode version is 15.3.
> 
> I have tried:
> 
> * Pod cache clean
> * Pod deintegrate
> * Pod install again
> 
> But this solution didn't fix my issue.

I also tried to set up the manual info.plist file for Turf & MapboxMaps. But this solution didn't work for Testflight too.

**Comment by mfazekas** [comment]
Closing as this is most likely a cocoapods issue, not @rnmapbox/maps related
