### ISSUE TITLE
[Bug]: snapshotManager.takeSnap does not work with bounds

### ISSUE THREAD

**Issue by NVTuann201** [rnmapbox/maps#3621]
### Mapbox Implementation

Mapbox

### Mapbox Version

default 

### React Native Version

0.75.2

### Platform

Android

### `@rnmapbox/maps` version

10.1.31

### Standalone component to reproduce

import {Camera, MapView, snapshotManager, StyleURL} from '@rnmapbox/maps';
import {useState} from 'react';
import {StyleSheet, Text, TouchableOpacity, View} from 'react-native';

const AppMap = () => {
  const bounds = [
    [73.7600360295555, 27.562587612793436],
    [77.33589097013527, 23.986732672213662],
  ];
  const [map, setMap] = useState<MapView | null>(null);

  const onPress = async () => {
    if (!map) {
      return;
    }
    const snapshot = await snapshotManager.takeSnap({
      bounds,
      width: 1024,
      height: 1024,
    });
  };

  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <MapView
          styleURL={StyleURL.SatelliteStreet}
          ref={c => setMap(c)}
          style={styles.map}></MapView>
        <TouchableOpacity style={styles.button} onPress={onPress}>
          <Text style={styles.buttonText}>Take Snap</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};
const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    height: '100%',
    width: '100%',
  },
  map: {
    flex: 1,
  },
  button: {
    position: 'absolute',
    bottom: 20,
    left: '50%',
    transform: [{translateX: -50}],
    backgroundColor: '#007AFF',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default AppMap;

### Observed behavior and steps to reproduce

![image](https://github.com/user-attachments/assets/364eaf52-9fb4-4ba9-a10c-b1812e50888a)

### Expected behavior

Can take screenshot with input bounds

**Comment by jayjo34** [comment]
The Problem is still existing, please Review it. !

**Comment by davepaiva** [comment]
I am facing the same issue please consider re-opening this
