### ISSUE TITLE
IOS Transporter Delivery Error

### ISSUE THREAD

**Issue by lourxd** [rnmapbox/maps#3635]
## Environment
- Dev OS: [OSX 14.6.1]
- @rnmapbox/maps version: [^10.1.31] 
- React Native version: [0.74.5]
- Expo version: [~51.0.34]

Since I upgraded to xcode 16, when I try to send my app to app store connect via Transporter I am getting this error on sending.
The build process works perfectly.

<img width="647" alt="image" src="https://github.com/user-attachments/assets/08795ac9-7252-4238-8f0b-27fa69e3fb68">

Asset validation failed (90482)
Invalid Executable. The executable 'SpeedLou.app/Frameworks/MapboxCoreMaps.framework/MapboxCoreMaps' contains bitcode. (ID: 429b18ba-0520-4fac-81c5-e79f8604223e)

Asset validation failed (90482)
Invalid Executable. The executable 'SpeedLou.app/Frameworks/MapboxMobileEvents.framework/MapboxMobileEvents' contains bitcode. (ID: e0a07491-dab2-44c0-93da-349ae17522c0)

Asset validation failed (90482)
Invalid Executable. The executable 'SpeedLou.app/Frameworks/MapboxCommon.framework/MapboxCommon' contains bitcode. (ID: 5153ba72-0efa-4171-bf35-4ffdbe39e0d4)

Upload failed.
Asset validation failed
Invalid Executable. The executable 'SpeedLou.app/Frameworks/MapboxCommon.framework/MapboxCommon' contains bitcode. (ID: 5153ba72-0efa-4171-bf35-4ffdbe39e0d4)
2024-09-24 11:44:56.272  INFO: [ContentDelivery.Uploader] 
=============
UPLOAD FAILED with 3 errors.
=============

**Comment by lourxd** [comment]
Also tried uploading through EAS and got this error 
[altool] 2024-09-24 04:13:40.117 *** Error: Asset validation failed Invalid Executable. The executable 'SpeedLou.app/Frameworks/MapboxMobileEvents.framework/MapboxMobileEvents' contains bitcode. (ID: 7b824ab0-c9b2-49f6-a27b-adf65b46ce27) (90482)
[altool]  {
[altool]     NSLocalizedDescription = "Asset validation failed";
[altool]     NSLocalizedFailureReason = "Invalid Executable. The executable 'SpeedLou.app/Frameworks/MapboxMobileEvents.framework/MapboxMobileEvents' contains bitcode. (ID: 7b824ab0-c9b2-49f6-a27b-adf65b46ce27)";
[altool]     NSUnderlyingError = "Error Domain=IrisAPI Code=-19241 \"Asset validation failed\" UserInfo={status=409, detail=Invalid Executable. The executable 'SpeedLou.app/Frameworks/MapboxMobileEvents.framework/MapboxMobileEvents' contains bitcode., id=7b824ab0-c9b2-49f6-a27b-adf65b46ce27, code=STATE_ERROR.VALIDATION_ERROR.90482, title=Asset validation failed, NSLocalizedFailureReason=Invalid Executable. The executable 'SpeedLou.app/Frameworks/MapboxMobileEvents.framework/MapboxMobileEvents' contains bitcode., NSLocalizedDescription=Asset validation failed}";
[altool]     "iris-code" = "STATE_ERROR.VALIDATION_ERROR.90482";
[altool] }

**Comment by lcfarias1501** [comment]
Have you tried to downgrade the mapbox version?

**Comment by lourxd** [comment]
> Have you tried to downgrade the mapbox version?

No but seems like I need to upgrade it, it defaults to version 10 when using, I did not have the version specified and version 11 does not use bitcode anymore

**Comment by lourxd** [comment]
40 builds later I was able to solve it.

Mapbox version 10 is no longer going able to be launched into app store connect because it contains bitcode. 
I had some issues with some scopes when transitioning into v11 but was able to solve them.
After that version 11.3.0 and version 11.4.0 were giving me build errors so I tried 11.6.0 and it worked
{
"RNMapboxMapsDownloadToken": "MAPBOX_DOWNLOADTOKEN",
  "RNMapboxMapsVersion": "=11.6.0"
}
If you transition into version 11 be aware of the scopes associated to your token, as this was not letting me build my app until I have set them right

**Comment by jbcrestot** [comment]
It worked for me too, thanks a lot for sharing @lourxd

**Comment by sabuhiteymurov** [comment]
Thanks you, worked without issues @lourxd

**Comment by lourxd** [comment]
Glad to help.
Just a small notice, you wont be able to build on android with "RNMapboxMapsVersion": "=11.6.0"
Replace the "=11.6.0" for "11.6.0", for IOS its not an issue, but on android was giving me a build error

**Comment by tomruijgrok** [comment]
Where do you set this RNMapboxMapsVersion variable?

**Comment by woerchri** [comment]
> Where do you set this RNMapboxMapsVersion variable?
> 
> edit: you can set it in your podfile by adding this line:
> 
> $RNMapboxMapsVersion = '= 11.6.0'

you can also set it in the app.config.js file as described here:
https://rnmapbox.github.io/docs/install?install-module=expo#using-v11
