### ISSUE TITLE
MapBox dependency error for React Native.

### ISSUE THREAD

**Issue by chaitanya-dharpale0209** [rnmapbox/maps#3641]
As of October 02 2024, Im using latest React Native Version.
after my complete installation of mapbox in react native, i got this error:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'. > Could not find com.mapbox.maps:android:10.1.31. Required by: project :app * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output

**Comment by Nitrammets** [comment]
Getting something similar when trying to build for ios

`The following build commands failed:
▸ 	CompileSwift normal arm64 (in target 'MapboxMaps' from project 'Pods')
▸ 	SwiftCompile normal arm64 Compiling\`

**Comment by chaitanya-dharpale0209** [comment]
> Getting something similar when trying to build for ios
> 
> ```
> The following build commands failed:
> ▸ 	CompileSwift normal arm64 (in target 'MapboxMaps' from project 'Pods')
> ▸ 	SwiftCompile normal arm64 Compiling\
> ```

i think we should declare the library name in babel.config file as well. Just like we did it for re-animated
