### ISSUE TITLE
Invalid `rnmapbox-maps.podspec` file: Setting $RNMapboxMapsImpl is now required - https://github.com/rnmapbox/maps/wiki/Deprecated-RNMapboxImpl-Unset#ios.

### ISSUE THREAD

**Issue by jesikaprabhuzcon** [rnmapbox/maps#3647]
## Environment
- Dev OS: 14.5
- @rnmapbox/maps version: "10.0.15"
- React Native version: "0.70.2"

Trying on React Native Cli

## Steps to reproduce
Recently, the library was upgraded in the project, and after that facing this error on pod install.

Performed yarn on the branch and then pod install

I have also tried pod repo update

Gone through the Installation steps for the iOS and all the lines/ instructions mentioned in the installation are performed.
<img width="1027" alt="Screenshot 2024-10-07 at 10 43 03 AM" src="https://github.com/user-attachments/assets/149c3dc2-09d7-47e4-b9f6-6299d7f1b326">

Any solution to this issue?

**Comment by hexadecy** [comment]
Change the **ios/Podfile** to
```Podfile
$RNMapboxMapsImpl = 'mapbox'
```

**Comment by jesikaprabhuzcon** [comment]
In ios/Podfile added these lines

$RNMapboxMapsVersion = '~> 10.11.1'
$RNMapboxMapsImpl = 'mapbox'

commented out below lines

# RNMapboxMapsVersion = '11.4.1'
# RNMapboxMapsImpl = "mapbox"
# $RNMapboxMapsImpl = "mapbox"


# Add Mapbox SDK dependency
# pod 'MapboxMaps', $RNMapboxMapsVersion

in

pre_install do |installer|
//Add below lines
    # $RNMBGL.pre_install(installer) 
    # For mapbox
    ENV['MAPBOX_DOWNLOADS_TOKEN'] = 'sk.eyJ1I...'
    $RNMapboxMaps.pre_install(installer)

in 

post_install do |installer|

//Add below line
$RNMapboxMaps.post_install(installer)


After all these changes issue was resolved
