### ISSUE TITLE
[Bug]: Does MapboxGL.offlineManager.createPack support custom styles?

### ISSUE THREAD

**Issue by vienha** [rnmapbox/maps#3651]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.1.31

### React Native Version

0.75.4

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.1.31

### Standalone component to reproduce

import Mapbox, {
  Camera,
  MapView,
  offlineManager,
  StyleURL,
} from '@rnmapbox/maps';
import React, { useState } from 'react';
import { Button, Dimensions, TextInput } from 'react-native';
Mapbox.setAccessToken('my_token_here');
const OfflineExample = () => {
  const [packName, setPackName] = useState('pack-1');
  const [showEditTitle, setShowEditTitle] = useState(false);
  const STYLE_URL = 'custom_style_url'
  const CENTER_COORD: [number, number] =[105.928, 21.0087];
  return (
    <>
      <Button
        title="Create Pack"
        onPress={() => {
          const options = {
            name: packName,
            styleURL: STYLE_URL,
            bounds: [
            [105.517826, 20.90185],
            [105.906464, 21.204365],
          ],
            minZoom: 0,
            maxZoom: 17,
            metadata: {
              whatIsThat: 'foo',
            },
          };
          console.log("options", JSON.stringify(options));
          offlineManager.createPack(options, (region, status) =>
            console.log('=> progress callback region:', 'status: ', status),(region,sattus)=>{
               console.log("Lỗi tải gói: " + sattus);
            }
          );
        }}
      />
      <MapView style={{ flex: 1 }} styleURL={STYLE_URL}>
        <Camera zoomLevel={10} centerCoordinate={CENTER_COORD} />
      </MapView>
    </>
  );
};
export default OfflineExample;

### Observed behavior and steps to reproduce

When i call the offlineManager.createPack method, I receive the status:

{"completedResourceCount": 0, "completedResourceSize": 0, "erroredResourceCount": 0, "loadedResourceCount": 0, "loadedResourceSize": 0, "name": "offlinePack", "percentage": NaN, "requiredResourceCount": 0, "state": "complete"}

I wonder if rnmapbox supports creating offline packs with custom styles?

**Comment by MarcAntoineCarrier28** [comment]
I had a similar issue, tried many ways to fix this but what worked for me was using the default mapbox style with a max zoom of 16 (I heard past that there might be issues).

offlineManager.createPack(
        {
          name: 'offline-pack',
          styleURL: 'mapbox://styles/mapbox/streets-v12',
          bounds: [
            [-71.23071, 46.71214],
            [-71.11413, 46.78164],
          ] as [[number, number], [number, number]],
          minZoom: 1,
          maxZoom: 16,
        }

I think that applying a different style to the mapviews and the downloaded pack might cause issues. I will try the other mapbox styles next while making sure that my mapviews use the same one to see if that is possible.

**Comment by phubner** [comment]
I have experienced this same issue using custom style URLs. I reproduced it using the [Offline Example](https://rnmapbox.github.io/docs/examples/CacheOffline/OfflineExample) and simply switching out the `StyleUrl.Satellite` with my custom style.

For reference:

Here is the code used.

```javascript
import geoViewport from '@mapbox/geo-viewport';
import Mapbox, {
  Camera,
  MapView,
  offlineManager,
  StyleURL,
} from '@rnmapbox/maps';
import { useState } from 'react';
import { Button, Dimensions, TextInput } from 'react-native';

const CENTER_COORD: [number, number] = [-73.970895, 40.723279];
const MAPBOX_VECTOR_TILE_SIZE = 512;
console.log('=> Mapbox[0]:', Mapbox);
console.log('=> Mapbox.StyleURL[1]:', Mapbox.StyleURL);
console.log('=> StyleURL[2]:', StyleURL);
const STYLE_URL = Mapbox.StyleURL.Satellite;

const oaStyle = 'https://outly.com/api/style/map?public_land_boundaries=0:0.75&roads_and_trails=0:0.75:0&hunting=0:0.75:0&wildlife=0:0.75:0:0:0&cell_coverage=0:0.75&terrain=0:1&camping=0:1&water=0:1&platform=mobile';

Mapbox.setAccessToken(
  'pk.<sometoken-I-PURPOSELY-REMOVED-THIS>'
  );

export default function OfflineExample() {
  const [packName, setPackName] = useState('pack-1');
  const [showEditTitle, setShowEditTitle] = useState(false);

  return (
    <>
      <Button
        title={`Pack name: ${packName}`}
        onPress={() => {
          setShowEditTitle(!showEditTitle);
        }}
      />
      {showEditTitle && (
        <TextInput
          value={packName}
          autoFocus={true}
          onChangeText={(text) => setPackName(text)}
          onBlur={() => setShowEditTitle(false)}
        />
      )}
      <Button
        title="Get all packs"
        onPress={async () => {
          const packs = await offlineManager.getPacks();
          console.log('=> packs:', packs);
          packs.forEach((pack) => {
            console.log(
              'pack:',
              pack,
              'name:',
              pack.name,
              'bounds:',
              pack?.bounds,
              'metadata',
              pack?.metadata,
            );
          });
        }}
      />
      <Button
        title="Get pack"
        onPress={async () => {
          const pack = await offlineManager.getPack(packName);
          if (pack) {
            console.log(
              'pack:',
              pack,
              'name:',
              pack.name,
              'bounds:',
              pack?.bounds,
              'metadata',
              pack?.metadata,
            );

            console.log('=> status', await pack?.status());
          }
        }}
      />
      <Button
        title="Resume pack"
        onPress={async () => {
          const pack = await offlineManager.getPack(packName);
          if (pack) {
            await pack.resume();
          }
        }}
      />
      <Button
        title="Remove packs"
        onPress={async () => {
          const result = await offlineManager.resetDatabase();
          console.log('Reset DB done:', result);
        }}
      />
      <Button
        title="Create Pack"
        onPress={() => {
          const { width, height } = Dimensions.get('window');
          const bounds: [number, number, number, number] = geoViewport.bounds(
            CENTER_COORD,
            12,
            [width, height],
            MAPBOX_VECTOR_TILE_SIZE,
          );

          const options = {
            name: packName,
            styleURL: oaStyle,
            tilesets: [],
            bounds: [
              [bounds[0], bounds[1]],
              [bounds[2], bounds[3]],
            ] as [[number, number], [number, number]],
            minZoom: 10,
            maxZoom: 20,
            metadata: {
              whatIsThat: 'foo',
            },
          };
          offlineManager.createPack(options, 
            (_region, status) => console.log('=> progress callback region:', 'status: ', status),
            (offlineRegion, err) => console.error('createPack error : ', offlineRegion, err)
          );

        }}
      />
      <MapView style={{ flex: 1 }} styleURL={STYLE_URL}>
        <Camera zoomLevel={10} centerCoordinate={CENTER_COORD} />
      </MapView>
    </>
  );
};
```

And here is what I see when the progress listener fires.

```json
{
    "state": "complete",
    "percentage": null,
    "loadedResourceCount": 0,
    "name": "pack-1",
    "completedResourceCount": 0,
    "requiredResourceCount": 0,
    "loadedResourceSize": 0,
    "completedResourceSize": 0,
    "erroredResourceCount": 0
}
```

I use the same style on my v10 version with no problems.
