### ISSUE TITLE
Cannot install mapbox in android for new arch in React Native version 76.0

### ISSUE THREAD

**Issue by Gautham495** [rnmapbox/maps#3666]
## Environment
- Dev OS: Mac M1 pro
- @rnmapbox/maps version: [eg. 10.1.31] 
- React Native version:  76.0

## Steps to reproduce

Install the latest version of rnmapbox in RN 76.0 bare project and enable new arch in android.

Does not work in android but builds in ios.

ERROR:

file:///Users/z/z/node_modules/@rnmapbox/maps/android/src/main/java/com/rnmapbox/rnmbx/utils/ViewTagResolver.kt:35:42 Type mismatch: inferred type is View? but View was expected FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details.

**Comment by mfazekas** [comment]
@Gautham495 pls try https://github.com/rnmapbox/maps/releases/tag/v10.1.33-rc.0

**Comment by Gautham495** [comment]
Thanks @mfazekas - Will try it out.

**Comment by Manikandan-saminathan** [comment]
@mfazekas  when can expect the stable version

**Comment by mfazekas** [comment]
10.1.33 is released so closing this

**Comment by EmilJunker** [comment]
@mfazekas Please reopen, the problem with the `Mapbox.UserLocation` component I mentioned above is still happening when using v10.1.33 with the new architecture enabled (but not when using it with the new architecture disabled). I also still see the same error message in the console:

```
Mapbox [error] ViewTagResolver | view: null found with tag: 368 but it's either null or not the correct type
```
