### ISSUE TITLE
Can't run my app after setting up rnmapbox 

### ISSUE THREAD

**Issue by Teeticode** [rnmapbox/maps#3678]
## Environment
- Dev OS: Mac OS, Xcode 16
- @rnmapbox/maps version: "^10.1.33"
- React Native version:  "0.73.6"
- Expo version: "~50.0.14"

## Steps to reproduce

```sh   
npx create-expo-app --template 
cd sample
npx expo install @rnmapbox/maps
add below to app.json
`"plugins": [
      "expo-router",
      "expo-secure-store",
      [
        "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow $(PRODUCT_NAME) to use your location."
        }
      ],
      [
        "@rnmapbox/maps",
        {
          "RNMapboxMapsDownloadToken": "sk....A",
          "RNMapboxMapsVersion": "10.0.0"
        }
      ]
    ],`
npx expo prebuild --clean
npx expo run ios
```

installs cocoapods correctly but when running npx expo run ios I run into the error below
also if I put this version 10.1.33 in app.json, pods fail to install, I'll really appreciate your help

<img width="564" alt="Screenshot 2024-11-03 at 12 58 01" src="https://github.com/user-attachments/assets/086c144d-83f1-4964-8f9a-d90a9a31a365">

**Comment by mfazekas** [comment]
> "RNMapboxMapsVersion": "10.0.0"

I don't think we support 10.0.0, can you use the latest version for 10.0.*

**Comment by Teeticode** [comment]
Used it and it worked, thank you 👍
