### ISSUE TITLE
Unable to use my custom style - Black Screen

### ISSUE THREAD

**Issue by ABertaud** [rnmapbox/maps#3691]
## Environment
- Dev OS: [e.g. iOS 18]
- @rnmapbox/maps version: [eg. 10.1.33] 
- React Native version: [eg. 0.74.5]
- Expo version: [eg. 51.0.39]

## Steps to reproduce

Create custom style on [mapbox studio](https://studio.mapbox.com/).
Make it standard, and publish it as public. Here's the [preview](https://api.mapbox.com/styles/v1/abertaud/cm3elvh0t005801pg4mqr50ob.html?title=view&access_token=pk.eyJ1IjoiYWJlcnRhdWQiLCJhIjoiY20zY3RxNnV4MjBubTJ2c2NqbHBwdDZpZSJ9.Q8DAm9AC363E54vA5QhGgQ&zoomwheel=true&fresh=true#11.73/48.8567/2.3639).

From share button retrieve the styleURL and use it directly into your component.
```typescript
import React from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

Mapbox.setAccessToken('<YOUR_ACCESSTOKEN>');

const App = () => {
  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <Mapbox.MapView style={styles.map} styleURL="<STYLE_URL>" />
      </View>
    </View>
  );
}

export default App;

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    height: 300,
    width: 300,
  },
  map: {
    flex: 1
  }
});
````

Now i'm encountering a black screen.
Note two things:
- If i replace my styleURL by `StyleURL.Light`, this do not display black screen anymore.
- My secret token literally has all permissions to make sure i wasn't missing one.

Really looking forward some help!

**Comment by ABertaud** [comment]
Solved by using mapbox v11 instead of default v10.

**Comment by gabrielsmborges** [comment]
> Solved by using mapbox v11 instead of default v10.

Just add `"RNMapboxMapsVersion": "11.0.0"` to your plugin config

**Comment by SulimanLab** [comment]
facing same issue, and adding `"RNMapboxMapsVersion": "11.0.0"` didn't solve it

**Comment by Xx-Parks-xX** [comment]
> facing same issue, and adding `"RNMapboxMapsVersion": "11.0.0"` didn't solve it

Don't forget to use "npx expo prebuild --clean" after add this line. I could resolve the same problem using V11 instead of V10.
I added "RNMapboxMapsVersion": "11.8.0" and used "npx expo prebuild --clean" after
