### ISSUE TITLE
[Bug]: Mapbox logo, compass and attribution are always enabled.

### ISSUE THREAD

**Issue by vasilring** [rnmapbox/maps#3728]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.1.33

### React Native Version

0.76.5

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.1.33

### Standalone component to reproduce

<Mapbox.MapView
        style={styles.map}
        logoEnabled={false}
        attributionEnabled={false}
        scaleBarEnabled={false}
        zoomEnabled={true}
        rotateEnabled={false}
        pitchEnabled={false}
        compassEnabled={false}>
        ....other code
              </Mapbox.MapView>

### Observed behavior and steps to reproduce

Compass, attribution and map box logo are always enabled with the new architecture, even if I set them to false, both on emulators and real devices.

### Expected behavior

When compass, logo and attribution are set to false they should not appear on the map.

**Comment by bardak-dev** [comment]
+
