### ISSUE TITLE
FAILURE: Build failed with an exception. BUILD FAILED EXPO APP 👎🏼 

### ISSUE THREAD

**Issue by thygasantos** [rnmapbox/maps#3729]
* What went wrong:

Could not determine the dependencies of task ':app:processDebugResources'.

> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.

   > Could not resolve com.mapbox.maps:android:10.18.4.

     Required by:

         project :app > project :rnmapbox_maps

      > Could not resolve com.mapbox.maps:android:10.18.4.

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.18.4/android-10.18.4.pom'.

            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.18.4/android-10.18.4.pom'. Received status code 403 from server: Forbidden

   > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0.

Required by:

         project :app > project :rnmapbox_maps

      > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0.

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom'.

            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom'. Received status code 403 from server: Forbidden

![Captura de tela de 2024-12-19 16-40-24](https://github.com/user-attachments/assets/d36bf29d-6b25-4b10-8fa3-fcdb1ce1d1ab)

**Comment by DmitriiLevchenko** [comment]
same

**Comment by LeonardoNoroWidelab** [comment]
Hi, 
I created a new Access Token on [Mapbox Access Tokens](https://console.mapbox.com/account/access-tokens), then set it in _app.json_  -> **RNMapboxMapsDownloadToken** and **Mapbox.setAccessToken** on my _App.tsx_ file.

Doing this solved for me.

**Comment by Elazar-Levin** [comment]
I had no problem before, but now suddenly my builds keep failing with this error. I have tried everything, using latest Gradle builds, creating and using a new SK, updating expo, but nothing is working.

**Comment by thygasantos** [comment]
I created a new Access Token in [Mapbox Access Tokens](https://console.mapbox.com/account/access-tokens), and then set it in app.json - RNMapboxMapMapsDownloadToken and Mapbox.setAccessToken in my App.tsx file. use import Mapbox from '@rnmapbox/maps'; in the App.tsx file
it worked normally for me



**screen app.tsx** 
![Captura de tela de 2024-12-26 20-06-45](https://github.com/user-attachments/assets/b271f2f5-d528-43b8-97bb-18f87c77f4e7)


**screen app.json** 
![Captura de tela de 2024-12-26 20-01-39](https://github.com/user-attachments/assets/45582b03-4b0d-44a1-9ed4-5ff6f614a3be)

**Comment by Elazar-Levin** [comment]
> I created a new Access Token in [Mapbox Access Tokens](https://console.mapbox.com/account/access-tokens), and then set it in app.json - RNMapboxMapMapsDownloadToken and Mapbox.setAccessToken in my App.tsx file. use import Mapbox from '@rnmapbox/maps'; in the App.tsx file it worked normally for me
> 
> **screen app.tsx** ![Captura de tela de 2024-12-26 20-06-45](https://private-user-images.githubusercontent.com/18157066/398812674-b271f2f5-d528-43b8-97bb-18f87c77f4e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNTQ4MDgsIm5iZiI6MTczNTI1NDUwOCwicGF0aCI6Ii8xODE1NzA2Ni8zOTg4MTI2NzQtYjI3MWYyZjUtZDUyOC00M2I4LTk3YmItMThmODdjNzdmNGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDIzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MDg4MTg2MzAxZjVlYTQ4MGMyZDBiZjkyMTExYzllYTU3Y2ZiNzY1Y2RmNGExNzJjMzQxZWEwZTFkNDA5MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-xWCTUGe1PpfcsXZIAkERnWZ8xJZeIbKJvci7ByQrAU)
> 
> **screen app.json** ![Captura de tela de 2024-12-26 20-01-39](https://private-user-images.githubusercontent.com/18157066/398812437-45582b03-4b0d-44a1-9ed4-5ff6f614a3be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNTQ4MDgsIm5iZiI6MTczNTI1NDUwOCwicGF0aCI6Ii8xODE1NzA2Ni8zOTg4MTI0MzctNDU1ODJiMDMtNGIwZC00NGExLTllZDQtNWZmNmY2MTRhM2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDIzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNmRjZWRiOTRjNWZlMWEwZDgyMzBjMTU5MTZjNzc1YzkwZDdkYjU3YmIxNTE2NTJlZjlkZjMzOTE2ZDZiYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jdkK71Ly71cfwBm_yczUBnPdo6SK-6y2T7LlB5OMIvw)

Thank you very much for your help. I tried creating a new token, and adding it into the app.json like you said, but I'm still getting the same error. I'll paste my error here, in case there's something I'm missing.

[RUN_GRADLEW] > Configure project :react-native-reanimated
[RUN_GRADLEW] Android gradle plugin: 8.6.0
[RUN_GRADLEW] Gradle: 8.10.2
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Could not determine the dependencies of task ':app:processDebugResources'.
[RUN_GRADLEW] > Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
[RUN_GRADLEW]    > Could not find com.mapbox.maps:android:10.18.4.
[RUN_GRADLEW]      Searched in the following locations:
[RUN_GRADLEW] - https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/maps/android/10.18.4/android-10.18.4.pom
[RUN_GRADLEW]        - https://repo.maven.apache.org/maven2/com/mapbox/maps/android/10.18.4/android-10.18.4.pom
[RUN_GRADLEW]        - https://dl.google.com/dl/android/maven2/com/mapbox/maps/android/10.18.4/android-10.18.4.pom
[RUN_GRADLEW]        - https://www.jitpack.io/com/mapbox/maps/android/10.18.4/android-10.18.4.pom
[RUN_GRADLEW]        - file:/tmp/root/eas-build-local-nodejs/f4978724-5959-4de8-8137-4a4a4f9d4d6e/build/node_modules/react-native/android/com/mapbox/maps/android/10.18.4/android-10.18.4.pom
[RUN_GRADLEW]        - file:/tmp/root/eas-build-local-nodejs/f4978724-5959-4de8-8137-4a4a4f9d4d6e/build/node_modules/jsc-android/dist/com/mapbox/maps/android/10.18.4/android-10.18.4.pom
[RUN_GRADLEW]      Required by:
[RUN_GRADLEW]          project :app > project :rnmapbox_maps
[RUN_GRADLEW]    > Could not find com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0.
[RUN_GRADLEW]      Searched in the following locations:
[RUN_GRADLEW]        - https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
[RUN_GRADLEW]        - https://repo.maven.apache.org/maven2/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
[RUN_GRADLEW]        - https://dl.google.com/dl/android/maven2/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
[RUN_GRADLEW]        - https://www.jitpack.io/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
[RUN_GRADLEW]        - file:/tmp/root/eas-build-local-nodejs/f4978724-5959-4de8-8137-4a4a4f9d4d6e/build/node_modules/react-native/android/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
[RUN_GRADLEW]        - file:/tmp/root/eas-build-local-nodejs/f4978724-5959-4de8-8137-4a4a4f9d4d6e/build/node_modules/jsc-android/dist/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom
[RUN_GRADLEW]      Required by:
[RUN_GRADLEW]          project :app > project :rnmapbox_maps
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] >
[RUN_GRADLEW] Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 27s

**Comment by thygasantos** [comment]
error in your application code, my application compilation is working .

**Comment by Elazar-Levin** [comment]
I have checked everything, isolated code I wrote after the issue started appearing, deleting node modules, clearing gradle cache, renewing tokens, literally nothing works, I don't think this is resolved

**Comment by anaselmo** [comment]
> error in your application code, my application compilation is working .

When I build my application I have no issues, but when my friend tries to do it, he gets this same issue. The codebase is the same for both of us, and we are using the same mapbox keys

**Comment by thygasantos** [comment]
created a new Access Token in [Mapbox Access Tokens](https://console.mapbox.com/account/access-tokens), and then set it in app.json - RNMapboxMapMapsDownloadToken and Mapbox.setAccessToken in my App.tsx file. use import Mapbox from '@rnmapbox/maps'; in the App.tsx file it worked normally for me
