### ISSUE TITLE
Specify host for customer headers

### ISSUE THREAD

**Issue by bartolkaruza** [rnmapbox/maps#504]
This issue is intended as a start of a discussion for adding support to limit the hosts to which custom headers are sent.

mapbox-gl-js map supports a [transformRequest option](https://docs.mapbox.com/mapbox-gl-js/api/#map) which allows custom headers to be set. It is implemented as a function where you can implement logic to add headers for specific hosts using something like this:
```
transformRequest: (url, resourceType) => {
        if (resourceType === 'Tile' && url.match('example.com')) {
            return {
                url: url,
                headers: { 'Authorization': 'secret' }
            };
        }
    }
```

The common use case for transformRequest is to add custom authorisation headers for authenticated tile servers.

In react-native-mapbox-gl/maps you can also add custom headers, but they will be added to every mapbox tile request, not just to a specific host/source. This leaks security sensitive data to mapbox servers (which ignore the headers) and also potentially to other hosts that shouldn't receive the headers.

I understand that a JS function passed to native code will not work, so the exact same approach as mapbox-gl-js doesn't fit on the react-native-mapbox-gl model. But because the custom headers intended for specific hosts is such a common thing for anyone using a custom tile server, I propose we solve at least the problem of limiting headers to specific hosts.

I see several ways to solve this and there may be more.
1. add `hosts` array to [addCustomHeader](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/CustomHttpHeaders.md)
2. add `urlFilter` regex to [addCustomHeader](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/CustomHttpHeaders.md)
3. Either 1 or 2 + `customHeaders`, but on [VectorSource](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/VectorSource.md), [ShapeSource](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/ShapeSource.md), [RasterSource](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/RasterSource.md) and [ImageSource](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/ImageSource.md).

I appreciate any feedback on the problem, the proposed solutions. I'm happy to contribute the solution in a PR if we can settle on an approach.

**Comment by dave-moser** [comment]
I am having the same issue.  I need to sign the request to our map tile provider.  I can do this with the react-map-gl component in a web page with the transformRequest option.  Is there any similar functionality for react-native-mapbox-gl?

**Comment by fcandi** [comment]
I am having the same issue. Is there already a solution?

**Comment by TamNhiDuong** [comment]
> I am having the same issue. Is there already a solution?

Do you mean solution for setting header for a request or limiting header for  specific hosts?

**Comment by RobertSasak** [comment]
You can intercept all the traffic on Android at 
_node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/http/CustomHeadersInterceptor.java_

You can start by patching this file and then generalise it to function similar to _add/removeHeader_. 

If any of you know the equivalent iOS interceptor with code example, please do share.

**Comment by vamshi9666** [comment]
@RobertSasak  what about ios interceptor ?

**Comment by RobertSasak** [comment]
@vamshi9666 I must admit that I have searched for it but without any success. I hope that somebody else might help us.
