### ISSUE TITLE
Feature request: Add setConnected() for iOS

### ISSUE THREAD

**Issue by gmaclennan** [rnmapbox/maps#513]
This depends on https://github.com/mapbox/mapbox-gl-native/pull/15650 adding the equivalent feature to the SDK. It is to add the iOS equivalent of https://github.com/react-native-mapbox-gl/maps/pull/508

**Comment by mzu** [comment]
Is this still relevant? Could this feature be used as a way to force the use of an offline pack, even if there is an internet connection available? Is there already a way prevent requesting tiles if an offline pack is available?

**Comment by mreda7** [comment]
Hello @gmaclennan, I saw that the [pull request ](https://github.com/mapbox/mapbox-gl-native/pull/15650) that integrate setConnected to iOS has been merged, and now it is available in the file [MGLNetworkConfiguration.mm](https://github.com/mapbox/mapbox-gl-native-ios/blob/main/platform/darwin/src/MGLNetworkConfiguration.mm).

I don't know if this merge request can be reopened ?

**Comment by gmaclennan** [comment]
I'm not able to re-open it (I'm not a maintainer here), but given that `setConnected()` is now implemented in iOS, it would be good to add it. I don't have the iOS knowledge to do this unfortunately. We're not building our app for iOS yet, but will be in the future and would need this feature.
